src/_patterns/01-core/05-objects/01-lists/bolt-ui-list/src/ui-list.scss

Adding small and large spacing to ui list.

---

src/_patterns/02-components/bolt-action-blocks/README.md
src/_patterns/02-components/bolt-background/README.md
src/_patterns/02-components/bolt-band/README.md
src/_patterns/02-components/bolt-blockquote/README.md
src/_patterns/02-components/bolt-button-group/README.md
src/_patterns/02-components/bolt-button/README.md
src/_patterns/02-components/bolt-card/README.md
src/_patterns/02-components/bolt-chip-list/README.md
src/_patterns/02-components/bolt-chip/README.md
src/_patterns/02-components/bolt-figure/README.md
src/_patterns/02-components/bolt-headline/README.md
src/_patterns/02-components/bolt-ordered-list/README.md
src/_patterns/02-components/bolt-sticky/README.md
src/_patterns/02-components/bolt-unordered-list/README.md

Just text fix. No code is touched.

Cleaning up typos in a bunch of README's.

---

src/_patterns/02-components/bolt-band/src/band.twig

fix: make band componentName and baseClass fixed values

---

src/_patterns/01-core/05-objects/bolt-ratio-object/src/ratio.scss
src/_patterns/01-core/05-objects/bolt-ratio-object/src/ratio.standalone.js
src/_patterns/01-core/05-objects/bolt-ratio-object/src/ratio.twig
src/_patterns/02-components/bolt-background/src/background.scss
src/_patterns/02-components/bolt-band/src/band.standalone.js
src/_patterns/02-components/bolt-device-viewer/src/_device-viewer--ipad.scss
src/_patterns/02-components/bolt-device-viewer/src/_device-viewer--iphone8.scss
src/_patterns/02-components/bolt-device-viewer/src/_device-viewer.scss
src/_patterns/02-components/bolt-device-viewer/src/device-viewer.twig
src/_patterns/04-pages/d8-product-landing/d8-product-t2.twig

Next Bolt Release Candidate:
- Workaround fix to address issue in IE11 with responsive images not fully filling the ratio container the image is added to
- Partially disabling background component animation of video layer to simplify for release
- Updating band animation to try to reduce jank of open and close animation
- Cleaning up iPad + iPhone 8 Device Viewer responsiveness
- Add additional iPhone device viewer examples for testing
CC @christophersmith262  @charginghawk

Bolt v0.9.0-rc.2: Improve Device Viewer Responsiveness + Bug Fixes 

---

build-tools/gulp-tasks/build-webpack/package.json
build-tools/gulp-tasks/build-webpack/webpack.config.release.js
package-lock.json
src/_patterns/02-components/bolt-background/src/background.scss
src/_patterns/02-components/bolt-headline/src/all-headlines.scss
src/_patterns/02-components/bolt-video/src/_videojs-enhancements.scss
src/_patterns/02-components/brightcove-player/src/brightcove-player.standalone.js

- Fix, re-enable uglify in prod build @remydenton 
- Kill off max-width for headlines for @christophersmith262 
- Update device viewer max-width sizes per chat with @MattNagy 
- Fix iOS safari scrolling issue w/ bands w/ embedded videos
- Fix vertical center of social share modal for IE11

Misc v0.9.0 Fixes

---

bolt-manifest.yml
config/config.yml
src/_patterns/02-components/bolt-video/demo/video--background-video-with-inline-script-and-external-controls.twig
src/_patterns/02-components/bolt-video/demo/video--external-controls.twig
src/_patterns/02-components/bolt-video/demo/video--inline-script-with-external-controls.twig
src/_patterns/02-components/bolt-video/demo/video--inline-script.twig
src/_patterns/02-components/bolt-video/src/_video-inline-script.twig
src/_patterns/02-components/bolt-video/src/video-static-test.twig
src/_patterns/02-components/brightcove-player/src/brightcove-player.standalone.js

- Update video init check to allow external config customization while still maintaining internal methods / functionality (ex. expand / collapse behavior, exposed `toggle`, `play` and `pause` methods, etc)
- Add example `_video-inline-script.twig` inline JS script with common config options already setup
- Add additional video player examples demoing using external controls + with and without inline script customization for both inline and background video embeds
CC @charginghawk @krlucas @remydenton

Update Video Init Check

---

apps/pattern-lab--workshop/package.json

Forgot to add this in #312 - nice catch @remydenton !

Adding dep for button

---

apps/pattern-lab--workshop/.boltrc.js
apps/pattern-lab--workshop/package.json
package.json
packages/components/05-bolt-background-shapes/package.json
packages/components/05-bolt-background-shapes/src/background-shapes.scss

#309 Updates for background shapes component

Update component for new build tools: background-shapes

---

packages/build-tools/commands/build.js
packages/build-tools/utils/run.js

We'll be using these a lot; let's get them separated out now.

Build Tools: Extracting run series and run parallel out into dedicated utilities

---

packages/build-tools/cli.js
packages/build-tools/commands/build.js
packages/build-tools/tasks/server-tasks.js

Address [our chats](https://github.com/bolt-design-system/bolt/pull/328#discussion_r161357645) about renaming.

Renaming server tasks

---

packages/build-tools/cli.js
packages/build-tools/utils/log.js

Just a tiny bit of polish for the start screen of Bolt CLI ^_^

Polish Up Bolt CLI Start Screen

---

apps/pattern-lab--workshop/package.json
package.json
packages/build-tools/package.json
packages/components/background-shapes/package.json
packages/components/button/package.json
packages/core/package.json
packages/global/package.json

This gets everything working again for me!

Hotfix: version bump fix

---

.gitignore
apps/pattern-lab--workshop/.boltrc.js
apps/pattern-lab--workshop/config/config.yml
apps/pattern-lab--workshop/package.json
apps/pattern-lab--workshop/src/_meta/_00-head.twig
apps/pattern-lab--workshop/src/_meta/_01-foot.twig
package.json
packages/build-tools/cli.js
packages/build-tools/create-webpack-config.js
packages/build-tools/package.json
packages/build-tools/tasks/internal-tasks.js
packages/build-tools/tasks/pattern-lab-tasks.js
packages/build-tools/tasks/task-collections.js
packages/build-tools/utils/assets.js
packages/build-tools/utils/config.schema.yml
packages/build-tools/utils/manifest.js
packages/build-tools/utils/sh.js
packages/components/bolt-band/package.json
packages/components/bolt-band/src/band-collection.standalone.js
packages/components/bolt-band/src/band.js
packages/components/bolt-band/src/band.scss
packages/components/bolt-band/src/band.standalone.js
packages/components/bolt-band/src/band.twig
packages/components/color-swatch/package.json
packages/global/package.json
packages/global/styles/05-objects/objects-wrapper/wrapper.twig
packages/twig-extensions/filters/custom-filters/webpack.filter.php

After building, look in `apps/pattern-lab--workshop/www/build/data`.

Manifest setup

---

apps/pattern-lab--workshop/.boltrc.js
packages/build-tools/cli.js
packages/build-tools/package.json
packages/build-tools/tasks/image-tasks.js
packages/build-tools/tasks/task-collections.js
packages/build-tools/utils/config.schema.yml

This sets up the very basics of the image tasks for #364 No resizing/minification nor watch. Does have support for size suffixes. When prod it copies (will resize/min later), and when not on prod it symlinks.

Foundation for Image Build Tasks

---

packages/bolt-core/index.js
packages/bolt-core/utils/renderer-preact.js
src/_patterns/02-components/bolt-button/src/button.standalone.js

Original work by @sghoweri with a little tidying up by me.  Makes buttons work from within forms.

fix: conditionally swap out button rendering when being used in a form

---

packages/components/bolt-blockquote/package.json
packages/components/bolt-blockquote/src/blockquote.scss
packages/components/bolt-blockquote/src/blockquote.twig
packages/components/bolt-button-group/package.json
packages/components/button/package.json
packages/components/button/src/button.js
packages/components/button/src/button.scss
packages/components/button/src/button.standalone.js
packages/components/button/src/button.twig

@sghoweri So I tried to pull in the newest version of the buttons and I noticed some strange behavior in the patternlab. The buttons would load correctly and look good for about 1 second, then switch to the default browser styling.

WIP migrate button 0.9.8 from 0.x to 1.x

---

packages/components/bolt-site/_components.site.scss
packages/components/bolt-site/package.json
packages/components/bolt-smooth-scroll/package.json
packages/components/bolt-sticky/package.json
packages/components/bolt-sticky/src/sticky.scss
packages/components/bolt-sticky/src/sticky.twig
packages/components/bolt-teaser/package.json
packages/components/bolt-unordered-list/package.json
packages/components/bolt-video/package.json
packages/components/bolt-video/src/_video-inline-script.twig
packages/components/bolt-video/src/_video.scss
packages/components/bolt-video/src/_videojs-enhancements.scss
packages/components/bolt-video/src/video.standalone.js
packages/components/bolt-video/src/video.twig
packages/components/brightcove-player/package.json
packages/components/brightcove-player/src/brightcove-meta.scss
packages/components/brightcove-player/src/brightcove-player.scss
packages/components/brightcove-player/src/brightcove-player.standalone.js
packages/components/brightcove-player/src/brightcove-player.twig
packages/components/page-footer/_page-footer.twig
packages/components/page-footer/package.json
packages/components/page-footer/page-footer.twig

- update @bolt/page-footer to 0.9.0
- update @bolt/site to 0.9.0
- update @bolt/smooth-scroll to 0.9.5
- update @bolt/sticky to 0.10.0
- update @bolt/teaser to 0.9.0
- update @bolt/video to 0.9.6
- update @bolt/unordered-list to 0.9.0
- update @bolt/brightcove-player to 0.9.6

Migrate Updates:Page-footer, site, smooth-scroll, sticky, teaser, video, ul, brightcove

---

src/_patterns/01-core/05-objects/bolt-ratio-object/src/ratio.scss
src/_patterns/02-components/bolt-card/demo/card-kitchen-sink.twig
src/_patterns/02-components/bolt-card/src/card.twig
src/_patterns/02-components/components-all/package.json

- Add missing breadcrumb component to components-all package; fixes bootstrap issue on release/0.x branch
- Update ratio object with overflow: hidden to prevent inner content from spilling out (ex. blurred image placeholder)
- Update card component to address rendering issues when an image isn't passed through
- Update card component icon logic to allow embedded buttons to choose a different icon + support an `external` option to change the default icon selection
v1.0 mirrored updates being added in separate PR :-)

Card, Button, Breadcrumb, and Ratio Object Fixes

---

packages/core-php/readme.md
scripts/update-read-only-git-repos.sh

This will push to read-only repos when we test. Currently set up is:
- `bolt/core-php` published to https://github.com/bolt-design-system/core-php

Setting up PHP Package Publishing

---

.travis.yml
packages/core-php/readme.md

Triggering read-only repo pushes and providing some test content.

PHP Package Publishing

---

packages/components/bolt-form/src/form.scss
packages/core/styles/01-settings/settings-shadow/_settings-shadow.scss
packages/core/styles/02-tools/tools-shadow/_tools-shadow.scss

Updates to the shadow mixin to handle custom colors. Default is old shadow color.
Updates to form scss to use the new shadow mixin.

shadow colors for form

---

apps/pattern-lab/src/styles/pl.scss
packages/core/styles/01-settings/settings-shadow/_settings-shadow.scss

Updated values as per @theSadowski notes in Jira. Wasn't sure what to do with hover state values, so I winged it a bit. 
Also added a small touch to styling of shadow demo (hovered example gets a z-index boost to get above neighbor's shadow).

update box shadow values

---

apps/bolt-site/composer.lock
apps/pattern-lab/composer.lock
apps/pattern-lab/src/_patterns/02-components/headline/15-headline-align-variations.twig
apps/pattern-lab/src/_patterns/02-components/headline/20-headline-style-and-weight-variations.twig
apps/pattern-lab/src/_patterns/02-components/sticky/00-sticky-docs.twig
packages/components/bolt-headline/headline.schema.yml
packages/components/bolt-headline/src/_typography.twig

Reverts bolt-design-system/bolt#523

Revert "headline schema improvements"

---

packages/drupal-modules/bolt_connect/bolt_connect.install
packages/drupal-modules/bolt_connect/bolt_connect.services.yml
packages/drupal-modules/bolt_connect/src/BoltConnectForm.php
packages/drupal-modules/bolt_connect/src/BoltConnectTwigNamespaces.php

Improving error messaging and failing more gracefully

Bolt Connect Module updates

---

packages/config-presets/babel-preset-bolt/index.js
packages/config-presets/babel-preset-bolt/package.json

- Updates Babel config packages to latest versions
- Updates plugins to add support for handling async / await functions on the client side of things
- Adds more generic / forgiving `export` support in JS modules

Update Bolt's Shared Babel Config

---

packages/components/bolt-button/src/button.twig
packages/components/bolt-headline/src/_typography.twig

Updates the button and headline components to support icon positioning (to the left or to the right of the text showing up); used in larger dropdown component work in #567

Add Icon Position Support to Buttons and Headlines

---

packages/global/styles/05-objects/objects-flag/_objects-flag.scss

Unquote alignment options of flag object Sass so vertical alignment works again as expected.

Fix Flag Object Alignment

---

apps/drupal-lab/config/sync/core.extension.yml

Simple adjustment to config to fix issues with Drupal Lab rebuild

Drupal Lab - fix rebuild artifact via config adjustment

---

apps/bolt-site/content/20-docs/05-principles/05-accessibility.md

Created a page about our commitment/accessibility principles

Added accessibility page

---

packages/components/bolt-breadcrumb/src/breadcrumb.scss
yarn.lock

The chevron was dropping too low, I lifted back up.

Fixing breadcrumb vertical alignment

---

packages/components/bolt-button/src/button.scss

This branch focuses on fixing a minor issue that crept up with some problematic scss added to button.scss. Simple fix was to remove the scss in question — all looks correct now.

Tweak Share Component

---

packages/components/bolt-smooth-scroll/src/smooth-scroll.js
packages/components/bolt-sticky/package.json
packages/components/bolt-sticky/src/sticky.js
yarn.lock

Updates sticky with QoL changes and compatibilty fixes from the Drupal fork, including a more accurate polyfill and better defaults.

Update sticky component to support advanced use cases.

---

apps/bolt-site/content/20-docs/30-components/00-index.md
apps/bolt-site/content/20-docs/30-patterns/00-index.md

Per @sghoweri's request, I updated the Components folder to be named "Patterns." I also updated the introductory text for that page.

Updated "Components" to "Patterns" 

---

apps/bolt-site/content/20-docs/30-patterns/bands.md
apps/bolt-site/content/20-docs/30-patterns/buttons.md
apps/bolt-site/content/20-docs/30-patterns/cards.md
apps/bolt-site/content/20-docs/30-patterns/forms.md

I had to go in and correct a couple of class names and update to relative paths.

Text updates to published docs

---

packages/components/bolt-video/src/video.standalone.js

Null value for this.props.controls now results in true for controls

properly default controls on bolt video web component

---

src/_patterns/02-components/bolt-background/src/background.scss

WWWD-2089 Fix fullscreen video

---

apps/pattern-lab/src/_patterns/02-components/card/10-card-band-variation.twig
packages/components/bolt-card/src/card.scss

This enables individually themed cards to have solid colored backgrounds, no transparency.

Fix: themed card to have solid colored background

---

packages/global/styles/03-generic/_generic-normalize.scss
packages/global/styles/index.scss

This is just a cleanup for clarity's sake.

Re-organize and comment on the normalize.css include

---

apps/pattern-lab/src/_patterns/02-components/buttons-group/20-button-group-contentItems.twig
packages/components/bolt-band/band.schema.yml
packages/components/bolt-band/src/band.twig
packages/components/bolt-button-group/button-group.schema.yml
packages/components/bolt-button-group/src/button-group.twig
packages/components/bolt-card/card.schema.yml
packages/components/bolt-card/src/card.twig

Card is definitely going to need more work, but this is a start.

Schema Update - band, button group, card

---

apps/pattern-lab/src/_patterns/02-components/unordered-list/15-unordered-list-contentItems-nested.twig
packages/components/bolt-chip-list/chip-list.schema.yml
packages/components/bolt-chip-list/chip-list.twig
packages/components/bolt-chip/chip.schema.yml
packages/components/bolt-chip/src/chip.twig
packages/components/bolt-teaser/src/teaser.twig
packages/components/bolt-teaser/teaser.schema.yml
packages/components/bolt-unordered-list/src/unordered-list.twig
packages/components/bolt-unordered-list/unordered-list.schema.yml

Schema - Chip, Chip List, Teaser, Unordered List

---

packages/components/bolt-share/src/share.scss
packages/components/bolt-share/src/share.twig

Update share inline component with "share this page" text, color change to dark gray, icon color to indigo, light instead of social brand colors.

Update share inline component 

---

packages/components/bolt-video/package.json
packages/components/bolt-video/src/video.standalone.js
yarn.lock

This PR is the second half of the functionality needed for BDS-25. **Please merge PR #717 before merging this!**
**Testing instructions**
1. At the root of repo, run `yarn install && npm run setup`
1. Navigate to PL `cd apps/pattern-lab`
1. Run the things! `npm run start`
1. Navigate to http://localhost:3000/pattern-lab/patterns/02-components-video-video--background-video-with-inline-script-and-external-controls/02-components-video-video--background-video-with-inline-script-and-external-controls.html
**Passes if** user is able to close the "modal" by hitting the "esc" key

Video Enhancement - Collapse video when hitting "escape" key

---

apps/pattern-lab/src/_patterns/04-pages/10-homepage/-00-homepage.twig
apps/pattern-lab/src/_patterns/04-pages/10-homepage/-01-homepage-w-background-video.twig
apps/pattern-lab/src/_patterns/04-pages/30-product-pages/-product-landing-page.twig
apps/pattern-lab/src/_patterns/04-pages/30-product-pages/-product-t2-page.twig
apps/pattern-lab/src/_patterns/04-pages/30-product-pages/-product-t3.twig
apps/pattern-lab/src/_patterns/04-pages/80-events/_event-register-form.twig
apps/pattern-lab/src/_patterns/04-pages/80-events/event-detail.twig
apps/pattern-lab/src/_patterns/04-pages/80-events/event-landing.twig

Certain include paths were meant to be changed to use the `@pl` prefix, this catches the ones that were missed and updates them.

Fix: update PL specific includes

---

packages/components/bolt-button/src/button.standalone.js

This PR removed the unused commented code.

Button Regression - Removed unused commented code

---

packages/components/bolt-nav-priority/nav-priority.js

Resolves http://vjira2:8080/browse/BDS-425

fix: update priority nav logic to only show nav items that fit

---

packages/components/bolt-nav-priority/nav-priority.scss
packages/components/bolt-smooth-scroll/src/smooth-scroll.js
packages/core/index.js
packages/core/utils/is-valid-selector.js
yarn.lock

- Tweak positioning of navbar links https://github.com/bolt-design-system/bolt/pull/764
- Fix javascript error caused by selector http://vjira2:8080/browse/BDS-434

Release v1.5.2

---

packages/components/bolt-nav-priority/nav-priority.scss

Resolves http://vjira2:8080/browse/BDS-439

fix: fix navbar smoothscroll at xs breakpoint (BDS-396)

---

packages/build-tools/package.json
packages/build-tools/tasks/pattern-lab-tasks.js
packages/build-tools/tasks/static-tasks.js
packages/build-tools/utils/sh.js

Setting up execa instead of child_process.exec for sh util - does better job killing orphaned child processes

Better sh util

---

packages/components/bolt-nav-indicator/nav-indicator.js

Resolves http://vjira2:8080/browse/WWWD-2278

fix: Add extra offset to gumshoe to fix perceived bug (WWWD-2278)

---

apps/pattern-lab/src/_patterns/02-components/pagination/15-pagination-count-variations.twig
apps/pattern-lab/src/_patterns/02-components/pagination/20-pagination-align-variations.twig
packages/components/bolt-pagination/pagination.schema.yml
packages/components/bolt-pagination/pagination.scss
packages/components/bolt-pagination/pagination.twig

Resolves http://vjira2:8080/browse/BDS-452
Additionally:
- Adds full support for link attributes
- Makes the active item not a link
- Adds align property to center by default

BDS-452 Pagination additional features and improvements

---

packages/components/bolt-pagination/pagination.scss

http://vjira2:8080/browse/BDS-505
This is also branched off of https://github.com/bolt-design-system/bolt/pull/827
Convert Pagination component to use new theming system.
Removed the interim theming fix in pagination and then replaced with `bolt-theme` function to define colors.
Run the branch locally and do cross browser testing to make sure there's no discrepancies. 
This is how it should look:

Wire up Pagination to use theming system

---

apps/pattern-lab/src/_patterns/04-pages/100-d8-Press-and-Media/d8-media-browse--list-view.twig
packages/components/bolt-band/src/band.scss

http://vjira2:8080/browse/BDS-605
Fixes mobile search filter positioning when inside bands
Removes 
- Go to https://bolt-design-system.com/pattern-lab/?p=pages-d8-media-browse--list-view
- In the browser, find the div that has a `c-bolt-band` class and change the element to `<bolt-band>`.
- Change your browser to a mobile size and confirm that the search facet icon does not display fixed (original issue described at http://vjira2:8080/browse/WWWD-2509)
-

Fix mobile search filter positioning when inside bands

---

packages/core/renderers/bolt-base.js

Testing potential hotfix to `this.useShadow` not working as expected

Hotfix: Fix `useShadow` Check

---

packages/uikit-workshop/src/html/index.html
packages/uikit-workshop/src/html/partials/controls.html
packages/uikit-workshop/src/sass/pattern-lab.scss
packages/uikit-workshop/src/sass/scss/03-vendor/_prism.scss
packages/uikit-workshop/src/sass/scss/04-components/_pattern-info.scss
packages/uikit-workshop/src/sass/scss/04-components/_tabs.scss
packages/uikit-workshop/src/sass/scss/05-themes/_light-theme.scss
packages/uikit-workshop/src/sass/scss/05-themes/_sidebar-theme.scss
packages/uikit-workshop/src/scripts/actions/app.js
packages/uikit-workshop/src/scripts/components/modal-viewer.js
packages/uikit-workshop/src/scripts/components/pl-drawer/pl-drawer.js
packages/uikit-workshop/src/scripts/components/pl-drawer/pl-drawer.scss
packages/uikit-workshop/src/scripts/components/pl-layout/pl-layout.js
packages/uikit-workshop/src/scripts/components/pl-toggle-info/pl-toggle-info.js
packages/uikit-workshop/src/scripts/components/pl-toggle-info/pl-toggle-info.scss
packages/uikit-workshop/src/scripts/components/pl-toggle-layout/pl-toggle-layout.js
packages/uikit-workshop/src/scripts/components/pl-toggle-theme/pl-toggle-theme.js
packages/uikit-workshop/src/scripts/patternlab-viewer.js
packages/uikit-workshop/src/scripts/reducers/app.js

http://vjira2:8080/browse/BDS-711
Ports [upcoming OS Pattern Lab UI improvements](https://github.com/pattern-lab/patternlab-node/pull/960) and refactor work into Bolt.
<h2>Before (left) and After (right)</h2>
We've already ported over the majority of the bug and cross browser fixes from #903 however the Modal / Drawer UI component refactor work is brand new that we can start taking advantage of immediately.

Refactor: Backport Upstream Pattern Lab UIKit Improvements

---

packages/components/bolt-video/TESTING.md

Related to #951
Testing checklist for the Bolt video component -- similar idea to #952
Read through items listed below to confirm this 1st pass outline of most of the current Bolt video player functionality is covered below.
> Note: programmatically controlling the player with built-in methods like `play`, `pause`, and `toggle` can be added separately -- this is just meant to be a quick punch list of existing expectations so we have the basics covered in manual and automated testing coverage.
CC @krlucas @charginghawk @margoromo @remydenton @danielamorse

Add testing checklist docs for the current <bolt-video> component

---

packages/components/bolt-table/src/table.scss

http://vjira2:8080/browse/BDS-759
CSS fix to address theming system issue reported for the Bolt Table component when compiled for production.
Confirm Table border styling working as expected with update here.

Fix Table Border Styles in Prod Build

---

packages/components/bolt-icon/icon.schema.yml
packages/components/bolt-icons/src/icons/star-solid.js
packages/components/bolt-icons/src/index.js
packages/components/bolt-icons/src/svgs/utility/star-solid.svg
yarn.lock

http://vjira2:8080/browse/BDS-858
Adds a solid star icon to the Bolt icon library.
This adds the solid version of the star icon, since the design doesn't call for an outlined version, we are not adding that yet. This one will be named `star-solid` to go with our current naming conventions.
Run the branch locally and navigate to the icons page. Make sure the star icon is there.

Icon Update: Add solid star icon

---

docs-site/src/pages/pattern-lab/_patterns/02-components/blockquote/35-blockquote-web-component.twig
docs-site/src/templates/_site-head.twig
packages/components/bolt-blockquote/package.json
packages/components/bolt-blockquote/src/Author/AuthorImage.js
packages/components/bolt-blockquote/src/Author/AuthorName.js
packages/components/bolt-blockquote/src/Author/AuthorTitle.js
packages/components/bolt-blockquote/src/Author/index.js
packages/components/bolt-blockquote/src/blockquote.js
packages/components/bolt-blockquote/src/blockquote.scss
packages/components/bolt-blockquote/src/blockquote.twig
packages/components/bolt-headline/src/_typography.twig
packages/components/bolt-image/src/image.twig
packages/components/bolt-logo/src/logo.twig
packages/components/bolt-text/src/text.js
packages/components/bolt-text/src/text.standalone.js
packages/components/bolt-text/src/text.twig
packages/components/bolt-text/text.schema.yml

(Enter a link to the Jira issue this PR applies to, if any)
(Enter a one-line summary of the changes in this PR.  This will be included in the release notes)
(Explain the changes in enough detail fo reviewers to understand.  Raise any questions for reviewers to consider.)
(List clear steps to test that the changes are working)

WIP: Blockquote Refactor Suggestions

---

docs-site/src/components/schema-form/component-explorer.js
packages/build-tools/api/index.js
packages/twig-renderer/twig-renderer.js

N/A
Pulling in renderer updates separately to test performance.

Chore: Pull In Twig Renderer Into PL Updates

---

.travis.yml
docs-site/__tests__/homepage.e2e.js
docs-site/__tests__/pattern-lab.e2e.js
nightwatch.js
package.json
packages/uikit-workshop/src/html/index.html
packages/uikit-workshop/src/scripts/patternlab-viewer.js
packages/uikit-workshop/webpack.config.js
yarn.lock

N/A
Short term workaround for an async loading issue in Pattern Lab occasionally observed that throws a JS error if the global Pattern Data doesn’t exist when a component expects it.
Updates the main PL JavaScript bundles to load asynchronously but execute in the order of the tags by using the `defer` attribute. Workaround till we can further debug the specific loading issue and come up with an async-friendly fix.
- Observe PL to see if loading issue previously seen goes away. Tricky to replicate given the issue only has only been observed a few times.

Workaround For Async Pattern Lab Data-Related JS Error

---

scripts/report-nightwatch-results.js

(Enter a link to the Jira issue this PR applies to, if any)
(Enter a one-line summary of the changes in this PR.  This will be included in the release notes)
(Explain the changes in enough detail fo reviewers to understand.  Raise any questions for reviewers to consider.)
(List clear steps to test that the changes are working)

WIP: Troubleshooting Nightwatch Screenshot Upload Error

---

docs-site/src/pages/pattern-lab/_patterns/02-components/chip/05-chip.twig
docs-site/src/pages/pattern-lab/_patterns/02-components/chip/10-chip-with-web-component.twig
packages/components/bolt-chip/TESTING.md
packages/components/bolt-chip/__tests__/__snapshots__/chip.js.snap
packages/components/bolt-chip/__tests__/chip.js
packages/components/bolt-chip/chip.schema.yml
packages/components/bolt-chip/index.js
packages/components/bolt-chip/index.scss
packages/components/bolt-chip/package.json
packages/components/bolt-chip/src/chip.js
packages/components/bolt-chip/src/chip.scss
packages/components/bolt-chip/src/chip.twig
packages/core/utils/index.js
packages/core/utils/validate-props.js

http://vjira2:8080/browse/BDS-954
http://vjira2:8080/browse/BDS-1056
When i saw that this component doesn't have web component i added code for that and updated documentation and testing.
I add web component section. Update documentation and added test for this component.
Run this code locally and check if it passes all js test by using `npm test:js`

Adding documentation, testing and web component to bolt-chip component

---

packages/components/bolt-blockquote/src/blockquote.twig
packages/core-php/composer.json
packages/core-php/src/TwigExtensions/BoltCore.php
packages/core-php/src/TwigExtensions/BoltExtras.php
packages/core-php/src/TwigFunctions.php
packages/core-php/src/Utils.php

Reverts bolt-design-system/bolt#1041

Revert "Initialize props pattern"

---

package.json

Fix setup:php install

---

packages/components/bolt-background/README.md

- http://vjira2:8080/browse/BDS-814
Add max-width spec to background readme.
Review updates to [background readme](https://github.com/bolt-design-system/bolt/blob/ce9ff7fc9dd83c7efbde5df22b9219d7fbf5202c/packages/components/bolt-background/README.md).

Update background docs

---

docs-site/.boltrc.js
example-integrations/drupal-lab/web/themes/bolt-starter/.boltrc.js
example-integrations/drupal-lab/web/themes/bolt-starter/index.js
example-integrations/drupal-lab/web/themes/bolt-starter/index.scss
packages/build-tools/package.json
packages/uikit-workshop/src/scripts/components/pl-nav/pl-nav.scss
packages/uikit-workshop/src/scripts/components/pl-viewport/pl-viewport.js
packages/uikit-workshop/src/scripts/patternlab-pattern.js

N/A
Misc fixes to UIKit's page navigation, dependency update to the @bolt/build-tools package + updates to the Drupal Lab build config to address issues when watching the filesystem for changes.

Fix: Misc UIKit and Drupal Lab Bug Fixes

---

packages/components/bolt-card/__tests__/__snapshots__/card.js.snap
packages/components/bolt-figure/__tests__/__snapshots__/figure.js.snap
packages/components/bolt-video/__tests__/__snapshots__/video.js.snap
packages/components/bolt-video/__tests__/bolt-video.e2e.js
packages/components/bolt-video/src/_video-inline-script.twig
packages/components/bolt-video/src/_video-tag.twig
packages/components/bolt-video/src/video.standalone.js

- http://vjira2:8080/browse/BDS-1339
Same as #1180 but branched off of master.
n/a
n/a

Video bug fixes

---

packages/components/bolt-block-list/TESTING.md
packages/components/bolt-block-list/__tests__/__snapshots__/block-list.js.snap
packages/components/bolt-block-list/__tests__/block-list.js

http://vjira2:8080/browse/BDS-978
Jest testing block-list component
Adding Jest snapshot tests to the block-list component as well as adding a TESTING.md file
yarn test:js

Block-list | Docs | Testing and documentation for block-list component

---

packages/components/bolt-band/src/band.js

Dupe of #1277 but based off of `release/2.x`

Band | Bug | Hotfix: Remove extra space below background video in IE

---

docs-site/src/pages/pattern-lab/_patterns/04-pages/80-micro-journeys/20-connection.twig
docs-site/src/pages/pattern-lab/_patterns/04-pages/80-micro-journeys/22-connection-w-editor.twig
docs-site/src/pages/pattern-lab/_patterns/04-pages/80-micro-journeys/_editor-wrapper.twig
packages/editor/src/blocks.js
packages/editor/src/editor.js
packages/editor/src/index.scss
packages/editor/src/setup-bolt.js

Adds the connection custom element to the micro journey

Feature/micro journey  connection

---

docs-site/src/pages/pattern-lab/_patterns/02-components/svg-animations/05-svg-animations.twig
packages/components/bolt-svg-animations/src/svg-animations.js
packages/components/bolt-svg-animations/src/svg-animations.twig
packages/components/bolt-svg-animations/src/svg/automation.js
packages/components/bolt-svg-animations/src/svg/connectionBand.js
packages/components/bolt-svg-animations/src/svg/index.js
packages/components/bolt-svg-animations/src/svg/orbit.js
packages/components/bolt-svg-animations/src/svg/radar.js
packages/components/bolt-svg-animations/svg-animations.schema.yml

https://app.asana.com/0/1126340469288208/1137561697872881/f
New SVG Animation:  a single gradient band with moving arrows.  
This is the first version of the connection band SVG, which only uses a single stripe.   The only usable prop is for direction, speed and theme are unchanging.  
View the new animations in /pattern-lab/?p=viewall-components-svg-animations

ConnectionBand svg animation 

---

docs-site/src/pages/pattern-lab/_patterns/02-components/modal/00-modal-docs.twig
docs-site/src/pages/pattern-lab/_patterns/02-components/modal/05-modal.twig
docs-site/src/pages/pattern-lab/_patterns/02-components/modal/10-modal-width-variations.twig
docs-site/src/pages/pattern-lab/_patterns/02-components/modal/15-modal-spacing-variations.twig
docs-site/src/pages/pattern-lab/_patterns/02-components/modal/20-modal-theme-variations.twig
docs-site/src/pages/pattern-lab/_patterns/02-components/modal/25-modal-scroll-variations.twig
docs-site/src/pages/pattern-lab/_patterns/02-components/modal/30-modal-trigger-variations.twig
docs-site/src/pages/pattern-lab/_patterns/02-components/modal/35-modal-usage-javascript.twig
docs-site/src/pages/pattern-lab/_patterns/02-components/modal/40-modal-usage-image-and-caption.twig
docs-site/src/pages/pattern-lab/_patterns/02-components/modal/50-modal-usage-content.twig
docs-site/src/pages/pattern-lab/_patterns/02-components/modal/999-modal-with-web-component.twig
docs-site/src/pages/pattern-lab/_patterns/02-components/modal/custom-events/_modal-usage-custom-events.twig
packages/components/bolt-button/TESTING.md
packages/components/bolt-image/src/image.js
packages/components/bolt-link/__tests__/link.js
packages/components/bolt-link/src/link.twig
packages/components/bolt-modal/README.md
packages/components/bolt-modal/TESTING.md
packages/components/bolt-modal/modal.schema.yml
packages/components/bolt-modal/package.json
packages/components/bolt-modal/src/modal.scss
packages/components/bolt-nav-indicator/nav-indicator.js

- Rewrote Button component's manual testing instructions so they are up to date with testing pages. #1358 
- Better modal documentations and misc CSS enhancements #1319
- Fix broken Nav Indicator in IE11. #1310 
- Fixed a JavaScript issue with the Image component occasionally rendering before lazysizes has finished booting up. #1368 
- Updated the Link component to prevent duplicate IDs from getting added when passed along via the `attributes` object #1329

Bolt v2.6.0 Release

---

packages/micro-journeys/starters/cta-text-lorem.html
packages/micro-journeys/starters/index.js
packages/micro-journeys/starters/one-character-lorem.html
packages/micro-journeys/starters/two-characters-lorem.html

Just some lorem starter html for the interactive steps

feat: add lorem impsum starters for the step top and bottom

---

packages/micro-journeys/src/interactive-pathway.js

https://app.asana.com/0/1126340469288208/1140521098191989/f

fix(micro-journeys): prevent rapid click of steps from showing multiple steps

---

packages/micro-journeys/src/interactive-pathways.js

https://app.asana.com/0/1126340469288208/1126339089882457/f
Pathways being there animations when scrolled into view
On IE11 it just triggers it right away, otherwise it uses `IntersectionObserver` to efficiently watch for when it's scrolled into view
Open http://localhost:3000/pattern-lab/patterns/06-experiments-micro-journeys-combos--95-in-page-example/06-experiments-micro-journeys-combos--95-in-page-example.html
Scroll down to second pathway (in dark background) and note that you can see the animation of the first step

feature(micro-journeys): trigger pathways animation on scroll

---

docs-site/src/pages/pattern-lab/_patterns/02-components/accordion/32-accordion-inactive-variations.twig
docs-site/src/pages/pattern-lab/_patterns/02-components/accordion/40-accordion-content-variations.twig
package.json
packages/components/bolt-accordion/__tests__/__snapshots__/accordion.js.snap
packages/components/bolt-accordion/__tests__/accordion.js
packages/components/bolt-accordion/accordion.schema.yml
packages/components/bolt-accordion/src/AccordionItem/AccordionItemTrigger.js
packages/components/bolt-accordion/src/AccordionItem/accordion-item.scss
packages/components/bolt-accordion/src/AccordionItem/accordion-item.twig
packages/components/bolt-accordion/src/AccordionItem/index.js
packages/components/bolt-accordion/src/accordion.js

- http://vjira2:8080/browse/WWWD-4037
Add accordion `inactive` prop.

Hotfix: Add accordion inactive prop

---

packages/core/styles/02-tools/tools-themes/_tools.themes.scss

Introduce more documentation for `bolt-theme

feat(core-styles): add documentation to bolt-theme

---

packages/editor/src/setup-bolt.js
packages/micro-journeys/starters/cta-text-2.html
packages/micro-journeys/starters/cta-text-3.html
packages/micro-journeys/starters/cta-text-4.html
packages/micro-journeys/starters/cta-text-5.html
packages/micro-journeys/starters/cta-text-lorem.html
packages/micro-journeys/starters/one-character-1.html
packages/micro-journeys/starters/one-character-lorem.html
packages/micro-journeys/starters/steo-one-character-lorem.html
packages/micro-journeys/starters/steo-two-character-lorem.html
packages/micro-journeys/starters/two-characters-3.html

Micro Journey "Bolt-CTA" component needs to wrap the "Bolt-link"

fix: update all micro journey cta to use bolt link over text

---

docs-site/src/pages/pattern-lab/_patterns/02-components/tabs/40-tabs-use-case-tabbed-band.twig

N/A
Adds a Tabbed Band demo within the Tabs section of Pattern Lab.
Run the branch locally and proof read the Tabbed Band demo page.

Tabs | Docs | Tabbed Band demo

---

packages/with-without/with-without.scss

Fix title bar overlap
Deploy, verify the toggle does not encroach upon the content.

fix(with-without): fix title bar overflow

---

packages/editor/src/editor.twig

http://vjira2:8080/browse/WWWD-4094
Updates the Editor template to autoescape config data in a Drupal and Bolt-friendly way.

Fix: Update Editor Template

---

docs-site/src/pages/pattern-lab/_patterns/02-components/video/tests/-test-brightcove-video-player.twig

- http://vjira2:8080/browse/BDS-1615
Add demo page for testing videos in a standard Brightcove player
Review files changed. Does not change any video player code.

Video | QA | Add Brightcove player demo page

---

docs-site/src/pages/pattern-lab/_patterns/02-components/device-viewer/05-device-viewer.twig
docs-site/src/pages/pattern-lab/_patterns/02-components/device-viewer/10-device-viewer-ipad-variation.twig
docs-site/src/pages/pattern-lab/_patterns/02-components/device-viewer/15-device-viewer-iphone8-variation.twig
docs-site/src/pages/pattern-lab/_patterns/02-components/device-viewer/20-device-viewer-macbook-variation.twig
docs-site/src/pages/pattern-lab/_patterns/04-pages/15-d8-resource-details-pages/00-resource-details-page.twig
docs-site/src/pages/pattern-lab/_patterns/04-pages/45-d8-blog/00-blog-homepage.twig
packages/components/bolt-image/src/_image-lazy-sizes.js
packages/components/bolt-image/src/image.js
packages/components/bolt-image/src/image.twig

TBD
Fixes the re-rendering and flickering issues observed in the Image component + optimizes the resize handler for updating the `sizes` prop.
TBD
TBD

Fix: Image Component Re-rendering / Perf Fix

---

.autorc
auto-release.js

N/A
Add extra checks to the auto-release script + update the CLI args passed along to Auto when automatically publishing to NPM.

Chore: Update Release Script / CLI Args Used When Auto Publishing

---

docs-site/src/components/pattern-lab-hacks/pattern-lab-hacks.scss
docs-site/src/components/pattern-lab-utils/docs.twig
docs-site/src/components/pattern-lab-utils/schema-docs.twig

n/a
Update component schema layout to fit more content on screen.
Changes were pulled from #1286 and applied to `master`.
Checkout branch and view any component landing page. Review the new look of schema table and the widened page.

feat: update schema table layout to fit more onscreen

---

packages/uikit-polyfills/index.js
packages/uikit-workshop/package.json
packages/uikit-workshop/src/scripts/components/modal-styleguide.js
packages/uikit-workshop/src/scripts/patternlab-pattern.js
packages/uikit-workshop/src/scripts/patternlab-viewer.modern.js

N/A
Handful of cross browser JS fixes (IE 11 mostly) I ran into the need for while testing out the ES Module-related work in https://github.com/boltdesignsystem/bolt/pull/1579.
Also includes the Edge polyfill issue fixed upstream in https://github.com/pattern-lab/patternlab-node/pull/1105

Pattern Lab UIKit Cross Browser Fixes

---

docs-site/.boltrc.js
docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-academy/15-search-results-t1a.twig
docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-academy/15-search-results-t1b.twig
docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-academy/15-search-results-t1c.twig
docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-academy/includes/_archived-text.twig
docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-academy/includes/_back-link.twig
docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-academy/includes/_card-list.twig
docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-academy/includes/_card.twig
docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-academy/includes/_chips--search-filter.twig
docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-academy/includes/_form--search-filter.twig
docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-academy/includes/_hero--archived.twig
docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-academy/includes/_hero.twig
docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-academy/includes/_nav--search.twig
docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-academy/includes/_pagination.twig
docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-academy/includes/_promo.twig

http://vjira2:8080/browse/BDS-1896
First pass at Search Results template using only existing Bolt components.
Added my notes to http://vconfluence2:8080/display/PEGAKIT/Academy+Design+UI
- Review new templates:
- [Search T1a](https://epic-academy-search.boltdesignsystem.com/pattern-lab/patterns/04-pages-55-d8-academy-15-search-results-t1a/04-pages-55-d8-academy-15-search-results-t1a.html)
- [Search T1b](https://epic-academy-search.boltdesignsystem.com/pattern-lab/patterns/04-pages-55-d8-academy-15-search-results-t1b/04-pages-55-d8-academy-15-search-results-t1b.html)
- [Search T1c](https://epic-academy-search.boltdesignsystem.com/pattern-lab/patterns/04-pages-55-d8-academy-15-search-results-t1c/04-pages-55-d8-academy-15-search-results-t1c.html)

Academy | FE | Search Results template

---

docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-academy/15-search-results-t1a.twig
docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-academy/15-search-results-t1b.twig
docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-academy/15-search-results-t1c.twig
docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-academy/includes/_form--search-filter.twig
docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-academy/includes/_hero--archived.twig
docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-academy/includes/_hero.twig
docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-academy/includes/_nav--search.twig
docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-academy/includes/_search-bar.twig
packages/components/bolt-page-header/src/page-header.twig

http://vjira2:8080/browse/BDS-1896
Incorporate feedback from meeting with Academy team.
Review code, call out any issues before we merge into epic branch.

Epic/academy  search edits

---

packages/components/bolt-code-snippet/src/code-snippet.standalone.js
packages/components/bolt-navbar/src/navbar.scss

N/A
Fixes a minor issue with the Navbar's vertical alignment of Icons + adds the requested support for SQL and Java to the Code Snippet component.

Fix Navbar Vertical Alignment + Add Java / SQL Support to Code Snippets

---

docs-site/src/components/schema-form/schema-form.js
packages/base-element/src/BoltActionElement.js
packages/components/bolt-blockquote/src/blockquote.js
packages/components/bolt-copy-to-clipboard/src/copy-to-clipboard.standalone.js
packages/components/bolt-device-viewer/src/device-viewer.standalone.js
packages/components/bolt-dropdown/dropdown.js
packages/components/bolt-figure/src/figure.js
packages/components/bolt-icon/src/icon.standalone.js
packages/components/bolt-image/src/image.js
packages/components/bolt-modal/src/modal.js
packages/components/bolt-nav-priority/nav-priority.js
packages/components/bolt-navlink/navlink.js
packages/components/bolt-placeholder/placeholder.standalone.js
packages/components/bolt-ratio/src/ratio.js
packages/components/bolt-stack/src/stack.js
packages/components/bolt-text/src/text.js
packages/components/bolt-video/src/video.standalone.js
packages/micro-journeys/src/interactive-pathways.js
packages/micro-journeys/src/two-character-layout.js

N/A
Internal web component updates that surfaced while working on https://github.com/boltdesignsystem/bolt/pull/1579.
These updates are almost entirely comprised of fixing constructor / event lifecycle-related issues encountered while working and testing out the ES Module work.
- Briefly review component changes
- Confirm tests pass as expected

ES Modules: Internal Component Updates

---

auto-release.js

n/a
Manually fix eslint errors not fixable with `--fix` and a few that are.
Review file changed.

fix: eslint errors not fixable with --fix

---

packages/components/bolt-list/src/_list-item.scss

http://vjira2:8080/browse/BDS-1957
Small CSS update to List based on Mission Landing template build
- moved border to right side
- updated the List's border color to now use the `bolt-theme` function + opacity.
- Double check List demos in PL

Academy-related List Component CSS Update

---

packages/components/bolt-nav-indicator/index.js
packages/components/bolt-nav-priority/index.js
packages/components/bolt-navlink/index.js

http://vjira2:8080/browse/BDS-1967?filter=-1
Cleans up the dynamic imports used by a few components. No functional changes - just helps us keep track of each component's loading strategy + see what's loading via the chunk name we're specifying.

Minor Dynamic Import Cleanup

---

packages/components/bolt-code-snippet/src/_code-snippet-base.scss

http://vjira2:8080/browse/BDS-1970
CSS update to the Code Snippet component that was left over from the initial Card refactor work. 
Is this worth keeping around?
- Review updates + latest Code Snippet demos. I can't 100% remember where this update was needed the most however I'm sure it had something to do with some of our custom component docs in PL.

Code Snippet Wrapping / Scrolling Updates

---

packages/components/bolt-card-replacement/src/card-replacement/card-replacement.js

N/A
Fixes some lint errors on the `master` branch.
Pull the branch down and run the lint command in terminal to make sure nothing else needs to be fixed.

Fix: card replacement lint errors

---

packages/experimental/editor/src/editor.js

Remove a stray console.log that get merged here: https://github.com/boltdesignsystem/bolt/pull/1685

chore(editor): remove console log

---

packages/experimental/editor/src/editor.js

Version of #1716 rebased for hotfix.

Fix Step removal event not firing due to removal of Animate parent

---

docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/collections/dashboard/_dashboard-band--my-missions.twig
docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/collections/dashboard/_dashboard-band.twig
docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/dashboard/dashboard--my-missions/dashboard--my-missions.md
docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/dashboard/dashboard--my-missions/dashboard--my-missions.twig
docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/dashboard/dashboard/dashboard-add-mission.md
docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/dashboard/dashboard/dashboard~add-mission.json

http://vjira2:8080/browse/BDS-1976
Add "My Mission" and "Add Mission" templates.
See ticket for Invision links.
- Review files changes
- Review templates in Pattern Lab:
- Dashboard (My Missions)
- Dashboard (Add Mission)

feat: add "My Missions" and "Add Mission" templates

---

docs-site/src/pages/pattern-lab/_patterns/01-visual-styles/00-color-palette/04-theming.twig
docs-site/src/pages/pattern-lab/_patterns/01-visual-styles/00-color-palette/_color-swatch.scss

N/A
Adds a theme colors reference page.
Created a table for developers and designers to reference the current theme colors.
Run the branch locally and check the Theming page under Color Palette.

Theming | Docs | Add theme colors demo page

---

packages/experimental/editor/src/editor.js
packages/experimental/micro-journeys/src/interactive-pathway.js
packages/experimental/micro-journeys/src/interactive-step.js

Fix micro journey up and down buttons

---

docs-site/src/pages/pattern-lab/_patterns/02-components/headline/05-headline.twig
docs-site/src/pages/pattern-lab/_patterns/02-components/headline/10-headline-tag-variations.twig
docs-site/src/pages/pattern-lab/_patterns/02-components/headline/15-headline-align-variations.twig
docs-site/src/pages/pattern-lab/_patterns/02-components/headline/20-headline-style-and-weight-variations.twig
docs-site/src/pages/pattern-lab/_patterns/02-components/headline/25-headline-icon-variations.twig
packages/components/bolt-headline/src/_tools.headlines.scss
packages/components/bolt-headline/src/headline.scss

N/A
Fixes a bug where the body text is using the headline text color.
1. Updated CSS to fix the color.
2. Updated incorrect headline docs.
Run the branch locally and view the headline component docs, make sure regular text is black and headline is indigo.

Fix: body text color

---

example-integrations/angular/.bolt/package.json
example-integrations/angular/.bolt/yarn.lock
example-integrations/angular/yarn.lock

(Enter a link to the Jira issue this PR applies to, if any)
(Enter a one-line summary of the changes in this PR.  This will be included in the release notes)
(Explain the changes in enough detail fo reviewers to understand.  Raise any questions for reviewers to consider.)
(List clear steps to test that the changes are working)

fix bolt core package name, update yarn.lock

---

docs-site/src/pages/docs/50-guides/15-building-a-new-component.md

[DS-102](https://pegadigitalit.atlassian.net/browse/DS-102)
Expanded upon existing documentation for creating a new component.
After creating a new component I have some feedback on how we might update the relevant documentation based on instruction from the DS team. What I have added here should help mitigate the particular points where I stumbled for anyone else taking this on. 
View the docs page [here](https://boltdesignsystem-g9u5csig7.vercel.app/docs/guides/building-a-new-component.html), and review what was added (everything below the second paragraph).

DS-102: Expand new-component docs

---

packages/components/bolt-accordion/accordion-item.schema.js
packages/components/bolt-action-blocks/action-blocks.schema.js
packages/components/bolt-blockquote/blockquote.schema.js
packages/components/bolt-copy-to-clipboard/copy-to-clipboard.schema.js
packages/components/bolt-grid/grid.schema.js
packages/components/bolt-headline/headline.schema.js
packages/components/bolt-image/image.schema.js
packages/components/bolt-logo/logo.schema.js
packages/components/bolt-navlink/navlink.schema.js
packages/components/bolt-table/table.schema.js
packages/experimental/editor/src/setup-bolt.js

n/a
Run `yarn fix`
Tests are passing. Review changes.

Lint fixes

---

.autorc
.github/PULL_REQUEST_TEMPLATE.md

https://pegadigitalit.atlassian.net/browse/DS-106
Minor cleanup that came up while discussing DS-106.
- Replaces Salem's name with the Bolt bot for release commits
- Adds a new "Release notes" section to the Github PR template.  See the 'Read more' link for why this is important.

DS-106 PR and release workflow housekeeping

---

docs-site/src/pages/pattern-lab/_patterns/02-components/modal/52-modal-usage-gated.twig
docs-site/src/pages/pattern-lab/_patterns/02-components/modal/52-modal-usage-persistent.twig
packages/components/bolt-modal/__tests__/__snapshots__/modal.js.snap
packages/components/bolt-modal/modal.schema.js
packages/components/bolt-modal/src/modal.js
packages/components/bolt-modal/src/modal.scss

https://pegadigitalit.atlassian.net/browse/DS-142
Updated the modal to supported being a gated modal
- Added a gated modal schema option
- Gated option disables close functionality and hides the close button
- Provides an example for a return button
1. Navigate to https://feature-ds-142.boltdesignsystem.com/pattern-lab/?p=components-modal-usage-gated
2. Open the model
3. Observe that there is a link present in the modal labeled "No thanks! Return to last page"
4. Observe there is not a close button
5. Click off the modal
6. Observe that the modal does not close and the cursor does not change to a pointer.

DS-142: Security Modal: "Unlocking" content with webform

---

docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-calculator/00-d8-calculator.twig

Fixes calculator landing page form field alignment and markup.
1. Updates form fields to top align.
1. Limits % field to max 3 digits.
1. Updates grid and grid cell to be custom list and list item.
Run the branch locally and make sure the calculator landing is displaying and behaving as expected.

DS-160: calculator quick follows

---

.travis.yml
packages/testing/testing-nightwatch/nightwatch.js
scripts/package.json

Updated the chrome driver version to 83
See if the Travis build works

Updated the Chromedriver version to the supported number

---

packages/components/bolt-stack/src/stack.js

[https://pegadigitalit.atlassian.net/browse/DS-197](https://pegadigitalit.atlassian.net/browse/DS-197)
Update bolt-stack to the newest renderer
In an attempt to make bolt more uniform, I am updating bolt-stack to use the latest renderer like many of the other components.
Check the code, and check the stack demo page to make sure both are up to par.

DS-197: Update Stack to the latest renderer.

---

packages/components/bolt-placeholder/placeholder.standalone.js
packages/components/bolt-placeholder/placeholder.twig

[https://pegadigitalit.atlassian.net/browse/DS-225](https://pegadigitalit.atlassian.net/browse/DS-225)
Update Placeholder to the latest renderer
Update Placeholder to the latest renderer
To test the conversion:
- Test placeholder demos

DS-225: Placeholder Renderer Conversion

---

packages/components/bolt-video/brightcove/_video.scss

CSS adjustments to fix display bugs with the social panel overlay

Brightcove CSS Update

---

packages/components/bolt-image/src/image.js
packages/components/bolt-link/src/link.js

[https://pegadigitalit.atlassian.net/browse/DS-290](https://pegadigitalit.atlassian.net/browse/DS-290)
Updated image and link constructors to fit our standards.
These were out of date and likely not functioning as intended. I updated the constructors on both of these elements to match our modern standards. 
Read the code and check patternlab.

DS-290: Update Constructor on image and link

---

packages/components/bolt-banner/src/banner.scss
packages/components/bolt-button/src/button.scss
packages/components/bolt-menu/src/_menu-item.scss
packages/components/bolt-menu/src/menu.scss
packages/components/bolt-stack/src/stack.scss

https://pegadigitalit.atlassian.net/browse/DS-292
Fixes a bug where `:host` combined with `[attribute]` CSS was not working as expected.
Updated some instances of `:host[*]` to `:host([*])`.
Run the branch locally and check banner, button, menu, and stack docs.

DS-292 Fix `:host` and `[attribute]` css

---

packages/components/bolt-typeahead/__tests__/typeahead.e2e.js

https://pegadigitalit.atlassian.net/browse/DS-238
Commenting out [failing Nightwatch test](https://travis-ci.com/github/boltdesignsystem/bolt/jobs/469689924#L941) and try `v3.0.0` release again.

DS-238: Comment-out failing Nightwatch test

---

docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/00-color/10-theming-system.twig
docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/00-color/_color-swatch.scss
docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/05-spacing/_spacing.scss
docs-site/src/pages/pattern-lab/_patterns/50-pages/99999-bolt-dev-sandbox/_wip-global-search.twig
docs-site/src/pages/pattern-lab/_patterns/50-pages/99999-bolt-dev-sandbox/styles/_global-search.scss
docs-site/src/pages/pattern-lab/_patterns/50-pages/99999-bolt-dev-sandbox/styles/index.scss

Updates theming and color docs to reflect the latest CSS vars.
Updated the doc page and some PL CSS that's using `bolt-theme()`.
Run the branch locally and read the Theming System doc page.

Docs: fix pattern lab theming and color docs

---

.github/PULL_REQUEST_TEMPLATE.md

https://pegadigitalit.atlassian.net/browse/DS-307
Add section for visual changes to PR template.
Add a section to the PR template so we can track visual changes associated with each PR. Then, it will be easier to track visual changes that need to be relayed to the QA team for VRT.
Review file changed.

DS-307 Add section for visual changes to PR template

---

packages/elements/bolt-button/package.json
packages/elements/bolt-text-link/package.json

n/a
Make Button and Text Link elements packages public.

Make button and text-link public

---

docs-site/src/pages/pattern-lab/_patterns/40-components/accordion/40-accordion-content-variations.twig
docs-site/src/pages/pattern-lab/_patterns/40-components/card/35-card-replacement-with-video.twig
docs-site/src/pages/pattern-lab/_patterns/40-components/card/999-card-replacement-with-web-component.twig
docs-site/src/pages/pattern-lab/_patterns/40-components/carousel/25-carousel-basic-variations.twig
docs-site/src/pages/pattern-lab/_patterns/40-components/device-viewer/25-device-viewer-video.twig
docs-site/src/pages/pattern-lab/_patterns/40-components/figure/10-figure-media-variations.twig
docs-site/src/pages/pattern-lab/_patterns/40-components/modal/45-modal-usage-video.twig
docs-site/src/pages/pattern-lab/_patterns/40-components/tabs/30-tabs-content.twig
docs-site/src/pages/pattern-lab/_patterns/40-components/teaser/25-teaser-type-and-time.twig
docs-site/src/pages/pattern-lab/_patterns/50-pages/10-d8-product-pages/product-t4.twig
docs-site/src/pages/pattern-lab/_patterns/50-pages/50-d8-careers/00-careers-homepage.twig
docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/05-pages/t2-inner-pages/topic-details/acd-topic-detail-page.twig
docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-gallery.twig
docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-homepage.twig
docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-listing-customers.twig
docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-listing-pegaworld.twig
docs-site/src/pages/pattern-lab/_patterns/60-experiments/editor/20-editor-modal.twig
packages/components/bolt-video/brightcove/_video.scss
packages/website-ui/styleguidekit-twig-default/views/partials/general-footer.twig

https://pegadigitalit.atlassian.net/browse/WWW-465
Merging in all the Brightcove control CSS adjustments and updating the doc site to use the QA video pllayer
* Updated the docs sites with the QA video
* Updated the video.scss file with the latest Brightcove styling
Review the Doc site and make sure that the videos are playing (you can see where the videos are in the "Files Changes" tab)

Brightcove Adjustments (WWW-465)

---

packages/core-v3.x/styles/02-tools/tools-visuallyhidden/_tools-visuallyhidden.scss

https://pegadigitalit.atlassian.net/browse/DS-422
Fix visual issues on input on Safari.
Updating the input `z-index` css styles.
1. Open Safari browser
2. Go to https://boltdesignsystem.com/pattern-lab/patterns/40-components-form-35-form-element-demo-checkbox-fieldset/40-components-form-35-form-element-demo-checkbox-fieldset.html
3. Check if you can reproduce the issue mentioned in https://pegadigitalit.atlassian.net/browse/PP-244
4. Go to https://bugfix-ds-422-safari-search-facet-texts-n.boltdesignsystem.com/pattern-lab/patterns/40-components-form-35-form-element-demo-checkbox-fieldset/40-components-form-35-form-element-demo-checkbox-fieldset.html
5. Check if the issue still exists, if not we are good to go.

Fix issues with checkboxes on Safari browser

---

packages/core-v3.x/styles/02-tools/tools-visuallyhidden/_tools-visuallyhidden.scss

https://pegadigitalit.atlassian.net/browse/DS-422
Fix visual issues on input on Safari.
Updating the input `z-index` css styles.
1. Open Safari browser
2. Go to https://boltdesignsystem.com/pattern-lab/patterns/40-components-form-35-form-element-demo-checkbox-fieldset/40-components-form-35-form-element-demo-checkbox-fieldset.html
3. Check if you can reproduce the issue mentioned in https://pegadigitalit.atlassian.net/browse/PP-244
4. Go to https://bugfix-ds-422-safari-search-facet-texts-n.boltdesignsystem.com/pattern-lab/patterns/40-components-form-35-form-element-demo-checkbox-fieldset/40-components-form-35-form-element-demo-checkbox-fieldset.html
5. Check if the issue still exists, if not we are good to go.

Updating the z-index

---

packages/components/bolt-button/src/button.twig

[https://pegadigitalit.atlassian.net/browse/DS-371](https://pegadigitalit.atlassian.net/browse/DS-371)
Standardize Twig and Schema for Button
Standardize Twig and Schema for Button
Check out the tests and demos and make sure nothing is a breaking change.

DS-371: Standardize Twig and Schema (Button)

---

packages/components/bolt-video/brightcove/_video.scss

https://pegadigitalit.atlassian.net/browse/DS-384
Updated the CSS to work with the DS-384 Brightcove Plugin work
https://gitlab.com/pegadigitalpublic/brightcove-player/-/merge_requests/3

DS-384: Brightcove Language Order

---

packages/base-element/src/lib/decorators/json-schema-props.js
packages/components/bolt-listing-teaser/src/listing-teaser.twig

n/a
- Fix button size bug on BOC template: https://github.com/boltdesignsystem/bolt/pull/2184
- Fix auto-escaping issues on Listing Teaser component: https://github.com/boltdesignsystem/bolt/pull/2186

Hotfix v3.5.4

---

docs-site/src/pages/pattern-lab/_patterns/40-components/device-viewer/30-device-viewer-content-magnifier-modal.twig
docs-site/src/pages/pattern-lab/_patterns/40-components/modal/05-modal.twig
docs-site/src/pages/pattern-lab/_patterns/40-components/modal/10-modal-width-variations.twig
docs-site/src/pages/pattern-lab/_patterns/40-components/modal/15-modal-spacing-variations.twig
docs-site/src/pages/pattern-lab/_patterns/40-components/modal/20-modal-theme-variations.twig
docs-site/src/pages/pattern-lab/_patterns/40-components/modal/25-modal-scroll-variations.twig
docs-site/src/pages/pattern-lab/_patterns/40-components/modal/30-modal-trigger-variations.twig
docs-site/src/pages/pattern-lab/_patterns/40-components/modal/35-modal-usage-javascript.twig
docs-site/src/pages/pattern-lab/_patterns/40-components/modal/40-modal-usage-image-and-caption.twig
docs-site/src/pages/pattern-lab/_patterns/40-components/modal/45-modal-usage-video.twig
docs-site/src/pages/pattern-lab/_patterns/40-components/modal/50-modal-usage-content.twig
docs-site/src/pages/pattern-lab/_patterns/40-components/modal/52-modal-usage-persistent.twig
docs-site/src/pages/pattern-lab/_patterns/40-components/modal/55-modal-usage-form.twig
docs-site/src/pages/pattern-lab/_patterns/40-components/modal/999-modal-with-web-component.twig
docs-site/src/pages/pattern-lab/_patterns/40-components/trigger/35-trigger-advanced-usage.twig
docs-site/src/pages/pattern-lab/_patterns/50-pages/55-d8-calculator/00-d8-results.twig
docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/05-pages/t1-landing-pages/certification-exam/acd-certification-exam-page.twig
docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/05-pages/t2-inner-pages/topic-details/acd-topic-detail-page.twig
docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-listing-customers.twig
docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-listing-pegaworld.twig
docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-quick-filters.twig
docs-site/src/pages/pattern-lab/_patterns/60-experiments/editor/20-editor-modal.twig
packages/components/bolt-listing-teaser/package.json
packages/components/bolt-trigger/__tests__/trigger.e2e.js
yarn.lock

https://pegadigitalit.atlassian.net/browse/DS-407
Update Modal demos and docs to use the `[data-bolt-modal-target]` convention. Update copy in demos.
I updated the Modal component demos and instances of Modal in other component demos and "Pages". I also updated some of the copy in the Modal component docs to reflect the new recommended convention.
> Note: fixes a [Listing Teaser dependency bug](https://github.com/boltdesignsystem/bolt/pull/2193/files#diff-dc47f6b3774425192c0192d558ad761b8a5bc1689442d96a3533ffbf643ca20eL20) which was required to get e2e tests to pass.
- Review [Modal docs](https://feature-ds-407-update-modal-docs-demos.boltdesignsystem.com/pattern-lab/?p=viewall-components-modal). Verify modals still toggle as expected. Review copy changes.
- Review other modified …

DS-407: Update modal demos to use [data-bolt-modal-target] convention

---

auto-release.js

Try increasing `maxBuffer` to `Infinity`. See #2202.

Release 3.6.0

---

auto-release.js

Attempt to fix auto-release bug

Release 4.0.0

---

docs-site/src/templates/homepage.twig
packages/components/bolt-navbar/src/navbar.scss

Includes: https://github.com/boltdesignsystem/bolt/pull/2242

Hotfix v4.0.1

---

packages/components/bolt-toolbar/toolbar.scss
packages/components/bolt-toolbar/toolbar.twig

https://pegadigitalit.atlassian.net/browse/DS-539
The Toolbar component ws updated, so that when there is a long breadcrumb the items on the right (download, share) do not wrap and align at the top of the container.
Above “medium” breakpoint Toolbar items do not wrap and are aligned to the top of the toolbar.
https://user-images.githubusercontent.com/85670248/124731768-d3c15400-df12-11eb-8ef6-b757978b73b8.mov
Check if items on the right (download, share) behave properly above and below `medium` breakpoint.

DS-539 Fix toolbar buttons alignment

---

docs-site/src/pages/pattern-lab/_patterns/999-tests/navbar/05-navbar-with-active-link.twig
docs-site/src/pages/pattern-lab/_patterns/999-tests/navbar/22-navbar-title-tags.twig
packages/components/bolt-band/band.schema.js
packages/components/bolt-navbar/src/navbar-li.twig
packages/components/bolt-navbar/src/navbar.scss
packages/twig-integration/twig-extensions-shared/src/Utils.php

Navbar bugfixes for 4.0. Includes:
- https://github.com/boltdesignsystem/bolt/pull/2271
- https://github.com/boltdesignsystem/bolt/pull/2268
- https://github.com/boltdesignsystem/bolt/pull/2270

Hotfix v4.0.2

---

docs-site/src/pages/pattern-lab/_patterns/40-components/page-header/05-page-header.twig
docs-site/src/pages/pattern-lab/_patterns/40-components/page-header/_main-site-page-header.twig
packages/components/bolt-page-header/page-header-nav-li.schema.js
packages/components/bolt-page-header/page-header-nav-ul.schema.js
packages/components/bolt-page-header/page-header.schema.js
packages/components/bolt-page-header/src/_page-header-desktop.scss
packages/components/bolt-page-header/src/page-header-nav-li.twig
packages/components/bolt-page-header/src/page-header-nav-ul.twig
packages/components/bolt-page-header/src/page-header.scss
packages/components/bolt-page-header/src/page-header.twig

https://pegadigitalit.atlassian.net/browse/DS-576
Cherry-pick https://github.com/boltdesignsystem/bolt/pull/2286 for `4.x`, resolve conflicts.
- Verify files changed are expected
- Especially review [page-header.twig](https://github.com/boltdesignsystem/bolt/pull/2289/files#diff-12ba7639b64374bb2fffb6e0654162b0df442ab338b66a6696fb1939beb9e0c0) which had conflicts

DS-576 fix static page header dropdown position

---

docs-site/src/pages/pattern-lab/_patterns/999-tests/icon/05-element-performance-test.twig
docs-site/src/pages/pattern-lab/_patterns/999-tests/icon/10-component-performance-test.twig

https://pegadigitalit.atlassian.net/browse/DS-262
Added an Icon Element and an Icon Component performance test page to the test folder.
No testing needed, this is just for running performance tests

DS-262: Bolt Icon Performance review

---

docs-site/src/pages/pattern-lab/_patterns/999-tests/code-snippet/15-code-snippet-table.twig
packages/components/bolt-code-snippet/index.js
packages/components/bolt-code-snippet/src/code-snippet.js
packages/components/bolt-table/package.json
packages/components/bolt-table/src/table.js
packages/components/bolt-teaser/__tests__/__snapshots__/teaser.js.snap
packages/components/bolt-teaser/src/teaser.scss
packages/components/bolt-teaser/src/teaser.twig

- https://github.com/boltdesignsystem/bolt/pull/2373
- https://github.com/boltdesignsystem/bolt/pull/2372

Hotfix v4.6.2

---

docs-site/src/pages/pattern-lab/_patterns/40-components/switch-button/00-switch-button-docs.twig
docs-site/src/pages/pattern-lab/_patterns/40-components/switch-button/05-switch-button.twig
docs-site/src/pages/pattern-lab/_patterns/999-tests/switch-button/switch-button-id.twig
packages/base-starter-kit/.boltrc.js
packages/base-starter-kit/package.json
packages/components/bolt-switch-button/README.md
packages/components/bolt-switch-button/__tests__/__snapshots__/switch-button.js.snap
packages/components/bolt-switch-button/__tests__/switch-button.js
packages/components/bolt-switch-button/index.scss
packages/components/bolt-switch-button/package.json
packages/components/bolt-switch-button/src/switch-button.scss
packages/components/bolt-switch-button/src/switch-button.twig
packages/components/bolt-switch-button/switch-button.schema.js
yarn.lock

https://pegadigitalit.atlassian.net/browse/DS-590
Adds a new component, Switch Button, which handles boolean UI functions that happens instantly.
1. Added new component, Jest test and docs.
2. Only bare minimum props are created to handle basic needs for the notifications project. We can expand on this component down the road.
Run the branch locally and proof read the Switch Button docs. Make sure the docs are intuitive. Inspect the demo and change on/off to some other language that might be longer, make sure it looks ok. Then check the component code for any mistakes in the code.

DS-590 Switch button component

---

docs-site/src/pages/pattern-lab/_patterns/40-components/chip/30-chip-color-variations.twig
packages/components/bolt-background/src/background-item.twig
packages/components/bolt-chip/chip.schema.js
packages/components/bolt-chip/src/chip.js
packages/components/bolt-chip/src/chip.scss
packages/components/bolt-chip/src/chip.twig

* Updated the Bolt Background lazy load conditional to default to lazy  (https://github.com/boltdesignsystem/bolt/pull/2394)
* Updated the Chip background color to include gray (https://github.com/boltdesignsystem/bolt/pull/2396)

Release v4.8.1: Background Image and Chip Color Update

---

docs-site/src/pages/pattern-lab/_patterns/999-tests/video/30-video-autoplay-on-viewport.twig

Fixed a typo on the video testing pages
Pull the branch and confirm all the videos are present on the /pattern-lab/?p=tests-video-autoplay-on-viewport page

Ratio Element Typo Fix

---

docs-site/src/pages/pattern-lab/_patterns/999-tests/tooltip/15-tooltip-link-whitespace.twig
packages/components/bolt-popover/src/popover.js
packages/components/bolt-tooltip/src/tooltip.js
scripts/deploy-tagged-release.js
scripts/package.json

- https://github.com/boltdesignsystem/bolt/pull/2426
- https://github.com/boltdesignsystem/bolt/pull/2430

Hotfix v5.2.1

---

packages/components/bolt-modal/src/modal.scss
packages/components/bolt-page-footer/src/page-footer-nav-li.twig
packages/components/bolt-page-footer/src/page-footer-nav-ul.twig
packages/components/bolt-page-footer/src/page-footer.scss
packages/components/bolt-page-footer/src/page-footer.twig

- https://github.com/boltdesignsystem/bolt/pull/2433
- https://github.com/boltdesignsystem/bolt/pull/2434

Hotfix v5.2.2

---

packages/testing/testing-nightwatch/package.json
scripts/package.json
yarn.lock

- I updated the version dependency in both places,
- then i ran yarn to update yarn.lock
☞𖤐☜

update chromedriver to 98.0.0

---

packages/layouts/bolt-holy-grail/package.json
packages/layouts/bolt-holy-grail/src/holy-grail.js
yarn.lock

[https://pegadigitalit.atlassian.net/browse/DS-442](https://pegadigitalit.atlassian.net/browse/DS-442)
We want to remember the user's preference when interacting with the holy grail side nav.
I added a cookie library to the holy grail layout and used it to set and get a cookie that will show or hide the side nav based on previous user interaction.
- Use a cookie manager to confirm the cookie is being set after interaction with the element.
- confirm that this is the desired behavior by interacting with the element and refreshing the page.

DS-442: Holy Grail Layout Cookie

---

packages/components/bolt-navbar/src/navbar-menu.scss
packages/components/bolt-navbar/src/overflow-menu.js

https://pegadigitalit.atlassian.net/browse/DS-612
The mobile navbar icon ("chevron-down") is updated to the 3 vertical dots ("more").
The "Chevron-down" icon was replaced with the "More" icon
Pull the branch. Go to navbar component `/pattern-lab/?p=viewall-components-navbar`. Confirm that displaying the "three dots" icon on small screens is correct.
The "Chevron-down" icon is replaced with the "More" icon.

DS-612 Update the navbar mobile icon

---

docs-site/src/pages/pattern-lab/_patterns/40-components/profile/15-profile-avatar-edit-button.twig
packages/components/bolt-profile/package.json
packages/components/bolt-profile/profile-avatar-edit-button.schema.js
packages/components/bolt-profile/profile.schema.js
packages/components/bolt-profile/src/profile-avatar-edit-button.twig
packages/components/bolt-profile/src/profile.scss
packages/components/bolt-profile/src/profile.twig
packages/components/bolt-tabs/src/tabs.js

- https://github.com/boltdesignsystem/bolt/pull/2529
- https://github.com/boltdesignsystem/bolt/pull/2531

Hotfix v5.7.1

---

docs-site/src/pages/pattern-lab/_patterns/40-components/profile/15-profile-avatar-edit-button.twig
docs-site/src/pages/pattern-lab/_patterns/999-tests/profile/00-profile-edit.twig
packages/components/bolt-profile/src/profile-avatar-edit-button.twig

https://github.com/boltdesignsystem/bolt/pull/2534

Hotfix v5.7.2

---

docs-site/src/pages/pattern-lab/_patterns/999-tests/profile/00-profile-edit.twig
packages/components/bolt-profile/src/profile.scss

https://pegadigitalit.atlassian.net/browse/DS-850
Fixes bug where user can't hover over bottom half of the avatar edit button because the "action" block covers it up.
Fix by adding `z-index: 1` to avatar block.
- Review code
- View demo

DS-850: Fix edit button z-index bug

---

docs-site/src/pages/pattern-lab/_patterns/999-tests/profile/00-profile-edit.twig
packages/components/bolt-profile/src/profile.scss
packages/components/bolt-profile/src/profile.twig

- https://github.com/boltdesignsystem/bolt/pull/2536
- https://github.com/boltdesignsystem/bolt/pull/2538

Hotfix v5.7.3

---

docs-site/src/pages/pattern-lab/_patterns/999-tests/teaser/05-teaser-video.twig
docs-site/src/pages/pattern-lab/_patterns/999-tests/teaser/10-teaser-video-card.twig

https://pegadigitalit.atlassian.net/browse/WWW-1554
Created a test page to double check the display behavior for the teaser card with a 
Pull down the branch and confirm the pages display (nothing particular to test here as this is just being used as an example/reference page).

Enhance Teaser Functionality

---

docs-site/src/pages/pattern-lab/_patterns/999-tests/popover/15-popover-disconnected-callback.twig
packages/components/bolt-popover/src/popover.js
packages/components/bolt-tooltip/src/tooltip.js

- https://github.com/boltdesignsystem/bolt/pull/2546

Hotfix v5.7.4

---

.gitlab.ci.yml

https://pegadigitalit.atlassian.net/browse/DS-779
Added the `.gitlab-ci.yml` file to the root.
This PR is in preparation of the repository migration. This will replace Travis when we move off of GitHub.

[6.x] DS-779: Bolt Gitlab CI/CD
