- .travis.yml
This adjusts a few things I saw in the Travis build process:
- Ensure that a successful compile and a failed deploy will mark the CI build as failed. [See here for example](https://travis-ci.org/bolt-design-system/bolt/builds/313187189#L1515)
- This is fixed by moving the deploy step from `after_success` (which can't fail and mark as failed as the build has already been marked as a success) to the `install` step after a successful build, done via `npm run build && npm run deploy`
- Not globally installing some npm modules (gulp, lerna, now, webpack) as they are installed locally from `package.json` and the CLIs get added to `$PATH` when used via `npm run`. Results in a sightly faster CI build.
- Not installing and configuring yarn since we're not using it yet
- Bumping up node version …
> CI build improvements - deploy / false positives, speed

- build-tools/gulp-tasks/build-webpack/webpack.js
This refactors the gulp webpack watch task from gulp watching and then running a full webpack compile to having webpack handling the watching and being able to compile from in-memory. This changed the time from around a 9s webpack recompile to less than a half second.
This was branched off [PR 234: Minimizing output of webpack compiles when in dev mode](https://github.com/bolt-design-system/bolt/pull/234) so it includes code from that as well.
> Faster webpack watch

- build-tools/gulp-tasks/build-webpack/webpack.js
I want to improve the signal to noise ratio in the command line output. Here's a simple start: this PR changes this output:
```
[14:45:38] Starting 'webpack:dev'...
[14:45:47] [es6Pipeline] Hash: b5d2d0ca3749ddd699fe
Version: webpack 3.10.0
Time: 8472ms
Asset     Size  Chunks             Chunk Names
0.chunk.js.map   134 kB       0  [emitted]
0.chunk.js   138 kB       0  [emitted]
2.chunk.js  2.25 kB       2  [emitted]  bolt-wc-polyfill--sd
3.chunk.js  1.74 kB       3  [emitted]  bolt-wc-polyfill--es5-adapter
4.chunk.js   196 kB       4  [emitted]
5.chunk.js  54.1 kB       5  [emitted]
bolt-app.min.js   244 kB       6  [emitted]  bolt-app
bolt-critical-path.min.js  54.8 kB    7, 8  [emitted]  bolt-critical-path
critical-fonts.min.js  54.8 kB       8  [emitted]  critical-fonts …
```
> Minimizing output of webpack compiles when in dev mode

- src/_meta/_00-head.twig
Just in case you were ever wondering why browser tabs said "Notice: Array to string conversion" in some place ;) - `title` isn't a string in most places; for example in the `nav-bar`.
> Fixes 'Notice: Array to string conversion' in PL compiles

- README.md
- config/config.yml
Initial setup of the repo results in the PL `config.yml` file being altered, which breaks the build since the Twig Namespaces aren't configured correctly. I've set `overrideConfig` to false to prevent that from happening. I've also enabled Twig Debug, so devs can use the [`{{ dump(var) }}` function](https://twig.symfony.com/doc/1.x/functions/dump.html). 
Finally, I typed up some quick setup notes - let me know what you all think of my use of `<details>` (make sure you [see it here](https://github.com/bolt-design-system/bolt/blob/feature/setup-feedback/README.md#installing) with the markdown rendered): I think that could be a good way of having less used, but detailed info available but not getting in the way of first time users.
> Setup feedback

- package.json
This removes the `pre-commit` and `precommit` package in favor of [`husky`](https://www.npmjs.com/package/husky), which can do [all of the git hooks](https://github.com/typicode/husky/blob/HEAD/HOOKS.md). I've also broken the precommit hook out into precommit and prepush so the precommit hooks takes a few seconds to run.
@sghoweri - what do you think about moving `npm run build:full` into the `prepublish` hook?
> Improving Git Hooks system

- lerna.json
Updates global Lerna config to limit publishing to only be done on the master branch
> Feature / Refactor: Limit Lerna Publishing

- package.json
Removing version number from Bolt's root package.json file (since it doesn't do / mean anything)
> Refactor: removing version number from root package.json

- package-lock.json
- packages/bolt-core/package.json
- packages/bolt-core/polyfills/polyfill-loader.js
- packages/bolt/bolt-wwwd8.js
- packages/bolt/package.json
Temporary workaround till a solution is in place that'll allow Drupal to compile JS on it's own and/or some of the more finicky components involved in sticky positioning (ie. Global Nav) are added to the Design System.
This update creates a separate standalone JS bundle for Pega.com D8 with the Bolt sticky and smooth scroll packages temporarily disabled.
Side notes (based on the diff below): 
1. The non-critical ratio object javascript component is being temporarily disabled in both the main Bolt JS bundle and the wwwd8 JS package until an existing IE11 bug is fixed. This JavaScript only handles adding additional cross-browser support to the ratio object however isn't required in order for the component to work in most situations.
2. The webcomponentjs shims updated in #259 are also …
> Add Standalone JavaScript Bundle for Pega.com D8, Disable Smooth Scroll + Sticky JS Packages

- src/_patterns/02-components/bolt-image/src/image.twig
This throws warnings in Drupal as we are not currently "officially supporting" publicpath, even though the extension is technically there.
@charginghawk
> Fix publicpath() getting called in Drupal

- src/_patterns/02-components/bolt-device-viewer/demo/device-viewer~ipad-landscape-magnify.json
- src/_patterns/02-components/bolt-device-viewer/demo/device-viewer~ipad-landscape-silver-magnify.json
- src/_patterns/02-components/bolt-device-viewer/demo/device-viewer~ipad-portrait-magnify.json
- src/_patterns/02-components/bolt-device-viewer/demo/device-viewer~ipad-portrait-silver-magnify.json
- src/_patterns/02-components/bolt-device-viewer/demo/device-viewer~iphone8-black-magnify.json
- src/_patterns/02-components/bolt-device-viewer/demo/device-viewer~iphone8-gold-magnify.json
- src/_patterns/02-components/bolt-device-viewer/demo/device-viewer~iphone8-landscape-black-magnify.json
- src/_patterns/02-components/bolt-device-viewer/demo/device-viewer~iphone8-landscape-gold-magnify.json
- src/_patterns/02-components/bolt-device-viewer/demo/device-viewer~iphone8-landscape-magnify.json
- src/_patterns/02-components/bolt-device-viewer/demo/device-viewer~macbook-magnify.json
- src/_patterns/02-components/bolt-device-viewer/demo/device-viewer~magnify.json
- src/_patterns/02-components/bolt-device-viewer/src/device-viewer.standalone.js
- src/_patterns/02-components/bolt-device-viewer/src/device-viewer.twig
The key change:
```
-    var drift = new Drift(this.querySelector('bolt-device-screen'), {
+    var drift = new Drift(this.querySelector('.js-bolt-device-viewer-screen'), { 
```
Magnify was triggering for every bolt-device-screen, but I changed it work off the unused js-bolt-device-viewer-screen class.
> Change magnify js to depend on the js- class.

- src/_patterns/01-core/05-objects/bolt-grid-object/_objects.grid.scss
- src/_patterns/02-components/bolt-blockquote/src/blockquote.scss
1. Fixes issue mentioned in [BK-104](http://vjira2:8080/browse/BK-104) - spacing in the grid system on Safari being off due to cross browser differences in how the inline-block spacing workarounds are getting calculated. Switches us over to using the font-size: 0; workaround which appears to be working much more consistently 
Note: this adds a default 1rem font size rule to prevent issues w/ nested expecting font sizes to be inherited (ie. font size isn't defined on the nested component itself).
2. Also includes a separate Safari browser quirk w/ overflowing content via border-radius not getting cropped off as expected. Apparently setting position relative + a z-index does the trick!
> Safari Bug Fixes for Grid System spacing and Cropped Images in Blockquote Component

- build-tools/gulp-tasks/build-webpack/webpack.config.js
- build-tools/gulp-tasks/build-webpack/webpack.config.release.js
1. Including sourcemaps in the production JS build should help at least help some of the pains in #247 for the short term (ie. inspecting minified JS from the console should be at least a tad better with this)
2. Enabling Config option w/ UglifyJS to strip out stray console.logs in production build. Addresses issue brought up in [BK-85](http://vjira2:8080/browse/BK-85)
CC @charginghawk
> Update Webpack Config to Include Sourcemaps, Strip Console Logs in Production

- src/_patterns/01-core/05-objects/bolt-ui-list-object/src/ui-list.scss
Force hardware accelerated rendering of the UI list border (via CSS 3d transform trick) to significantly improve rendering consistently -- especially inside of Pattern Lab's iframe viewer.
Before half the time only some of the UI List borders would show up inside of PL but would always be visible outside of it -- now it just works!
Inconsistent Rendering in IE11 inside of Pattern Lab (Before) -- **Broken**
When Viewed Outside of Iframe Viewer in IE11:
Now with this 3d Transform Rendering Hack in Pattern Lab (After):
CC @EvanLovely - thought you'd get a kick out of this one ;)
> More Consistant UI List Border Rendering

- src/_patterns/02-components/bolt-headline/src/_tools.headlines.scss
- src/_patterns/02-components/bolt-headline/src/_typography.twig
- Remove auto-selecting selecting a text alignment option from the headline component by default so that the component can inherit text alignment (ex. by a utility class)
- Remove display: flex from headline to fix utility class text align behavior (@todo: re-evaluate when we add nested icons -- we might need to adjust based on vertical alignment behavior CC @mikemai2awesome @theSadowski)
> Fix Headline Text Alignment + Allow Alignment via Text Align Utility Class

- src/_patterns/02-components/bolt-page-header/src/_page-header.scss
Remove none-existent image references from the placeholder page-header component - begone 404 errors!
> Chore: Remove Non-Existant Image References in Placeholder Page Header Component

- src/_patterns/02-components/bolt-figure/src/_figure.scss
- src/_patterns/02-components/components-all/components-all.scss
- src/_patterns/02-components/components-all/package.json
Update the figure component's <custom-element> default layout from inline (inherited default) to block to fix an IE 11 rendering issue when being vertically aligned via flexbox (aka. fixes vertical alignment inside of the flag object because of this)
> Fix Flag Object Vertical Alignment 

- packages/bolt/bolt-wwwd8.js
- packages/bolt/bolt.js
- src/_patterns/01-core/05-objects/bolt-ratio-object/src/ratio.scss
- src/_patterns/01-core/05-objects/bolt-ratio-object/src/ratio.standalone.js
- src/_patterns/01-core/05-objects/bolt-ratio-object/src/ratio.twig
- src/_patterns/02-components/bolt-image/src/image.twig
- Re-enabled including the ratio object JavaScript in the Bolt and Pega.com D8 JS bundles
- Simplifies and cleans up the ratio object Sass partial
- Fixes some gaps in the original JS logic + significantly improves cross browser support in browsers that don't fully support Shadow Dom (ie. IE 11) -- now visually much more consistant across the board!
- Adds new `aspectRatioHeight` and `aspectRatioWidth` parameters that can get passed into the ratio object for configuring the dimensions directly (which the original didn't have) -- updates the Image component to now take advantage of this these new params
CC @theSadowski @EvanLovely @mikemai2awesome
> Refactor Ratio Object + Improve Cross Browser Support

- src/_patterns/01-core/05-objects/bolt-flag-object/src/flag.scss
Proactively this approach helps reduce encountering one of the most frequently seen flexbox gotchas / browser quirks in IE10 and IE11.
https://github.com/philipwalton/flexbugs#flexbug-6
> Fix: Update the Flag Object's CSS to use longhand flexbox rules.

- build-tools/gulp-tasks/build-webpack/package.json
- build-tools/gulp-tasks/build-webpack/webpack.config.js
- package.json
TLDR: Updates leading us to a much faster, much less painful local front-end dev environment :)
- Switch on Webpack's awesome HMR feature in prep of even more substantial build tool upgrades in flight
- Update Webpack Dev Server rules to automatically reload the page whenever Pattern Lab finishes compiling AND not cause multiple page refreshes in the progress
- Remove old regex in the babel-loader config exclude rules which aren't getting used and no longer apply
- Update Webpack Dev Server to another port to avoid conflicts with current BrowserSync server setup
> Feature: Enable Webpack Hot Module Replacement (HMR)

- src/_patterns/01-core/05-objects/bolt-grid-object/_objects.grid.scss
- src/_patterns/02-components/bolt-card/src/card.scss
- Removes automatically making the children of a "flex grid" to also be set to display flex as well. This fixes an unreported issue where misc components like buttons are stretched horizontally
Before:
After:
- Updates the card component to still allow for equal column layouts when used with the grid system set to "flex"
CC @theSadowski
> Fix Grid Layout Flex Behavior + Maintain Equal Height Cards

- build-tools/gulp-tasks/build-webpack/webpack.config.release.js
- src/_patterns/01-core/05-objects/bolt-ratio-object/src/ratio.scss
- Temporarily disable UglifyJS's mangle option after encountered an unexpected JS error in testing prior to release
- CSS workaround to address layout issue in IE11 with ratio object -- temp solution till problem further looked into (basically the ShadyCSS polyfill randomly stopped working after getting it to work yesterday - therefore the selector for getting the ratio object's contents positioned isn't working at all, ShadyCSS or not.... bizarre)
> Hotfix: Address Unexpected JS Errors, Ratio Object Issue in IE11

- config/config.yml
- package-lock.json
- src/_patterns/01-core/05-objects/bolt-ratio-object/src/ratio.standalone.js
- src/_patterns/02-components/bolt-video/src/_videojs-enhancements.scss
- src/_patterns/02-components/bolt-video/src/video.twig
- src/_patterns/02-components/brightcove-player/demo/brightcove-player--inline-script.twig
- src/_patterns/02-components/brightcove-player/package.json
- src/_patterns/02-components/brightcove-player/src/brightcove-player.standalone.js
- Add integration example of adding extra plugins to vanilla Bolt Video component (via inline JS script) using the new `onInit` property
- Fix issue with ratio object IE11 workaround
- Fix video player icon alignment in IE11
- Fixing issue with the ratio object getting extra Twig attributes when including in the video player 
- Adding solution to allow data attributes added to the video player (via `attributes`) to trickle down to the internal `<video>` tag that gets rendered
CC @christophersmith262 @krlucas @remydenton
> Add Video Player Event Hooks + Integration Example

- apps/pattern-lab--workshop/.boltrc.js
- packages/build-tools/cli.js
- packages/build-tools/commands/build.js
- packages/build-tools/tasks/pattern-lab-tasks.js
- packages/build-tools/tasks/webpack-tasks.js
- packages/build-tools/utils/config-store.js
This puts in a really nice & flexible config solution.
Where does config come from?
The order goes like this, as this list increases, the later override the earlier. [Order inspired by `rc`](https://www.npmjs.com/package/rc#standards).
1. `defaultConfig` in `config-store.js`
2. `userConfig` from `.boltrc.js` that's in same cwd as where `bolt` was ran, unless they use `--config-file path/to/.boltrc.js`
3. Env Vars with `bolt_` prefix; `bolt_verbosity=1` will override `config.verbosity` - case matters!
4. Certain command line options like `bolt build --verbosity 5` - not every config option is overridable this way.
Now any file can do this to get the config:
```js
const { getConfig } = require('../utils/config-store');
const config = getConfig();
```
Also, any config can update the config …
> Implementing config solution

- apps/pattern-lab--workshop/.boltrc.js
- packages/build-tools/cli.js
- packages/build-tools/commands/build.js
- packages/build-tools/create-webpack-config.js
- packages/build-tools/package.json
- packages/build-tools/tasks/serve.js
- packages/build-tools/utils/assets.js
- packages/build-tools/utils/config-store.js
This contains commits from PR #327 , so either wait till that is merged in for a better diff, or just [look at this diff](https://github.com/bolt-design-system/bolt/compare/feature/build-tools-config...feature/build-tools-updates).
This adds `bolt serve`, and also adds the serve task to `bolt build --watch`!
There's some WebPack entry function cleanup in here too that lays foundations for some future work. Doesn't change around the functionality at all.
There's definitely more I'd like to do in the config department, but just wanted this out.
> Adding build tools server

- package.json
- scripts/monorepo-tests.js
I'd like to get some scripts to ensure that developers have everything set up correctly, like:
- yarn version
- node version
- correct monorepo bootstrap setup
This is a very basic beginning to test for something I look for all the time: is everything in `./node_modules/@bolt/` a symlink? When it's not, it's bad and tends to be solved when I do one of a couple things:
- point workspaces path to correct package
- ensure the dependencies of something are using the version that the package in the repo is using
These subtleties  no one besides architects should have to deal with; let's prevent them from having to with tools. I totally expect the approach of running this script to evolve and change, but I just wanted to get this basic function out for our use now.
> monorepo preflight script start

- packages/build-tools/package.json
- packages/build-tools/utils/config-store.js
- packages/build-tools/utils/config.schema.yml
- packages/build-tools/utils/schemas.js
- packages/build-tools/utils/yaml.js
This validates all use of the `bolt` config; to test, add some config that does not belong and try to run any command. Open to any all PRs and ideas for changes to how the config is structured.
> Adding Build Tools config schema

- packages/build-tools/commands/build.js
- packages/build-tools/create-webpack-config.js
- packages/build-tools/package.json
- packages/build-tools/tasks/pattern-lab-tasks.js
- packages/build-tools/tasks/webpack-tasks.js
- yarn.lock
- Compile PL by default on first run (temp workaround till work @EvanLovely is working on is in place)
- Switch on Hot Module reloading
- Update PL watch tasks to compile based on files in packages folder as well
> Update Pattern Lab Watch, Reload Tasks, 1st Pass Webpack Dev Server

- apps/pattern-lab--workshop/.boltrc.js
- packages/build-tools/cli.js
- packages/build-tools/tasks/server-tasks.js
- packages/build-tools/utils/config-store.js
- packages/build-tools/utils/config.schema.yml
IMHO, this is really important to keep on. If we don’t, we’ll be lazy with keeping the schema updated. If this build fails, let’s work together on this PR to document the config till it passes.
> Re-enabling Strict Schema for Build Tools

- packages/build-tools/commands/build.js
- packages/build-tools/tasks/webpack-tasks.js
Super simple change on how you get a whole tasks file: just require it instead of require and execute the function to receive more functions. Another PR that's great to see [without whitespace](https://github.com/bolt-design-system/bolt/pull/340/files?w=1).
> Changing WebPack tasks to not be a function

- src/_patterns/01-core/05-objects/bolt-flag-object/demo/flag~align-middle.json
- src/_patterns/01-core/05-objects/bolt-flag-object/src/flag.scss
- src/_patterns/01-core/05-objects/bolt-flag-object/src/flag.twig
@christophersmith262 You can set `valign: middle` to vertical align items inside a flag object.
> QA fix: vertical alignment of flag items

- src/_patterns/02-components/brightcove-player/src/brightcove-player.scss
Small typo on the max-height and max-width, resulted in the close button positioned incorrectly. I've fixed it now and it is displaying in the right place.
> QA Fix: video player width and close button bug

- bolt-manifest.yml
- src/_patterns/02-components/bolt-smooth-scroll/demo/-smooth-scroll-xl.demo.twig
This will create a new Smooth Scroll demo that is ~7500px tall. It will only be accessible via the Pattern Lab menu and won't be shown on the View All page (since the file is prefixed with `-`).
> Adding a very very tall Smooth Scroll demo

- .travis.yml
- deploy.sh
- package.json
The old behavior deployed to http://bolt.netlify.com from every latest commit and branch. This changes it to only to deploy to that when on the main branch, `release/0.x` and deploy to draft sites on other branches which create URLs like http://5a6795abdf995365a3315400.bolt.netlify.com
> Adding Netlify deploy script that only deploys to main site on main branch

- packages/build-tools/package.json
- packages/build-tools/tasks/image-tasks.js
OK, so `sharp` is awesome! This PR will resize the images when it's a production build. I opened all the files it resized and ran it through my own copy of ImageOptim and got an average savings of 3.5%, so it's looking like it's doing some nice minification for us.
What do we do when an image is smaller than the size we are resizing to? So when the original is 700px wide, and we're dealing with the 1024px size step. Do we not make it? Do we make a 700px wide image with a `-1024` filename suffix?
Also: this sets the ground for removing the need for people to install ImageMagick!
> Resizing images when prod

- packages/build-tools/create-webpack-config.js
- packages/build-tools/tasks/internal-tasks.js
- packages/build-tools/tasks/task-collections.js
- packages/build-tools/utils/config.schema.yml
If `config.env === 'pl'` then our tasks run Pattern Lab compile & watch. If `config.wwwDir` is present, then we use servers. This sets the foundation for more environments and greater flexibility.
> Setting up optional tasks for specific envs/config

- packages/components/button/src/button.scss
Most component updates aren't being ported over to 1.x one at a time.  This seems like it should be an exception though because Salem has done a lot of net new work on the button in 1.x.
Merge this only if #388 is accepted.
> Update hack for IE11 button colors to work with button refactoring

- config/config.yml
- packages/bolt/bolt-wwwd8.js
- packages/bolt/bolt.js
- src/_patterns/01-core/05-objects/bolt-ratio-object/src/ratio.standalone.js
- src/_patterns/01-core/05-objects/bolt-ratio-object/src/ratio.twig
- src/_patterns/02-components/bolt-band/src/band.standalone.js
- src/_patterns/02-components/bolt-button/src/button.standalone.js
- src/_patterns/02-components/bolt-device-viewer/src/device-viewer.standalone.js
- src/_patterns/02-components/bolt-icon/src/icon.standalone.js
- src/_patterns/02-components/bolt-image/src/image.js
- src/_patterns/02-components/bolt-nav-bar/src/nav-bar.standalone.js
- src/_patterns/04-pages/button-perf-test.twig
Updating a handful of components to now conditionally bundle CSS if Shadow Dom is supported natively (which, incidentally, helps with performance when doing this sort of thing) in addition to omitting the spacing utility in the button component due to the extremely large file size currently (a known issue which needs to get refactored);
These in combination addres most if not all of the lingering IE 11 performance issues while retaining Custom Element functionality.
Also adding in a button performance test example w/ 200 web components on a page which, in IE 11, performs even better than expected: https://5a73ce9a7b6ee845ca711085--bolt-design-system.netlify.com/patterns/04-pages-button-perf-test/04-pages-button-perf-test.html
> Hotfix: Conditionally Inline Encapsulated CSS

- packages/build-tools/create-webpack-config.js
- packages/build-tools/package.json
OK, this should fix the situation where css classes like `.u-hide\@large` get turned into `.u-hide-large` until [the bug in `css-loader`](https://github.com/webpack-contrib/css-loader/issues/578) can get fixed. /cc @sghoweri 
Jake, can you check to see if this fixes the issue, then merge if it does?
> Fix for css class names with escaped characters

- src/_patterns/02-components/bolt-card/src/card-simple.twig
This is a pattern @sghoweri and I discussed a week or two ago.  It allows using card just for the background.
I don't think this is an ideal solution (for example, it's a little confusing in the context of the main card pattern, which potentially should have been named "teaser card" instead.  We also probably don't want consumers to override the `card_media` or `card_footer` blocks when using it, but they could).  The main advantage is it's fully backwards compatible and hopefully simple enough to layer on too much additional complexity to the overall card pattern.
> Add simplified card pattern (BK-200)

- apps/pattern-lab--workshop/src/_includes/utils/md-embed.twig
- packages/core-php/src/TwigExtensions/BoltExtras.php
- packages/core-php/src/TwigFunctions.php
- packages/core-php/src/Utils.php
Adding `md-embed.twig` util for embedding Markdown and linking to GitHub for edits. This let's one do this:
```twig
{% include '@utils/md-embed.twig' with {
file: 'path/to/doc.md',
} %}
{% include '@utils/md-embed.twig' with {
file: '@bolt-thing/README.md',
} %}
```
And it will render the markdown **and** put in a link to "Edit this on GitHub". I've got some logic in there to find out where it is in the repo and so it can link to it. This will help a lot by getting rid of [this approach in `docs.twig`](https://github.com/bolt-design-system/bolt/blob/epic/refactor/apps/pattern-lab--workshop/src/_includes/utils/docs.twig#L18-L20)
Not quite ready to merge yet, let's do this first:
> Adding Markdown Embed Util

- package.json
- Rearrange order of meta info in root package.json file
- Remove npm scripts not currently getting used; some of these might come back but no sense cluttering up our code if something's currently switched off and not in use atm
- Also wipes a couple unused dependencies -- web-component-tester and backstop JS will be returning but again, until we have a working script or test requiring these, I'm leaning towards keeping things lean and only adding stuff back in when we're ready to go
> Refactor: Clean Up Root Package.json File on Epic/Refactor

- packages/build-tools/cli.js
This adds `bolt pattern-lab` (alias: `bolt pl`) and `bolt webpack` (alias: `bolt wp`) to the build tools.
Just a little tip for you personally Salem, run this to get a global `bolt`:
```bash
cd apps/pattern-lab--workshop/node_modules/.bin/
ln -s `pwd`/bolt /usr/local/bin
```
Now you can run `bolt` commands anywhere... and yes, if you ran that in `apps/example_drupal_theme` it'd still work and only run there.
> Adding solo commands for PL and WebPack

- packages/core-php/src/TwigExtensions/BoltCore.php
Schema validation only happens if `enable_json_schema_validation` is set to true; this was done in the old `_twig-components/` approach, but we forgot to migrate that over to our new approach with the Twig Extensions; so here we go. 
/cc @joekarasek @sghoweri @rockymountainhigh1943
> Re-enabling schema validation

- src/_patterns/02-components/components-all/package.json
The latest code up on the release/0.x branch (released 2 days ago) can't compile due to the `@bolt/components-all` package missing the new Breadcrumb component as a dependency when doing a fresh install (ie. not already symlinked locally via Lerna).
@remydenton - do we need to republish `@bolt/components-all` ASAP? Is this getting used in production on the Drupal side of things? I didn't think it was but wanted to double-check...
CC @EvanLovely
> Hotfix: Add missing Breadcrumb dependency to @bolt/components-all

- packages/build-tools/cli.js
- packages/build-tools/tasks/server-tasks.js
- packages/build-tools/tasks/task-collections.js
- packages/build-tools/utils/config-store.js
- packages/build-tools/utils/config.schema.yml
This disables the WebPack Dev Server by default, which allows us to have two servers running at the same time since Browser Sync will just grab the next highest available port number. 
It can be enabled in any of these ways:
- Adding `webpackDevServer: true` to the `.boltrc.js` file
- Setting an Env Var of `bolt_webpackDevServer=true`
- Passing `--webpack-dev-server` into command
> Adding option for enabling WebPack Dev Server

- package-lock.json
- packages/bolt-core/index.js
- packages/bolt-core/package.json
- packages/bolt-core/renderers/renderer-hyperhtml.js
- packages/bolt-core/renderers/renderer-preact.js
- packages/bolt-core/utils/declarative-click-handler.js
- src/_patterns/01-core/04-elements/elements-code/_elements.code.scss
- src/_patterns/02-components/bolt-button/demos/05-button-theming.twig
- src/_patterns/02-components/bolt-button/demos/button--data-attributes.twig
- src/_patterns/02-components/bolt-button/demos/button--form-submit.twig
- src/_patterns/02-components/bolt-button/demos/button--icon-only.twig
- src/_patterns/02-components/bolt-button/demos/button--no-shadow.twig
- src/_patterns/02-components/bolt-button/demos/button--static-html.twig
- src/_patterns/02-components/bolt-button/demos/button--utils.twig
- src/_patterns/02-components/bolt-button/package.json
- src/_patterns/02-components/bolt-button/src/_button.mixins.scss
- src/_patterns/02-components/bolt-button/src/_button.settings.scss
- src/_patterns/02-components/bolt-button/src/button.scss
- src/_patterns/02-components/bolt-button/src/button.standalone.js
- src/_patterns/02-components/bolt-button/src/button.twig
- src/_patterns/02-components/bolt-button/src/link.scss
- src/_patterns/02-components/bolt-icon/src/icon.scss
- src/_patterns/02-components/bolt-video/src/_videojs-enhancements.scss
@remydenton check these out when you get a chance -- all these updates below are based on the conversations we had on Friday and are meant to put a nail in the button component woes + providing you guys more flexibility while also avoiding any major breaking changes or losing out on any functionality already in place.
**TLDR:** Makes the button component do a heckofalot less (but still some) work without really changing or breaking current functionality, while also providing more control downstream on how the Button component can get configured and customized. Also fixes a couple small things in the process to boot.
^ also, the HyperHTML renderer mentioned below, if this PR checks out, is my go-to workaround for addressing some additional JS-hook related issues @charginghawk and I have …
> RFC (Request for Comment) Simplify Button + Provide More Flexibility

- packages/build-tools/cli.js
- packages/build-tools/create-webpack-config.js
- packages/build-tools/package.json
- packages/build-tools/tasks/image-tasks.js
- packages/build-tools/utils/config-store.js
- packages/build-tools/utils/config.schema.yml
This enables prod builds. 
Doing any of the below will set `config.prod` to `true`:
- Passing in `--prod` to any `bolt` command: `bolt build --prod`, `bolt start --prod` etc. 
- This also sets `NODE_ENV=production` (which is how PHP Twig Extensions can tap into this).
- Setting `NODE_ENV=production` 
When `config.prod` is true, then:
- WebPack will:
- Uglify JS
- Minimize CSS via CSSnano
- Change the source maps setting
- Image Tasks will actually resize and compress images instead of symlinking them (former PR).
> prod builds

- package-lock.json
- packages/bolt-core/polyfills/webcomponents-hi-sd-ce-pf-index.js
- packages/bolt-core/renderers/renderer-hyperhtml.js
- src/_patterns/01-core/05-objects/bolt-ratio-object/src/ratio.standalone.js
- src/_patterns/02-components/bolt-band/src/band.standalone.js
- src/_patterns/02-components/bolt-button/src/button.standalone.js
- src/_patterns/02-components/bolt-device-viewer/src/device-viewer.standalone.js
- src/_patterns/02-components/bolt-icon/src/icon.standalone.js
- src/_patterns/02-components/bolt-nav-bar/src/nav-bar.standalone.js
- src/_patterns/02-components/brightcove-player/src/brightcove-player.standalone.js
- Swaps out the mixin order on JS classes using Preact to fix IE11 errors previously getting thrown
- Replaces the document-register-element JS polyfill for IE11 with more resilient custom-elements.js solution
- Move `<replace-with-children>` custom element logic to standalone Class + IE11 workaround
- Wire up HyperHTML renderer in a few extra places causing JS binding behavior with previous release
CC @remydenton @charginghawk
> Fix Rendering in IE 11 for 0.x Release + Replace `InnerHTML` Renderer Workaround

- packages/build-tools/create-webpack-config.js
Re-enable the workaround to the `\@` character bug in the Webpack CSS Loader to work around us needing CSS modules enabled in latest build; Also updates the find and replace ever so slightly so all the breakpoint Sass suffixes are replaced properly (some were getting wiped with the original implementation switched on verbatim).
> Fix: Re-enable Webpack CSS Build Char Fix on Master

- packages/global/styles/07-utilities/_utilities-spacing.scss
No functional changes to this technically - basically just cleaning up some tech debt with the initial implementation:
- Properly adds in `auto` and `none` values (which were previously getting hard coded in)
- Re-arranges the for-loop so breakpoints getting output are consolidated (ie. not unnecessarily duplicated) to save a couple hundred lines of outputted code ;)
- Cleans up the file for maintainability + match convention used in the partial handling width utility classes
todo (not in this PR): output negative utility class value equivalents to this
CC @mikemai2awesome @joekarasek @rockymountainhigh1943 @remydenton
> Refactor: Clean Up, Consolidate Bolt's Spacing Utility Class

- apps/pattern-lab/.patches/beautifyHTML.patch
Removing this cut memory usage on Pattern Lab compiles in half. It's purpose was to pretty print the PL code viewer output.
> Enabling HTML Beautify only on prod deploys

- package.json
This prevents any packages published from the 0.x branch from getting the `latest` tag.   It should be
standard practice to add this to package.json anytime we create a branch to support a no-longer-most-recent major version.
> Set release tag for 0.x branch

- packages/components/bolt-form/src/elements/form-fieldset.twig
- packages/components/bolt-form/src/form-icons.twig
- packages/components/bolt-form/src/form.scss
- packages/components/bolt-form/src/inputs/form-checkboxes.twig
This PR includes all updates made on the [feature/BK-10-forms-consolidated branch](https://github.com/bolt-design-system/bolt/commits/feature/BK-10-forms-consolidated) since the forms components was migrated to 1.x.  The full commit messages and rationale can been seen at my link above.
Yes, I know the proper workflow would have been to make these changes to 1.x first and _then_ move them back to 0.x.  Alas, this was the easier way (since pega.com Drupal, where these fixes were needed, is all using 0.x) and I succumbed to laziness.  Please forgive me :).
> chore: port updates to form component from 0.x

- packages/components/bolt-form/src/form.scss
The shadow is HUGE! This decreases it down to a similar level as what the design mockup had.
> Decreasing the level of shadow on form inputs from 30 to 20

- packages/global/styles/05-objects/objects-ratio/ratio.scss
Update the ratio object to vertically align content by default. Prevents instances where nested image content alignment mis-matches with background container (ie. average background color / placeholder image doesn't match with the actual image itself).
Thanks @mikemai2awesome for pointing out this one to me!
> Fix: Vertically Center Ratio Object Content

- apps/bolt-site/templates/home.twig
- apps/drupal-lab/composer.json
- packages/build-tools/utils/manifest.js
- packages/core-php/src/TwigExtensions/BoltCore.php
- packages/drupal-modules/bolt_connect/bolt_connect.info.yml
- packages/drupal-modules/bolt_connect/composer.json
- scripts/update-php-package-versions.js
Can now get to the version of the build tools (which is same version as all bolt components) by hitting `bolt.data.fullManifest.version`.
Can also get to the version of core-php by hitting `BoltCore->version`.
This also tightens how `bolt_connect` pulls in `core-php` by specifying the exact version.
The end goal is to make sure that the components pulled in via NPM and the PHP packages pulled in via Packagist are the same version.
> Bolt Versions in Data

- package.json
- packages/components/bolt-image/src/image.test.js
- scripts/monorepo-tests.js
- scripts/monorepo.test.js
- yarn.lock
Was thinking this should be in Jest anyway; also [`assert` is a core node module](http://nodejs.org/api/assert.html) so we don't need a new dependency for it. Let's chat soon to go over if you want.
> Moving publish config tests to Jest

- apps/bolt-site/content/20-docs/40-guides/10-install-component.md
- apps/bolt-site/content/20-docs/40-guides/15-Adding-a-new-component.md
- package.json
- packages/components/bolt-image/src/image.test.js
- packages/core/package.json
- scripts/monorepo-tests.js
- scripts/monorepo.test.js
- yarn.lock
TLDR: add testing coverage to prevent Lerna publishing failures midway through publishing due to a config option missing from the package's package.json file.
- Adds new logic to monorepo tests to asynchronously find the locations and contents to all package.json files of packages being managed by Lerna
- Using this new script ^ - add a two tests to check that a publishConfig config option exists in each package's `package.json` file and that the config is properly set
- Update docs to the "Adding a New Component" to include info on this `publishConfig` option needed
CC @remydenton
> Add Monorepo Pre-Publishing Test for PublishConfig

- packages/core/utils/environment.js
- packages/global/styles/05-objects/objects-ratio/ratio.scss
- Updates global Bolt Core check to treat polyfilled bowsers the same as natively supported browsers
- Also updates the Ratio Object's internal selector to work around differences in rendered HTML structure (differs slightly based on polyfills loaded).
Partially addresses the Ratio Object bug in Firefox reported by @charginghawk
Side note: two other existing PRs further button these up by addressing [vertical alignment](https://github.com/bolt-design-system/bolt/pull/565) + [re-rendering issues](https://github.com/bolt-design-system/bolt/pull/561) (ie. get rid of `.innerHTML` workarounds)
> Hotfix: Update Core Environmental Check, Fix Ratio Object Inner Selector

- packages/global/styles/05-objects/objects-ratio/ratio.scss
Fixes instances @mikemai2awesome pointed out where the ratio object can become misaligned with the child content (image), causing the image and the background color shown to not perfectly match up
> Hotfix: Fix Ratio Object Misalignment

- packages/components/bolt-icon/src/icon.standalone.js
Fixes JS error getting thrown in the icon component if the browser (like IE 11) doesn't support the Node `contains` method and isn't properly polyfilled. 
@rockymountainhigh1943 this was the same thing we chatted about last week during cross browser testing!
> Hotfix: Fix Icon Component 'Contains' Method

- apps/pattern-lab/core/console
- apps/pattern-lab/src/_patterns/02-components/button/10-button-sizes.twig
- apps/pattern-lab/src/_patterns/02-components/button/15-button-styles.twig
- apps/pattern-lab/src/_patterns/02-components/button/25-button-widths.twig
- apps/pattern-lab/src/_patterns/02-components/button/30-button-tags.twig
- apps/pattern-lab/src/_patterns/02-components/button/35-button-align-items.twig
- apps/pattern-lab/src/_patterns/02-components/button/40-button-transform.twig
- apps/pattern-lab/src/_patterns/02-components/headline/15-headline-align-variations.twig
- apps/pattern-lab/src/_patterns/02-components/headline/20-headline-style-and-weight-variations.twig
- package.json
- packages/build-tools/utils/config-store.js
- packages/build-tools/utils/manifest.js
- packages/build-tools/utils/schemaSchema-v4.json
- packages/build-tools/utils/schemas.js
- packages/components/bolt-block-list/block-list.schema.yml
- packages/components/bolt-button/button.schema.yml
- packages/components/bolt-button/src/button.twig
- packages/components/bolt-device-viewer/device-viewer.schema.yml
- packages/components/bolt-headline/headline.schema.yml
- packages/components/bolt-headline/src/_typography.twig
- packages/components/bolt-headline/src/headline.twig
- packages/core-php/src/TwigExtensions/BoltCore.php
This is addressing a few things that create silent errors (things that do not exit non-0, so Travis does not fail, nor do the tools show errors).
- Invalid JSON Schemas. This introduces validation of those via the JSON Schema Schema :)
- Invalid YAML. Adding Yaml Linting.
- Array to String notices that happen when one uses an array as a var in PL. I have added an error handler in PL for this.
Next up is fixing the invalid schemas:
> Fixing Silent Errors

- apps/pattern-lab/.boltrc.js
- packages/build-tools/create-webpack-config.js
- packages/build-tools/package.json
- packages/build-tools/utils/general.js
- Add missing log dependency (error thrown when log level set to certain level of verbosity)
- Fix webpack dev server + HMR in build config
- Add [inline-source-loader](https://github.com/mortenson/inline-source-loader) to Webpack to prep us for https://github.com/mortenson/twig-components and https://github.com/mortenson/twig-components-ssr
> Misc Webpack Updates

- packages/global/styles/05-objects/objects-ratio/ratio.scss
Hotfix to fix ratio object hotfix
If this fix is working as expected this page should be working again in Chrome and in Firefox (the issue originally flagged in): https://bolt-design-system.com/pattern-lab/?p=components-video--show-meta
> Fix Ratio Object Hotfix

- packages/components/bolt-headline/headline.schema.yml
- packages/components/bolt-headline/src/_typography.twig
Updates the headline / sub headline / eyebrow / text component's "align" option in the schema to _not_ set a default value -- text alignment needs to be inherited by default unless the explicitly set to prevent visual regressions like the ones we're seeing on the live bolt-design-system.com site.
CC @joekarasek @EvanLovely @rockymountainhigh1943 @mikemai2awesome @theSadowski
> Hotfix: Fix Headline Alignment Regression on Master

- packages/components/bolt-copy-to-clipboard/src/copy-to-clipboard.standalone.js
- packages/components/bolt-nav-bar/src/nav-bar.standalone.js
- packages/components/bolt-share/src/share.standalone.js
Updates a few JS components referencing the HyperHTML renderer to point at the newer BoltComponent renderer (which is still powered by HyperHTML under the hood) to fix errors thrown by Webpack
> Hotfix: Fix HyperHTML Renderer Imports

- packages/components/bolt-copy-to-clipboard/src/copy-to-clipboard.standalone.js
- packages/components/bolt-dropdown/dropdown.scss
- Workaround to fix copy to clipboard rendering
- Updating CSS rule to fix Travis build error (oddly not happening locally)
> Hotfix: Dropdown CSS Var Fix + Fix for Copy to Clipboard

- packages/components/bolt-headline/headline.schema.yml
- packages/components/bolt-headline/src/_typography.twig
@sghoweri Saw that you fixed a regression in Headline with the alignment prop...
Didn't feel good seeing null back in the schema, as this causes issues elsewhere. And the type was dropped. So here is a slightly different approach. If `align` is not passed in by the user, it remains undefined and nothing happens with it.  This seems simpler than saying it can be undefined, null, or a string, and that undefined will be transformed into null internally.
I also feel like this is a spot where we should have a consistent solution. There is nothing special about the align prop, so it shouldn't need a different schema pattern from the rest of the props that can be omitted. 
Thoughts?
> Refactor of Headline Align Regression

- packages/build-tools/cli.js
- packages/build-tools/tasks/webpack-tasks.js
- packages/build-tools/utils/config-store.js
- packages/build-tools/utils/config.schema.yml
This allows one to pass `--webpack-stats` to either `bolt build` or `bolt webpack`, and will output `webpack-stats.json` in the `buildDir`. This is what most WebPack analyziation tools want, in particular the [official one](http://webpack.github.io/analyse/).
> Adding WebPack stats option to build tools

- packages/components/bolt-device-viewer/src/device-viewer.scss
- packages/components/bolt-dropdown/dropdown.scss
- packages/components/bolt-form/src/form.scss
- packages/components/bolt-icon/src/icon.scss
- packages/components/bolt-video/src/video.scss
- packages/core/styles/02-tools/tools-css-vars/_tools-css-vars.scss
- packages/global/styles/05-objects/objects-ratio/ratio.scss
- packages/global/styles/05-objects/objects-ui-list/_objects-ui-list.scss
- packages/global/styles/06-themes/themes-general/_themes-dark.scss
- packages/global/styles/06-themes/themes-general/_themes-light.scss
- packages/global/styles/06-themes/themes-general/_themes-medium.scss
- packages/global/styles/06-themes/themes-general/_themes-xdark.scss
- packages/global/styles/06-themes/themes-general/_themes-xlight.scss
Across the board hotfix for all CSS custom property-based theming disappearing on the built Bolt site (locally and on prod) due to some recent change with how CSS vars no longer permit Sass functions / variables to be used as CSS var property values without interpolation (similar to https://github.com/jgthms/bulma/issues/1283#issue-264285920)
Haven't been able to pinpoint the exact breaking change on this with the build tools dependencies or why we haven't gotten any warnings / errors on this but I can confirm this fixes the problem locally. My suspicion is that a dependency change downstream is ultimately what's causing this (unconfirmed)
CC @mikemai2awesome @theSadowski @EvanLovely @rockymountainhigh1943 @joekarasek @charginghawk
> Hotfix: Global Fix for Broken CSS Vars Theming

- package.json
Addresses situations where a designer or developer running Bolt might not have Lerna installed locally or globally, resulting in the `npm run setup` command failing unexpectedly as @theSadowski encountered earlier today 😉
> Enhancement: Add Yarn Command to `npm run setup`

- packages/core/styles/01-settings/settings-spacing/_settings-spacing.scss
As requested from the Drupal team, [BDS-210](http://vjira2:8080/browse/BDS-201), utility spacing classes now have a "default" of medium size if a size in not included in the utility class name. 
`.u-bolt-magin-bottom` and `.u-bolt-margin-bottom-medium` are equivalent.
> return "default" for spacing utility classes

- apps/pattern-lab/package.json
- packages/core/polyfills/polyfill-loader.js
- Updates the `@bolt/core` polyfill loader to always use the `document-register-element` instead of the es5 custom element adapter to avoid load order issues depending on if a component is lazy loaded or loaded immediately
- Update the unpublished footer component referenced in PL to get locally referenced to make local testing / installs work
> Fix: Update Polyfill Loader, Link Unpublished Footer in PL

- packages/build-tools/create-webpack-config.js
- packages/build-tools/package.json
- yarn.lock
This allows the ability to `import` or `require` yaml files in JS and get a JS object back. This will be useful for JS files that want to get access to their schema, like so:
```js
import schema from '../button.schema.yml';
// or
const schema = require('../button.schema.yml');
```
> Adding yaml-loader

- packages/build-tools/utils/manifest.js
Tweaks how the `@bolt/build-tools` manifest figures out which version of Bolt should get displayed on the site by directly referencing the `lerna.json` version number in the root of the repo vs expecting the `@bolt/build-tools` version to always be set to the same version number (which isn't always the case)
> Fix Bolt Site Version Referenced - use version from `lerna.json`, not `@bolt/built-tools`

- packages/components/bolt-chip-list/package.json
- packages/components/bolt-link/package.json
- packages/components/bolt-page-footer/package.json
- packages/components/bolt-site/package.json
- packages/components/bolt-smooth-scroll/package.json
- packages/components/bolt-sticky/package.json
When Bolt undergoes an update (eg recently to 1.3), there's consistently a few packages that get left behind due to lacking a @bolt/core dependency. For instance, here's the current version of all packages:
```
@bolt/components-placeholder       v1.3.0
@bolt/components-action-blocks     v1.3.0
@bolt/components-background-shapes v1.3.0
@bolt/components-background        v1.3.0
@bolt/components-band              v1.3.0
@bolt/components-block-list        v1.3.0
@bolt/components-blockquote        v1.3.0
@bolt/components-breadcrumb        v1.3.0
@bolt/components-button-group      v1.3.0
@bolt/components-button            v1.3.0
@bolt/components-card              v1.3.0
@bolt/components-dropdown          v1.3.0
@bolt/components-chip-list         v1.3.0
@bolt/components-chip              v1.3.0 …
```
> Add @bolt/core dependencies to the few packages that lacked such.

- packages/components/bolt-video/src/video.scss
When clicking the fullscreen button on a background video, it doesn't go fullscreen because of the max-width of 1400px.
> Fix background video not going fullscreen issue.

- packages/global/styles/05-objects/objects-block/_objects-block.scss
Fix the Sass output for the block object's align options (broken otherwise)
> Fix Block Object's Alignment Options

- packages/core/styles/01-settings/settings-font-family/_settings-font-family.scss
- packages/global/styles/03-generic/_generic-font-stacks.scss
Refactors how we wire up `@font-face` font families to be exportable as JSON data -- part of the underlying work related to wiring up our font loader JS to the actual font families used in the design system.
> Feat: Restructure `@font-face` To Be Exportable

- packages/components/bolt-ordered-list/ordered-list.scss
This fixes an issue where the number inside the circle is not vertically centered in IE only. This also fixes the incorrect counter-reset issue in IE.
http://vjira2:8080/browse/BDS-286
> Fix: ordered list number vertically centered in IE

- packages/components/bolt-headline/src/_tools.headlines.scss
- packages/components/bolt-headline/src/_typography.twig
- packages/components/bolt-headline/src/headline.scss
This simple PR fixes an issue where the xxxl font size larger than 60 characters long was being switched to xxl font size. With these adjustments made we'll now be setting the font size to `$bolt-font-size--xxxlarge--min` rather than dropping down one full size.
This PR also removes an necessary wrapper when including an icon.
> Headline Component Updates > xxxl fluid size & extra wrapper

- packages/components/bolt-blockquote/src/blockquote.scss
z-index on the blockquote image is creating undesired results (ie, covering up things that has lower z-index). It was intended to be a fix for Safari where border radius and overflow are not cropping the image, but that is not true anymore, tested in all versions of Safari to confirm.
So z-index and position relative has been removed. 
See demo: https://fix-wwwd-2149-blockquote-image-z-index-remove.bolt-design-system.com/pattern-lab/?p=components-blockquote-alignItems-variation
> Fix: remove z-index on blockquote image

- packages/components/bolt-nav/nav.scss
Resolves http://vjira2:8080/browse/WWWD-2150
This backs out the change introduced at 
https://github.com/bolt-design-system/bolt/commit/d25ec362#diff-5c1b2065daa942358746a52cf8077fc2L83.  It's unclear whether there was an important reason for that change-- everything _seems_ to still work as expected after removing it.
In IE, visit https://fix-WWWD-2150-navbar-indicator-positioning-IE.bolt-design-system.com/pattern-lab/patterns/02-components-sticky--15-sticky-with-content-example/02-components-sticky--15-sticky-with-content-example.html and click the navbar links.  The nav indicator underline should animate to the correct position under each link (as it currently does in other browsers).
Important note for @sghoweri: this does not fix the indicator positioning in IE for the nav when …
> fix: Fix nav indicator positioning in IE (WWWD-2150)

- packages/components/bolt-smooth-scroll/src/smooth-scroll.js
This fixes a flashing issue in IE (see WWWD-2151) by instantiating SmoothScroll once instead of attaching a SmoothScroll to every anchor link. In the process it simplifies the code more towards [recommended usage](https://github.com/cferdinandi/smooth-scroll#3-initialize-smooth-scroll)
This negates the ability to set offset on a per-link basis. We weren't using this on the Drupal-side anyway, but we may have to at some point if the navbar height varies. This fix will get us through our next major release, in any case.
Also, this will break the navbar demo within Pattern Lab, eg:
http://localhost:3000/pattern-lab/?p=components-sticky-with-content-example
But the demo will work when viewed on its own page, eg:
http://localhost:3000/pattern-lab/patterns/02-components-sticky--15-sticky-with-co …
> Fix smoothscroll flash in IE.

- packages/components/bolt-video/src/video.standalone.js
This works with multiple videos on the page and is cross-browser / device tested.
**Testing Instructions**
1. Boot up PL
1. Navigate to http://localhost:3000/pattern-lab/patterns/02-components-video-video--background-video-with-inline-script-and-external-controls/02-components-video-video--background-video-with-inline-script-and-external-controls.html
1. Click the button to launch video
1. Click anywhere outside bolt-video to see the video close
> Video Enhancement - Collapse video when clicking away

- packages/components/bolt-video/src/video.scss
Removes a single CSS line put in place ~2 months ago without any context.
This fixes a Safari for iOS issue w/ the video player + layered content on bands behaving unexpectedly (ex. not triggering click events as expected). Tested this out locally in Chrome, Safari, Firefox, IE 11, and Safari for iOS (iPhone) doesn't appear to reveal any apparent regressions.
CC @krlucas @charginghawk @theSadowski @remydenton
> Hotfix: remove background video z-index being set

- packages/components/bolt-video/src/_video-tag.twig
- packages/components/bolt-video/src/video.scss
Update the Bolt video player Twig config to manually disable the `resizeManager` option in Brightcove + revert CSS hotfix added yesterday.
This fixes the Safari for iOS issue encountered in production with background-embedded video players not allowing UI elements on top / in the same parent container (like a Band) to be interacted with due to the `<iframe>` element this new resizeManager functionality added in the Brightcove player.
CC @theSadowski @charginghawk @krlucas
> hotfix: revert removing z-index from video player CSS + disable `resizeManager` config in Brightcove

- apps/pattern-lab/src/_patterns/02-components/button/15-button-styles.twig
- packages/components/bolt-button/src/_button.mixins.scss
- packages/components/bolt-button/src/button.standalone.js
This pull request adds a fix for the broken button demo page. The logic to make this happen is a little cumbersome and might need to be refactored in another ticket.
The issue arose because `sanitizeBoltClasses()` function strips out all `c-bolt-` classes. This makes it so classes being passed, like `c-bolt-button--hover`, never make it onto the button.
**Steps to fix this issue were:**
1. Update PL demo page to use simplified classes that wont be stripped out (e.g. `is-hover`) and removed the "is" attributes
1. Update our button mixin to catch the new class names
> Button Regression Fix

- packages/components/bolt-button/src/_button.mixins.scss
Resolves http://vjira2:8080/browse/BDS-325
For reference, the styles I'm removing were originally added in 33846bbdb1d
> feature: remove blue outline from Firefox button focus state (BDS-325)

- apps/pattern-lab/src/_patterns/04-pages/60-d8-homepage/-15-d8-homepage-video-band.twig
- packages/components/bolt-band/src/band.scss
- packages/components/bolt-band/src/band.standalone.js
- packages/components/bolt-video/src/_videojs-enhancements.scss
- packages/components/bolt-video/src/video.scss
- packages/components/bolt-video/src/video.standalone.js
1. Update homepage w/ background video player example to test use case of video player + button trigger being in different locations.
2. Consolidate and clean up video player and band logic to only listen to window resize events / video player events when videos are embedded as backgrounds. This update is meant to speed up initial bootup times and help reduce some delays seen in older devices.
3. Update video player aspect ratio CSS to re-implement expected behavior on smaller / shorter screen sizes. Note: CSS being removed here is no longer required based on current behavior / functionality expected.
4. Clean up video player animation logic to address rendering issues seen when resizing / animating / playing in different combinations.
CC @theSadowski @krlucas @charginghawk @remydenton …
> Hotfix / Refactor: Consolidate Background Video Player Logic + Fix Aspect Ratio Regression

- packages/core/styles/02-tools/tools-font-family/_tools-font-family.scss
- packages/global/styles/04-elements/_elements-page.scss
Updates our global `@bolt-font-family` Sass mixin to now output the font family stacks as CSS variables on the root (html) element + tell components using the mixin to automatically include the `font-family: var(--bolt-font-family);` styles. 
^ this specifically is the thing that lets fully encapsulated components (like the Text component) be automatically wired up to styling and configs outside of the component itself since this is the "official way" to precisely customize Web Components from the outside while keeping most of the styles encapsulated and consistent.
Before fonts async load:
After fonts async load:
> Feature: Add Support for Async Loaded Critical Fonts in Fully Encapsulated Web Components

- packages/components/bolt-headline/src/_typography.twig
Resolves http://vjira2:8080/browse/BDS-368
The problem is that, with the commit below, I inadvertently changed the logic from "If type is not text, give it the headline styling" to "if type _is_ text, give it the headline styling".
https://github.com/bolt-design-system/bolt/commit/730953b7a50d89abe4700e2d4fec80493cee7274#diff-96af1223b5d80a416426920a13a79b52
> fix: Fix headline styling regression (BDS-368)

- packages/core/styles/01-settings/settings-font-family/_settings-font-family.scss
- packages/core/styles/02-tools/tools-font-family/_tools-font-family.scss
This fixes the declaration for each specific type of font-family such as heading, body, and code. Previously, the CSS variable was only producing one type.
This is a fix from @sghoweri
> Fix: font family tools and settings

- packages/components/bolt-navlink/navlink.js
Update the <bolt-navlink> to check if the link being interacted with is a hashed link and if so, preventDefault to ensure a much less jumpy smooth scroll experience. 
Fixes issues noticed when testing in Safari and IE 11
CC @theSadowski @remydenton @mikemai2awesome
> Fix: Less Jumpy Smooth Scroll / Nav Links

- packages/components/bolt-text/src/text.scss
- packages/components/bolt-text/src/text.standalone.js
Updates the new (unreleased) bolt-text component on master to use a unique class name instead of being scoped to the custom element selector.
Fixes styling regression when putting together the v1.5.0 release.
> Hotfix: fix bolt-text component CSS class on master

- packages/global/styles/05-objects/objects-inline-list/_objects-inline-list.scss
The last child is not supposed to have any spacing, this is consistent in all other lists.
> Fix: remove margin on inline list's last item

- packages/components/bolt-nav-indicator/nav-indicator.js
- packages/components/bolt-nav-priority/nav-priority.js
Resolves http://vjira2:8080/browse/BDS-380
- add a custom event to the nav-priority component to let others know when the component is ready to go (like the nav-indicator)
- update nav indicator logic to listen for this even before trying to animate if the nav-priority is a nested component AND isn't yet ready to go
> Add indicator to active item on page load

- packages/components/bolt-nav-priority/nav-priority.twig
In Drupal, we use headerOffset to manage the gumshoe offset (for more information, see [this comment](https://github.com/bolt-design-system/bolt/pull/714#issuecomment-392167450)). This PR restores that functionality in Bolt.
> Restore headerOffset to navbar.

- packages/components/bolt-nav-priority/nav-priority.scss
I noticed in further testing the latest code released yesterday that in fixing one particular item with the new Navbar / Nav Priority updates on Friday, we inadvertently partially broke the center alignment of the priority nav (when stacked in the Navbar). This PR addresses that.
Broken:
Fixed:
CC @remydenton @theSadowski @charginghawk
> hotfix: remove flex-grow from `<bolt-nav-priority>` updates

- packages/components/bolt-smooth-scroll/src/smooth-scroll.js
- packages/core/index.js
- packages/core/utils/is-valid-selector.js
- yarn.lock
Iterates on the approach we've been taking to find which links are smooth scrolled by first filtering out all _possible_ links with those that have a valid class or ID.
Addresses a few issues seen with hash bang links locally + places where the `Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Document': '#' is not a valid selector.` has been reported such as http://vjira2:8080/browse/WWWD-2254
CC @charginghawk
> Hotfix / Refactor: Fix Smooth Scroll Selector By Filtering Out Invalid Selectors

- apps/pattern-lab/src/_patterns/02-components/dropdown/30-dropdown-custom-element-demo-collection.twig
- packages/components/bolt-dropdown/_dropdown-item.twig
- packages/components/bolt-dropdown/dropdown.twig
I spent a lot of time getting our Dropdown component to be fully server-side rendered and mouse + keyboard accessible via Twig prior to our web component's JavaScript kicks in (which, for reference, further enhances this component with cleaner animations + even better accessibility).
This PR fixes a small but fatal issue with how the original code we shipped handles content composition when using Twig embeds.
<br>
**With & Without JS**
For reference, the actual 
**Source Code (before Web Component JS kicks in):**
**Source Code (with Web Component JS kicked in):**
CC @theSadowski
> Fix Twig-Embedded Dropdown Menu Server-side Rendering / Progressive Enhancement

- packages/components/bolt-navlink/navlink.js
Resolves http://vjira2:8080/browse/BDS-412
- View the [content hub demo page in this PR](https://fix-bds-412-remove-navbar-focus-state-for-anchor-links.bolt-design-system.com/pattern-lab/patterns/04-pages-90-content-hub-anchor-ribbon-example/04-pages-90-content-hub-anchor-ribbon-example.html#transformation)
- Confirm that the bug described in http://vjira2:8080/browse/BDS-412 is resolved.
> fix: Remove navlink focus state when clicking anchor links (BDS-412)

- packages/components/bolt-code-snippet/src/code-snippet-syntax.scss
- packages/components/bolt-code-snippet/src/code-snippet.scss
- packages/global/styles/04-elements/_elements-code.scss
This fixes the long `pre` and `code` tags breaking the doc page layout.
> Fix: word wrap and word break settings

- packages/components/bolt-nav-indicator/nav-indicator.schema.yml
- packages/components/bolt-nav-indicator/package.json
- packages/components/bolt-nav-priority/nav-priority.schema.yml
- packages/components/bolt-nav-priority/nav-priority.twig
- packages/components/bolt-navbar/navbar.schema.yml
- packages/components/bolt-navlink/navlink.js
- packages/components/bolt-smooth-scroll/src/smooth-scroll.js
Adds support for modifying scroll offset. It looks for the link's first ancestor that has an 'offset' attribute, returning that value. You'll find offset on the nav-indicator, where gumshoejs also gets its offset.
> Make smooth scroll offset dynamic.

- apps/pattern-lab/src/_patterns/02-components/button/35-button-align-items.twig
- packages/components/bolt-button/src/_button.mixins.scss
- packages/components/bolt-button/src/button.scss
- packages/components/bolt-button/src/button.twig
Resolves http://vjira2:8080/browse/BDS-438
The bug turned out to be the one described here: https://github.com/philipwalton/flexbugs/issues/236
I used the same workaround from that ticket.  Considerations for this PR:
- Does the naming of `c-bolt-button__inner-wrapper` make sense?
- Could this change conceivably cause other regressions?
> BDS-438 Button alignment safari

- apps/pattern-lab/.boltrc.js
- apps/pattern-lab/.patches/configurableSchemaErrorReporting.patch
- apps/pattern-lab/composer.lock
- apps/pattern-lab/composer.patches.json
- apps/pattern-lab/src/_patterns/04-pages/30-product-pages/-product-t3.twig
- apps/pattern-lab/src/_patterns/04-pages/60-d8-homepage/-10-d8-homepage-alt.twig
- apps/pattern-lab/src/_patterns/04-pages/60-d8-homepage/-15-d8-homepage-video-band.twig
- apps/pattern-lab/src/_patterns/04-pages/70-d8-agenda-manager/-agenda-manager-detail.twig
- packages/build-tools/utils/config-store.js
- packages/build-tools/utils/config.schema.yml
Resolves http://vjira2:8080/browse/BDS-369
This PR makes the following changes:
- Adds a new Bolt configuration option called `schemaErrorReporting` that can be set to `none`, `console`, or `cli`.  It defaults to `console`, which means errors get printed to the browser js console (current behavior).
- Sets `schemaErrorReporting` in our pattern-lab app to be `cli`, which means schema errors will be reported on the command line and the build will not update.
- Fixes all outstanding schema errors in our pattern-lab app so we're starting with a clean slate
Note that adding the config option requires a patch to the basalt-inc/twig-tools project.  Since the patch relies on Bolt namespaced config, it's not appropriate for a PR against that project.  Some longer-term solutions (maybe for after …
> BDS-369 louder schema errors

- packages/build-tools/create-webpack-config.js
Need this to work with the max breakpoint calc of `-0.001em`.
> Fix: increase sass math precision to 3 decimals

- packages/build-tools/create-webpack-config.js
See my [comment on WWWD-2139](http://vjira2:8080/browse/WWWD-2139?focusedCommentId=43391&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-43391) for some of the back story.
In summary, adding a `.broswerslistrc` file to the Drupal theme fixes the autoprefixer issues, but then we have duplicate browser requirement lists.  This commit seems to accomplish the same thing.  Outstanding questions:
- Are the browser requirements in `@bolt/config-browserlist` accurate?  They seem really aggressive.  But if they are right, I at least need to update this PR to match them.  And the ones I put in this PR are really just placeholders.
- If we want to specify browser requirements as this PR does (i.e. as inline options), we should probably remove/deprecate …
> RFC [DO NOT MERGE]: Fix autoprefixer in Drupal builds (WWWD-2139)

- apps/pattern-lab/.boltrc.js
- packages/components/bolt-icon/icon.schema.yml
(No Jira issue)
@sghoweri I'll be honest, I'm disappointed that I have to create this PR to get this working again.  Here's the sequence of events as I see it:
- I set up an automated test to make sure we followed our own schema in pattern lab
- You disabled the automated test when it failed because you couldn't figure out why it was breaking
- I helped you by fixing the (legitimate) schema errors you had committed and merged
- You left the test disabled (I realize I could have re-enabled it myself-- I suppose I was hoping you would take the initiative since you had done the disabling)
- You committed and merged additional code that again broke the schema (again, legitimate errors: you had forgotten to update the icon yaml file when adding a new icon)
- I recognized that schema validation …
> Fix newly broken schema, re-enable louder schema errors

- packages/components/bolt-navbar/src/navbar.scss
Resolves http://vjira2:8080/browse/BDS-464
- To reproduce the original issue, see http://vjira2:8080/browse/WWWD-2296
- Review this code and confirm that it makes sense.  There is no demo where you can see it in action-- you can create a temporary one by making the title of one of the navbar demos in pattern lab as long as the one in Drupal.  Do so here: https://fix-bds-464-prevent-navbar-icon-being-overlapped-safari-9.bolt-design-system.com/pattern-lab/?p=components-navbar--centered
> BDS-464 prevent navbar icon being overlapped safari 9

- packages/components/bolt-device-viewer/src/_device-viewer--iphone8.scss
Resolves http://vjira2:8080/browse/BDS-454
Fixes device viewer button positioning, especially for landscape devices on small screens
At first, I tried using the same approach used elsewhere in this file (multiplying pixels by 100% and dividing by the total height or width of the device).  However, it didn't work well because the percentages of some of these buttons are actually based on the size of their parent, not the total height of the phone.
Additionally, to be frank, all these measurements should have been percentages all along-- the pixel measurements are meaningless and arbitrary, and trying to preserve them adds complexity with no advantage.
- Go to https://bolt-design-system.com/pattern-lab/?p=viewall-components-device-viewer, set the screen size to about 350px.  Observe that …
> BDS-454 Make device viewer button size relative

- packages/components/bolt-nav-indicator/nav-indicator.js
Resolves WWWD-2336. Gumshoe wasn't initiating correctly because it was occasionally firing before the nav priority was ready.
> Fix issue with event listener in nav indicator.

- packages/components/bolt-video/src/_videojs-enhancements.scss
http://vjira2:8080/browse/BDS-511
Add shadows to play button so it doesn't bleed into the same color video background.
Marketing raised a concern about the their videos using the brand yellow as the background color, this will add a separation between the yellow play button and a yellow video background.
Pull down the branch and go to any video demo page. Use browser inspector to change the video thumbnail HTML element to use brand yellow as the `background-color`.
> Fix: add shadow to video play button

- .github/PULL_REQUEST_TEMPLATE.md
(No issue)
Adds a template for Github PR descriptions
Helps standardize our PR descriptions.  See https://blog.github.com/2016-02-17-issue-and-pull-request-templates/
Is the text I included in the template adequately useful?  Should we just include the headings without help text that you have to delete every time?
I _think_ we have to merge this into master in order to test.  Once merged:
- Create a new PR
- Confirm that the description for the PR is pre-populated with the markup in .github/PULL_REQUEST_TEMPLATE.md
> feat: Add Github PR template

- packages/components/bolt-video/src/_videojs-enhancements.scss
http://vjira2:8080/browse/BDS-495
http://vjira2:8080/browse/WWWD-2367
Prevent scrollbar from appearing on video overlay unless absolutely necessary.
Stakeholders were pretty adamant about not seeing scrollbars in the video overlay.  This takes previous measures a step further still without hindering usability.
Specifically, this removes the top and bottom padding from the overlay.  It's vertically centered anyway, so this only affects cases where the content is slightly too large to fit vertically.  In those cases, the share content now presses closer to the top and bottom of the video player without activating the scrollbar.  However, the scrollbar still activates if the content would actually be cropped.
- Go to the videos page `pattern-lab/?p=viewall-components-video`
- Make the …
> feat: Remove all vertical padding on video share overlay (BDS-495)

- packages/components/bolt-form/src/form.js
http://vjira2:8080/browse/BDS-509
http://vjira2:8080/browse/WWWD-2345
Prevent Drupal webforms javascript from triggering form field error display
As summarized in my comment on http://vjira2:8080/browse/WWWD-2345, when external javascript (on the Drupal side) triggers a blur event on one of the form fields, the Bolt form javascript assumes that the user has blurred the field and proceeds to display the form validation errors.
This PR adds a check for whether the blur event was triggered by a human or another script-- only if it's a human do we proceed to display an relevant form errors.
The way I tested was by manually making applying this change to Bolt within Drupal, rebuilding the webpack javascript with fin exec npm run build:default`, then confirming that the bug described in …
> fix: Prevent error display when form blur is triggered by js (BDS-509)

- packages/components/bolt-chip/src/chip.scss
http://vjira2:8080/browse/BDS-506
This is also branched off of https://github.com/bolt-design-system/bolt/pull/827
Convert Chip component to use new theming system.
Removed the interim theming fix in chip and then replaced with `bolt-theme` function to define colors.
Run the branch locally and do cross browser testing to make sure there's no discrepancies. 
This is how it should look:
> Wire up Chips to use theming system

- scripts/deploy.js
- tests/e2e/pattern-lab-compiling.js
With the Bolt v2.0 release, we should finish fully making the switch over to using the original design system domain name we originally wanted to start off with -- and all public URLs (like Github) reference: https://boltdesignsystem.com.
This PR goes in and updates our now.sh deploy script to switch our deploy aliases + branch subdomains over so the initial Bolt v2.0 release gets a clean start.
> Epic v2: update now.sh deploys to use boltdesignsystem.com domain

- packages/components/bolt-share/src/share.twig
http://vjira2:8080/browse/WWWD-2454
Prevent auto-escaping of patterns included within the Share component
Auto-escaping is not enabled in Pattern Lab, so you won't see this issue on the PL side.
Auto-escaping _is_ enabled on the Drupal side, as it should be for security.  However, one of the side affects of the way the escaping is done is that if you set a variable to the result of an include function, the output will be escaped HTML.  In the example below, link1 will be escaped HTML, while link2 and link3 will print as rendered links
```
{% set link1 = include("@bolt-components-link/link.twig", {
text: "Link 1",
url: "#!"
}) %}
{% set link2 %}
{{ include("@bolt-components-link/link.twig", {
text: "Link 2",
url: "#!"
}}
}) %}
{% set link3 %}
{% include "@bolt-components-link/link.twig" …
```
> RFC: Prevent escaping of other patterns included in share

- packages/components/bolt-copy-to-clipboard/src/copy-to-clipboard.scss
- packages/components/bolt-copy-to-clipboard/src/copy-to-clipboard.standalone.js
- packages/components/bolt-copy-to-clipboard/src/copy-to-clipboard.twig
http://vjira2:8080/browse/BDS-554
http://vjira2:8080/browse/WWWD-2469
http://vjira2:8080/browse/WWWD-2468
- Allow copy-to-clipboard to work multiple times
- Change icon on copy-to-clipboard when complete to indicate success
Aside from some general cleanup (like naming conventions), one important thing this PR does is modify the transitions somewhat.  I took the liberty of speeding them up a bit because I felt impatient when using them.
I also updated the CSS transition properties a bit.  There's a weird situation where we're trying to have something finishing animating out before the next thing animates in, which is why we have the transition delay properties.  Here's the difference:
Without any transition delay:
With transition delay:
I'm all ears if there's a better way to handle that. …
> BDS-554 copy to clipboard updates

- packages/components/bolt-sticky/src/sticky.twig
The wrong schema here will throw a 500 error when loading sticky with twig_debug enabled. This fixes it.
Enabled twig_debug. View a page with the sticky component. It doesn't return a 500 error.
> Fix schema validation for sticky.

- packages/components/bolt-copy-to-clipboard/src/copy-to-clipboard.standalone.js
- packages/components/bolt-copy-to-clipboard/src/copy-to-clipboard.twig
http://vjira2:8080/browse/WWWD-2469
Fixes IE 11 bug where copy to clipboard was not resetting properly
In addition to updating javascript syntax to work with IE 11 (see https://stackoverflow.com/questions/11115998/is-there-a-way-to-add-remove-several-classes-in-one-single-instruction-with-clas), I also revert a change that turned the confirmation text into text rather than a link.  That is what we want long-term, but it introduced some regressions that I will deal with in http://vjira2:8080/browse/BDS-569.
Go to `https://bug-wwwd-2469-copy-to-clipboard-ie-11.bolt-design-system.com/pattern-lab/?p=components-share-inline` in IE 11 and confirm that copy to clipboard resets as expected in IE 11.  Also confirm that the text "copied!" does not appear in the inline share component.
> Hotfix: WWWD-2469 copy to clipboard ie 11

- packages/drupal-modules/bolt_connect/bolt_connect.routing.yml
There are specialized admin users who don't need access to Bolt admin pages, and for whom it's just distracting.
> Limit access to bolt_connect admin pages.

- apps/pattern-lab/src/_patterns/02-components/card/00-card-docs.twig
- apps/pattern-lab/src/_patterns/02-components/card/05-card.twig
- apps/pattern-lab/src/_patterns/02-components/card/10-card-band-variation.twig
- apps/pattern-lab/src/_patterns/02-components/card/15-card-with-teaser.twig
- apps/pattern-lab/src/_patterns/02-components/card/20-card-with-video.twig
- apps/pattern-lab/src/_patterns/04-pages/90-content-hub/anchor-ribbon-example.twig
- packages/components/bolt-button/button.schema.yml
- packages/components/bolt-button/src/button.scss
- packages/components/bolt-button/src/button.twig
- packages/components/bolt-card/src/card.twig
http://vjira2:8080/browse/BDS-575
- Deprecates `itemAlignment` property of button component.  Use `align` instead.
- Deprecates `left` and `right` values for `align` property.  Use `start` and `end` instead.
More important than this specific deprecation is that we're defining the workflow for deprecation.  The steps in this PR create the deprecation; after it's merged, I'll create an additional PR against 2.x to remove support for the deprecated parameter.
I've created this page in the wiki to describe the whole process: https://github.com/bolt-design-system/bolt/wiki/Deprecating-component-properties
1. Confirm schema shows as invalid if there's any usage of `itemAlignment`
- Check out this branch
- Add `itemAlignment: "start"` to button (anywhere it is removed in this PR)
- Run `cd …
> BDS-575 Deprecate itemAlignment parameter in button component

- packages/components/bolt-list/src/list.twig
- yarn.lock
http://vjira2:8080/browse/BDS-548
Replace `parentAttributes` method in bolt-list with `inner_attributes`.
As discussed with @sghoweri and @remydenton, the `inner_attributes` method is the new standard of handling outer and inner attributes. By default, all attributes go to the parent container, `inner_attributes` only render the component specific class names.
In addition, I fixed some variable names to follow our conventions.
Try to pass util classes (`u-bolt-whatever`) or other attributes to the bolt-list component and make sure they only get added to the `<bolt-list>` tag and not anything inside.
> Fix: convert bolt-list to use the inner attributes convention

- apps/pattern-lab/src/_patterns/04-pages/80-events/form-example.twig
Standalone example of rendering a form inside of a card in Bolt, wired up to use validation.
> docs: add example of standalone form inside a card

- apps/pattern-lab/src/_patterns/02-components/button/45-button-icon-only.twig
- packages/components/bolt-button/button.schema.yml
- packages/components/bolt-button/src/button.standalone.js
- packages/components/bolt-button/src/button.twig
Fixes a few things I noticed with the Button Component's `iconOnly` and `rounded` props (but mostly relating to the `iconOnly` prop). 
Besides fixing a whitespace issue I noticed in the button component's Twig template (causing issues with the `rounded` prop) and adding a missing visually hidden utility class inside the rendered web component, this PR includes two main changes:
1. Adds a new Pattern Lab demo showing the `icon-only` option that shipped in the Button component in Bolt v0.x but, for whatever reason I can't seem to figure out, doesn't appear to ever have been migrated over to Bolt v1.x's instance of Pattern Lab (even the earliest 1.x releases we've made)
2. Updates the classnames in the Button component's JS to all get run through the new `classnames` NPM package being …
> Fix / Refactor Button Component's Rounded / Icon Only Options

- apps/pattern-lab/src/_patterns/02-components/navbar/05-navbar-width.twig
- packages/build-tools/plugins/postcss-themify/src/index.js
- packages/components/bolt-nav-priority/nav-priority.js
- packages/components/bolt-nav-priority/nav-priority.scss
- packages/components/bolt-navbar/navbar.schema.yml
- packages/components/bolt-navbar/src/navbar.scss
- packages/components/bolt-navbar/src/navbar.twig
- packages/components/bolt-navlink/navlink.scss
- packages/core/utils/index.js
- packages/core/utils/wait-for-transition-end.js
- packages/core/utils/which-transition-event.js
- packages/uikit-workshop/src/sass/scss/components/_viewport.scss
Using the existing Navbar + related components to build out the updated docs site revealed several areas in need of improvement relating to animations, the need for more reasonable UI sizing on smaller screens, the ability to extend the Navbar Twig template itself in order to add UI elements not originally planned for, the need to make the Navbar component not always be full width in size (required for CSS Grid support), among others.
This PR takes full advantage of the takeaways from much more extensively using these components to make things much more polished and extensible for everybody.
> Bolt v2: Navbar, Nav Priority, and Navlink-related UI Polish

- apps/pattern-lab/src/styles/_docs.scss
- packages/core/styles/01-settings/settings-themes/index.scss
Updates all link colors on dark themes to be white (not just headline links). 
This was an intentional design decision made on the v1.x version of Bolt that needs to carry over to the v2.x version.
> fix: update all link colors on dark themes to be white

- apps/pattern-lab/src/styles/_docs.scss
- packages/core/renderers/bolt-base.js
- packages/core/styles/01-settings/settings-themes/index.scss
- Fixed useShadow check #877
- Updated all link colors on dark themes to be white (not just headline links) #878
> Bolt Release: v2.x

- packages/components/bolt-list/index.scss
- packages/components/bolt-list/src/list.scss
http://vjira2:8080/browse/BDS-634
Remove margin overflow from bolt-list that breaks page layout.
Margin-right was used before to determine space between items, this actually pokes out of its container and messes up the layout. The method has been changed to margin-left instead and there is no overflow issue.
Pull down the branch and navigate to the List component view all page, make sure there is no side scrolling whatsoever.
> Fix: bolt-list margin overflow

- packages/components/bolt-icon/src/icon.scss
http://vjira2:8080/browse/WWWD-2624
http://vjira2:8080/browse/WWWD-2625
Fix incorrect icon color in Edge
- In Edge, go to `pattern-lab/?p=components-headline-link-variations` on the 2.x branch before this commit.  Confirm the icons are missing.
- In Edge, go to `pattern-lab/?p=components-headline-link-variations` on this branch.  Confirm the icons are present.
> fix: Fix icon color in Edge

- packages/components/bolt-share/src/share.scss
N/A
Fixes a bug that the `bolt-share` links don't have any transition defined.
Adding in the global transition for the `bolt-share` CSS, so that it feels consistent with other links.
Pull down the branch and navigate to the Share view all page, hover over the links to see the smooth transition.
> Fix: add transition to bolt-share link styles

- packages/components/bolt-background/src/background.scss
http://vjira2:8080/browse/WWWD-2633
Ensure background overlay covers entire background
This feels like a legitimate bug in Chrome, but I wasn't able to find any reports of it.  The solution is certainly hacky-- I'm open to other suggestions.
The most reliable way to reproduce the issue for me was to go to these three pages in Chrome version 69 (you may have to adjust the width of your browser as it comes and goes). 
https://www.pega.com/
https://www1.pega.com/products/crm-applications/marketing
https://www1.pega.com/services/partnerships
The brief test is to manually apply the CSS updates from this PR using developer tools.  For full testing, review Bolt pages that have backgrounds with overlays across different browsers.
> WWWD-2633 Ensure background overlay covers entire background

- apps/pattern-lab/src/_patterns/04-pages/05-homepage/-01-homepage-w-background-video.twig
- packages/components/bolt-icon/src/icon.scss
http://vjira2:8080/browse/WWWD-2642
Prevent icons from overlapping background video
This creates a stacking context for icons.  Approach is based on #864 where a similar issue was seen with device viewer overlapping the background video.
- On this branch, go to `/pattern-lab/?p=pages-homepage-w-background-video`.  Confirm that you see a `marketing` icon to the right of the text "What's Trending".
- In browser developer tools, inspect the icon and disable the line "transform: translate3d(0, 0, 0);" on the `<bolt-icon>` element (the fix in this PR's second commit).
- Click "Toggle Video" to open the video
- Confirm that the marketing icon displays on top of the video
- Reload `/pattern-lab/?p=pages-homepage-w-background-video` to clear the changes made in developer tools
- Click "Toggle …
> WWWD-2642 Prevent icon from overlapping background video

- apps/bolt-site/.boltrc.js
- apps/pattern-lab/.boltrc.js
- jest-global-setup.js
- jest.config.js
- packages/build-tools/cli.js
- packages/build-tools/create-webpack-config.js
- packages/build-tools/plugins/postcss-themify/src/index.js
- packages/build-tools/tasks/task-collections.js
- packages/build-tools/tasks/webpack-tasks.js
- packages/build-tools/utils/config-store.js
- packages/build-tools/utils/config.schema.yml
- travis.sh
A few related issues with the Bolt build tools cropped up when used in certain configurations that our Travis CI tests and builds weren’t checking against. 
Relating to this PR specifically, running the non-prod version of the Webpack build would compile as expected, however wouldn’t exit the task when complete in at least 3 scenarios: 
- Running via the Webpack CLI directly without
- Compiling via the Bolt CLI’s `start` or `build` commands, without the prod flag or prod option enabled in the `.boltrc' config file
- or via the Build Tool’s Webpack compile task — as I discovered when testing updates to have Jest compile a slimmed down version of the build
This appears to be related to the new Bolt Themify PostCSS plugin’s internal caching system configured to watch for local file changes …
> Hotfix for Bolt v2.1.0-beta.0 Build Tools Issues

- apps/pattern-lab/src/index.js
- packages/global/styles/04-elements/_elements-page.scss
- packages/uikit-workshop/package.json
- packages/uikit-workshop/src/html/index.html
- packages/uikit-workshop/src/html/partials/modal.html
- packages/uikit-workshop/src/sass/scss/01-abstracts/_mixins.scss
- packages/uikit-workshop/src/sass/scss/02-base/_body.scss
- packages/uikit-workshop/src/sass/scss/04-components/_header.scss
- packages/uikit-workshop/src/sass/scss/04-components/_modal.scss
- packages/uikit-workshop/src/sass/scss/04-components/_navigation.scss
- packages/uikit-workshop/src/sass/scss/04-components/_pattern-info.scss
- packages/uikit-workshop/src/sass/scss/04-components/_tabs.scss
- packages/uikit-workshop/src/sass/scss/04-components/_viewport.scss
- packages/uikit-workshop/src/sass/scss/05-themes/_light-theme.scss
- packages/uikit-workshop/src/sass/scss/05-themes/_sidebar-theme.scss
- packages/uikit-workshop/src/scripts/components/pl-layout/pl-layout.js
- packages/uikit-workshop/src/scripts/components/pl-layout/pl-layout.scss
- packages/uikit-workshop/src/scripts/components/pl-search/pl-search.scss
- packages/uikit-workshop/src/scripts/patternlab-pattern.js
- yarn.lock
Misc bug fixes + cross-browser related updates to Pattern Lab's UI
> Note the extra whitespace on the left and right sides when viewing on a notched device like the iPhone XS Max
> Safari UI bug with the dropdown buttons + global UI bug with the background color
> IE 11 rendering bug with the side nav layout
> Full screen support + responsive UI layout via the new `viewport-fit` meta tag + CSS `env` constants: https://css-tricks.com/the-notch-and-css/ 
> Fixed dropdowns + fixed default `<button>` styles in Safari
> Fixed layout bugs in IE 11
In particular, this PR:
1. Fixes several mobile, Safari and IE 11-specific issues encountered in local dev testing (like default browser-specific styles for buttons and input elements)
2. Fixes major scrolling issues seen on mobile devices while still …
> Pattern Lab UIKit Bug Fixes

- apps/pattern-lab/src/_patterns/02-components/band/band-w-pinned-content/70-band-w-pinned-content--via-combined-content-and-items-data-example.twig
- packages/components/bolt-band/band.schema.yml
- packages/components/bolt-band/src/band.twig
Related to http://vjira2:8080/browse/WWWD-2674
Adds a default `row_start` position value if no `content_row_start` config option is specified in the Band component.  
Test band + social share examples using the new CSS Grid to confirm proper placement in IE 11 + Chrome.
> Fix: Add Default `row_start` Band Component's `content`

- packages/components/bolt-icon/src/icon.scss
http://vjira2:8080/browse/BDS-704
Fixes and provides full cross-browser parity for blue and teal icons in IE
These attributes should be the last conceivable stage at which a color CSS variable might be set, i.e. any contextual CSS variables shouldn't make a difference.  We might as well keep it simple AND have parity across browsers then by just setting color values normally.
- In IE 11, go to
https://boltdesignsystem.com/pattern-lab/patterns/02-components-icon-15-icon-theme-background-shape-variations/02-components-icon-15-icon-theme-background-shape-variations.html
- Confirm that the blue and teal icons do not match other browsers and have accessibility issues on dark backgrounds:
- In IE 11, go to `/pattern-lab/patterns/02-components-icon-15-icon-theme-background-shape-variations/02-com …
> fix: Allow explicit icon color attributes to work in IE

- packages/components/bolt-video/src/_videojs-enhancements.scss
http://vjira2:8080/browse/WWWD-2678
Adjusts the size of the video play button icon to ensure it looks consistent across all screen sizes.
Due to the complexity of making the button scale with the video width, there was a subpixel issue where the play icon (drawn with CSS) was not displaying correctly at certain sizes. This is fixed by adjusting the width and height just a tiny bit.
Pull down and run the branch locally. Go to any video demo page and adjust the screen size, make sure the play button does not break in any particular size.
cc @krlucas
> Fix: bolt-video play button icon subpixel bug

- packages/components/bolt-list/src/list.scss
N/A. Found it as I was using the bolt-list component.
Prevents item styling to trickle down in nested lists.
CSS for the items are not specific enough and it was causing the styles to apply to a list inside a list, for example, using the share component as an item for the list component (share component is built with the list component). 
Pull down and run the branch locally. Try to build a page with a list component, then pass either a share component or another list component as an item. Change some prop settings on the parent list and make sure they don't affect the inner list.
> Fix: make sure item styling doesn't trickle down in a nested bolt-list

- apps/pattern-lab/.patches/beautifyHTML.patch
Disables part of our custom patch that handles auto-indenting the code displayed in Pattern Lab’s code viewer (now more closely matches the v1.x version of this: https://github.com/bolt-design-system/bolt/blob/release/1.x/apps/pattern-lab/.patches/beautifyHTML.patch)
Twig markup displayed in Pattern Lab’s code viewer should at least not be flattened to a single line while we look for a better PHP library to handle automatically removing excess white space / indents!
Before:
After:
CC @charginghawk
> fix: revert auto-indenting Twig code in PL code viewer

- apps/pattern-lab/src/_patterns/02-components/list/50-list-tag-variations.twig
- packages/components/bolt-list/list.schema.yml
- packages/components/bolt-list/src/list.scss
- packages/components/bolt-list/src/list.twig
N/A. This is discovered as I built out pages.
Fixes visual bugs when the `bolt-list`'s display prop is used in conjunction with other props such as spacing and border.
The spacing and border were not displaying correctly when `inline@whatever` display is defined, I updated the CSS to accommodate those scenarios.
Also there was a bug with the tag prop that was always making it a `ul`, now you can use the correct tag as needed.
Pull down the branch and run it locally. Go wild with a test page and try to use all the prop combos you can think off. Make sure all props are displaying as expected.
> Fix: enable bolt-list display prop to interact perfectly with other props

- apps/pattern-lab/src/_patterns/02-components/button/60-button-with-3rd-party-js.twig
- packages/components/bolt-button/src/button.standalone.js
http://vjira2:8080/browse/BDS-728
Fixes the Bolt button component's JS logic so the `ready` and `rendered` JavaScript events —recently added to the globally shared Bolt base component in v2.x when a component renders initially + re-renders, respectfully— fires as expected.
Note: a recent update made to improve the cross-browser rendering of dynamically injected buttons caused this event to stop working as expected (forgot to call `super.rendered()`, however it's worth mentioning that given the virtually undocumented nature of this update and how the how this feature was only just recently added, it's incredibly unlikely this update was getting used downstream just yet.
For reference, these events were added in the v2.x release as a possible new pattern to help with consistently binding / …
> Bug: Fix Button JS `Rendered` Event Emitted + Update Button JS Demo

- packages/components/bolt-band/src/band.twig
http://vjira2:8080/browse/WWWD-2711
Prevent double rendering of legacy content variable/block in bands
Using the conditional statement `{% if  block('band_content') | length > 0 %}` appears to require the `band_content` band to get rendered in order to perform the check, which results in the Drupal render system thinking it is rendering the content twice.  This results in bugs like the one described in http://vjira2:8080/browse/WWWD-2711.
This is unfortunately one of those things we'll probably just have to be aware of when writing future code.
I tested by applying this same fix directly in Drupal and confirming that it fixes the bug described in http://vjira2:8080/browse/WWWD-2711.  I don't know of a good way to test in Bolt directly.
> Hotfix: WWWD-2711 duplicate submissions

- packages/components/bolt-list/src/list.twig
N/A
Fixed a typo in the bolt-list twig file about the inset prop. 
The inset prop line had a typo:
```
{% set inset = inset in spacing_options ? inset : schema.properties.inset.default %}
```
Fixed it to be `inset_options`.
Pull down and run the branch locally. Make sure the inset doc pages on bolt-list are displaying correctly.
> Fix: typo in the bolt-list twig

- lerna.json
- package.json
- yarn.lock
N/A
This is a monorepo maintenance update upgrading us to the latest version of Lerna for the latest bug fixes and updates (current version is from August 28th). 
We'll need to get this in place first before I can further troubleshoot some strange behavior I've been noticing when publishing out recent Bolt updates (specifically, all packages are getting a version bump vs just the ones that have been updated)
CC @remydenton
> Upgrade lerna to latest version

- packages/build-tools/utils/webpack-helpers.js
N/A
Fixes a small issue with the recent Webpack build updates / refactor that's causes the Webpack build process to not properly emit build errors as expected when the Bolt build tools verbosity config is set to a 1 or a 2.
Currently the progress spinner does indicate that a Webpack build error has occurred, however without this fix, it doesn't actually output the error text like it's supposed to.
**Without this fix in place:**
**With the fix in place, the error with file + line number outputs as expected:**
> Fix Bolt Build Tools Not Properly Logging Webpack Errors

- packages/components/bolt-button/src/button.standalone.js
- packages/core/utils/contains-any.js
- packages/core/utils/index.js
- packages/core/utils/watch-for-component-mutations.js
N/A
Slightly refactors + breaks out the mutation observer logic currently used in the button component into it's own standalone JS utility library for reuse in Bolt core.
Confirm button components rendering to the Shadow DOM re-render as expected when slotted content added (including the correct slot classes change accordingly).
```javascript
const buttonIconBefore = document.createElement('bolt-icon');
buttonIconBefore.setAttribute('name', 'arrow-left');
buttonIconBefore.setAttribute('slot', 'before');
const buttonIconAfter = document.createElement('bolt-icon');
buttonIconAfter.setAttribute('name', 'chevron-right');
buttonIconAfter.setAttribute('slot', 'after');
const buttonElement = document.querySelector('bolt-button'); 
buttonElement.textContent = 'Hello world!'; …
```
> Refactor: Break Apart Component Mutation Observer Logic

- apps/pattern-lab/src/_patterns/02-components/grid/10-grid-row-gutter-variations.twig
- apps/pattern-lab/src/_patterns/02-components/grid/20-grid-vinset-variations.twig
- packages/components/bolt-grid/src/grid.scss
http://vjira2:8080/browse/BDS-719
Adds support for the grid component's row_gutter parameter in IE 11.
Notes:
- I did not add CSS for `row_gutter=none` since it works by default.
Questions that should be resolved before merging:
- Is it correct to use the `$bolt-spacing-values` variable for the scss loop?
- vinset doesn't appear to work as I would have expected in the examples (`pattern-lab/?p=components-grid-row-vinset-variations`).  Namely, It only adds an inset to the bottom of the grid.  Am I doing something wrong or is this a separate bug?
- On the this branch, go to `/pattern-lab/?p=components-grid-row-gutter-variations`
- Confirm that the row gutter have parity between IE-11 and other modern browsers
> Support row_gutter in IE

- apps/bolt-site/components/version-selector/version-selector.js
N/A
Updates the new Bolt version selector on the docs site to optionally allow the Bolt version being selected to open in a new tab if the ⌘ (CMD) / meta key is being pressed down at the same time. 
This is a small usability improvement to more easily allow multiple / different versions of Bolt to easily get pulled up side-by-side for comparison.
**Bolt Version Selected Opens In A New Tab**
Navigate to the updated Bolt Design System site from this PR branch (link will be below in the comments once this deploys) and try clicking on a version of Bolt from the dropdown menu while holding down the ⌘ key on your keyboard. 
Confirm this opens in a new tab as expected.
<br>
**Bolt Version Selected Opens In The Same Tab**
Navigate to the updated Bolt Design System site from this PR branch (link …
> Update Bolt version selector to optionally open in a new tab

- apps/pattern-lab/src/_patterns/02-components/button/60-button-with-3rd-party-js.twig
N/A
Updates the Button component's 3rd party JS integration demo in Pattern Lab with additional logs to help annotate the step-by-step process going on.
Latest version confirmed working in IE 11 as expected.
> Update Button Component JS Demo in Pattern Lab

- apps/bolt-site/templates/_site-footer.twig
- apps/bolt-site/templates/_site-head.twig
N/A
Adds a quick cache buster query string to the Bolt docs site head and footer’s main CSS and JS bundles.
Quick workaround to the now.sh cache not always getting cleared in certain situations — namely when aliasing an existing deployment (like taking the existing deployment that’s running on the master.boltdesignsystem.com URL alias) and remapping it to another domain (like the live boltdesignsystem.com site).
Screenshots below show some of the old CSS showing up in the new version selector UI  (before manually clearing the browser cache):
Note: we already deal with cache busting hashes in async loaded bundles — this is specifically dealing with cache busting the main entry file loaded till we get a more advanced Webpack solution wired up for this.
Confirm docs site JS and CSS loading …
> Add quick cache buster to Bolt docs site

- apps/pattern-lab/src/_patterns/02-components/navbar/40-navbar--no-links.twig
http://vjira2:8080/browse/WWWD-2764
http://vjira2:8080/browse/BDS-748
TBD
TBD
- In iPhone 6s Plus Safari, go to the newly created example of navbar without links on this branch: https://boltdesignsystem-atauusuzzv.now.sh/pattern-lab/?p=components-navbar--no-links
- Confirm that a chevron shows despite there not being nav links
> WIP: Add example of navbar without links (BDS-748)

- packages/build-tools/create-webpack-config.js
N/A
Updates the default sourcemap config settings used in Bolt's Webpack's devtool configuration for local dev. 
This PR switches us over to use the even more detailed sourcemap data when doing dev work / debugging locally after out the extra processing time this adds with the added Hard Source Cache config updates.
> Chore: Update Default Webpack Sourcemap Config Used for Local Development

- packages/build-tools/utils/bolt-versions.js
N/A
Defers running the check for available Bolt versions (the info that we display in the new version selector) if the build isn't being run in `prod` mode -- speeds up the initial boot up process when doing local dev work so no-one has to wait around unnecessarily.
- Confirm version selector logic continues to work on the staged version of the Bolt site (`prod` mode)
- Confirm that locally the check for Bolt versions that are available runs almost instantly (`dev` mode)
> Update `@bolt/build-tools` to skip Bolt version check during non-prod builds

- apps/pattern-lab/composer.patches.json
N/A
Temporarily disables the custom Pattern Lab patch that automatically indents HTML code previews in Pattern Lab + removes extra white space.
Workaround to address PHP CLI memory issues being encountered on Travis that have been causing Pattern Lab to semi-silently fail to finish compiling (resulting in 404 errors on the deployed now.sh site).
Confirm that Pattern Lab compiled as expected on the URL we grab from now.sh.
^ CC @danielamorse @adam2661 @remydenton
> Fix: Temporarily Disable “Pretty” HTML in Pattern Lab Code Viewer

- now.json
- package.json
- scripts/deploy.js
N/A
Updates now.sh CLI to latest version + switch Bolt’s deployment config to still use the previous version of the API (v1)
Should at least help a little with addressing missing deployment links on Github + avoid breaking the build till we’re ready to update to now.sh’s new platform.
Confirm now.sh deploy + url alias portion of the build process completes successfully.
> fix: update now.sh deploy script

- packages/components/bolt-list/src/list.twig
N/A
Fixes an issue with the bolt-list's `inset` prop not rendering correctly.
The twig logic for the boolean `inset` prop was not written correctly. It has been updated with our latest convention on how to handle boolean values.
Run the branch locally and navigate to the bolt-list's inset demo pages, make sure the spacing is correct, and the class `.c-bolt-list--inset` is added to any `.c-bolt-list` with inset turned on.
> Fix: bolt-list inset prop twig logic

- packages/components/bolt-button/src/button.twig
N/A
Removes redundancies from and documents button CSS class sorting logic
Note that I removed a `utils` variable that doesn't exist anywhere else and wasn't documented in the schema.  I assume it was an unused relic, but let me know if not so I can put it back in.
Review the code and confirm that it will not introduce any functional changes
> refactor: Clean up button CSS class sorting logic

- example-integrations/vue/package.json
http://vjira2:8080/browse/BDS-532
Update package.json to be working with vue.js
Nohoist configuration doesn't give expected results and i can run this integration by removing caret from a version of webpack. From my perspective, that is only a workaround but at this moment i don't see a better solution.
Run this code locally, go to `example-integrations > vue` if `node_modules` exists please remove them and then run `yarn` command. After this steps please run `npm start` and check if compilation is ended with success.
> Fix Vue.js - Exmaple Integration

- packages/components/bolt-code-snippet/src/code-snippet.standalone.js
http://vjira2:8080/browse/BDS-543
Fix to prevent this special characters `&, <, >` be escaped.
Update `code-snippet` component.
Run this code locally. Run `npm start` and go to `localhost:3000/pattern-lab`. Navigate: `Styleguide > Sassdocs > View All` then on right navigation `Tools: typhography > @mixin bolt-font-family` and/or `Tools: typhography > @mixin bolt-font-size` and check if `&, <, >` are showed unescaped.
> Prevent escaping on SCSS code

- apps/pattern-lab/src/_patterns/02-components/video/65-video-with-custom-share-text.twig
- packages/components/bolt-video/__tests__/__snapshots__/video.js.snap
- packages/components/bolt-video/src/_video-tag.twig
- packages/components/bolt-video/src/_videojs-enhancements.scss
- packages/components/bolt-video/src/video.standalone.js
- packages/components/bolt-video/video.schema.yml
http://vjira2:8080/browse/BDS-519
Makes "Share This Video" text translatable by creating a new property for the `bolt-video` component
With the new `share_description` parameter, "Share This Video" could be translated on the Drupal side in either of these two ways:
```html
<bolt-video share-description="partage cette vidéo">
```
```twig
{% include "@bolt/video.twig" with {
"videoId": "3861325118001",
"accountId": "1900410236",
"playerId": "r1CAdLzTW",
"share_description": "Custom Share Text"|t
} only %}
```
Note that in the second example, if you just want to use "Share This Video", you don't need to pass a custom value for `share_description` because it will be set by default to a translatable string (i.e. one that's passed through the t function in twig).
- Go to the videos demo page …
> Translatable share text

- apps/pattern-lab/src/_patterns/02-components/code-snippet/10-code-snippet-display-variation.twig
- apps/pattern-lab/src/_patterns/02-components/code-snippet/15-code-snippet-language-variation.twig
- apps/pattern-lab/src/_patterns/02-components/code-snippet/20-code-snippet-syntax-variation.twig
- packages/components/bolt-code-snippet/src/code-snippet.standalone.js
- packages/components/bolt-code-snippet/src/code-snippet.twig
http://vjira2:8080/browse/BDS-543
Apply escaping to all languages in code snippet component.
Changes are only in a js file. It's simple remove of variable and escape without checking language.
Run this code locally. Go to `localhost:3000/pattern-lab`. Navigate: `Styleguide > Sassdocs > View All `then on right navigation Tools: `typhography > @mixin bolt-font-family` and/or `Tools: typhography > @mixin bolt-font-size` and check if `&, <, >` are showed unescaped. You can create new pattern-lab page and apply to it: `{% include "@bolt-components-code-snippet/code-snippet.twig" with {
display: "block",
lang: "html",
content: "&lt;bolt-list&gt;
&lt;bolt-list-item&gt;&lt;/bolt-list-item&gt;
&lt;bolt-list-item&gt;&lt;/bolt-list-item&gt;
&lt;bolt-list-item&gt;&lt;/bolt-list-item&gt; …
> Prevent escaping in all languages

- apps/pattern-lab/src/_patterns/04-pages/20-d8-press-and-media/00-d8-news-landing.twig
- apps/pattern-lab/src/_patterns/04-pages/20-d8-press-and-media/05-d8-browse-page.twig
- apps/pattern-lab/src/_patterns/04-pages/20-d8-press-and-media/20-d8-details-page-press.twig
- apps/pattern-lab/src/_patterns/04-pages/40-d8-content-hub/00-sticky-navbar.twig
- packages/components/bolt-copy-to-clipboard/copy-to-clipboard.schema.yml
- packages/components/bolt-share/share.schema.yml
http://vjira2:8080/browse/BDS-836
Fixes schema formatting for components with multiple deprecated props
In addition to fixing the issue, I've also updated the [deprecations wiki page](https://github.com/bolt-design-system/bolt/wiki/Deprecating-component-properties).
On master, add a copy-to-clipboard component anywhere in pattern lab using the following deprecated syntax, then start pattern lab:
```
{% include "@bolt-components-copy-to-clipboard/copy-to-clipboard.twig" with {
text_to_copy: "this property is required",
url: "this property shouldn't be here since it's deprecated"
} only %}
```
The command line will not fail with an error-- it should.
On this PR branch, repeat the above.  Pattern lab should fail when building with a warning about invalid schema usage.
> fix: Update schema syntax when multiple props are deprecated

- package.json
- packages/components/bolt-button/src/button.standalone.js
- packages/core/polyfills/index.js
- packages/core/renderers/renderer-lit-html.js
- yarn.lock
http://vjira2:8080/browse/BDS-840
Swaps out our `document-register-element` polyfill with Google's seemingly more predictable https://github.com/webcomponents/custom-elements polyfill -- workaround to address rendering inconsistencies reported in IE 11 and Edge,
- No component-level functional changes and no updates needed in Drupal other than pulling in this latest version of Bolt.
- Also includes necessary dependency bump on `npm-run-all` to not require `flatmap-stream` as an upstream dependency
- Fixed eslint / prettier warning that would have caused the Travis build on this to fail (unrelated to the reported issue)
Confirm the server-side rendered injected card demo works and renders as expected in IE 11 and Edge: The URL path for this should be: …
> Hotfix: Update custom elements polyfill

- packages/core/elements/replace-with-children/index.js
- packages/core/polyfills/index.js
- packages/core/renderers/bolt-base.js
BDS-840
Bolt core Javascript updates related to more consistent cross-browser rendering when dealing with dynamically injected content rendering as expected.
Supersedes #992 (reverts previous update swapping out the custom element renderer); instead this PR makes two small updates to Bolt core based on local testing in IE 11:
1. Simplifies the `<replace-with-children>` element to not use any extra libraries or renderers to help speed up the initialization time + reduce the risk of the component re-rendering instead of automatically removing itself when booting up.
2. Adjusts the constructor method in bolt-core to return itself (needed when using the document-register-element polyfill) + remove the connectedCallback method which I suspect may be causing extra unnecessary component …
> Hotfix: Bolt Core Rendering Updates

- apps/pattern-lab/src/_includes/utils/schema-docs.twig
http://vjira2:8080/browse/BDS-847
Adds the ability to hide or show certain props in the Pattern Lab schema table.
Each prop in the schema table should have the ability to hide or show, in case a developer does not want to expose an internal prop from being consumed by a design system user. Hence the option to hide or show it in the schema table on the Pattern Lab site.
Try to add `hidden: true` to any prop in a component's schema, make sure it doesn't show up in Pattern Lab anymore.
> Add the ability to hide or show a prop in the schema table on the Pattern Lab site

- apps/bolt-site/components/layout/layout.scss
N/A
CSS fix to prevent the Bolt version selector from overlapping the off-canvas / side-nav on medium-ish screen sizes as reported by @joekarasek. 
Resets the z-index for the Bolt Docs site off-canvas nav back to `auto` on wider screens to prevent the different component's z-indexes from colliding.
Confirm the version selector dropdown no longer is incorrectly overlapping the off-canvas nav on larger screen sizes (screenshot below of what we should expect to confirm this is working):
> Fix: Address Nav Overlap Issue w/ Dropdown Selector

- apps/pattern-lab/src/_patterns/02-components/link/20-custom-element-links.twig
- packages/components/bolt-link/src/_link-macros.twig
- packages/components/bolt-link/src/link.js
- packages/components/bolt-link/src/link.scss
- packages/components/bolt-link/src/link.twig
- packages/core/renderers/renderer-lit-html.js
http://vjira2:8080/browse/BDS-865
There is unwanted space around bolt-links that is revealed once links are set to display `inline`.
Whitespace lies in and around the link and between the link's slot tags. Upon debugging, I found that this space could only be closed by removing the line breaks added by Prettier when formatting lit-html template markup.
For example, this code:
```
>${innerSlots}</a
>
`;
```
Must be changed to:
```
>${innerSlots}</a
>`;
```
Otherwise, the line break before the closing tick will add a space after the inner anchor. Same issue applies to `slot` tags. All spaces around tags needed to be closed, **including some on the bolt-base class**.
Also, if a link is to be displayed `inline`, the markup itself must be in a single line, i.e.
```
<bolt-link url="#!">Link …
```
> Remove space around inline links

- packages/core/polyfills/index.js
http://vjira2:8080/browse/BDS-861
Updates the Bolt Core polyfill loader test to more specifically check for IE 11 (to opt out of loading the Shady DOM polyfill) — intended to address a noticeable performance hit with Bolt v2.2.0.
- Confirm overall JS functionality continues to work as expected
- Confirm update fixes perf hit in IE 11 — recommend checking out 
https://fix-update-polyfill-loader-ie11-check.boltdesignsystem.com/pattern-lab/patterns/04-pages-15-d8-product-pages--product-t3-extra-videos/04-pages-15-d8-product-pages--product-t3-extra-videos.html especially 
CC @margoromo @remydenton @semiuniversal @krlucas @charginghawk
> Hotfix: Update Bolt Core Polyfill Loader Test

- packages/core/elements/index.js
- packages/core/elements/replace-with-grandchildren/index.js
- yarn.lock
N/A
Fixes the broken `<replace-with-grandchildren>` helper element on master -- related to component lifecycle event updates recently made to the `<replace-with-children>` element that are being extended.
> Fix Broken `replace-with-grandchildren` helper element on master

- docs-site/src/templates/_page-header.twig
N/A
Revert renaming the top-level nav link on the docs site for the time being.
CC @mikemai2awesome @margoromo
> chore: revert renaming the components section on the docs site

- docs-site/src/components/pattern-lab-hacks/pattern-lab-hacks.scss
- docs-site/src/components/pattern-lab-utils/docs.twig
- docs-site/src/components/schema-form/component-explorer.js
- docs-site/src/components/schema-form/component-explorer.scss
- docs-site/src/components/schema-form/index.js
- docs-site/src/components/schema-form/schema-form.js
- docs-site/src/components/site-layout/site-layout.scss
- packages/core/package.json
- yarn.lock
http://vjira2:8080/browse/BDS-879?filter=-1
UI cleanup + overall improvements to the new component explorer component on the boltdesignsystem.com site. 
These updates should help speed up the initial and subsequent component being rendered + improves the accuracy of the component re-renders (via splitting apart the React JSON Schema Form UI into a Preact-specific component and decoupling this from the rendered component via Lit-HTML...)
Funny enough, no longer rendering this component preview in an iFrame helps a TON with the overall performance of this!
- Check out the button and navbar docs pages in Pattern Lab and verify the component explorer is rendering as expected
- Spot check a few other component docs pages to verify the top section of the page still check out OK (even though the …
> Component Explorer Improvements + Speed Boost

- docs-site/src/pages/pattern-lab/_patterns/02-components/card/30-card-link-variations.twig
- docs-site/src/pages/pattern-lab/_patterns/02-components/card/45-card-with-web-component.twig
- packages/components/bolt-button/src/button.standalone.js
- packages/components/bolt-button/src/button.twig
- packages/components/bolt-card/__tests__/__snapshots__/card.js.snap
- packages/components/bolt-card/card.schema.yml
- packages/components/bolt-card/src/_card-link.js
- packages/components/bolt-card/src/_card-link.scss
- packages/components/bolt-card/src/card.js
- packages/components/bolt-card/src/card.twig
- packages/components/bolt-link/src/link.js
- yarn.lock
- http://vjira2:8080/browse/BDS-911
- http://vjira2:8080/browse/BDS-912
1. Update `BoltCardLink` to extend `BoltAction` class instead of `BoltLink`.
2. Update `BoltButton` component to set `target` attribute on initial semantic anchor element.
1. `BoltCardLink` was extending `BoltLink` which meant it always output an anchor element and required an `href`. Now, it outputs an anchor *or* a button depending upon the presence of the `url` attribute.
2. `BoltButton` was not setting the `target` attribute on the semantic anchor tag inside the component. Now, if there is a semantic anchor without a `target` attribute, and `target` prop is set on the component, that attribute will be set on the anchor. This bug was discovered while QA'ing `BoltCardAction`, so fixing it now.
- Go to [Card with …
> Bolt Card Link and Action updates

- docs-site/src/components/schema-form/component-explorer.js
- packages/build-tools/api/index.js
- packages/twig-renderer/twig-renderer.js
http://vjira2:8080/browse/BDS-913?filter=-1
Speed up response times for the new in-browser component explorer. [Testing Steps](https://github.com/bolt-design-system/bolt/pull/1034#user-content-testing-steps)
Speeds up the response times for the in-browser component explorer by allowing the Twig renderer to conditionally allow certain requests to keep the service alive under the hood (ie. in-browser API requests) while having other services (like the static site generator or Jest snapshot tests) automatically opt out of `keepAlive` to help prevent runaway tasks that don't exit when expected. 
Re-rendering times (when you change content in the component explorer form) are especially faster when compared to the latest that's up on master!
<h2 id="testing-steps">Testing Steps</h2>
> Speed Up Component Explorer Rendering Times

- packages/components/bolt-button/src/_button.mixins.scss
http://vjira2:8080/browse/BDS-660 (follow up to #987).
Fixes a sass syntax error in introduced as part of the button radius updates in #987
@mikemai2awesome pointed out that some button corners had lost their radius, e.g.
https://boltdesignsystem-tsabjixlew.now.sh/pattern-lab/?p=components-custom-element-buttons
https://boltdesignsystem-tsabjixlew.now.sh/pattern-lab/?p=components-video-show-meta-title-and-duration
https://boltdesignsystem-tsabjixlew.now.sh/pattern-lab/?p=components-video-injection-test
should be 
I'm stumped as to how the existing syntax worked for other buttons as clearly `map-get()` is the correct sass function, not `index()`.   
View the URLs above in the build branch for this PR and confirm the corners have a 3px radius.
> fix: Replace index() sass function with map-get()

- packages/components/lists/bolt-list/src/_list-item.js
- packages/components/lists/bolt-list/src/list.scss
http://vjira2:8080/browse/BDS-926
Fixed an issue with the inline list's horizontal alignment in IE11, and props not rendering in real time when using the web component.
In IE11, the inline bolt-list was not filling the available space of a container, so the alignment was not able to display correctly. A simple CSS line to make the bolt-list parent full width fixes the issue.
Also @sghoweri fixed a bug with the JS context, instead of this:
```javascript
static get consumes() {
return [
[
ListContext,
['tag', 'spacing', 'inset', 'separator', 'display', 'align'],
],
];
}
```
It's changed to this:
```javascript
static get consumes() {
return [
[ListContext, 'spacing'],
[ListContext, 'tag'],
[ListContext, 'inset'],
[ListContext, 'separator'],
[ListContext, 'display'],
[ListContext, 'align'], …
```
> Fix: inline list alignment

- packages/components/lists/bolt-li/src/li.scss
- packages/core/styles/02-tools/tools-ie11-only/README.md
- packages/core/styles/02-tools/tools-ie11-only/_tools-ie11-only.scss
- packages/core/styles/index.scss
- yarn.lock
N/A
Adds a SCSS mixin for Bolt devs to define IE11 CSS.
Created `bolt-ie11-only` mixin under tools in the core. This will make it easier every time we need to write CSS that only applies to IE11.
1. Run the branch locally.
2. Add the following test code to any component CSS to target that component:
```scss
@include bolt-ie11-only {
* {
background-color: red !important;
}
}
```
3. Make sure whatever you targeted turned to red.
> Dev tool: IE11-only SCSS mixin

- docs-site/src/components/site-layout/site-layout.scss
- docs-site/src/templates/_site-head.twig
- nightwatch.js
http://vjira2:8080/browse/BDS-1016
Hotfix to address a `display: flex` + `min-height` related layout issue in IE 11 and Firefox that was causing certain bands to display incorrectly on the Bolt docs site -- reported by @mikemai2awesome 
Confirm fix working in IE 11 and Firefox by checking the band demos in PL on the docs site.
> Hotfix: Band / Height Issue In IE 11 & Firefox

- docs-site/src/pages/pattern-lab/_patterns/02-components/link/20-link-valign-variations.twig
- packages/components/bolt-link/src/link.scss
N/A
Fixes a regression with the link text and icon spacing.
Reverts back the CSS to make the link text and icon spacing stay the same as last release.
Run the branch locally and compare the link demo page between local and 2.2 on the bolt website. Make sure the spacing did not change.
> Fix: link text and icon spacing

- .travis.yml
- LICENSE
- lerna.json
- scripts/deploy-branch-alias.js
- scripts/deploy-tagged-release.js
- scripts/deploy.js
- scripts/release/after-release.sh
- scripts/release/rc-release.sh
- scripts/release/release.sh
- scripts/report-nightwatch-results.js
- scripts/utils.js
- scripts/utils/branch-name.js
- scripts/utils/handle-now-aliases.js
- scripts/utils/travis-vars.js
http://vjira2:8080/browse/BDS-1024
Implements several housekeeping updates, improvements and fixes to our DevOps CI / CD process to continue to improve how smooth we ship Bolt releases. There's still more work to be done but this should at least help tackle some of the more pressing issues. 
- Adds logic to auto-regenerate the Bolt version data used to populate the version select / dropdown menu on the boltdesignsystem.com site
- Also adds logic to the after-publish script to regenerate and include this updated data after a release
- Updates our post-publish logic + root lerna.json config to try and fix the tagged version mis-match issues. This issue has been causing Lerna to think every single package in Bolt has been changed since the previous release (vs only a handful at times)
- …
> Publishing / Deployment-related DevOps Fixes

- .travis.yml
N/A
Removes the extra Github Checks API call that’s causing one of our status checks to never fully finish running. 
- Confirm all Github Checks all finish running successfully.
> fix: remove extra status call to Github Checks API

- package.json
- scripts/package.json
- scripts/report-nightwatch-results.js
- yarn.lock
Re-testing Nightwatch test reporting reliability after adding a wrapper around the node-fetch library to auto-retry failed requests that return a 500-series error.
Potential solution to infrequent / sometimes flaky serverless reliability.
> WIP: Testing Automatic Fetch Retries For Nightwatch Testing

- packages/drupal-modules/bolt_connect/src/BoltConnectTwigNamespaces.php
None
Most of the performance issues I'm observing in local are related to disc I/O. And a large portion of that was caused by this function in bolt_connect module that runs any time a twig template is used for the first time.
The impact may be mitigated on cloud with twig caching, but not in all cases. And developers in local disable twig caching, causing a severe impact.
These changes add a basic persistent cache to the twig namespace path discovery.
Confirm twig namespace paths are still discovered correctly.
> feat: add persistent caching to twig namespace path discovery.

- packages/components/bolt-teaser/src/teaser.twig
- http://vjira2:8080/browse/BDS-1030
In IE, content is disappearing from the first band on [this page](https://v2-3-0.boltdesignsystem.com/pattern-lab/patterns/04-pages-00-full-page-theming-01-full-page-theming--xlight/04-pages-00-full-page-theming-01-full-page-theming--xlight.html). Removing the 'striptags' filter from the teaser component fixes the problem.
Using the 'striptags' filter on `bolt-teaser` text, causes twig to render *only* the anchor tags, sans `bolt-link` custom element, like so:
```
<a href="google.com" is="shadow-root" class="c-bolt-link  c-bolt-link--display-inline c-bolt-link--valign-center">Pega Customer Service</a>
```
In IE only, this results in everything inside the band getting replaced with *just* the link when web components boot up.
A simple fix for this is to …
> Fix IE disappearing content bug

- docs-site/src/pages/docs/45-workflow-and-process/00-index.md
- docs-site/src/pages/docs/45-workflow-and-process/10-release-types.md
http://vjira2:8080/browse/BDS-734
Adds release types documentation
This is copied mostly verbatim from http://vconfluence2:8080/display/PEGAKIT/Bolt+Sprints+and+Release+Strategies.  We should probably delete that section of the Confluence page and direct readers to the docs site with a link instead once this is published to avoid duplication.
> docs: Add release documentation

- scripts/__tests__/now-url-alias.test.js
- scripts/utils/handle-now-aliases.js
- scripts/utils/normalize-url-alias.js
http://vjira2:8080/browse/BDS-1186
Updates the logic for our now.sh deploy URL aliases to ensure the alias name (based off of the name of the Git branch) doesn't exceed 63 characters long and cause the now.sh deployment to fail as seen on https://github.com/bolt-design-system/bolt/pull/1120 and https://github.com/bolt-design-system/bolt/pull/1120/checks?check_run_id=80710490
- Slightly refactors the deploy JS logic so the function that formats the URL is more easily testable
- Updates the logic to truncate URL aliases that would be 62 characters in length or longer
- Adds a few Jest tests to make sure the branch name and URL alias logic are working as expected
- Confirm the URL alias for this branch is properly truncated
- Confirm the tests for this all pass
> Hotfix: Prevent Now.sh Deploy Alias Failures 

- packages/build-tools/create-webpack-config.js
- packages/build-tools/package.json
- packages/build-tools/utils/config.schema.yml
- yarn.lock
N/A 
Adds a new `configureWebpack` advanced config option to the Bolt Build Tools `.boltrc` config to allow extending the default Webpack config generated with additional plugins, module configs, etc via [weback-merge](https://github.com/survivejs/webpack-merge).
- This was requested by @christophersmith262 as part of the ongoing Drupal theming improvements work.  
- Test adding a new plugin to the Webpack build to confirm this small addition is working as expected.
> Add Ability To Extend / Update Generated Webpack Config 

- packages/build-tools/cli.js
- packages/build-tools/utils/config-store.js
- packages/build-tools/utils/config.schema.yml
- packages/build-tools/utils/log.js
- packages/core-php/src/TwigFunctions.php
http://vjira2:8080/browse/BDS-1207
- Updates the Bolt Build Tools configuration + PHP logic to automatically enable server-side rendering in `prod` mode, disable in local `dev` mode, and provide a new `enableSSR` config option to allow SSR to be manually be enabled / disabled (overriding the default `auto` behavior).
- Should help speed up the initial compile times of Pattern Lab locally till we can get a more advanced caching system in place (prevent unnecessary recompiles when not needed). 
- Confirm these updates speed up initial boot times for local development
- Confirm server-side rendering still working as expected on the prod version of the site built on Travis.
CC @mikemai2awesome
> Improve Server Side Rendering Configuration + Auto-disable For Local Dev Perf

- packages/core-php/composer.json
The PHP package `bolt-design-system/core-php` has `phpunit` v7 as a dependency in `require` and this moves it to a dev dependency in `require-dev`. When Drupal sites that want to install Bolt PHP packages have a PHPUnit dependency that is different, it throws an install error. We just use it for testing and it is not used for run time at all.
> fix(core-php): moving phpunit from dep to devDep

- packages/components/bolt-video/src/video.scss
- http://vjira2:8080/browse/BDS-1164
- http://vjira2:8080/browse/WWWD-3278
Brightcove hides volume and other video controls below 400px. Add CSS to show these controls. This issue was fixed on .COM site. I am moving the fix back into Bolt.
- Open a [video page](https://master.boltdesignsystem.com/pattern-lab/patterns/02-components-video-05-video/02-components-video-05-video.html) on master with the browser window at < 425px wide.
- See that the volume controls do not appear.
- Run this feature branch locally and perform the same test.
- Verify on hover that the volume, time, playback-speed, and share icons are visible.
- Repeat @ < 320px and < 210px and verify the same.
Note: You must open page at the above sizes to test. Simply resizing the window will not hide the icons. That's how …
> Fix missing volume control

- scripts/utils/handle-now-aliases.js
N/A
Fixes a typo with the Github Checks API name used to report back on which Travis CI steps are pending, in-progress, and pass / fail.
This should fix the recent issue relating to 1 out of the 7 status checks incorrectly reporting back as never finishing (specifically the Now.sh basic / alias deployments):
- Confirm the Travis build for this passes + all 7 status checks finish
> Fix Github Checks API Status for Now.sh

- docs-site/.boltrc.js
- docs-site/package.json
- docs-site/src/components/banner/banner.scss
- docs-site/src/components/banner/package.json
- docs-site/src/components/banner/release-banner.twig
- docs-site/src/index.scss
- docs-site/src/templates/_page-header.twig
TBD
Replaces the previously hard-coded logic in the docs site banner component (added right before Drupalcon) to now point out if you are viewing the latest stable version of the design system, a previous version, or a new upcoming version + suggest a different version to help that distinction a lot more straightfoward.
- Also adds a package.json to the very recently added banner component so pulling this component into **older versions of Bolt** shouldn't be an issue!
No additional testing is needed until this is deployed and can get tested on a version different versions of Bolt.
> Feat: Docs Site "Bolt Release" Banner

- packages/components/bolt-blockquote/__tests__/bolt-blockquote.e2e.js
N/A
Adds 1 basic E2E cross browser Nightwatch test to the Blockquote component VRT fix in #1167
- Confirm update passes eslint and Nightwatch tests
> Add Blockquote Component Nightwatch Test

- packages/components/bolt-figure/src/figure.twig
- packages/global/styles/05-objects/objects-flag/src/flag.twig
http://vjira2:8080/browse/BDS-1293
Fixes a regression where the flag component went missing.
I started by cherry picking 9893c60, which is part of https://github.com/bolt-design-system/bolt/pull/1064.  However, I noticed that commit also updated the spacing (before/after shown below, with the narrower one being after):
To limit this PR to the bug fix only (and exclude the spacing changes), I included only a subset of the files from Mike's full PR in this PR.
- Go to https://v2-3-0.boltdesignsystem.com/pattern-lab/?p=pages-product-landing
- Confirm that flag icons don't show up to the left of the 'Marketing', 'Sales and Automation', etc list items as they did in earlier versions (e.g. https://v2-1-4.boltdesignsystem.com/pattern-lab/?p=pages-product-landing-page)
- Go to …
> Hotfix: Restore flag component

- packages/components/bolt-link/src/link.js
- packages/components/bolt-link/src/link.scss
http://vjira2:8080/browse/BDS-1292
Fixes an issue where the icon inside an inline link gets pushed to its own line. 
CSS is updated for inline links to have the last word to always wrap together with the icon. The icon will never be by itself on its own line.
1. Run the branch locally.
2. Go to this page: http://localhost:3000/pattern-lab/patterns/02-components-link-15-link-theme-variation/02-components-link-15-link-theme-variation.html
3. Adjust the page width to make the headline link to wrap to a second line, make sure the icon NEVER wraps to a new line by itself.
> Hotfix: inline link text's last word and icon wrap together

- packages/components/bolt-figure/src/figure.twig
- packages/components/bolt-link/src/link.js
- packages/components/bolt-link/src/link.scss
- packages/global/styles/05-objects/objects-flag/src/flag.twig
Addresses:
- http://vjira2:8080/browse/BDS-1293
- http://vjira2:8080/browse/BDS-1292
1. Fixed a regression where the flag component went missing. #1170 
2. Fixed an issue where the icon inside an inline link gets pushed to its own line. #1169
> Bolt v2.3.2 Hotfix

- now.json
Adds a max scale config of 1 to limit the total number of server instances running in the background. Might slow down response times for older servers that haven't been frequently accessed but should hopefully help to keep our "Premium" [now.sh v1 plan](https://zeit.co/account/plan-v1) down in the interim.
> hotfix: update now.sh scaling max config

- packages/api/index.js
- packages/api/package.json
- yarn.lock
When rendering via the `/api/render` endpoint and forgetting to include the header of `'Content-Type': 'application/json'`, then this error was seen:
```
PHP TwigRenderer Error: The response callback is expected to resolve with an object implementing Psr\Http\Message\ResponseInterface, but rejected with "TypeError" instead.
```
Without that header, the body of the request is a string, with that header, it's parsed into an object. This allows both approaches via a conditional that can lead to a `JSON.parse()`. All fixed!
Send an API request to `http://localhost:3004/api/render?template=%40bolt-components-text%2Ftext.twig` with the body:
```
{
"text": "hi"
}
```
Try it with and without the header `'Content-Type': 'application/json'`
> fix(api): handle requests w/o 'Content-Type': 'application/json' header

- packages/components/bolt-form/src/form.js
http://vjira2:8080/browse/BDS-1284
Adds an event listener to bolt inputs for a new custom `showerrors` event.
Currently, Bolt's HTML5 form validation issues are invisible until a user blurs an input field.  Additionally, only user input works for this-- scripts that fire the `onblur` event on an input intentionally do NOT reveal these errors (see http://vjira2:8080/browse/WWWD-2345 for an explanation of why we did that).
The goal of this PR is to add a way for js to intentionally reveal validation errors.  The primary use case would be when submitting a form-- if there are validation errors when the user submits, we could stop the submission and fire the `showerrors` event on any invalid field.
- Is a custom event the best way to allow javascript to show errors for a given field?
- What's …
> RFC: Allow js to reveal form input errors

- packages/components/bolt-list/src/_list-item.twig
- packages/components/bolt-table/src/table.twig
http://vjira2:8080/browse/BDS-709
Fixes character encoding string "UTF-8" when passing content into table
Removing the `join` function here fixes the bug, and _as far as we can tell_, it was an unnecessary vestige of some past problem that is no longer present.
Admittedly, removing things that don't appear to be necessary without knowing why they were originally added is a dangerous game.  In this case, the purpose of the join would be to support passing an array of renderable items for {{item.content}}.  I could not find any instance of this happening in pattern lab, and I can't think of any use case where that would be anything more than a convenience.  Given that, I think it's as low risk as you can get without knowing the origin story. 
- Go to …
> BDS-709 remove uft8

- packages/components/bolt-navbar/__tests__/navbar.js
- scripts/report-nightwatch-results.js
http://vjira2:8080/browse/BDS-1313?filter=-1
Fixes a failing Jest test + fixes our Nightwatch.js test reporting logic so the build status is correctly reported + the browser screenshots captured show up again.
1. Reduces the overall size of the Nightwatch.js test report sent back to Github so we don't exceed the max message size allowed.
2. Also adds a slight delay before starting to collect and report back on Nightwatch test results to address occasional issues with the test result asset (image) being requested not being immediately available.
3. Fixes the Navbar component's Jest test to have Puppeteer wait until page being navigated to has finished loading before the rest continuing. Addresses occasional Navbar test failures that are still popping up from time to time.
1. Does the …
> Fix Navbar Jest Test + Nightwatch Test Reporting

- docs-site/src/templates/homepage.twig
N/A
Removes a piece of junk code from the homepage.
There's a piece of development code that didn't get removed while working on the Stack component. This fix removes it and make sure the homepage is not broken.
Check the homepage and make sure there's no extra content other than the banner, the nav, the logo, the tagline, and the buttons.
> Fix: remove development code from homepage

- packages/components/bolt-action-blocks/src/action-block.twig
http://vjira2:8080/browse/BDS-1385
Temporarily re-adds the `action-block.twig` template to the action blocks package to fix an integration issue identified with the v2.4.x integration.
With this update, we re-add the renamed `action-block.twig` Twig template and point it to the now renamed `_action-block.twig` template to work around any path-related issues.
@remydenton any thoughts on this?
CC @danielamorse
> Hotfix: Add temporary `action-block.twig` Twig template alias

- packages/drupal-modules/bolt_connect/src/Controller/BoltConnectController.php
http://vjira2:8080/browse/BDS-1400
Restores missing namespaces on bolt_connect info page
When #1086 was merged, there was regression where the namespaces list on the bolt_connect module info page was now blank.  Specifically, once the data is cached on the first page load, subsequent loads don't populate the `BoltConnectTwigNamespaces->twigLoaderConfig` property.
This PR restores that list without adding extra overhead to any page except the bolt_connect info page at `/admin/config/bolt_connect/info`.
Pull this version of the module into Drupal (either Drupal Lab or an actual site) and confirm that namespaces show as expected at `/admin/config/bolt_connect/info`.
Note: while it is a regression, it's not urgent enough to warrant a hotfix all by itself.  If a 1.4.x hotfix turns out to be …
> fix: Restore Bolt namespaces	on Drupal admin info page

- packages/core/styles/01-settings/_settings-z-index.scss
- packages/core/styles/01-settings/settings-breakpoints/_settings-breakpoints.scss
- packages/core/styles/01-settings/settings-colors/_settings-colors.scss
- packages/core/styles/01-settings/settings-font-family/_settings-font-family.scss
- packages/core/styles/01-settings/settings-font-size/_settings-font-size.scss
- packages/core/styles/01-settings/settings-global/_settings-global.scss
- packages/core/styles/01-settings/settings-opacity/_settings-opacity.scss
- packages/core/styles/01-settings/settings-shadow/_settings-shadow.scss
- packages/core/styles/01-settings/settings-spacing/_settings-spacing.scss
- packages/core/styles/01-settings/settings-themes/index.scss
- packages/core/styles/index.scss
N/A
Adds any missing `!default` flags to the `@bolt/core` style settings files to allow config options to be more easily updated and extended.
- Confirm Travis build runs successfully
- Spot check visual styles / component styles to ensure Sass compiled as expected (Jest tests and VRT should fail if this wasn't the case...)
> Chore: Add Missing @bolt/core Style Default Flags

- docs-site/src/pages/pattern-lab/_patterns/02-components/image/15-image-source-variations.twig
http://vjira2:8080/browse/BDS-1289
Remove the image examples from the docs-site where srcset is not found in bolt data. This was originally included so that all possible config options were shown, but this one is not needed for our documentation and causing confusion amongst the QA team.
Before merging, I will be sure to update release notes so that the QA team is expecting this visual change and does not flag as a regression.
n/a
- Are you ok with these demos being removed?
- Review the code changes
> feat: remove srcset not found example from image page

- packages/components/bolt-blockquote/src/blockquote.js
- packages/components/bolt-image/src/image.js
- packages/core/renderers/bolt-base.js
http://vjira2:8080/browse/BDS-1135
`getModifiedSchema()` is now used in image and blockquote components and will probably be used in more. Move it to base so that all components can benefit from the work we've already done.
I moved `getModifiedSchema()` to base and refactored it so that it accepts a list of props to be removed. Previously it was hardcoded.
The default value of `propsToRemove` is `content`. If you want to remove `content` *and* pass in additional props you must include `content` in the array, e.g. `getModifiedSchema(schema, ['content', 'prop2', 'prop3'])`.
- Run feature branch locally and view the blockquote and image demos
- Verify there are no errors or visual regressions on these pages
- Temporarily pass in additional props and log the modified …
> Move getModifiedSchema to base

- packages/components/bolt-video/src/video.scss
http://vjira2:8080/browse/BDS-1405
http://vjira2:8080/browse/BDS-1377
Hide certain video controls when video is playing in smaller screens.
Removed some CSS overrides that were forcing ALL the controls to be visible in smaller screens. Now the video player will hide volume and duration controls in smaller screens, to make sure the toolbar is not overflowing. Volume and duration controls are available natively, so they are not essential to be shown in the toolbar.
Run the branch locally, go to the video doc pages, and view those pages in small screen sizes. Make sure the toolbar fits all the controls and nothing is overflowing.
> Fix: selectively hide less essential video controls for smaller screens

- docs-site/src/pages/pattern-lab/_patterns/02-components/carousel/25-carousel-basic-variations.twig
- docs-site/src/pages/pattern-lab/_patterns/02-components/figure/15-figure-with-web-component.twig
- packages/components/bolt-figure/__tests__/__snapshots__/figure.js.snap
- packages/components/bolt-figure/src/figure.js
- packages/components/bolt-figure/src/figure.twig
http://vjira2:8080/browse/BDS-1338
Fix JS bugs in carousel component.
Carousel clones slides when `loop` is `true`. When `bolt-figure` elements were cloned they were not properly re-rendering. Update the Twig and JS so that initial tags are properly replaced by JS template each time it renders.
tbd
> Carousel | QA | Fix various JS issues

- packages/components/bolt-modal/src/modal.scss
http://vjira2:8080/browse/BDS-1431
Adjusts how the new modal component's open / close animation is handled so the animation no longer skips to being open + the close animation fades the entire container correctly.
**Before:**
**After:**
- Confirm build passes as expected
- Manually test out the updated animation
> Fix / Improve Modal Animation

- packages/components/bolt-placeholder/TESTING.md
- packages/components/bolt-placeholder/__tests__/__snapshots__/placeholder.js.snap
- packages/components/bolt-placeholder/__tests__/placeholder.js
Adding Jest snapshot tests to the Placeholder component and a TESTING.md file
Wrote and ran Jest snapshot tests for the different Placeholder variations and included testing instructions in the TESTING.md 
yarn test:js
> Placeholder | Docs | Testing and Documentation for Placeholder component

- package.json
- packages/uikit-workshop/src/scripts/components/styleguide.js
- tsconfig.json
- yarn.lock
This add type checking (not compiling) of JS files using TypeScript via `yarn test:types`. Currently there are a lot of errors coming in and fine tuning the `includes` and `excludes` properties in `tsconfig.json` would be a good start to narrow the focus would be a good idea. The big advantage from this is much better editor auto-completion.
> test: add type checking of JS using TypeScript

- docs-site/src/pages/pattern-lab/_patterns/02-components/modal/40-modal-usage-image-and-caption.twig
N/A
Fixed a typo in the image modal caption's markup that causes the caption text to not render.
`slot="footer"` was accidentally used on the figcaption container, which is a goof from an older mockup.
Run the branch locally and make sure image modal examples have captions.
> Fix: typo in image modal's caption markup

- example-integrations/drupal-lab/web/themes/bolt-starter/.boltrc--ja.js
- example-integrations/drupal-lab/web/themes/bolt-starter/.gitignore
- example-integrations/drupal-lab/web/themes/bolt-starter/__tests__/index.js
- example-integrations/drupal-lab/web/themes/bolt-starter/package.json
- example-integrations/drupal-lab/web/themes/bolt-starter/patches/@bolt+build-tools+2.5.2.patch
- example-integrations/drupal-lab/web/themes/bolt-starter/yarn.lock
- packages/build-tools/cli.js
- packages/build-tools/create-webpack-config.js
- packages/build-tools/tasks/api-tasks/bolt-versions.js
- packages/build-tools/tasks/criticalcss-tasks.js
http://vjira2:8080/browse/BDS-1527
Updates the `@bolt/build-tools` to address two indirectly related issues that were causing the original approach for generating multiple language-specific builds to not work as expected.
This PR also adds two new Jest tests to Drupal Lab to now test to confirm that this particular configuration setup continues to work as expected.
> Note: the more up to date version of this language-specific build config involves adding a new `lang: ['en', 'ja']` setting to a single `.boltrc.js` config which will compile both sets of assets to the exact same build / dist folder, albeit with non-English languages getting an extra suffix added to the filenames.
```
dist/
bolt-global.css
bolt-global-ja.css
bolt-global.js
bolt-global-ja.js
```
1. One of these changes …
> Hotfix: Fix `@bolt/build-tools` CLI `--config-file` Option

- packages/components/bolt-button/__tests__/__snapshots__/button.js.snap
- packages/components/bolt-button/__tests__/button.js
- packages/components/bolt-button/src/button.twig
http://vjira2:8080/browse/BDS-1415
Added `target` to Twig-rendered button-style link if passed in via attributes.
Currently the way to add a `target` to a button is to pass it in via Twig `attributes`. This adds the prop to the custom element but not the inner semantic `<a>`, so you have to wait until the JS kicks in for it to be added. This PR adds it to the Twig-rendered markup so that it works with and without JS.
Note: the button schema needs to be updated to include `url` and `target`. This will be handled in [a separate ticket](http://vjira2:8080/browse/BDS-1573).
- Run the `fix/button-missing-target` branch locally.
- Add this code to any button demo page:
```
{% include "@bolt-components-button/button.twig" with {
text: "This is a button",
url: "http://pega.com",
attributes: { …
```
> Button | Twig | Add missing 'target' attribute

- packages/components/bolt-device-viewer/src/device-viewer.twig
http://vjira2:8080/browse/BDS-1521
One line Twig template fix that removes an old override in the Device Viewer component that had been overriding the value set to the `sizes` prop in the nested image component. This fix allows for more optimally sized images to get auto/manually selected.
As an added bonus, this update appears to increase our Lighthouse performance scores when testing the device viewer demo page in Pattern Lab -- taking us from a 67/100 to 76/100 (on desktop)!
- Confirm tests passing as expected
- Review the device viewer demo in this PR's staged instance of Pattern Lab to confirm that the sizes prop is no longer getting overwritten (see Lighthouse test results)
CC @krlucas
> Hotfix: Remove Device Viewer Logic Overriding The Image Component's `Sizes` Prop

- packages/core/styles/02-tools/tools-repeat-rule/README.md
- packages/core/styles/02-tools/tools-repeat-rule/_tools-repeat-rule.scss
- packages/core/styles/index.scss
http://vjira2:8080/browse/BDS-1506
Add new mixin to repeat a block of styles as a separate rule-set for each selector provided.
This mixin will most often be used with selectors like `:host` which do not work properly when combined with other selectors via comma.
- Given I am running the `feature/repeat-rule-mixin` branch locally and I add the following CSS to any component's SCSS file:
```
@include bolt-repeat-rule(('html', 'body')) {
border: 1px solid red;
}
```
- When I open a page in PL, for example: http://localhost:3000/pattern-lab/patterns/02-components-link-05-link/02-components-link-05-link.html
- Then I should see a red border around the `html` and `body` elements
- When I inspect the source `bolt-global.css` file
- Then I should find the red border output as separate rule-sets, …
> Repeat Rule | Tools | Add bolt-repeat-rule mixin

- packages/components/bolt-sticky/src/sticky.scss
http://vjira2:8080/browse/BDS-1609
Updates sticky component's z-index to be lower than mega nav.
The z-index conflicts with the mega nav and the modal will be fixed by an update from Bolt and an update from Drupal:
1. Bolt changes bolt-sticky to use `z-index: bolt-z-index(nav)`
2. Drupal changes .c-page-header to use `z-index: bolt-z-index(navFixed)`
Get both updates in Drupal and make sure modals will cover up the mega nav.
> Fix: change sticky z-index to not cover up mega nav

- packages/components/bolt-modal/src/modal.scss
http://vjira2:8080/browse/BDS-1672?filter=-1
CSS fix to address quirky animation flashes reported in IE 11. 
Forcing the modal component to animate with `translate3d` + scale forces the browser's animation of this to be more accurate + less janky (especially since we're dealing with nested transform styles).
Review this page in Pattern Lab to confirm that hovering over CSS-transformed components nested inside the modal no longer jumps around in IE 11:
- pattern-lab/patterns/02-components-modal-55-modal-usage-form/02-components-modal-55-modal-usage-form.html
> Hotfix: Fix Nested Component Animations When Inside Modal

- packages/components/bolt-modal/focus-trap/focus-trap.js
http://vjira2:8080/browse/BDS-1682
Fix `focus-trap` IE-only JS error that is causing images to be distorted.
Focus-trap, a subcomponent of modal, hits an error in IE that causes downstream issues with the ratio component. Due to the error, the ratio component defaults to 1:1 or "square" which distorts most images.
The error surfaced when `bolt-modal` was placed inside a `bolt-band`. In IE the band triggers modal to re-render and throw an error. This fix prevents the error on re-render.
- Drop this code onto a Pattern Lab page and open in IE11. The image should be distorted.
```
<bolt-image
src="https://via.placeholder.com/400x200"
srcset="https://via.placeholder.com/400x200"
alt="A Rock Climber"
sizes="auto"
ratio="2/1"
></bolt-image>
<bolt-band>
<bolt-modal
width="optimal"
spacing="none" …
```
> Focus Trap | JS | focus-trap IE JS error

- packages/components/bolt-modal/modal.schema.yml
- packages/components/bolt-modal/src/modal.scss
http://vjira2:8080/browse/BDS-1678
Restores the `regular` option for the `width` prop.
CSS are added back in and schema is updated to have the prop available.
Run the branch locally and check the modal width demo page. Make sure `regular` is one of the options.
> Fix: restore regular modal width

- packages/components/bolt-modal/modal.schema.yml
- packages/components/bolt-modal/src/modal.scss
Dupe of #1292 but branched off of `release/2.x`.
> Hotfix: Fix/2.x restore regular modal width

- __tests__/monorepo-deps.test.js
- packages/generators/yeoman-create-component/package.json
N/A
Renames our Yeoman component generator NPM package name from `generator-bolt` to `@bolt/generator-bolt` to prevent future NPM publishing issues from not being under the @bolt org that @danielamorse and I had to work through during yesterday's release.
Previously Yeoman required generators to have the `generator-` prefix in the package name however it looks like the updates from https://github.com/yeoman/environment/pull/23 should have addressed this (even though the current Yeoman docs say otherwise).
I've already went ahead and told NPM to point the [old NPM package](https://www.npmjs.com/package/generator-bolt) to the new https://www.npmjs.com/package/@bolt/generator-bolt I'll be publishing as soon as this gets merged in.
> Chore: Rename Yeoman Component Generator's Package.json Name

- packages/analytics/autolink/__tests__/autolink.test.js
- packages/api/index.test.js
- packages/components/bolt-accordion/__tests__/accordion.js
- packages/components/bolt-band/__tests__/band.js
- packages/components/bolt-blockquote/__tests__/blockquote.js
- packages/components/bolt-button/__tests__/button.js
- packages/components/bolt-carousel/__tests__/carousel.js
- packages/components/bolt-headline/__tests__/__snapshots__/headline.js.snap
- packages/components/bolt-icons/__tests__/icons.js
- packages/components/bolt-link/__tests__/link.js
- packages/components/bolt-logo/__tests__/logo.js
- packages/components/bolt-modal/__tests__/modal.js
- packages/components/bolt-navbar/__tests__/navbar.js
- packages/components/bolt-ratio/__tests__/ratio.js
- packages/components/bolt-text/__tests__/text.js
- packages/generators/yeoman-create-component/generators/component/templates/component.test.js
- packages/servers/testing-server/index.js
- packages/twig-renderer/twig-renderer.js
http://vjira2:8080/browse/BDS-1653
Minor config updates that I noticed could speed up our Jest tests by quite a bit! 🎉
- Adds a missing `timeout` config to avoid hitting the default Jest timeouts.
- Updates most Jest tests that use Puppeteer to now reuse the same browser tab (saving resources and increasing load times) and now clear out the inner HTML after each test has finished running (clean up Puppeteer for the next test)
- Tweaks the default testing server template to make it easier for tests to clean out the body’s inner HTML
- Also updates Jest test suites using Puppeteer to close the Puppeteer browser tab when complete to try and help reduce system resources
<p>
</p>
> Speed Up Jest Tests By ~70% (4 minutes faster!)

- docs-site/src/components/docs-search/docs-search.scss
- docs-site/src/components/version-selector/version-selector.twig
- packages/components/bolt-navbar/src/navbar.scss
http://vjira2:8080/browse/BDS-1662
Tweaks the Navbar component's CSS rules to better handle the space between extra items added to the Navbar Title section + extra items added to the main content section of the Navbar.
- Neither of these Navbar regions are frequently used as far as I know, however I know we certainly use them with the docs site global header to add the version selector to the Title section + the docs site to the default main content section). 
This update eliminates the need to have extra spacing hacks added to these individual components since this now gets taken care of by the main component itself.
> No visible change expected
<br>
> No visible change expected
<br>
> Small expected spacing change (improvement) to our own docs site nav
<br>
> Feature: Improve Navbar Spacing

- packages/testing/testing-nightwatch/nightwatch.js
- packages/testing/testing-nightwatch/nightwatch.local.js
All my local nightwatch tests started failing. After so investigation, I found that updates to chrome that happened around version 75 required updated config. This update fixes the issue for me.
All nightwatch/selenium tests started returning the following error:
```TypeError [ERR_UNESCAPED_CHARACTERS]: Error while trying to create HTTP request for "/wd/hub/session/1f46ad787c5fe86269b8302ca2414201/element/[object Object]/click": Request path contains unescaped characters```
I found a solution to the issue here: https://github.com/nightwatchjs/nightwatch/issues/2126
Run nightwatch locally using `yarn test:e2e:quick-local`
> fix: update nightwatch config to fix chrome driver issues

- packages/components/bolt-modal/src/modal.js
- http://vjira2:8080/browse/BDS-1616
Add `toggle` method to modal.
Add `toggle` as an alternative to existing `show` and `hide` methods.
- Run locally and go to [Basic modal page](http://localhost:3000/pattern-lab/patterns/02-components-modal-05-modal/02-components-modal-05-modal.html).
- Run the following JS in the console and the modal should open:
```
document.querySelector('bolt-modal').toggle()
```
- Run it again and it should close.
> Modal | JS | Add `toggle` method

- packages/components/bolt-image/src/image.js
http://vjira2:8080/browse/BDS-1800
Fix JS error when images are rendered.
We are pushing to an array that is sometimes undefined. Add a check to prevent a JS error.
- Run branch locally: `fix/image-lazysizes-error`
- View basic image demo page and verify image loads as expected.
- In the console, run the following JS:
```
document.querySelector('body').insertAdjacentHTML('beforeend',  `
<bolt-image src="https://demo6.d8.pega.com/sites/default/files/styles/640/public/media/images/2018-11/sprint-logo-color.png?itok=reLNq5Ki" srcset="https://demo6.d8.pega.com/sites/default/files/styles/50/public/media/images/2018-11/sprint-logo-color.png?itok=tnJpDmF0 50w, https://demo6.d8.pega.com/sites/default/files/styles/100/public/media/images/2018-11/sprint-logo-color.png?itok=4-Z206MY 100w, …
```
> Image | JS | Fix JS error when images are rendered

- docs-site/src/pages/pattern-lab/_patterns/02-components/micro-journeys/30-status-dialogue-bar.twig
- docs-site/src/pages/pattern-lab/_patterns/02-components/micro-journeys/billing-micro-journey-fragments/_step-five.twig
- docs-site/src/pages/pattern-lab/_patterns/02-components/micro-journeys/billing-micro-journey-fragments/_step-four.twig
- docs-site/src/pages/pattern-lab/_patterns/02-components/micro-journeys/billing-micro-journey-fragments/_step-one.twig
- docs-site/src/pages/pattern-lab/_patterns/02-components/micro-journeys/billing-micro-journey-fragments/_step-three.twig
- docs-site/src/pages/pattern-lab/_patterns/02-components/micro-journeys/billing-micro-journey-fragments/_step-two.twig
- packages/micro-journeys/src/status-dialogue-bar.scss
https://app.asana.com/0/1126340469288208/1136467560091702
force black text; remove bolt-text passed to dialog; widen left/right padding
The problem was that `bolt-text` components embedded in `bolt-status-dialogue-bar` can only use the color of the theme text (unless you pass in an additional class in the `attributes` property). 
The solution was to only pass in `p` tags and then style the component to match the `<bolt-text font-size="xsmall">`
Check out tpattern-lab/patterns/02-components-micro-journeys-92-micro-journey-in-band/02-components-micro-journeys-92-micro-journey-in-band.html, make sure that the `dark` theme text in the dialog is visible.
> fix(status-dialogue-bar): force black text

- packages/micro-journeys/src/one-character-layout.scss
- packages/micro-journeys/src/status-dialogue-bar.scss
- packages/micro-journeys/src/two-character-layout.scss
https://app.asana.com/0/1126340469288208/1138736873218902/f
Status bars no longer overlap on mobile layouts.
> fix: mobile styling of status bars, no longer overlap

- packages/components/bolt-animate/utils.js
https://app.asana.com/0/1126340469288208/1139247289936295/f
Add debug code to bolt-animate
In with/without, I needed to see what animations were failing and why.
Having permanent debug code in place made it much easier to see.
I think we should make this permanent because animation sequencing is often tricky to debug.
```
await triggerAnims({
animEls,
stage: 'IN',
debug: true, // <- here is the flag you can now use
});
```
> feat(bolt-animate): add debug optional debug flag

- packages/editor/src/setup-bolt.js
https://app.asana.com/0/1126340469288208/1133408741134181/f
Add two starter templates (vertical and horizontal) with three icons so an editor can quickly setup up the three icon set.
All the needed components were already available in the editor. However, it would have taken several convoluted steps to re-create the layout of three icons in a group. These templates make it simple for an editor to add a three icon group to any of the standard slots. 
- Pull this branch and rebuild. 
- Go to http://localhost:3000/pattern-lab/patterns/06-experiments-micro-journeys-combos--92-micro-journey-in-themes/06-experiments-micro-journeys-combos--92-micro-journey-in-themes.html
- Turn on editing
- Select a character. Using the slot dropdowns, add a three icon group.
- Play with it. You can customize …
> feat: add three icon group for quick editor slot drop-in

- packages/components/bolt-table/src/table.js
- packages/components/bolt-tabs/src/tabs.js
- packages/core/polyfills/index.js
Quick fix to address table JS bug exposed by polyfilling `findIndex`.
> fix: comment-out findIndex polyfill for now, exposing a bug in table JS

- .boltrc.js
- packages/servers/testing-server/index.js
N/A
Precompiles Webpack vs using Webpack Dev Server to address Jest tests never running on Travis due to low memory.
> fix: manually backport Jest testing server fix added in v2.8.0-beta.1

- packages/testing/testing-utils/dependency-map.js
I had seen this error on [another build](https://travis-ci.com/bolt-design-system/bolt/jobs/235285326#L509-L530):
```
FAIL __tests__/monorepo-deps.test.js (40.529s)
510  ● Bolt Components declare dependencies in package.json if used in Twig files › pkg: @bolt/components-action-blocks
511
512    More than 1 possible Twig file found when looking for "@bolt/icon.twig".
513
514  ● Bolt Components declare dependencies in package.json if used in Twig files › pkg: @bolt/components-device-viewer
515
516    More than 1 possible Twig file found when looking for "@bolt/icon.twig".
517
518  ● Bolt Components declare dependencies in package.json if used in Twig files › pkg: @bolt/components-form
519
520    More than 1 possible Twig file found when looking for "@bolt/icon.twig".
521
522  ● Bolt …
```
> test(testing-utils): remove error when multiple Twig files found

- docs-site/src/templates/_site-footer.twig
- docs-site/src/templates/_site-head.twig
The browser is caching JS between re-builds and it leads to hard to debug situations. This restores the Pattern Lab built-in cache buster feature.
```html
<script src="/build/bolt-global.js" async=""></script>
```
```html
<script src="/build/bolt-global.js?cacheBuster=1568827392" async=""></script>
```
> fix(docs-site): restore js/css cachebuster

- packages/editor/src/editor.js
- packages/editor/src/index.js
- packages/micro-journeys/starters/one-character-1.html
- packages/micro-journeys/starters/one-character-lorem.html
- packages/micro-journeys/starters/steo-one-character-lorem.html
- packages/micro-journeys/starters/steo-two-character-lorem.html
- packages/micro-journeys/starters/two-characters-1.html
- packages/micro-journeys/starters/two-characters-3.html
- packages/micro-journeys/starters/two-characters-4.html
- packages/micro-journeys/starters/two-characters-lorem.html
https://app.asana.com/0/1126340469288208/1140098113160425/f
remove empty `<bolt-animate>`s on save
We need to make sure that any `<bolt-animate>` elements that are empty get removed. These are usually added via the slot controls, then had their children/contents (the actual elements being animated) deleted by user but the `<bolt-animate>` (which is almost always a slot) remains. We need this gone so that conditionals that check for empty slots don't return a false positive (i.e. conditional that says a slot is not empty but no visible elements are shown)
- Go to http://localhost:3000/pattern-lab/patterns/06-experiments-micro-journeys-combos--92-micro-journey-in-themes/06-experiments-micro-journeys-combos--92-micro-journey-in-themes.html
- Open console and run this to show there are no …
> fix(editor): remove empty <bolt-animate>s on save

- packages/micro-journeys/src/bolt-svg-animations/svg/tripleConnectionBand.js
https://app.asana.com/0/1126340469288208/1139869914404437/f
Refine  triple band SVG animation. 
TripleBandConnection SVG Animation has an issue where the first  arrow group hangs at the end of the animation.   this addresses that and improves the animation somewhat.  
View/create a page with the triple band connection SVG, medium characters, and a darkbackground.   
Simplest method is to visit:  
/pattern-lab/?p=experiments-svg-animations and utilize the inspector to make the background dark.   Compare to [here](https://boltdesignsystem-epic-interactive-pathways.now.sh/pattern-lab/patterns/06-experiments-micro-journeys-combos--95-in-page-example/06-experiments-micro-journeys-combos--95-in-page-example.html     
Browser Name: chrome             ) where the arrows hang above the character.
> Fix triple band SVG animation 

- packages/components/bolt-animate/animate.schema.js
https://app.asana.com/0/1126340469288208/1140951723352001/f
Reduces the default exit animation from 500ms to 350ms for UX reasons. When clicking on an inactive step, this will decrease the default time to that step being "active" and thus making the application feel more responsive to user interactions. 
See the Doherty Threshold principle for background on this: https://lawsofux.com/doherty-threshold.html
Click through steps. It should feel a bit more responsive than before.
> feat: speed up default exit animation to create a smoother experience

- packages/micro-journeys/src/interactive-pathways.scss
https://app.asana.com/0/1126340469288208/1142826690191123/f
Quick fix for stacking conflict between the character's status/dialogue bar and the pathways dropdown menu.
Dropdown was behind the status bar text (see below). This PR puts it on top.
Create a two character step layout with a dialogue above the left character. then open the dropdown menu. The status bar should be behind the dropdown menu now.
> fix: z-index clash between dropdown menu and status bars

- packages/core/package.json
- packages/core/polyfills/index.js
- packages/core/renderers/renderer-lit-html.js
- packages/micro-journeys/package.json
- packages/micro-journeys/src/bolt-svg-animations/svg-animations.js
- packages/micro-journeys/src/connection.js
- packages/micro-journeys/src/interactive-pathway.js
- packages/micro-journeys/src/interactive-pathways.js
- packages/micro-journeys/src/interactive-step.js
- yarn.lock
N/A
Upgrades several components used in Micro Journeys to use this new [`wc-context` library](https://github.com/blikblum/wc-context) instead of the original withContext mixin to fix the JavaScript errors still occurring with the latest code up on develop.
- Confirm tests pass as expecting
- Confirm JS errors no longer occur on https://develop.boltdesignsystem.com/pattern-lab/?p=viewall-experiments-micro-journeys once the build finishes
> Upgrade withContext Solution

- packages/micro-journeys/src/interactive-step.scss
- packages/micro-journeys/src/nav-shared.scss
- packages/micro-journeys/src/one-character-layout.scss
- packages/micro-journeys/src/status-dialogue-bar.scss
- packages/micro-journeys/src/two-character-layout.scss
N/A
Adjusts the spacing (especially for smaller screen sizes) after checking out the latest updates on develop after pulling in #1463.
- Double-check my work to make sure I'm not missing / overlooking anything here
- Cross browser checks (Edge / IE 11)
> Micro Journey RWD / Layout Fixes

- packages/editor/src/setup-bolt.js
Packages shouldn't import other packages with relative paths; they should use package names. This fixes the editor importing the schema from the link component.
> fix(editor): use package name for import

- docs-site/src/pages/pattern-lab/_patterns/02-components/tooltip/05-tooltip.twig
- packages/components/bolt-tooltip/__tests__/__snapshots__/tooltip.js.snap
- packages/components/bolt-tooltip/index.js
- packages/components/bolt-tooltip/src/tooltip.js
- packages/components/bolt-tooltip/src/tooltip.scss
- packages/components/bolt-tooltip/src/tooltip.twig
TBD
Internal refactoring + fixes to the current Tooltip component to address rendering issues when passing along complex content (HTML vs only simple text content). These updates should also address the main problem that #1484 is solving (albeit, just with a different approach).
- Switches from copying over content via the `content` prop to instead render the content in the Web Component's default slot
- Fixes an issue with the Tooltip prematurely closing when hovering from the Tooltip's trigger to content container
- Addresses a problem with the `direction` prop documented in the component's schema not matching up with the prop name used in the Web Component internally
- Updated the component's internal logic to now open / close based on JS logic vs CSS logic (which didn't account for …
> Hotfix: Tooltip Refactor + Updates

- packages/generators/yeoman-create-component/generators/component/__tests__/__snapshots__/component-generator.js.snap
- packages/generators/yeoman-create-component/generators/component/templates/component.html.twig
- packages/generators/yeoman-create-component/generators/component/templates/component.js
n/a
Update component generator to use the latest conventions.
- Remove `base_class`
- use `init()`
- add `<replace-with-children>`
- remove `is="shadow-root"`
- remove `useShadow`
Checkout branch, run `npm run cc` and make sure the new component works properly and doesn't throw any Twig or JS errors.
> Component Generator | Update | Use latest component conventions 

- docs-site/config/config.yml
- packages/uikit-workshop/src/scripts/components/pl-nav/pl-nav.js
- packages/uikit-workshop/src/scripts/components/pl-viewport/pl-viewport.js
N/A
Adds upstream Pattern Lab UIKit fixes PR'd in https://github.com/pattern-lab/patternlab-node/pull/1053
- Updates the Viewport component to use the Pattern Lab `defaultPattern` config (if it exists) when setting up the iframe URL that initially loads.
- Updates the Nav component to re-enable displaying the top level `All` link by default unless the `ishControlsHide['views-all]` config option is enabled.
- Fixes an unreported Pattern query string-related issue I noticed when testing out the All link updates. Basically the top most `All` page doesn't seem to emit the name of that page's "pattern" which the iframe emits the patternLoad event. 
- Minor code formatting based on our Prettier rules
- Confirm Travis build passes as expected (which already includes some basic UI checks for …
> Fix: Backport Upstream Pattern Lab UIKit Bug Fixes

- docs-site/src/pages/pattern-lab/_patterns/02-components/tabs/30-tabs-content.twig
- packages/components/bolt-tabs/src/tabs.js
- http://vjira2:8080/browse/WWWD-4173
Fix IE/Edge bug that breaks dropdown menu when Tabs are nested inside a Band.
In IE/Edge Tabs are disconnected and reconnected when placed inside a band. After disconnecting, certain event handlers were not getting re-added and breaking the dropdown menu.
To fix, I made sure the `ready` flag was unset on disconnect so that the component will properly setup the next time it connects.
- View Tab Content page in IE and Edge. There is a new example of a Tab inside a Band. Make sure the dropdown works properly. Resize the window and test.
> Tabs | Bug | Fix tabs inside band IE/Edge bug

- packages/components/bolt-tabs/src/tabs.js
http://vjira2:8080/browse/WWWD-4244
Close "More" menu when a menu item is selected.
Also includes related accessibility fixes to handle focus when menu closes.
- Check out branch and test locally in Chrome and IE.
- Verify that the More menu closes after selecting a Tab item from the menu.
> Tabs | JS | Close dropdown menu after selecting tab item

- packages/components/bolt-modal/src/modal.scss
http://vjira2:8080/browse/BDS-1699
Fix modal video content shifting on hover in IE Edge.
To prevent blurry text we're using a CSS hack that involves the "perspective" property. In Edge only, this hack is causing modal content to shift when you hover over it, as it interacts with some default Brightcove styles. As a compromise, we're simply removing the hack from IE Edge. The blurry text is not very noticeable but the content shifting bug is.
1. Reproduce the bug by checking out `master`.
2. Open the Modal Usage Video page in a text editor (`/docs-site/src/pages/pattern-lab/_patterns/02-components/modal/45-modal-usage-video.twig`).
3. Add this code to the top of the file:
```
{% embed "@bolt-components-sticky/sticky.twig" %}
{% block sticky_content %}
<div …
```
> Modal | FE | Fix modal video content shifting in IE Edge

- docs-site/src/pages/pattern-lab/_patterns/02-components/tabs/30-tabs-content.twig
- packages/components/bolt-image/src/image.js
- http://vjira2:8080/browse/WWWD-4245
Fix images in tabs appearing fuzzy.
Images that are in an inactive tab were not getting properly lazyloaded because they had no width.
We must check that an image has width before setting `sizes`.
Run locally and view the Tabs Content page in an incognito window. Click on the "Image" tab and verify the image is not fuzzy.
> Image | JS | Fix images in tabs appearing fuzzy

- packages/micro-journeys/src/status-dialogue-bar.scss
https://app.asana.com/0/1126340469288208/1146062428777064/f
Tighten spacing around icon in dialog bar.
Before
After
/?p=experiments-micro-journeys
Note: there are other dialog bar tickets, this is just a low-hanging fruit ticket.
> fix(micro-journeys): tighten dialog icon spacing

- docs-site/src/pages/pattern-lab/_patterns/02-components/list/40-list-align-variations.twig
- packages/components/bolt-list/list.schema.yml
- packages/components/bolt-list/src/list.scss
Issue first raised in: http://vjira2:8080/browse/WWWD-4211?focusedCommentId=68872&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-68872
Fixes an issue where the List component does not align correctly in Firefox when `display` is set to `inline@breakpoint`.
1. Added CSS to make sure `.c-bolt-list` container takes up full width of its parent.
2. Updated docs to demo the alignment when List is set to display inline@breakpoint.
Run the branch locally and check the following:
> Fix: List component's inline@breakpoint display options not aligning correctly in Firefox

- packages/editor/src/setup-bolt.js
- packages/editor/src/utils.js
- packages/micro-journeys/starters/index.js
- packages/micro-journeys/starters/step-one-character-starter.html
- packages/micro-journeys/starters/step-two-character-starter.html
https://app.asana.com/0/1126340469288208/1146085721698826/f
Add Single and Multiple Pathways starters, add specific One and Two Character layouts from starter docs from Ross.
The PDF describing these specific layouts can be found on the asana task.
This button is added, with two pathways representing one and two character layouts respectively from the PDF:
One char: 
Two char:
> feat(micro-journeys): starter templates for one and two character

- docs-site/src/pages/pattern-lab/_patterns/02-components/accordion/45-accordion-trigger-and-content-spacing-variations.twig
- packages/components/bolt-accordion/__tests__/__snapshots__/accordion.js.snap
- packages/components/bolt-accordion/__tests__/accordion.js
- packages/components/bolt-accordion/accordion.schema.yml
- packages/components/bolt-accordion/src/AccordionItem/AccordionItemContent.js
- packages/components/bolt-accordion/src/AccordionItem/AccordionItemTrigger.js
- packages/components/bolt-accordion/src/AccordionItem/accordion-item.scss
- packages/components/bolt-accordion/src/AccordionItem/accordion-item.twig
- packages/components/bolt-accordion/src/AccordionItem/index.js
http://vjira2:8080/browse/BDS-1664
Adds two new spacing configuration options for `<bolt-accordion-item>`s, `content-spacing` and `trigger-spacing` to allow the default spacing inherited from the parent `<bolt-accordion>` to get customized in certain situations.
> Note: this breaks out the Accordion work from #1286 into its own PR and omits the docs-site changes that were a part of the original PR. Those will be added separately.
Nested content that already contains internal space doesn't work well with our current accordion implementation as I quickly found out when I tried to put a Table component in the accordion's content and noticed that our current config options didn't allow me to line up the Table component in my accordion with other tables already on the page.
This update adds a …
> Accordion | Dev | Add custom accordion spacing option

- docs-site/src/pages/pattern-lab/_patterns/02-components/accordion/40-accordion-content-variations.twig
- docs-site/src/pages/pattern-lab/_patterns/02-components/tabs/30-tabs-content.twig
- packages/components/bolt-accordion/__tests__/accordion.js
- packages/components/bolt-accordion/src/AccordionItem/index.js
- packages/components/bolt-accordion/src/accordion.js
- http://vjira2:8080/browse/BDS-1870
Fix bug where an accordion inside an accordion does not render properly.
It appears that changing when `ssrHydrationPrep` gets called resolves this issue on its own ([see commit](https://github.com/boltdesignsystem/bolt/commit/b7f14efa74e778f888e9c122882929869fc03105#diff-d45fd62db4da766d397ba2b3eaae5990)). Still, the changes here make the component more resilient. Before, accordion items were initialized on 'rendered', which could be unpredictable as components may render multiple times, and on certain renders we got different results when we queried the 'renderRoot`. Now, we're initializing on 'ready', inside a `Promise`, which waits for all accordion items to finish before setting up the Accordion.
- Check out `fix/nested-accordion-bug` branch …
> Accordion | JS | Fix nested accordion bug

- packages/testing/testing-nightwatch/nightwatch.local.js
- packages/testing/testing-nightwatch/package.json
- yarn.lock
N/A
Fixes to the Nightwatch Updates the Chrome Driver version to the latest version of Chrome (used when running Nightwatch tests locally) + disables assigning a port to Selenium Server to help prevent issues if port `4444` is unavailable.
Try running Nightwatch tests locally to confirm everything is working as expected.
> Fix: Update Nightwatch Config for Local Testing

- packages/micro-journeys/starters/cta-text-1.html
- packages/micro-journeys/starters/cta-text-2.html
- packages/micro-journeys/starters/cta-text-3.html
- packages/micro-journeys/starters/cta-text-4.html
- packages/micro-journeys/starters/cta-text-5.html
- packages/micro-journeys/starters/cta-text-lorem.html
- packages/micro-journeys/starters/one-character-1.html
- packages/micro-journeys/starters/one-character-lorem.html
- packages/micro-journeys/starters/step-one-character-lorem.html
- packages/micro-journeys/starters/step-one-character-starter.html
- packages/micro-journeys/starters/step-two-character-lorem.html
- packages/micro-journeys/starters/step-two-character-starter.html
- packages/micro-journeys/starters/two-characters-3.html
https://app.asana.com/0/1126340469288208/1146297619076806
Make link component to use `slot-after` for `bolt-icon` in `bolt-cta`, remove whitespace
See screenshot.
Visit patterns/06-experiments-micro-journeys-90-micro-journeys/06-experiments-micro-journeys-90-micro-journeys.html and shrink until chevron widows.
> fix(micro-journeys): move link component to use slot-after for icon

- packages/uikit-workshop/src/sass/scss/02-base/_body.scss
N/A
Pattern Lab UIKit CSS fix for IE 11 to address the main viewport container collapsing in height. This change matches up with the hotfix that went out earlier today: https://github.com/pattern-lab/patternlab-node/pull/1099
> Hotfix: Pattern Lab CSS Fix for IE 11

- packages/editor/src/index.js
http://vjira2:8080/browse/WWWD-4312
Allow handleEditorSave to be defined at runtime.
Previously, handleEditorSave got defined on load, which meant that other javascript that wanted to define it using window.__handleEditorSave needed to run before it.  This commit instead waits until runtime (i.e. when the edit save button is clicked), which gives other scripts more time to set window.__handleEditorSave.
I've only tested in Drupal-- to test in Bolt, you'd have to set window.__handleEditorSave after the editor js loads, then confirm that the function you defined is used when closing the editor.
> Hotfix: define handleEditorSave at runtime

- packages/base-element/src/BoltElement.js
N/A
Patches the constructable stylesheet rendering in lit-element to address an issue encountered in Chrome (when rendering Button in the GrapeJS editor) where styles no longer show up.
Adds a new check to the default lit-element render function to automatically render styles via a `<style>` tag (the default fallback for browsers supporting Shadow DOM but not adoptedStyles) when the render root doesn't have any adoptedStyleSheets, the symptom of the error that is silently thrown when I tried to force the behavior in this particular use case.
I'll be submitting a patch to lit-element shortly!
Confirm that Button styles now show up correctly when editing http://localhost:3000/pattern-lab/patterns/06-experiments-editor-10-editor-simple/06-experiments-editor-10-editor-simple.html
> hotfix: patch lit-element's constructable stylesheet rendering behavior

- packages/components/bolt-accordion/__tests__/accordion.js
http://vjira2:8080/browse/BDS-1871
Switch to using Puppeteer's page selector in Jest test.
This is a small PR just to capture an example of where we can use Puppeteer's page selector instead of always using evaluate to interact with the `page`.
https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageselector
- Review the file changed
> Accordion | Test | Use Jest page selector instead of evaluate

- packages/components/bolt-tabs/src/tabs-dropdown.scss
n/a
Fixes miscalculation of width in IE11 which causes e2e test to intermittently fail.
Adds `flex-shrink: 0` to prevent "More" button and icon from stacking on resize in IE11. When they stack, the button width is miscalculated and menu does not resize properly.
- Test locally in Chrome and IE, especially around 600px breakpoint
- e2e Tabs tests are passing
> Tabs | SCSS | Fix resize bug in IE11

- docs-site/.boltrc.js
- docs-site/package.json
- docs-site/src/components/theme-switcher/index.js
- docs-site/src/components/theme-switcher/package.json
- docs-site/src/components/theme-switcher/theme-switcher.js
- docs-site/src/components/theme-switcher/theme-switcher.scss
- package.json
N/A
Manually ports over the new `<bolt-theme-switcher>` helper component from #1542; allows devs to more easily demo and test components within different themes. 
- Actual usage can be viewed in the original [Typeahead theming demo](https://feature-typeahead-filtering.boltdesignsystem.com/pattern-lab/?p=components-typeahead--customize-theming)
- Test using the new helper component within the docs site (ex. test dropping a Button into this)
```html
<bolt-theme-switcher>
<bolt-button color="primary">
</bolt-theme-switcher>
```
- Depended on for the [incoming Typeahead theme updates]( https://github.com/boltdesignsystem/bolt/pull/1542)
> New Theme Switcher Demo Component

- packages/components/bolt-typeahead/typeahead.autosuggest.js
- packages/components/bolt-typeahead/typeahead.status.js
N/A
Significantly improves Typeahead's accessibility features, in no small party by selectively pulling in some great a11y ideas from https://github.com/alphagov/accessible-autocomplete
NOTE: I'm patching up a few of the API updates that were made in the broader Typeahead work (ex. like https://github.com/boltdesignsystem/bolt/compare/feature/typeahead-a11y?expand=1#diff-fee3ffa51420f9ad7a303cad8291a4d9R117) but am limiting changes to the updated API to just the methods being updated / used by this chunk of work.
Also, I'm holding off on adding the full `README.md` docs updates I've made to keep this PR as focused as possible. Planning on adding those separately with the other docs site updates for Typeahead.  
- Test using the Typeahead component with your keyboard + screen reader before …
> Typeahead: Accessibility Enhancements

- packages/core/package.json
- packages/core/styles/index.scss
N/A
Adds [SassyLists](https://github.com/at-import/SassyLists) to @bolt/core's styles. Used to the handle the updated theming system used with Typeahead in #1542 which require this as a hard dependency.
NOTE: this is getting added to Core directly (vs just to Typeahead, as I did originally), since we already have a number of places where this new library could easily get used (and likely replace some custom code we're currently maintaining). 
If the build's not broken then we're good to go.
> Core: Add Sassy List to @bolt/core

- packages/build-tools/__tests__/multi-lang/__snapshots__/index.js.snap
- packages/build-tools/package.json
- packages/core/styles/01-settings/settings-themes/index.scss
N/A
Adds two new options to Bolt's color theming system: `text-on-background` (which I was surprised we didn't actually have) and `text-on-background-secondary`.
These updates are a subset of the work from https://github.com/boltdesignsystem/bolt/pull/1542 and are a hard dependency on the theme-specific updates to Typeahead.
- Updates the build tools Jest snapshot with the CSS custom property additions
- Tweaks the build tool's test command to make it easier to update Jest snapshots, simply by switching to yarn
- Modifies the theming system's Sass logic in `@bolt/core` to support adding new theme options that include text variations (`text-on-THEME-OPTION`) without requiring a bunch of auto-generated variations that we might not actually need.
- Confirm build compiles as expected
> Core: Add New Text on Background/Secondary Background Options to Theme Options

- packages/components/bolt-button/button.schema.js
http://vjira2:8080/browse/BDS-1905
Demos the usage of one schema (icon) within another (button), with modification
One visible change in the docs is that the details for icon no longer appear within a collapsed fieldset, as shown in the screenshots below.  We could probably make that still happen by modifying the schema docs template (and adding some indication that a schema should be collapsed?).
One advantage to the new method, however, is that the schema now includes the additional `position` prop that only icons within buttons can include.
Before
After:
Confirm no regressions.
> BDS-1905 Reference icon schema in button schema

- packages/editor/src/setup-bolt.js
http://vjira2:8080/browse/WWWD-4331
http://vjira2:8080/browse/WWWD-4332
- Makes the text in bolt-button components editable
- Removes unused/non-functional options from the bolt-text component
Fixes these the two bugs refrenced in Jira, which I will copy here for those who can't see it ;).
*Bug 1*: When adding a bolt-text component in the editor, several fields appear in the 'Selected' palette that do nothing.
- Go to https://boltdesignsystem.com/pattern-lab/patterns/06-experiments-editor-10-editor-simple/06-experiments-editor-10-editor-simple.html
- Add a bolt-text element by dragging and dropping into the editor
- In the Selected pane, change the text or url field
Expected: something updates
Actual: Nothing changes
*Bug 2*: After dragging a new button into the editor, the text cannot be …
> Editor component bugfixes

- docs-site/src/pages/pattern-lab/_patterns/02-components/carousel/00-carousel-docs.twig
- docs-site/src/pages/pattern-lab/_patterns/02-components/carousel/25-carousel-basic-variations.twig
- docs-site/src/pages/pattern-lab/_patterns/02-components/figure/00-figure-docs.twig
- docs-site/src/pages/pattern-lab/_patterns/02-components/figure/05-figure.twig
- docs-site/src/pages/pattern-lab/_patterns/02-components/figure/10-figure-media-variations.twig
- docs-site/src/pages/pattern-lab/_patterns/02-components/modal/40-modal-usage-image-and-caption.twig
- docs-site/src/pages/pattern-lab/_patterns/04-pages/10-d8-product-pages/_product-t3-extra-videos.twig
- docs-site/src/pages/pattern-lab/_patterns/04-pages/10-d8-product-pages/_product-t3.twig
- docs-site/src/pages/pattern-lab/_patterns/04-pages/10-d8-product-pages/product-landing.twig
- docs-site/src/pages/pattern-lab/_patterns/04-pages/10-d8-product-pages/product-t2.twig
- docs-site/src/pages/pattern-lab/_patterns/04-pages/10-d8-product-pages/product-t4.twig
- docs-site/src/pages/pattern-lab/_patterns/06-experiments/micro-journeys/combos/-95-in-page-example.twig
- packages/components/bolt-figure/__tests__/__snapshots__/figure.js.snap
- packages/components/bolt-figure/__tests__/figure.js
- packages/components/bolt-figure/figure.schema.yml
- packages/components/bolt-figure/src/figure.twig
- packages/global/styles/05-objects/objects-flag/src/flag.twig
http://vjira2:8080/browse/BDS-1781
Add `media.content` prop to Figure. Deprecate `media.image`, `media.icon`, `media.video`, `media.table`.
This makes the Figure component more flexible. Users can pass in any renderable content to the `media.content` prop. This opens up the possibility of passing in a Drupal render array. Previously users could only pass in data.
Before:
```
{% include "@bolt-components-figure/figure.twig" with {
media: {
image: {
src: "/images/placeholders/500x500.jpg",
},
},
caption: "Figure caption"
} only %}
```
After:
```
{% include "@bolt-components-figure/figure.twig" with {
media: {
content: include("@bolt-components-image/image.twig", {
src: "/images/placeholders/500x500.jpg"
}),
},
caption: "Figure caption"
} only %}
```
- Checkout locally …
> Figure | Twig | Add media content prop

- docs-site/src/pages/pattern-lab/_patterns/02-components/modal/35-modal-usage-javascript.twig
http://vjira2:8080/browse/BDS-1361
Add demo of modal auto-closing after a set period of time.
Adds another Custom JavaScript Usage demo, showing how to hook into modal component to auto-close after 3 seconds.
- Checkout `feature/modal-auto-close` locally
- Review the second demo on the [Custom JS Usage](http://localhost:3000/pattern-lab/patterns/02-components-modal-35-modal-usage-javascript/02-components-modal-35-modal-usage-javascript.html) page
- Verify demo works as expected
- Review the custom JS
> Modal | FE | Add auto-close demo

- docs-site/composer.lock
- package.json
- packages/core-php/composer.lock
- packages/drupal-twig-extensions/composer.lock
- packages/twig-renderer/composer.json
- packages/twig-renderer/composer.lock
- packages/twig-renderer/package.json
- yarn.lock
N/A
Virtually identical to [this update in PL Node](https://github.com/pattern-lab/patternlab-node/pull/1107), this PR updates the [`@basalt/twig-renderer` to v0.13.0](https://github.com/basaltinc/twig-renderer/releases/tag/v0.13.0) + updates the version of Twig being used in Bolt to v1.42.2 so we can take advantage of the new `filter`, `map`, and `reduce` functions that were [just added](https://symfony.com/blog/twig-adds-filter-map-and-reduce-features).
Thanks @EvanLovely for the upstream update to the Twig renderer!
Confirm existing Travis tests are passing.
> Feat: update Twig Renderer to use Twig's new filter, map, and reduce functions

- .travis.yml
- lighthouserc.json
Wires up Lighthouse CI for monitoring performance and accessibility moving forward — subset of updates from https://github.com/boltdesignsystem/bolt/pull/1579.
Supersedes the work from https://github.com/boltdesignsystem/bolt/pull/1495.
> Add Lighthouse CI Performance Monitoring / Github Integration

- packages/editor/src/setup-bolt.js
- packages/micro-journeys/index.scss
- packages/micro-journeys/src/interactive-pathways.js
https://app.asana.com/0/1126340469288208/1151276850580121/f
Restores ability to edit bolt-interactive-pathways props/traits in grapesjs editor.
Details
This was a regression, now the bolt-interactive-pathways element is properly registered.
I also fixed a bug wherein editing the bolt-interactive-pathways props caused it to have opacity: 0.
Go to editor page, add pathway, edit bolt-interactive-pathways layer, add customImageSrc.
> fix(editor): restore pathways editable traits; fix opacity: 0

- packages/micro-journeys/src/status-dialogue-bar.js
- packages/micro-journeys/src/status-dialogue-bar.schema.js
https://app.asana.com/0/1126340469288208/1150972142674288/f
Add ability to remove icon from `bolt-status-dialogue-bar`. 
Previously the empty attribute `""`was not getting removed when selected through the editor UI. The old value persisted. I created a value `-none-` that can be selected more explicitly.
Use the 2-char starter in the editor, remove the icon from `bolt-status-dialogue-bar` by selecting `iconName` as `-none-`.
> feat(editor): add ability to remove icon from status-dialogue-bar

- packages/components/bolt-ul/src/ul.scss
N/A
Fixes an issue where the unordered list has less stack spacing than usual.
Sets the margin-bottom on `bolt-ul` to be `medium`, the same value we use for `bolt-ol`.
Pull down and run the branch locally. Stack 2 ordered lists and 2 unordered lists in a dummy page, compare them side by side and make sure they line up perfectly.
> Fix: unordered list's inconsistent stack spacing

- packages/components/bolt-device-viewer/src/device-viewer.scss
N/A
Two small Device Viewer-related CSS fixes I ran into the need for while working on https://github.com/boltdesignsystem/bolt/pull/1579.
Prevents accidentally highlighting the device viewer image (which actually happened to me while zooming in on an image) + fixes the terribly janky transition when the device viewer image is magnified.
Check out the device viewer section in Pattern Lab and confirm that images can no longer get highlighted (click and drag) + the animation when magnifying an image with your mouse is much smoother.
> Fix: Device Viewer CSS Fix

- packages/configs/babel-preset-bolt/index.js
- packages/configs/babel-preset-bolt/package.json
N/A
Adds optional chaining support to Babel. Subset of the work from #1602.
> Add Optional Chaining Support to Babel

- packages/micro-journeys/src/status-dialogue-bar.scss
http://vjira2:8080/browse/WWWD-4363
Fixes color of dialog bar text in IE
Previously, a slot-based CSS selector was being used to set text color.  This won't work in IE.
Additionally, setting a color on &__slot--text seems redundant and unnecessary-- removing this appears to allow colors to work as originally intended.
- In IE 11, go to https://boltdesignsystem.com/pattern-lab/patterns/06-experiments-micro-journeys-35-status-dialogue-bar-kitchen-sink/06-experiments-micro-journeys-35-status-dialogue-bar-kitchen-sink.html
- Confirm that the text color within the red status bar is black, not white as in other browsers
In IE/Edge
In Chrome/Firefox (expected behavior)
- In IE 11, go to `/pattern-lab/patterns/06-experiments-micro-journeys-35-status-dialogue-bar-kitchen-sink/06-experiments-micro-j …
> Remove slot-based CSS selector so status bar color works in IE

- docs-site/src/pages/pattern-lab/_patterns/06-experiments/editor/25-editor-with-two-character-layout.twig
- packages/micro-journeys/src/character.js
- packages/micro-journeys/src/character.scss
- packages/micro-journeys/src/connection.js
- packages/micro-journeys/src/connection.scss
- packages/micro-journeys/src/interactive-step.js
- packages/micro-journeys/src/interactive-step.scss
- packages/micro-journeys/src/two-character-layout.js
- packages/micro-journeys/src/utils/equalize-relative-heights.js
- packages/micro-journeys/starters/step-two-character-starter.html
This fixes several `bolt-two-character-layout` issues, including:
* https://app.asana.com/0/1126340469288208/1130525745807684/f
* https://app.asana.com/0/1126340469288208/1151276850580125/f
* Connection band disappears in editor
* Connection band background is sometimes invisible in Chrome
* `bolt-two-character-layout` layout problems in IE
Detail:
In general I simplified the code here a bunch and made it readable and maintainable. I also added a persistent `setTimeout` promise to ensure that child components have `offsetHeight`. This is because bolt `render` event was reporting that components were rendered when they had not yet been painted on the dom. I also tried mutation observers on both shadow and non-shadow components, as well as `requestAnimationFrame` and `setTimeout(0)`
How to …
> Fix Micro Journey-related Issues with the Two-Character Layout

- package.json
- yarn.lock
N/A
Auto-format + re-order any `package.json` files that get updated.
Uses https://www.npmjs.com/package/sort-package-json + our new super fast commit hooks to automatically take care of everything!
It just works + only applies to the monorepo. Super low risk quality of life improvement! 😉
> Automatically Format Package.json Files

- packages/components/bolt-link/__tests__/__snapshots__/link.js.snap
- packages/components/bolt-link/__tests__/link.js
- packages/components/bolt-link/src/link.js
N/A
Upgrades the Link over to the new LitElement-based BoltElement base class after running into complications (ex. not being able to stack up decorators / use the original version of `convertInitialTags`) while working on the [broader ES Module work](https://github.com/boltdesignsystem/bolt/pull/1579).
Except for very minor prop validation logic (which will come to all new BoltElement components in the near future), the updated logic here is almost 1:1.
This PR also updates the related component Jest tests based on the internal syntax differences with LitElement accordingly.
Note: because this work uses some small changes in Core (the upgraded [`convertInitialTags` decorator](https://github.com/boltdesignsystem/bolt/pull/1586/files#diff-9e82038665bdf44b4be8e5c8f32a5994R64)) this PR …
> ES Modules: Upgrade Link to BoltElement

- packages/base-element/src/Slotify.js
- packages/base-element/src/lib/decorators.js
- packages/base-element/src/lib/utils.js
- packages/core/decorators/convert-initial-tags.js
- packages/core/package.json
- packages/core/renderers/bolt-base.js
- packages/core/renderers/renderer-lit-html.js
- packages/core/renderers/renderer-preact.js
- packages/core/renderers/wc-context.core.js
- packages/core/renderers/wc-context.js
- packages/core/renderers/with-events.js
- packages/core/utils/environment.js
- packages/core/utils/find-parent-tag.js
- packages/core/utils/index.js
N/A
Bolt Core renderer, decorator, and BoltElement-related Class updates that are all a required part of the broader ES Module work https://github.com/boltdesignsystem/bolt/pull/1579.
- Migrates existing component decorators over to use the new decorator spec when supported (using[ lit-element's approach](https://github.com/Polymer/lit-element/blob/master/src/lib/decorators.ts#L80) as a starting point).
- Migrates a handful of the most common Core utils over to the new `@bolt/element` base
- Refactors `withLitHtml`, `withEvents`, `withPreact` base classes to directly extend classes (required otherwise blocking errors are thrown when all the ES Module-related work is switched on)
- Forks (temporarily?) the `wc-context` package (the library used for our newest Context approach with minimal …
> ES Modules: Bolt Core / BoltElement Updates

- packages/base-polyfills/index.js
- packages/base-polyfills/modern.js
- packages/components/bolt-button/index.js
- packages/core/polyfills/index.js
N/A
Incorporates the majority of the polyfill consolidation / simplification that's part of the [broader ES Module work](https://github.com/boltdesignsystem/bolt/pull/1579) without any component or build tool related changes required, or inadvertently introducing any major breaking changes. 
When the full set of updates from https://github.com/boltdesignsystem/bolt/pull/1579 are in place, the Core polyfill loader essentially becomes unnecessary since we only include the necessary polyfills once in the main `bolt-global` Webpack bundle.
That said (and something I especially use @danielamorse and @remydenton's feedback on) — the upstream ES Module work does NOT auto-include polyfills in any of the independent bundles from Webpack since these may or may not require the polyfill loader in …
> ES Modules: Simplified "Polyfill Loader"

- packages/build-tools/create-webpack-config.js
http://vjira2:8080/browse/WWWD-4467
Restores font files when creating multiple builds at once
- Check out the [bolt-release-build repo](http://vstash:7990/projects/BOLT/repos/bolt-release-build/browse)
- Run `npx gulp --bolt-version=v2.13.1 --additional-components="@bolt/components-icon"` (FYI, the additional-components option is a temporary workaround for a separate problem)
- Observe that there is a `builds/v2.13.1/builds/en--dev/fonts` directory, but not a `builds/v2.13.1/builds/en/fonts` directory.
Note: it's possible this is an intermittent bug and may not always be reproducible the same way
The fix in this PR is based on the discussion in https://github.com/webpack-contrib/cache-loader/issues/82
Why it works, I'm less sure.  The comments there mention a few things:
> it should not …
> hotfix: Remove cache-loader from webpack fonts rule

- docs-site/.boltrc.js
- docs-site/package.json
- docs-site/src/components/shadow-toggle/index.js
- docs-site/src/components/shadow-toggle/package.json
- docs-site/src/components/shadow-toggle/shadow-toggle.js
- docs-site/src/components/shadow-toggle/shadow-toggle.scss
- docs-site/src/components/shadow-toggle/shadow-toggle.twig
- docs-site/src/templates/_site-footer.twig
- package.json
- packages/base-element/index.js
- packages/base-element/src/lib/utils.js
n/a
Adds a new `<bolt-shadow-toggle>` helper component (based off of the upcoming `<bolt-radio-switch>`) that allows devs to globally enable / disable Shadow DOM rendering while developing in Bolt.
Replaces #1538 which got out of sync with `master`.
Adds a new feature flag to @bolt/core to carefully allow the default Shadow DOM feature detection check results to be overwritten while debugging / testing. 
Uses Modal to tuck away the config options while not in use.
Try the new helper component out!
> Feature: Add bolt-shadow-toggle component

- packages/micro-journeys/src/status-dialogue-bar.scss
https://app.asana.com/0/1126340469288208/1154819220959433/f
Broaden desktop width of `bolt-status-dialog-bar`.
View broadened status bar on micro journeys page.
> fix(micro-journeys): broaden desktop width of status bar

- docs-site/src/pages/pattern-lab/_patterns/02-components/typeahead/_typeahead-demo.twig
- packages/components/bolt-typeahead/__demos__/dynamically-fetch-data/typeahead.dynamically-fetch-data.js
- packages/components/bolt-typeahead/__demos__/navigate-to-exact-result/typeahead.navigate-to-exact-result.js
- packages/components/bolt-typeahead/__demos__/navigate-to-search-results/typeahead.navigate-to-search-results.js
- packages/components/bolt-typeahead/typeahead.autosuggest.js
- packages/components/bolt-typeahead/typeahead.js
- http://vjira2:8080/browse/BDS-1928
- http://vjira2:8080/browse/BDS-1931
- http://vjira2:8080/browse/BDS-1930
Fixes IE11 Typeahead bug that prevents search terms from submitting, breaks autocomplete menu.
In IE11, when the Typeahead is inside a Band, the component connects and disconnects multiple times as the page renders. In our code, we are removing all external event listeners on disconnect to prevent duplicate event listeners from being added. This breaks IE11 because the event listeners are never re-added when the component re-connects. This PR adds a workaround so that every time Typeahead re-connects the "ready" event will fire, and any external event listeners added initially will be re-added.
**Key code changes:**
- Unset `_wasInitiallyRendered` on Typeahead and Autosuggest on …
> Hotfix: Fix IE11 Typeahead bugs

- docs-site/src/templates/_site-footer.twig
- docs-site/src/templates/_site-head.twig
N/A
Tweaks the critical path assets in the header / footer to speed up the initial rendering + reduce the jumpiness seen on master.
I'm not 100% sure if the order of the `<script>` tags really matters here (haven't spent enough time on this to measure all the different combos) however I know that clearing up much of the `<head>` / virtually eliminating the inline Critical Font code should help quite a bit on this front.
Further updates to our async font loader might further help us here however in the interim we're going super lightweight here to reduce the amount of render blocking code getting run.
https://www.webpagetest.org/video/view.php?id=200103_3429bc8b8293e6df31a9a750ba377979bdf96894
> Note: the long "visually complete" bit of the video is sometimes finicky due to our animated …
> Improve Initial SSR Rendering (Especially in IE 11)

- packages/build-tools/create-webpack-config.js
http://vjira2:8080/browse/BDS-1963?filter=-1
Webpack updates to speed up ES Module build times.
- Removes remaining places using the cache-loader from our create Webpack config after the fun times from the font loader updates recently (CC @remydenton)
- Adds separate caches in Webpack for modern vs legacy builds to speed up build times
> Webpack Cache Related Updates

- packages/components/bolt-site/site.scss
http://vjira2:8080/browse/BDS-1959
Small CSS update to the "Site" component to prevent negative margin offsets from adding extra whitespace on the bottom of the page + shadows from spilling out.
This update was originally required for Academy's homepage designs but could also be used in any places where we want to have Cards getting pulled up / over into neighboring sections.    
> Side note 1. I know `overflow: hidden;` might look scary but considering that anything that would normally overflow (ex. the global header / dropdown) is contained within a separate region, this PR should have a quite low risk.
> Side note 2. The original homepage build absolutely required this but the most recent iteration seems to tolerate not having this slightly more (although shadows still spill out). I'd …
> Add Overflow Hidden to "Site" Content Container

- packages/components/bolt-band/__tests__/__snapshots__/band.js.snap
- packages/components/bolt-band/band.schema.yml
- packages/components/bolt-band/src/band.twig
http://vjira2:8080/browse/BDS-1952
Adds two minor updates to Band required for the broader Academy work.
1. Adds support for our new (terribly named) `xxdark` theme (aka our new "black" theme)
2. Adds `inner_attributes` support to the Band component's Twig (required for very specific utility class placement)
> Academy-related Band Updates

- packages/components/bolt-headline/headline.schema.yml
- packages/components/bolt-headline/src/_tools.headlines.scss
- packages/components/bolt-headline/src/_typography.twig
- packages/components/bolt-headline/src/headline.scss
http://vjira2:8080/browse/BDS-1954
New options to our Headline component to better support the Academy designs
- Adds a new `light` font weight option
- Adds a new `autoshrink` prop to prevent text from automatically shrinking in size if over a certain letter count
- Makes `<strong>` tags used within eyebrows / text use a bold font weight
> Headline Component Updates

- packages/components/bolt-chip/src/chip.scss
http://vjira2:8080/browse/BDS-1953?filter=-1
Small Chip-related CSS updates from the larger Academy build.
- Improved Chip component background / background psuedo states
- Slightly tweaked padding; also now better matches the comps
- Review changes + Chip demos
> Chip Updates for Academy

- packages/base-element/src/Slotify.js
- packages/components/bolt-button/src/button.js
- packages/components/bolt-link/src/link.js
http://vjira2:8080/browse/BDS-1964?filter=-1
Renames the internal map used in Slotify from being named `templateMap` to `slotMap` (note: was originally used by the new Card component so an update might be needed after merging this in).
This also requires us to update the Slotify API referenced in a handful of new components (Button and Link).
- Confirm tests pass as expected
> Update Slotify Internal `templateMap` API

- .travis.yml
- docs-site/src/templates/_site-head.twig
- packages/build-tools/__tests__/multi-lang/.boltrc.multi-lang.js
- packages/testing/testing-jest/package.json
- patches/jest-image-snapshot+2.11.1.patch
- tsconfig.json
http://vjira2:8080/browse/BDS-1965?filter=-1
Handful of misc monorepeo updates spun off from the overall Academy prototype work:
- Fixed the `uikit-workshop` path in `tsconfig.json`
- Updated Jest Snapshot library + patch-package patch
- Fixed path used in `scripts/release/update-read-only-git-repos.sh`
- Updated `.gitignore` to include the Icon index.js file
- Added additional folder to Travis CI cache + no longer delete the dependencies / postinstall tasks in the - "Build + Deploy Website + Lighthouse CLI" task
- Automatically adds `js-fonts-loaded` to class to our docs site `<html>` tag when running in dev mode
- Confirm tests pass as expected
> Misc Monorepo Updates

- packages/generators/yeoman-create-component/generators/component/__tests__/__snapshots__/component-generator.js
http://vjira2:8080/browse/BDS-1966?filter=-1
Restores our missing component-generator.js file accidentally removed recently
Confirm tests pass / run as expected
> Restore Missing Yeoman Generator Jest Test

- packages/base-element/index.js
- packages/base-element/package.json
http://vjira2:8080/browse/AC-382
Temporary workaround to address a Babel regenerator runtime JS error getting thrown after running the  Bolt Build Tools externally with the Webpack DLL plugin added on top.
Testing this within Bolt isn't currently possible until the Webpack DLL plugin work is folded within the design system itself; our next best thing would be to retest a new build after this goes out the door.
> Webpack DLL / Polyfill Workaround

- packages/components/bolt-card-replacement/src/card-replacement-body/_card-replacement-body.twig
N/A
Implements a small Twig update to the new Card component's Body template to address an auto-escaping / HTML encoding issue identified in Drupal. 
This update (confirmed locally in Drupal after troubleshooting with the Academy team) fixes HTML content passed into the Card Body from rendering as plain text (vs actually rendering HTML).
N/A -  already tested the fix in Drupal + spot checked in Pattern Lab to ensure everything on our end continues to render as expected.
> fix: address HTML rendering / escaping issue w/ Card Replacement Body in Drupal

- packages/experimental/editor/src/editor.js
- packages/experimental/editor/src/utils.js
https://app.asana.com/0/1126340469288208/1157449394066073/f
Add prop schema descriptions underneath traits.
I chose the approach I did (appending our own div to existing traits at runtime) because otherwise we would have to create custom traits from scratch, and traits are extendible, so we'd have had to create them all from scratch.
Before:
After:
Edit components. See that the descriptions from their prop schema are added underneath the traits in editor. Make sure editor still works.
> feat(editor): add prop schema descriptions underneath traits

- docs-site/.boltrc.js
- docs-site/package.json
- docs-site/src/pages/pattern-lab/_patterns/02-components/banner/00-banner-docs.twig
- docs-site/src/pages/pattern-lab/_patterns/02-components/banner/05-banner.twig
- docs-site/src/pages/pattern-lab/_patterns/02-components/banner/10-banner-status-variations.twig
- docs-site/src/pages/pattern-lab/_patterns/02-components/banner/15-banner-align-variations.twig
- docs-site/src/pages/pattern-lab/_patterns/02-components/banner/20-banner-use-case-status-report.twig
- docs-site/src/pages/pattern-lab/_patterns/02-components/banner/999-banner-with-web-component.twig
- packages/components/bolt-banner/README.md
- packages/components/bolt-banner/__tests__/__snapshots__/banner.js.snap
- packages/components/bolt-banner/__tests__/banner.js
- packages/components/bolt-banner/banner.schema.js
- packages/components/bolt-banner/index.js
- packages/components/bolt-banner/index.scss
- packages/components/bolt-banner/package.json
- packages/components/bolt-banner/src/banner.js
- packages/components/bolt-banner/src/banner.scss
- packages/components/bolt-banner/src/banner.twig
Shipping the new Banner component work from https://github.com/boltdesignsystem/bolt/pull/1693 that didn't get merged down to the correct branch before the release was cut!
http://vjira2:8080/browse/BDS-1891
Introduces a new component called Banner: a content container that delivers important messages to the user.
1. `status` prop indicates what kind of message.
2. `align` prop controls text-alignment.
3. Fully built out the JS and Twig.
4. Documented all props and existing use cases (mainly used on Academy Challenge Details page).
Pull down the branch and run locally. Review the code and the docs.
> Ship new Banner component originally slated for v2.15.0

- docs-site/src/pages/pattern-lab/_patterns/03-blueprints/02-molecules/cards/_vertical-card.twig
N/A
Fixes a bug where tooltips inside vertical card's media section is getting overlapped by subsequent card body content.
1. Removed z-index and position util classes
2. Moved the icon banner markup up before anything inside the media
Hover over a tooltip and make sure said tooltip does not get covered up by another card's body content.
> Fix: corrects the stacking order in vertical card media

- docs-site/src/templates/_site-head.twig
- packages/components/bolt-icon/src/icon.twig
- packages/components/bolt-toolbar/toolbar.twig
http://vjira2:8080/browse/BDS-1987?filter=-1
Adds 3 small Twig template updates to smooth over some issues with the v2.16.1 release.
1. Updates the Icon component's Twig-only fallback (used to display SVG icons before JS kicks in) to use the `raw` Twig filter + escape HTML correctly.
2. Updates the Toolbar component's main template to also add the raw filter (fixes HTML displaying that isn't rendered)   
3. Updates the internal docs site + Pattern Lab `<head>` Twig file to address an internal visual regression with the CSS variable fallback styles.
- Confirm that the buttons on [this demo page](https://boltdesignsystem.com/pattern-lab/?p=components-button-style-variations) (using the deploy URL) now looks correct in IE 11
- Very quick smoke test to confirm that the Toolbar + Icon …
> Twig rendering fixes for Toolbar + Icon; fix for docs site visual regression w/ CSS vars fallback

- packages/experimental/micro-journeys/src/status-dialogue-bar.schema.js
http://vjira2:8080/browse/WWWD-4536
Restore -none- option for icons in dialog bar
This restores the functionality introduced in cc58925 that was later lost in a merge conflict with cba55e55.
- Go to `/pattern-lab/?p=experiments-editor-with-two-character-layout`
- Click edit
- Select the dialog bar above the second character
- In the icon dropdown for that character, select "-none-"
- Save.  There should be no icon or funky spacing in the dialog bar you just edited.
> Restore -none- option for icons in dialog bar

- packages/components/bolt-toc/__tests__/__snapshots__/toc.js.snap
- packages/components/bolt-toc/package.json
- packages/components/bolt-toc/src/_toc-item.js
- packages/components/bolt-toc/src/toc.js
- packages/components/bolt-toc/src/toc.twig
- packages/components/bolt-toc/src/waypoint/computeOffsetPixels.js
- packages/components/bolt-toc/src/waypoint/getBounds.js
- packages/components/bolt-toc/src/waypoint/getCurrentPosition.js
- packages/components/bolt-toc/src/waypoint/index.js
- packages/components/bolt-toc/src/waypoint/parseOffsetAsPercentage.js
- packages/components/bolt-toc/src/waypoint/parseOffsetAsPixels.js
http://vjira2:8080/browse/BDS-1975
Add smooth scroll and scroll-spy behavior to Table of Contents component.
- Uses an adapted version of [React Waypoint](https://github.com/civiccc/react-waypoint) for scroll-spy behavior (i.e. update active item as you scroll). For now, Waypoint-specific code lives with the component in `./waypoint`. This could easily be refactored into Core and used with Nav Priority later on.
- Updates component to use `getUniqueId` helper
- Makes sure only one active item at a time and initial active item is taken into account.
- Fix SSR hydration prep issues in IE11 by switching from `<ssr-keep>` to a new method, avoids the race conditions caused by `<ssr-keep>` loading late in IE11.
- Test TOC demos, especially "Use Case Sticky" for scroll spy …
> TOC | JS | Add smooth scroll and scroll-spy behavior

- packages/components/bolt-menu/__tests__/__snapshots__/menu.js.snap
- packages/components/bolt-menu/src/_menu-item.js
- packages/components/bolt-menu/src/_menu-item.twig
- packages/components/bolt-menu/src/menu.js
- packages/components/bolt-menu/src/menu.twig
http://vjira2:8080/browse/BDS-1986
Adds the proper `role` attributes to indicate `menu` and `menuitem`.
1. `role="menu"` added to parent container.
2. `role="menuitem"` added to each trigger.
3. `role="presentation"` added to any containers in between the menu and menu item to remove any native semantics.
Run the branch locally and check the markup in the Menu docs. Make sure the `role` attributes are in the right places, with or without JS.
> Fix: add missing role attributes to menu component

- packages/base-element/index.js
- packages/base-element/src/lib/decorators.js
- packages/base-element/src/lib/utils.js
- packages/components/bolt-button/src/button.js
http://vjira2:8080/browse/BDS-1981
`@bolt/element` related updates from https://github.com/boltdesignsystem/bolt/pull/1711
- Exposes the `css` lit-element export to `@bolt/element`
- Fixes / addresses the  need for BoltElement components to be able to optionally disable Shadow DOM rendering (regardless of cross-browser support) via a static Class property that can be defined.
Ex.
```
@customElement('bolt-button')
class BoltButton extends BoltElement {
constructor() {
this.useShadow = false; // --> this does NOT work! (and might not ever work) 
}
static useShadow = false; // --> however THIS now works!
```
> `@bolt/element` conditional Shadow DOM fix; add `css` export

- docs-site/src/pages/pattern-lab/_patterns/02-components/icon/999-icon-with-web-component.twig
http://vjira2:8080/browse/BDS-1922
Adds documentation for using `bolt-icon` as a web component.
Simple usage and prop usage are demonstrated in the doc page.
Run the branch locally and check for any typos on the Icon web component doc page.
> Icon | Docs | Add web component documentation

- packages/components/bolt-list/src/_list-item.scss
http://vjira2:8080/browse/BDS-1989
Remove right padding on last list item.
CSS that should be removing this padding is not scoped properly. This fixes the scoping.
- Review code changes.
- Check Inline List demo and verify last item has no right padding.
> fix: remove padding on last list item

- packages/experimental/micro-journeys/src/interactive-pathway.scss
- packages/experimental/micro-journeys/src/interactive-step.scss
- packages/experimental/micro-journeys/src/nav-shared.scss
http://vjira2:8080/browse/WWWD-4540
Remove CSS workarounds for micro journeys in dark theme
- Removes all usages of the `.t-bolt-dark` class in micro journeys CSS.
- Updates dark theme behavior slightly.
Previously, active waypoints looked like this: 
Now, they look like this:
- Go to /pattern-lab/?p=experiments-micro-journeys-solo and confirm micro journeys look as expected in both themes.
- Confirm no regressions
> Remove CSS workarounds for micro journeys in dark theme

- packages/components/bolt-popover/src/popover.js
http://vjira2:8080/browse/BDS-1986
Fix popover double-focus.
We were checking the wrong slot for focusable content. Now we're checking the "default" slot which contains the trigger, the content we actually want to inspect. With that change, it's working as expected.
- Review code change.
- Test this demo on PL: `/pattern-lab/patterns/02-components-popover-20-popover-use-case-menu/02-components-popover-20-popover-use-case-menu.html`. You should only have to tab once to focus on the Popover trigger.
> Fix popover double-focus

- packages/components/bolt-video/plugins/email-plugin.js
Uncaught TypeError: player.emailSocialShare is not a function
COMM-1617 (fixing console.log errors during Bolt upgrade)
Site is throwing following error in console:
```
email-plugin.js?155c:4 Uncaught TypeError: player.emailSocialShare is not a function
at Object.emailPlugin [as email] (email-plugin.js?155c:4)
at eval (video.standalone.js?3c58:161)
at Array.forEach (<anonymous>)
at HTMLElement._setupPlugins (video.standalone.js?3c58:158)
at a.handlePlayerReady (video.standalone.js?3c58:172)
at a.eval (video.standalone.js?3c58:591)
at e (index.min.js:1)
at index.min.js:1
```
Added additional check to prevent TypeError
1. Open Community homepage page before applying the fix. 
2. Check console - you'll see the error.
3. Apply the fix.
4. Check console again - there should be no error.
> Preventing TypeError on emailSocialShare

- docs-site/src/components/pattern-lab-utils/schema-docs.twig
- docs-site/src/components/schema-table/schema-table.scss
Schema docs fixes
This fixes schema docs problems found while working on #1701.  Specifically:
- When `type` in the schema was an array, it was not printed.  For example, here's the breadcrumb component (https://boltdesignsystem.com/pattern-lab/?p=viewall-components-breadcrumb) before and after this PR:
Before:
After:
- When `type` was an array but each item did not have properties, an empty "Properties" label was printed.  For example, here's the content items row of the buttons group component (https://boltdesignsystem.com/pattern-lab/?p=viewall-components-buttons-group) before and after this PR:
Before:
After:
Compare the two links above between master and this branch and confirm that the issues are fixed.
> WWWD-4219 schema docs fixes

- docs-site/src/pages/pattern-lab/_patterns/02-components/card-replacement/00-card-replacement-docs.twig
- docs-site/src/pages/pattern-lab/_patterns/02-components/card-replacement/30-card-replacement-link-variations.twig
- docs-site/src/pages/pattern-lab/_patterns/02-components/card-replacement/999-card-replacement-with-web-component.twig
- packages/components/bolt-card-replacement/src/_card-replacement-settings-and-tools.scss
- packages/components/bolt-card-replacement/src/card-replacement-actions/_card-replacement-actions.scss
- packages/components/bolt-card-replacement/src/card-replacement-background/_card-replacement-background.scss
- packages/components/bolt-card-replacement/src/card-replacement-body/_card-replacement-body.scss
- packages/components/bolt-card-replacement/src/card-replacement-link/_card-replacement-link.scss
- packages/components/bolt-card-replacement/src/card-replacement-media/_card-replacement-media.scss
- packages/components/bolt-card-replacement/src/card-replacement/card-replacement.scss
http://vjira2:8080/browse/BDS-1985
Fixes whole-card clickability which is currently broken because card-body element has greater z-index.
Z-index was added to card-body ([see commit](https://github.com/boltdesignsystem/bolt/commit/37d427863c60e793a6cae34df0777e2852baa5fa)) so that it layers above the new card-background element. This inadvertently blocks the card-link element from being clickable. This PR resorts the z-indexes to fix the bug.
- Review code changes.
- See broken whole-card clickability [on master](https://master.boltdesignsystem.com/pattern-lab/?p=components-card-replacement-link-variations) and verify it's fixed on feature branch.
> fix: whole-card clickability

- packages/build-tools/__tests__/multi-lang/__snapshots__/index.js.snap
- packages/core-v3.x/styles/01-settings/00-settings-lang/_settings.lang-ja.scss
- packages/core-v3.x/styles/01-settings/settings-spacing/_settings-spacing.scss
- packages/global/styles/07-utilities/_utilities-spacing.scss
http://vjira2:8080/browse/BDS-2013
Fixes a bug where negative margins do not match with positive margins.
1. Rewrote the negative margin mixn to be more intuitive.
2. Removed the redundant negative spacing map in both `en` and `ja`.
3. Negative spacing is done with `regular spacing * -1`.
Run the branch locally and test all `.u-bolt-negative-margin-*` utility classes.
> Fix: negative margin mixin and maps

- docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/collections/dashboard/_dashboard-band.twig
http://vjira2:8080/browse/BDS-2010
Fixes links in a list that are wrapping when they should not be.
There is a bug in Safari with our `bolt-list` component that occurs when an inline list is placed inside certain containers. So far we've observed it happening when placed inside a flex grid cell and nested inside `bolt-list`. The bug causes inline elements to wrap to a new line when they have space to fit on a single line.
It appears to be a sub-pixel rounding issue because when we pad the list `width` by 1 pixel (add `+ 1px` to [this](https://github.com/boltdesignsystem/bolt/blob/master/packages/components/bolt-list/src/list.scss#L80-L96) calc function) it fixes itself. However, it causes a separate problem in FF where it's then 1px too wide and can cause scroll bars to appear if the list …
> Fix wrapping links in Safari

- lighthouserc.json
http://vjira2:8080/browse/BDS-2048
Updates Lighthouse assertions to "warn" not "error" on pages that are not crawlable.
Lighthouse Travis job was failing when it hit pages that weren't crawlable, and these are indeed pages we do not want to be crawled. So, the assertion has been updated to only "warn" when a page is not crawlable. It was not specified before, so I assume it was defaulting to "error" as part of the "minScore" assertion.
I also tested a branch with additional feature changes ([fix/test-lighthouse-with-feature](https://travis-ci.com/boltdesignsystem/bolt/builds/150747790)) and it's passing.
- Verify passing builds
> Fix failing Lighthouse job

- packages/website-ui/uikit-workshop/src/scripts/lit-components/pl-viewport-size/pl-viewport-size.js
N/A
Fixes the Pattern Lab UI logic so the width of the viewport displayed is no longer off by 80px. 🤦‍♂ 
Confirm that the width of Pattern Lab's iframe matches up with the width displayed in the header / sidenav.
> Fix Pattern Lab Viewport Resizer Calculation

- packages/build-tools/package.json
- packages/build-tools/tasks/image-tasks.js
- packages/components/bolt-image/src/image.twig
- yarn.lock
http://vjira2:8080/browse/BDS-2045
Fixes animated Gif support in Bolt + updates the Twig to no longer expect multiple `srcset`s to be generated for Gifs.
While working on Hero examples for #1758, I noticed in one of the examples (the one that replicates [this existing Hero](https://www.pega.com/events/pegaworld)) that we have a couple of issues with how Bolt handles (or rather, _doesn't_ handle) animated Gifs:
1. The way animated Gifs were previously getting compressed / handled by our Image build task breaks existing Gif's animations
2. Our image component's Twig template expects Gifs to have multiple sizes generated vs just sticking to generating a single src / srcset.
```
<bolt-image
src="/images/heros/hero-foreground--orange--animated-gif.gif" …
```
> Fix Animated Gif Support in Bolt

- docs-site/src/pages/pattern-lab/_patterns/02-components/popover/25-popover-theme-variations.twig
- packages/components/bolt-popover/__tests__/__snapshots__/popover.js.snap
- packages/components/bolt-popover/__tests__/popover.js
- packages/components/bolt-popover/popover.schema.js
- packages/components/bolt-popover/src/popover.js
- packages/components/bolt-popover/src/popover.scss
- packages/components/bolt-popover/src/popover.twig
N/A (related to http://vjira2:8080/browse/BDS-1465)
Adds a new `theme` prop to Popover so theming classes are added to the correct inner container -- particularly important when wiring up the new Tertiary button styles in https://github.com/boltdesignsystem/bolt/pull/1764.
Note: without this update, themed Popovers using the new Tertiary button have broken styles (colored container that doesn't match up with the button) 
- Test that the new `theme` prop works / is styled correctly for Popover
> Fix / update Popover to better support color theming

- packages/build-tools/__tests__/multi-lang/__snapshots__/index.js.snap
- packages/components/bolt-button/button.schema.js
- packages/components/bolt-button/src/_button-settings-and-tools.scss
- packages/components/bolt-button/src/button.scss
- packages/global/styles/06-themes/_themes.all.scss
http://vjira2:8080/browse/BDS-1465?filter=-1
Adds a new semi-transparent "tertiary" variant of the Button, including psuedo states for hover, active, focus, disabled, etc + full theming support.
- Manually specs out the `tertiary` theming system values to reduce the amount of cruft getting auto-generated --> likely a similar direction we're going to want to be going with other UI work moving forward
- Note: since I'm _not_ using the `bolt-theme` Sass function here, I'm manually including basic IE 11 theming fallbacks styles (but can be easily removed in the near future)
- As a first for Bolt, tertiary Buttons now include basic theming support when _only_ the Button component's CSS / JS is compiled / loaded (unlike other Themed components which are visually broken if the `@bolt/global` …
> Add new tertiary variant to the Button component

- docs-site/src/pages/pattern-lab/_patterns/02-components/breadcrumb/10-breadcrumb-use-case-popover.twig
N/A
Fixes incorrect usage in breadcrumb popover demo page.
Changes `bolt-link` to `bolt-trigger` as the popover trigger. Currently there's a [bug](http://vjira2:8080/browse/BDS-2057) with using `bolt-link` as the trigger. This hides the bug for now.
Run the branch locally and check this page (http://localhost:3000/pattern-lab/?p=components-breadcrumb-use-case-popover). Make sure the popover works as expected.
> Fix: change breadcrumb popover demo to reflect valid usage

- .boltrc.js
- __tests__/monorepo-deps.test.js
- docs-site/src/pages/pattern-lab/_patterns/03-blueprints/02-molecules/numbered-headline/__demos__/10-numbered-headline-blueprint.md
- docs-site/src/pages/pattern-lab/_patterns/03-blueprints/02-molecules/numbered-headline/__demos__/10-numbered-headline-blueprint.twig
- docs-site/src/pages/pattern-lab/_patterns/03-blueprints/02-molecules/numbered-headline/numbered-headline.schema.js
- docs-site/src/pages/pattern-lab/_patterns/03-blueprints/02-molecules/numbered-headline/package.json
- docs-site/src/pages/pattern-lab/_patterns/03-blueprints/02-molecules/numbered-headline/src/_numbered-headline-bullet.twig
- docs-site/src/pages/pattern-lab/_patterns/03-blueprints/02-molecules/numbered-headline/src/numbered-headline.md
- docs-site/src/pages/pattern-lab/_patterns/03-blueprints/02-molecules/numbered-headline/src/numbered-headline.scss
- docs-site/src/pages/pattern-lab/_patterns/03-blueprints/02-molecules/numbered-headline/src/numbered-headline.twig
- docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t2-inner-pages/challenge-details/t2-challenge-detail-page.twig
- docs-site/src/pages/pattern-lab/_patterns/03-blueprints/index.scss
- docs-site/src/pages/pattern-lab/_patterns/03-blueprints/package.json
- package.json
http://vjira2:8080/browse/BDS-2063
Adds a new Numbered Headline variation under Blueprints + basic docs / demo support.
Since this isn't a full blown component, I had to get a little creative on how to get at least _something_ to show up in the Pattern Lab menu + get some basic schema support in place.
Thoughts? Suggestions?
- Review PL docs and demos
> Create new "Numbered Headline" blueprint

- docs-site/src/pages/pattern-lab/_patterns/03-blueprints/02-molecules/training/_completed-training-item.twig
- docs-site/src/pages/pattern-lab/_patterns/03-blueprints/03-organisms/modals/_test-completed-modal.twig
- docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/certification-exam/certification-exam-page.twig
n/a
Replace `xxsmall` text with `xsmall` in Blueprints.
`xsmall` is small enough and `xxsmall` may be deprecated in the future. Replace now proactively so that these values aren't copied into the Academy project.
- [Certification Exam](http://localhost:3000/pattern-lab/patterns/03-blueprints-05-pages-t1-landing-pages-certification-exam-certification-exam-page/03-blueprints-05-pages-t1-landing-pages-certification-exam-certification-exam-page.html): "e.g., in a quiet, uninterrupted room..."
- [Completed Training](http://localhost:3000/pattern-lab/patterns/03-blueprints-05-pages-completed-training-completed-training/03-blueprints-05-pages-completed-training-completed-training.html): "Archived"
> feat: replace `xxsmall` with `xsmall` in Blueprints

- .travis.yml
- docs-site/composer.json
- docs-site/composer.lock
- packages/twig-integration/twig-extensions-compat/composer.json
- packages/twig-integration/twig-extensions-compat/composer.lock
- packages/twig-integration/twig-extensions-shared/composer.lock
- packages/twig-integration/twig-renderer/composer.json
- packages/twig-integration/twig-renderer/composer.lock
http://vjira2:8080/browse/BDS-2075
Updates composer dependencies to work around a Composer [install issue](https://travis-ci.com/github/boltdesignsystem/bolt/jobs/302673561#L436) that just started to pop up on Travis.
I'm not 100% sure on this but I *think* this fix works because one or more of the following (but probably the first two bullets here):
- We're no longer referencing some older composer dependencies (ex. update Twig to `1.42.5`)
- We're switching to using the `stable` channel instead of the `dev` channel
- All Github repos referenced have the [`no-api` flag](https://getcomposer.org/doc/05-repositories.md) added
- We removed the no-longer-needed Github repo reference to `https://github.com/drupal/core-render`
Confirm Travis CI build passes as expected
> Hotfix: Fix for Composer Install Issues on Travis

- packages/components/bolt-hero/hero.twig
http://vjira2:8080/browse/BDS-2079
Fixes a bug where hero `reverseOrder` prop does not work when `imageValign` is `bottom`
I set out only to fix the original bug.  However, I found the existing twig logic for `hero` to be pretty difficult to read, in part because there were a number of logic errors.  For example:
```
{% set _isImageFirstOnMobile = (imageValign != 'bottom') or (imageValign == 'top') %}
{% set _isImageLastOnMobile = (imageValign != 'top') or (imageValign == 'bottom') %}
```
First, both of these statements are logically identical if you remove the second conditions (if something is "not bottom", you don't need to also check for whether it could be "top").
```
{% set _isImageFirstOnMobile = (imageValign != 'bottom') %}
{% set _isImageLastOnMobile = (imageValign != 'top') %} …
```
> fix: Rework logic for grid ordering in hero component

- packages/components/bolt-card-replacement/src/card-replacement-body/_card-replacement-body.twig
- packages/components/bolt-card-replacement/src/card-replacement-media/_card-replacement-media.twig
- packages/components/bolt-card-replacement/src/card-replacement/card-replacement.twig
http://vjira2:8080/browse/BDS-2059
Adds support for render arrays to replacement card
This PR replaces `{{content | join}}` (and all the related workarounds, such as `{{ card_replacement_body_content | join | replace({"UTF-8": ""}) | raw }}`
) with a solution that supports render arrays, doesn't require any workarounds, and is consistent with our docs and all our other components.  It's also quite simple:
`{{ content }}`.
**Why was the `join` filter used to begin with?**
I think it was just a mistake.  There's no usage of `| join` in the original card.  There are some usages of the join filter [directly](https://github.com/boltdesignsystem/bolt/blob/master/docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/module-landing/t1-module-landing-page.twig#L147) in …
> fix: Remove join filters and related workarounds in replacement card

- .travis.yml
- scripts/get-branch-alias.js
http://vjira2:8080/browse/BDS-2037 (Related But Doesn't 100% Resolve) 
Re-enables the our ability to easily find the commit-specific and branch-specific deployment URLs in Github -- a core piece of functionality that we unfortunately lost recently (when we added a temp workaround to the check run bad credentials error on Travis). 
This PR adds inline "View Deployment" buttons next to specific commits that are pushed up in addition to providing a super helpful box at the bottom of the PR screen with the latest branch and commit-specific URLs:
NOTE: I renamed the labels for these `branch-preview` and `commit-preview` deployments mid-way through the work on this, hence why this PR has 4 links but [this bugfix test PR](https://github.com/boltdesignsystem/bolt/pull/1816) only has the two …
> Re-enable branch and commit-specific now.sh deploy preview URLs on Github

- packages/components/bolt-list/src/list.scss
http://vjira2:8080/browse/BDS-2087
Fixes Safari sub-pixel rendering bug.
Setting a width on List was required to fix a FF-only bug, but it turns out it causes a different bug in Safari. To fix Safari, simply scope the `width` rule to FF-only.
Supercedes #1805.
Review the following pages in Chrome, Safari, FF, and Edge. Verify they work as expected:
- [Completed Training template](https://fix-list-wrapping-bug.boltdesignsystem.com/pattern-lab/patterns/03-blueprints-05-pages-completed-training-completed-training/03-blueprints-05-pages-completed-training-completed-training.html)
- [List demos](https://fix-list-wrapping-bug.boltdesignsystem.com/pattern-lab/patterns/02-components-list/index.html)
> Fix List wrapping bug

- packages/components/bolt-card-replacement/src/card-replacement/card-replacement.twig
N/A
Allows card url attributes to be empty
null arguments to the `create_attributes()` twig function result in PHP errors in Drupal.  Based on existing Bolt conventions, you should provide an empty default argument unless you know the argument will not be null.
> fix: Allow card url attributes to be empty

- docs-site/src/pages/pattern-lab/_patterns/02-components/accordion/999-accordion-web-component.twig
N/A
Fixes a typo on the Accordion web component demo page.
Run the branch locally and check the Accordion web component demo page, make sure the `open` prop is named `open` not `auto-open` on the accordion item.
> Fix: accordion open prop typo in web component demo

- docs-site/__tests__/pattern-lab.e2e.js
- packages/components/bolt-typeahead/__tests__/typeahead.e2e.js
http://vjira2:8080/browse/BDS-2033
Remove uses of `browser.sendKeys()` from our tests, only needed if we're supporting IE11.
> IE11 deprecation testing updates

- .travis.yml
- scripts/get-git-sha.js
N/A
Updates the Travis CI logic handling deployment URL integration with more that most recent deployments don't accidently wipe older deployments (especially on different branches).
> Update Github Deployment Status logic so deployment env names are tied to a specific branch 

- packages/components/bolt-li/src/li.js
- packages/components/bolt-li/src/li.scss
- packages/components/bolt-li/src/li.twig
- packages/components/bolt-ol/__tests__/__snapshots__/ol.js.snap
- packages/components/bolt-ol/src/ol.js
- packages/components/bolt-ol/src/ol.twig
- packages/components/bolt-ul/__tests__/__snapshots__/ul.js.snap
- packages/components/bolt-ul/src/ul.js
- packages/components/bolt-ul/src/ul.twig
http://vjira2:8080/browse/BDS-2042
Fixes an issue where `bolt-ol` and `bolt-ul` are not being read as a list by screen readers.
1. `role="list"` is added to the `.c-bolt-ol` and `.c-bolt-ul` elements
2. `role="listitem"` is added to the `.c-bolt-li` element
3. `role="presentation"` is added to any layers in between `.c-bolt-ol` and `.c-bolt-li`
4. `role="presentation"` is added to any layers in between `.c-bolt-ul` and `.c-bolt-li`
Pull down the branch locally and perform the following.
> Fix: add proper attributes to bolt-ol and bolt-ul for accessibility

- docs-site/src/pages/pattern-lab/_patterns/03-blueprints/01-atoms/_badge.twig
- docs-site/src/pages/pattern-lab/_patterns/03-blueprints/05-pages/t1-landing-pages/mission-landing/t1-mission-landing.twig
- docs-site/src/pages/pattern-lab/_patterns/03-blueprints/index.scss
http://vjira2:8080/browse/BDS-2114
Add "locked" Badge template to Blueprints.
> Opened instead of #1847 which had unexplained failing tests.
Add "locked" option to Badge template that fades out the badge and displays a lock over it.
Added a new utility class, `u-bolt-absolute-center`, to help set this up. Also removed some unnecessary grid and utility classes from the Badge template.
- Do you approve of the [new utility class](https://github.com/boltdesignsystem/bolt/pull/1847/files#diff-1c64ddc1abae139b0b22adc69eb8fbb2)?
- See "locked" badge demo on feature branch: `/pattern-lab/patterns/03-blueprints-05-pages-t1-landing-pages-mission-landing-t1-mission-landing/03-blueprints-05-pages-t1-landing-pages-mission-landing-t1-mission-landing.html`
> Add "locked" Badge to Blueprints

- packages/components/bolt-chip-list/src/chip-list.js
- packages/components/bolt-chip-list/src/chip-list.twig
N/A
Hotfix to the new `<bolt-chip-list>` truncate functionality released in `v2.22.0` that handles when the `.c-bolt-chip-list__input` element doesn't exist... throws a JS error otherwise when you hit the main Chip List docs section: https://v2-22-0.boltdesignsystem.com/pattern-lab/?p=viewall-components-chips-list
1. Confirm that the new Chip List functionality still works as expected after this fix is applied
2. Confirm that the JS error that was getting thrown on the [Chip List docs page in `v2.22.0`](https://v2-22-0.boltdesignsystem.com/pattern-lab/?p=viewall-components-chips-list) no longer occurs.
> hotfix: update Chip List JavaScript to handle when the `.c-bolt-chip-list__input` element doesn't exist

- docs-site/src/pages/docs/50-guides/60-migrating-to-3.x.md
- packages/build-tools/plugins/postcss-themify/README.md
- packages/components/bolt-critical-css-vars/README.md
- packages/components/bolt-critical-css/README.md
- packages/components/bolt-critical-fonts/README.md
- packages/components/bolt-critical-path-polyfills/README.md
- http://vjira2:8080/browse/BDS-2091 (deprecate packages)
- http://vjira2:8080/browse/BDS-2071 (migration docs)
Deprecate packages that will be removed in `v3.x` and add docs for migrating to `v3.x`.
- Deprecates the following packages in the NPM registry:
- `postcss-themify`
- `components-critical-css`
- `components-critical-css-vars`
- `components-critical-fonts`
- `critical-path-polyfills`
- Add note to each package's `README.md` linking to migration docs
- Add initial migration docs (subject to change as we get closer to v3.0)
1. View the following on NPM and verify they are deprecated:
- https://www.npmjs.com/package/@bolt/postcss-themify
- https://www.npmjs.com/package/@bolt/components-critical-css
- https://www.npmjs.com/package/@bolt/components-critical-css-vars
- …
> Add deprecation notices and migration docs

- packages/experimental/micro-journeys/src/interactive-pathways.js
http://vjira2:8080/browse/WWWD-4726
Updates the Micro Journey JS logic in the Interactive Pathways subcomponent to only have the `beginItAll` (aka init() function) method fire _once_ so the animation sequence won't be unintentionally restarted. 
This small patch also cleans up any existing observers present which also helps to ensure that animations (or previous interactions the user has taken) aren't unintentionally restarted.
This JS update is 1:1 with what was already tested and approved downstream ([see this comment for reference](http://vjira2:8080/browse/WWWD-4726?focusedCommentId=79974&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-79974)) but in general with these updates any panels that have already been opened (or scrolled away from before …
> Micro Journey intersection observer-related fix to prevent "restarts" when scrolling away

- docs-site/src/pages/pattern-lab/_patterns/02-components/link/28-link-with-button-element.twig
- packages/build-tools/__tests__/multi-lang/__snapshots__/index.js.snap
- packages/components/bolt-link/__tests__/__snapshots__/link.js.snap
- packages/components/bolt-link/__tests__/link.js
- packages/components/bolt-link/src/link.js
- packages/components/bolt-link/src/link.scss
- packages/components/bolt-link/src/link.twig
http://vjira2:8080/browse/BDS-2057
Allows Link to be used as a trigger for Popover.
Currently, if you pass `<bolt-link>` as a trigger for Popover it results in nested anchor tags, which is invalid and breaks the layout. This happens because Twig wraps the trigger in an anchor to make the Popover accessible when JS is off.
We want to use Link with Popover, and we want to keep our current no-JS solution. So, the fix was to make Link internally render a `<button>` when no `url` is provided. Semantically, this is better than outputting an `<a>` that is not actually an anchor, and it solves the nested anchor problem.
- See the [Link with Button element](https://feature-link-as-popover-trigger.boltdesignsystem.com/pattern-lab/?p=components-link-with-button-element) demo …
> Link as popover trigger

- docs-site/src/pages/pattern-lab/_patterns/03-blueprints/index.scss
http://vjira2:8080/browse/AC-727
Tiny CSS update to fix a layout issue in Safari and Firefox.
Confirm that compared to the [previous release](https://v2-22-1.boltdesignsystem.com/pattern-lab/?p=blueprints-t1-mission-landing--test-with-modal), the updated [Mission Landing Test w/ Modal page](http://localhost:3000/pattern-lab/?p=blueprints-t1-mission-landing--test-with-modal) no longer wraps to multiple lines unexpectedly in Safari and Firefox on larger screens + looks the same in Chrome / Edge.
> Rate This Mission Blueprint Layout Fix for Safari / Firefox

- packages/testing/testing-nightwatch/package.json
- yarn.lock
http://vjira2:8080/browse/BDS-2140
Attempt to fix intermittent build failures on Travis.
Several branches plus `master` are failing intermittently on Travis, but not failing locally. Some failures point to a [`chromeDriver` error](https://travis-ci.com/github/boltdesignsystem/bolt/jobs/339700602#L738). Try upgrading `chromeDriver` to latest stable version to see if it is the root problem.
`master` consistently builds successfully on Travis.
> test: upgrade Chromedriver, troubleshooting Travis test failures

- docs-site/src/pages/pattern-lab/_patterns/02-components/video/autoplay/-autoplay-and-loop-hide-controls.twig
- docs-site/src/pages/pattern-lab/_patterns/02-components/video/autoplay/-autoplay-and-loop.twig
- docs-site/src/pages/pattern-lab/_patterns/02-components/video/autoplay/-autoplay.twig
- packages/components/bolt-video/src/video.standalone.js
WWWD-4750
Video autoplay does not work on iPhone and iPad.
Because IOS policy `<video>` tag require extra parameter `playsinline` added.
Refer docs:
- https://medium.com/code-divoire/autoplaying-inline-videos-on-iphone-ios-10-using-angular-d4e2eaba2164
- https://webkit.org/blog/6784/new-video-policies-for-ios/
> Allow autoplay video for iPhone/iPad when controls disabled

- docs-site/src/pages/pattern-lab/_patterns/02-components/video/70-video-with-default-error-message.twig
- docs-site/src/pages/pattern-lab/_patterns/02-components/video/70-video-with-error-message.twig
- docs-site/src/pages/pattern-lab/_patterns/02-components/video/71-video-with-custom-error-message.twig
- packages/components/bolt-video/src/_video-tag.twig
- packages/components/bolt-video/src/_videojs-enhancements.scss
- packages/components/bolt-video/src/video.standalone.js
- packages/components/bolt-video/video.schema.yml
BDS-2118: Investigate options for Brightcove error styling/UX
Included an update to the display of the Brightcove error to make it closer to brand
This is a hotfix to make the Brightcove video display look better before PegWorld. This is a quick fix and a better solution should be figured out post PegaWorld.
1. Navigate to https://feature-bds-2118.boltdesignsystem.com/pattern-lab/?p=components-video-with-error-message
2. Observe the video is now displaying with an indigo background color and white text horizontally and vertically centered.
> BDS-2118: Investigate options for Brightcove error styling/UX

- packages/components/bolt-tooltip/src/tooltip.js
http://vjira2:8080/browse/BDS-2134
Fix flicker when you hover over Button with Tooltip by removing debounce on mouse events.
See [demo on master](https://master.boltdesignsystem.com/pattern-lab/?p=components-tooltip-use-case-button-and-link) and hover over "Download" Button. Notice how the button begins to animate, flickers, then resumes animating.
This is an unfortunate side effect of [debouncing the Tooltip](https://github.com/boltdesignsystem/bolt/blob/master/packages/components/bolt-tooltip/src/tooltip.js#L73-L75) `mouseleave` and `mouseenter` events, which was added to fix another bug: if you mouse quickly over the Tooltip triggers on this [demo](https://fix-tooltip-flicker.boltdesignsystem.com/pattern-lab/?p=components-tooltip-placement-variations) (your mouse must enter and leave …
> Fix tooltip flicker

- docs-site/src/pages/pattern-lab/_patterns/02-components/code-snippet/25-code-snippet-web-component.twig
- docs-site/src/pages/pattern-lab/_patterns/02-components/code-snippet/999-code-snippet-web-component.twig
- packages/components/bolt-code-snippet/src/_code-snippet-base.scss
- packages/components/bolt-code-snippet/src/code-snippet.standalone.js
https://pegadigitalit.atlassian.net/browse/DS-104
Fixes default lang prop for the code snippet component
WC logic was previously such that lang was not set to the schema default by default.
Confirm that the new web component example works without any attributes.
/pattern-lab/patterns/02-components-code-snippet-25-code-snippet-web-component/02-components-code-snippet-25-code-snippet-web-component.html
> DS-104 code snippet web component default props and text wrapping

- packages/components/bolt-table/src/table.scss
https://pegadigitalit.atlassian.net/browse/PPR-37
Fixes an issue where the regular table is using monospace font (which is intended for numeric table only).
Updated the CSS to only use monospace under the numeric modifier.
Run the branch locally and check the Table docs. Make sure regular tables are using Opens Sans and numeric tables are using monospace.
> Fix: font family for regular table

- packages/experimental/micro-journeys/index.js
- packages/experimental/micro-journeys/package.json
WWWD-4473
A bolt-release release process based on webpack create a chunkName based on a name defined in package.json.
During that process, from name, there are removed special characters.
The cleaned name match a chunkName was used on `index.js` file, that cause duplicate chunkName error:
`It's not allowed to load an initial chunk on demand. The chunk name "bolt-micro-journeys" is already used by an entrypoint.`
> MicroJourneys: Remove calling `main.js` file with a chunkname; Add missing dependency

- packages/components/bolt-list/src/list.scss
https://pegadigitalit.atlassian.net/browse/ACD-17
Fixes bug where Table inside a List is not properly responsive.
Bug is caused by the List being set to display `flex`. This allows the Table to overflow the container and the horizontal scroll bar on the Table never kicks in.
After setting List to `block`, I noticed the negative margin used on list was collapsing the margin around the List. For example, if you put a List inside a Stack, the space provided by the Stack collapses. This I fixed with a pseudo element clearfix.
- Review files changed.
- Review List demos, especially "display" and "spacing", and check for any regressions.
- Copy this demo code into PL and verify:
- Table is responsive inside the List
- There is proper space between each Stack
```
<h3>Test 1: Table in List is …
```
> Fix Table overflowing List bug

- docs-site/src/components/pattern-lab-utils/docs.twig
- packages/generators/yeoman-create-component/generators/component/add-bolt-package.js
- packages/generators/yeoman-create-component/generators/component/index.js
- packages/generators/yeoman-create-component/generators/component/templates/package.json
- packages/generators/yeoman-create-component/generators/component/templates/package.tpl.json
https://pegadigitalit.atlassian.net/browse/DS-114
Fix component generator regressions, update to reflect recent architectural changes.
- Check that changelog file exists before using it in Twig.
- Don't assume latest Bolt release version number matches latest Bolt Core version number. In the case of a hotfix they might be different, and this causes generator to add core dependency at a version number that doesn't exist.
- We've consolidated how we include Bolt components in `.boltrc`. Instead of adding each component individually to [docs-site `.boltrc`](https://github.com/boltdesignsystem/bolt/blob/master/docs-site/.boltrc.js#L87-L119), we add them to [Starter Kit `.boltrc`](https://github.com/boltdesignsystem/bolt/blob/master/packages/base-starter-kit/.boltrc.js#L3-L68). Updated …
> Component generator updates

- auto-release.js
- packages/core-v3.x/styles/02-tools/tools-font-family/_tools-font-family.scss
- packages/core-v3.x/styles/02-tools/tools-font-size/_tools-font-size.scss
- packages/core-v3.x/styles/02-tools/tools-font-weight/_tools-font-weight.scss
- packages/core-v3.x/styles/02-tools/tools-spacing/_tools-spacing.scss
- packages/core-v3.x/styles/02-tools/tools-spacing/libs/_tools-spacing-margin.scss
- packages/core-v3.x/styles/02-tools/tools-spacing/libs/_tools-spacing-padding.scss
N/A
Builds on the Drupal side are stalling (e.g. http://vbamboo:8085/browse/BOLT-RPKG84-2)
It seems that the problem started happening when we added the sass warnings.  I suspect the warnings are causing memory issues or similar.
- Create a build locally using the tip of this branch and the bolt-release-build project:
`git clone git@vstash:7999/bolt/bolt-release-build.git` (must be on VPN)
`cd bolt-release-build`
`yarn gulp --bolt-version=2fbf8680`
- Confirm no errors
- To reproduce and/or troubleshooting the problem, try building with Bolt version 2.25.0
`yarn gulp --bolt-version=v2.25.0`
> Hotfix: sass warnings drupal build issues

- package.json
https://pegadigitalit.atlassian.net/browse/DS-131
Fix pre-commit, pre-push, Git hooks.
Git hooks appeared to stop working. Actually, they are working when you commit from command line, but are skipped if you use Source Tree, as I do.
Looks like there are issues with both Husky (which we use for hooks) and Source Tree that contribute to this issue ([see issue](https://github.com/typicode/husky/issues/734)), but it can be fixed by simply downgrading Husky.
- On master, edit [`packages/components/bolt-popover/src/popover.scss (L40-41)`](https://github.com/boltdesignsystem/bolt/blob/master/packages/components/bolt-popover/src/popover.scss#L40-L41)  and switch the order of the `display` and `position` rules, so that `position` comes first. This should produce a stylint error.
- Stage and …
> Fix Git hooks

- packages/configs/stylelint-config/ideal.js
https://pegadigitalit.atlassian.net/browse/DS-132
Stylelint's [`value-list-comma-newline-after`](https://stylelint.io/user-guide/rules/value-list-comma-newline-after) conflicts with Prettier, so you get different results depending upon which is run last. Remove rule from Stylelint and go with Prettier.
The conflict only happens in certain scenarios, for example [this type](https://github.com/boltdesignsystem/bolt/blob/master/packages/components/bolt-carousel/src/_carousel.next-previous-buttons.scss#L51-L58) of CSS rule:
```
box-shadow:
0 -1px 2px bolt-theme(background),
0 1px 2px bolt-theme(background),
0 0 5px rgb(59, 153, 252),
0 -1px 0.65rem rgb(59, 153, 252),
0 1px 0.65rem rgb(59, 153, 252);
}
```
Prettier will try to put values on the same line until a max line length is reached. …
> Fix Stylelint conflict with Prettier

- .autorc
- .github/pr-labeler.yml
- .github/workflows/pr-labeler.yml
https://pegadigitalit.atlassian.net/browse/DS-106
Simplifies the labels and their usage in the auto release
All PRs should now only have one of three labels: `type: docs`, `type: bugfix`, or `type: feature`.  This will determine the section of the release notes in which the PR is listed.  Also, none of these labels should need to be added manually-- they should get added automatically based on the branch name.
The only label that should need to be applied manually to any normal PR (`feature/`, `bugfix/`, or `docs/`) is the the `breaking change` label, if it contains a breaking change and therefore requires a major release.
Finally, to create a release, create a PR going into the `release/2.x` branch.  Label it either `version: minor` (90% of the time), `version:hotfix` (10% of the time), …
> DS-106 simplify labels

- jest.config.js
- packages/base-starter-kit/.boltrc.js
- packages/base-starter-kit/package.json
- packages/elements/bolt-link/__tests__/__snapshots__/link.js.snap
- packages/elements/bolt-link/__tests__/link.js
- packages/elements/bolt-link/index.js
- packages/elements/bolt-link/index.scss
- packages/elements/bolt-link/link.schema.js
- packages/elements/bolt-link/package.json
- packages/elements/bolt-link/src/_link-macros.twig
- packages/elements/bolt-link/src/link.js
- packages/elements/bolt-link/src/link.scss
- packages/elements/bolt-link/src/link.twig
- packages/layouts/bolt-list/__tests__/__snapshots__/list.js.snap
- packages/layouts/bolt-list/__tests__/list.js
- packages/layouts/bolt-list/index.js
- packages/layouts/bolt-list/index.scss
- packages/layouts/bolt-list/list.schema.js
- packages/layouts/bolt-list/main.js
- packages/layouts/bolt-list/package.json
- packages/layouts/bolt-list/src/_list-item.js
- packages/layouts/bolt-list/src/_list-item.scss
- packages/layouts/bolt-list/src/_list-item.twig
- packages/layouts/bolt-list/src/list.js
- packages/layouts/bolt-list/src/list.scss
- packages/layouts/bolt-list/src/list.twig
https://pegadigitalit.atlassian.net/browse/DS-140
Setup initial "elements" and "layouts" namespaces in Bolt. Add _private_ Link element and List layout as starting point.
For the most part, adding "elements" and "layouts" requires no config changes, just adding new packages with the appropriate name, e.g. `@bolt/elements-*`. The only config change required was Jest, adding `elements` and `layouts` to the list of directories that are compiled by Babel before running tests.
At the moment, "elements" and "layouts" are top-level directories within the "packages" folder. It would be nicer if they were grouped together with "components", but as that would require moving _every single component_ I suggest we wait and reevaluate once we're ready to ship our first "element" and/or "layout".
Note: …
> DS-140: setup "elements" and "layouts" namespaces

- packages/core-v3.x/index.js
- packages/core-v3.x/modules/click-handler.js
- packages/core-v3.x/modules/index.js
- packages/core-v3.x/modules/modules.js
- packages/core-v3.x/modules/src/click-handler.js
https://pegadigitalit.atlassian.net/browse/DS-24
Add "modules" to Bolt Core, a place to add JS outside of web components.
Currently the way we ship JS in the design system is with web components (Example: `bolt-carousel`). Going forward, we're adopting a hybrid approach, where we use WCs when appropriate but we also have the option to ship JS functionality without requiring the use of WCs. Basically, we want progressive enhancement without requiring a new custom element. To solve this we're trying out a system where JS modules are instantiated on a DOM element via data attribute.
As an initial example, I setup a `ClickHandler` module, which is JS functionality from Link and Button that will be dropped when converted to an "element".
Other JS functionality that might make sense as a …
> Add "modules" to Bolt Core

- packages/base-element/src/lib/decorators/json-schema-props.js
https://pegadigitalit.atlassian.net/browse/DS-169
Fix broken icons in Micro Journeys GrapesJS editor.
The bug was introduced when Icon was refactored to use `BoltElement` as its renderer in #1861.
The underlying issue was not `BoltElement` itself but one of the custom decorator functions used by `BoltElement`.
[The `jsonSchemaProps` function](https://github.com/boltdesignsystem/bolt/blob/master/packages/base-element/src/lib/decorators/json-schema-props.js#L33-L88) loops through the schema and automatically adds schema props to Web Components. It was also adding Twig-only props like `attributes`, `content`, `items`. Everywhere else, having these Twig-only props defined on our Web Components is harmless. However, GrapesJS uses its own `attributes` prop to store data on each element. When …
> DS-169: Fix broken icons in Micro Journeys

- packages/components/bolt-band/__tests__/__snapshots__/band.js.snap
- packages/components/bolt-blockquote/__tests__/__snapshots__/blockquote.js.snap
- packages/components/bolt-headline/src/_typography.twig
https://pegadigitalit.atlassian.net/browse/DS-171
Fix fatal error in Drupal when twig debugging is enabled
Schema validation is duplicated in the headline component (the result of a botched merge?).  It wasn't a problem until we changed our schema to js, at which point it uncovered another bug in Basalt twig tools.  This PR is the easiest path to fixing.
- Run Bolt 2.26 (or probably 2.25) in Drupal
- Enable twig debugging by adding or uncommenting the following lines in docroot/sites/development.services.yml
```
parameters:
twig.config:
debug: true
```
- Refresh the homepage of the site.  You should see a fatal error
- Apply the patch in this PR to make it go away.
> DS-171 Remove redundant and incorrect schema validation for headline

- packages/components/bolt-hero/hero.twig
https://pegadigitalit.atlassian.net/browse/COM-93
Fix hero center alignment
When you pass "center" as a value for the imageAlign prop, it doesn't work.  After this fix, it does. 
There is no example of this in pattern lab-- you'd need to add an example with `imageAlign: 'center'` to see it in action.  Before this commit, it won't center align (it will behave the same as `imageAlign: right`).  After this commit, it should behave.
> COM-93 Fix hero center alignment

- packages/core-v3.x/styles/02-tools/tools-spacing/_tools-spacing.scss
- packages/core-v3.x/styles/02-tools/tools-spacing/libs/_tools-spacing-margin.scss
- packages/global/styles/05-objects/objects-grid/_objects-grid.scss
- packages/global/styles/07-utilities/_utilities-spacing.scss
Fixed a bug where one direction `.u-bolt-margin-*` and `.u-bolt-padding-*` utils were adding spacing to all directions.
1. Fixes an incorrect logic in the spacing util CSS.
1. Converted spacing mixin and functions to also use CSS vars.
1. Reverted a change on xlarge grid to only increase gutter spacing and not row gutter spacing.
Run the branch locally and do the following
1. Make sure one direction `.u-bolt-margin-*` and `.u-bolt-padding-*` utils are only adding spacing to specified direction.
1. Use a dummy component to test out `bolt-margin()` and `bolt-padding()` mixins and `bolt-spacing` and `bolt-v-spacing` functions. Make sure they are rendering css vars.
1. Change a grid modifier on any page under "Pages", see if xlarge grid spacing (when cells stack vertically) is exactly the …
> DS-139: fix spacing utils

- packages/components/bolt-link/src/link.scss
https://pegadigitalit.atlassian.net/browse/DS-180
Fixes an issue where a button link (`<button class="c-bolt-link">`) is displaying font styles incorrectly.
1. Updated `button.c-bolt-link` specific CSS to inherit font styles from parent container.
1. Added comments about the inherit rule.
Run the branch locally and try to pass a button link to the `text` prop of a headline. Make sure all the font styles are displayed correctly according to how the headline is configured.
> DS-180: fix font styles on button link

- packages/components/bolt-form/src/form.scss
https://pegadigitalit.atlassian.net/browse/DS-179
Updates the input focus styles to be more noticeable in dark themes.
1. Box-shadow on `:focus` is updated to be stronger.
1. Separated hover and focus styles.
1. Removed out-dated comments in CSS.
Run the branch locally and check the form demo in various themes. Make sure the focus styles are noticeable in dark themes.
> DS-179: update input focus styles to display well in dark themes

- packages/core-v3.x/styles/02-tools/tools-spacing/_tools-spacing.scss
Reverted the `bolt-spacing` and `bolt-v-spacing` functions back to scss.
1. Updated spacing.scss in tools to generate the functions based on old maps
1. Comments added in CSS to turn on the new converted functions after all scss math has been converted to use `calc()`
Run the branch locally, and pick a random component to use the `bolt-spacing` and `bolt-v-spacing` functions in CSS. Make sure the spacing are rendering correctly with plain tokens or scss math.
> DS-139: revert spacing functions back to scss

- docs-site/src/pages/pattern-lab/_patterns/04-pages/55-d8-calculator/calculator.scss
Fixes an issue where styles were not loading if the OS's reduced motion setting is turned on.
Reset the transform and opacity inside the reduced motion logic.
Run the branch locally. Turn on reduced motion in your OS and load the calculator page, make sure everything still shows up.
> DS-160: fix reduced motion logic on animation

- packages/build-tools/tasks/api-tasks/bolt-versions.js
https://pegadigitalit.atlassian.net/browse/DS-191
Check that tag is valid semver before adding to array of Bolt versions.
Prevents an invalid version from causing the whole build to fail.
- Review code
- Build + Deploy step of build is passing. Note Jest tests are currently failing for other reasons.
> DS-191: Fix invalid version error

- .travis.yml
https://pegadigitalit.atlassian.net/browse/DS-183
Remove `vrt-urls` test from "Nightwatch End-to-End (Full)" Post-deploy step.
I suspect the `vrt-urls` test is failing here because `yarn run build` is not run in this Post-deploy step. The test needs the build to be run to generate required JSON. The file is either not there or not where we expect it to be when run this way.
The test seems to be working reliably in the Pre-deploy step where `yarn run build` is always run. I'm leaving it there and removing from the Post-deploy step.
Build is passing.
> DS-183: Remove vrt-urls test from Post-deploy step

- packages/components/bolt-nav-priority/nav-priority.js
https://pegadigitalit.atlassian.net/browse/DS-196
Fix bug in Safari where Priority Nav "More" menu appears even when there's enough room to display all the items.
Compare [Navbar centered on master](https://master.boltdesignsystem.com/pattern-lab/patterns/40-components-navbar-05-navbar--centered/40-components-navbar-05-navbar--centered.html) to [Navbar centered on this feature branch](https://boltdesignsystem-kerxi2y1q.vercel.app/pattern-lab/patterns/40-components-navbar-05-navbar--centered/40-components-navbar-05-navbar--centered.html). On master, in Safari at medium-large screen size, you'll see that the "More" menu stays visible even when all the items fit.
I assume this is what the [`offsettolerance`](https://github.com/boltdesignsystem/bolt/commit/997998ad6e99f7420d320ef13914107f0606a …
> DS-196: Fix Priority Nav bug in Safari

- packages/components/bolt-tabs/src/tabs.scss
https://pegadigitalit.atlassian.net/browse/WWW-171
Fixes padding issues in Edge 17, Edge 42, etc. on tabs
It's unclear why this works and why it's not a problem in other places.  We need to follow up with a bigger discussion with marketing.
- Open https://boltdesignsystem.com/pattern-lab/?p=components-tabs in Browserstack using Edge 17
- Confirm that the tabs are smooshed together
- Open the same page on this branch and confirm the bug is fixed.
> WWW-171 Add workaround for tabs bug in older Edge

- packages/components/bolt-video/src/_videojs-enhancements.scss
https://pegadigitalit.atlassian.net/browse/DS-209
Use `clip-path` to render the play button.
Below I add a picture showing the before and after effect on Safari.
I check if the play button is rendered correctly on Safari, Chrome, Edge, Firefox, on iOS, and Android. In all places, the button was rendered correctly. Here is a link to Can I Use showing that this solution should work on all browsers that we support: https://caniuse.com/css-clip-path
Go to the video component page and check if the play button is rendered properly especially in Safari but we should check that on all browsers that we support.
(Optionally, add details that will be added to the release notes. Use this to call out deprecations. [Read more](https://intuit.github.io/auto/docs/generated/changelog#additional-release-not …
> Fix issue with play icon on Safari

- docs-site/src/pages/pattern-lab/_patterns/50-pages/55-d8-calculator/00-d8-calculator.twig
- docs-site/src/pages/pattern-lab/_patterns/50-pages/55-d8-calculator/00-d8-results.twig
- docs-site/src/pages/pattern-lab/_patterns/50-pages/55-d8-calculator/calculator.scss
https://pegadigitalit.atlassian.net/browse/WWW-209
Fixes an issue where the calculator content flashes while it's loading.
1. Updated CSS animation to wait for the bolt-band to become ready first.
1. `<noscript>` markup is added to show a message saying calculator requires JS to load.
Run the branch locally and navigate to the calculator page. Use your browser's dev tool to run the page using fast 3G speed, make sure the content of the page slowly animates in without any flickering.
> WWW-209: make animation wait till JS is loaded

- packages/components/bolt-accordion/package.json
- packages/components/bolt-card-replacement/package.json
- packages/components/bolt-list/package.json
https://pegadigitalit.atlassian.net/browse/DS-45
Add missing `wc-context` dependency to recently converted components, including List.
Forgot to add `wc-context` as a dependency, previously import came from core, so this was missed. Adding it now.
Review code changes, build is passing.
> DS-45: Add missing 'wc-context' dependencies

- packages/components/bolt-accordion/src/accordion.js
- packages/components/bolt-carousel/src/carousel.js
- packages/components/bolt-tabs/src/tabs.js
https://pegadigitalit.atlassian.net/browse/DS-198
Rename `update` to `updateLayout` to prevent conflict with the [Lit Element's `update` method](https://lit-element.polymer-project.org/guide/lifecycle#update).
We have been using a custom method called `update` on components that need to "update" their layout when a parent component changes state. For example, when an Accordion item that contains a Carousel opens, the Accordion component calls `update` on the Carousel to tell it to resize itself.
LitElement already has a method called `update`, so I'm renaming ours to `updateLayout`. Tabs is the first component where there will be a conflict between the two. So, I'm making this change separately before including the Tabs renderer upgrade changes.
- Checkout code locally.
- Go to Accordion …
> DS-198: Rename `update` to `updateLayout`

- docs-site/src/pages/pattern-lab/_patterns/50-pages/55-d8-calculator/00-d8-calculator.twig
- docs-site/src/pages/pattern-lab/_patterns/50-pages/55-d8-calculator/calculator.scss
https://pegadigitalit.atlassian.net/browse/WWW-269
Fixes an issue where the calculator background image overflows.
1. Updated CSS to contain the overflow.
1. Added a class in the markup to contain the image.
Run the branch locally and navigate to the calculator page, open it in a new tab outside of PL. Make the browser narrow (below 600px). Try to side scroll and make sure it doesn't happen.
> WWW-269: fix calculator background overflow

- docs-site/src/pages/pattern-lab/_patterns/40-components/modal/52-modal-usage-persistent.twig
- packages/components/bolt-modal/__tests__/__snapshots__/modal.js.snap
- packages/components/bolt-modal/src/modal.js
https://pegadigitalit.atlassian.net/browse/DS-149
Properly set initial focus when modal first opens.
On open, modal now focuses on 1) the built-in close button 2) the first element with `autofocus` attribute or 3) the first focusable element, in that order.
I updated the persistent modal demo so that the custom close button has `autofocus`.
> Note: @mikemai2awesome in the persistent demo the custom close button _does_ get focus, but the focus style doesn't seem to apply unless you tab onto it. If I add an explicit `.c-bolt-link:focus` style to the Link SCSS that style _does_ work.
- Review Modal demos and verify the expected element gets focus on open.
> DS-149 Fix Modal focus

- packages/components/bolt-video/src/_videojs-enhancements.scss
https://pegadigitalit.atlassian.net/browse/DS-184
Updated the brightcove video styles to style the details section
CSS changes to fix the brightcove error message.
Unfortunately I am not sure how to set this up to test without manually updating the DOM in the inspector. I have attached a screenshot of the styled message (the "The media could not be loaded, either because the server or network failed or because the format is not supported." is the additional styled bit).
> DS-184: Video error message styling doesn't always work

- packages/components/bolt-tabs/__tests__/__snapshots__/tabs.js.snap
- packages/components/bolt-tabs/__tests__/tabs.js
- packages/components/bolt-tabs/src/TabPanel/index.js
- packages/components/bolt-tabs/src/tabs.js
https://pegadigitalit.atlassian.net/browse/DS-198
Convert Tabs component to BoltElement renderer.
Convert Tabs to use new renderer, along with new `wc-context` library.
Because `wc-context` works well with props, it made sense to convert some variables into internal props. As that conversion was underway, I noticed there was some unnecessary complexity (written by yours truly) that it made sense to simplify just to better understand how the component worked. So this PR does includes some careful rework in addition to the renderer upgrade.
Test snapshots are updated. Due to errors waiting for promises to resolve in Puppeteer, some of the updated snapshots are taken before the component finishes updating, so they're not very helpful. I commented out the Light DOM test as there's a bug with …
> DS-198 Tabs renderer conversion

- packages/components/bolt-menu/package.json
- packages/components/bolt-menu/src/_menu-item.js
- packages/components/bolt-menu/src/_menu-item.scss
- packages/components/bolt-menu/src/menu.js
- packages/components/bolt-menu/src/menu.scss
https://pegadigitalit.atlassian.net/browse/DS-231
Update Menu 'core' dependency to `@bolt/core-v3.x`. Update Menu JS to use the latest conventions.
- Update to `@bolt/core-v3.x`. All components should use this now. It was an oversight that it used the old `@bolt/core` when first created.
- Switch from `wc-context` to `wc-context/lit-element`.
- Remove `ssrHydrationPrep()`. This is now in the base class.
> Note: this is the last known use of `@bolt/core` in the repo. Upgrading this allows us to consolidate 'core' in `v3.0`.
- Review code changes.
- Test Menu demos on feature branch for regressions.
> DS-231 Update Menu 'core' dependency, JS conventions

- packages/components/bolt-tooltip/src/tooltip.js
https://pegadigitalit.atlassian.net/browse/DS-190
Fix tooltip placement bug when tooltip is hidden on load.
When a tooltip trigger is hidden on load (e.g. in an inactive tab panel), the tooltip placement is not properly set. Then, when you hover over the tooltip, nothing appears because it's positioned offscreen.
This PR adds a check before showing the tooltip to see if the position needs to be updated.
- Reproduce the bug by going to this page: https://boltdesignsystem.com/pattern-lab/?p=visual-styles-typography-tokens
- Open the "Font-size" tab, then hover over a px value in the last column. The tooltip does not appear.
- Resize the browser window and then try again - it should work this time.
- Run the feature branch and repeat the steps above.
- Very the tooltip works the first time, …
> DS-190 Fix tooltip placement bug

- docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/02-molecules/cards/_horizontal-card.twig
- docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/03-organisms/collections/search/_search-results--results-list.twig
- docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/index.scss
https://pegadigitalit.atlassian.net/browse/ACD-286
Add custom Academy component to fix bug where popover gets clipped by `<div>` with overflow "hidden".
Academy's horizontal card used the grid with `--bordered` class, negative margin, and overflow "hidden" to create a layout with border-separated items. Because this layout requires overflow hidden, any popover inside the content gets clipped. This PR introduces a custom component that uses very simple css grid styles to accomplish the border-separated layout without requiring overflow "hidden".
It also adds a demo of the popover menu in search results: `/pattern-lab/patterns/50-pages-60-academy-05-pages-search-search-results-acd-search-results-page/50-pages-60-academy-05-pages-search-search-results-acd-search-results-page.html`
> Note: …
> ACD-286 Academy popover overflow bug

- packages/components/bolt-blockquote/src/blockquote.js
- packages/components/bolt-blockquote/src/blockquote.scss
- packages/components/bolt-blockquote/src/blockquote.twig
https://pegadigitalit.atlassian.net/browse/DS-178
Fixes quotes in Safari which were previously not showing.
Safari doesn't support the CSS selector we were using to add quotation marks. That selector is `::slotted()` combined with a pseudo-selector, example: `::slotted(p):before { }`. I couldn't find any Safari docs specifically saying this isn't supported, but it's what I found after testing. It supports chaining `::slotted()` with other selectors, just no pseudo-selectors.
Given that limitation of Safari, I had to refactor the CSS to use attribute selectors not classes in order to target the blockquote `<p>` tags. In the end this actually reduced a lot of complexity in the CSS _and_ in the JS.
I switch to use `first-of-type` rather than `.is-first-child` classes and eliminated some …
> DS-178 Fix Blockquote quotes in Safari

- docs-site/composer.json
- docs-site/composer.lock
n/a
Update `cweagans/composer-patches` to fix Travis build failure.
Travis is now using Composer 2, which is incompatible with the current version of `cweagans/composer-patches`. See failing build: https://travis-ci.com/github/boltdesignsystem/bolt/jobs/407817182#L461
Updating this package to `1.7.0` fixes the issue.
Build is passing: https://travis-ci.com/github/boltdesignsystem/bolt/builds/192947578
> Fix composer version conflict on Travis

- packages/components/bolt-video/src/_videojs-enhancements.scss
https://pegadigitalit.atlassian.net/browse/WWW-277
Allows closed caption button to display, but only on videos that have stored captions.
From all my testing, the CC button only shows if there is actually a stored caption available for the video.  I'm not sure why it was ever a problem before-- fingers crossed that it was just a bug on the bc side that's since been fixed.
Confirm that all videos that don't have stored closed caption files (as of now, all of them) don't show the CC button.
> WWW-277: Allow video captions button to show

- packages/analytics/autolink/__tests__/autolink.test.js
- packages/analytics/autolink/__tests__/fixtures/test-analytics-config.data.js
n/a
Fix failing autolink test.
Autolink tests are failing on all branches due to a new Brightcove redirect.
In these tests, we click on a link, go to a new URL, and check if the URL includes the expected query param. Where we use `brightcove.com`, that query param is stripped out when `brightcove.com` redirects to `brightcove.com/en`. To fix, I changed the test URL to `boltdesignsystem.com`.
> Fix failing autolink test

- packages/components/bolt-tooltip/__tests__/__snapshots__/tooltip.js.snap
- packages/components/bolt-tooltip/src/tooltip.js
- packages/components/bolt-tooltip/src/tooltip.scss
- packages/components/bolt-tooltip/src/tooltip.twig
https://pegadigitalit.atlassian.net/browse/DS-128
Updated the tooltip to meet accessibility requirements
* Added a 'Esc' key event to close the tooltip
* Added functionality to highlight the tooltip trigger
* Disable JS and check to see if the border is present
* Tab to a tooltip trigger and press "Esc" to close the flyout
> DS-128: Tooltip | a11y | Enable ESC key to close and style no-js version

- docs-site/src/components/pattern-lab-utils/docs.twig
- docs-site/src/pages/pattern-lab/_patterns/40-components/action-blocks/15-action-blocks-borderless-variations.twig
- packages/components/bolt-action-blocks/src/_action-blocks-settings-and-tools.scss
- packages/components/bolt-action-blocks/src/action-block.scss
- packages/components/bolt-action-blocks/src/action-blocks.scss
https://pegadigitalit.atlassian.net/browse/DS-250
Fixes an issue where the action block text is underlined and a bottom border is showing up at random breakpoints.
1. Set text-decoration to none in CSS.
2. 1.5px is used to fix the subpixel border issue.
3. Fixed a doc where `url` was not passed to an action block.
4. Fixed a small issue with the PL doc frame template.
Run the branch locally and view the action blocks docs. Make sure the text is not underlined and a bottom border on the whole container doesn't show up at random breakpoints.
> DS-250 remove text underline and fix subpixel border issue

- docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/02-molecules/cards/_vertical-card.twig
- docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/03-organisms/collections/dashboard/_dashboard-band--my-missions.twig
https://pegadigitalit.atlassian.net/browse/ACD-365
Update Academy dashboard template to include Popover, remove overflow "hidden" utility class.
This just keeps our PL template in sync with changes to production, so we can continue to use PL to troubleshoot front-end issues on Academy. Only affects Academy templates, which are not used directly anywhere outside of Bolt.
Review code changes and deployed [Dashboard page](https://feature-acd-365-dashboard-popover.boltdesignsystem.com/pattern-lab/?p=pages-acd-dashboard). Dashboard should now have a popover on the first and fourth cards in the My Missions carousel.
> ACD-365: Update Academy dashboard

- packages/components/bolt-accordion/src/accordion.js
- packages/components/bolt-band/src/band.js
https://pegadigitalit.atlassian.net/browse/DS-253
Fix a bug where accordion content is invisible on initial load, occurs intermittently when you put an accordion inside and band and use deep linking.
When you put an Accordion in a Band, sometimes Accordion renders first, sometimes Band, because our components load asynchronously. When the Accordion loads first _and_ you are deep linking to an accordion section, Accordion starts to open the deep linked section and the CSS animation gets interrupted by the parent Band rendering. Handorgel, the accordion library we use, waits for the `transitionend` event to make the content visible. When Band interrupts the animation, this event never fires and we get this bug.
The fix is really just a workaround. It waits for the closest band to finish …
> DS-253 Fix invisible Accordion content

- packages/components/bolt-stack/src/stack.scss
- packages/components/bolt-stack/src/stack.twig
- packages/components/bolt-stack/stack.schema.js
https://pegadigitalit.atlassian.net/browse/DS-258
Cleaned up code in the Stack component.
1. Fixed typos in schema and remove the no-shadow props.
2. Removed unrelated code in twig.
3. Convert to using repeat-rule mixin for styling custom elements.
There is no existing visual bugs, just bad code. Run the branch locally and check the Stack docs. Make sure it's still working the same way.
> DS-258 fix typos and bad code in Stack component

- packages/components/bolt-hero/hero.schema.js
- packages/components/bolt-hero/hero.twig
https://pegadigitalit.atlassian.net/browse/DS-264
Add srcset support to an image in hero component
This PR just allows passing one additional attribute to the hero image.  We don't want to handle similar problems in the same piecemeal way; this is a quick way to unblock some performance work, and the whole pattern with the hero component is not necessarily one we'll follow in the future.
There are no changes to pattern lab.  [This line in image.twig ](https://github.com/boltdesignsystem/bolt/blob/master/packages/components/bolt-image/src/image.twig#L20-L22) automatically fills srcset in any images within pattern lab, so you'd need to comment it out in order to test that a string value can be passed to image_srcset in the hero component, like this:
```
{% include …
```
> DS-264: Add srcset support for hero component

- packages/components/bolt-video/src/_videojs-enhancements.scss
https://pegadigitalit.atlassian.net/browse/WWW-384
Create Edge ~v.42 specific CSS to handle the video player "play" icon
Make play icon responsive
View "/pattern-lab/?p=components-video" in Edge v.18 Browserstack (this browser also doesn't support clip-path)
Check it on different screen sizes.
> WWW-384: Fix responsiveness on Edge 42/44 

- packages/components/bolt-video/src/_videojs-enhancements.scss
https://pegadigitalit.atlassian.net/browse/WWW-384
Create Edge ~v.42 specific CSS to handle the video player "play" icon
The previous fix was based on media queries and it works when we have a video with the same dimensions as the page but if we have video as a part of the page fix was not working correctly. This will work in that case now.
View "/pattern-lab/?p=components-video" and "/pattern-lab/?p=components-card-replacement-with-video" in Edge v.18 Browserstack (this browser also doesn't support clip-path)
Check it on different screen sizes.
> Fix play icon

- .travis.yml
- auto-release.js
https://pegadigitalit.atlassian.net/browse/DS-211
Disables canary releases every time a PR (or any branch) is merged to master.
Since this only affects Travis, I don't know of a way to test other than to merge this to master and then confirm that future merges to master don't create a canary release as part of their build.  A good look at the code is probably the best alternative before merging this.
> DS-211: Disable canary releases when merging to master

- docs-site/src/pages/pattern-lab/_patterns/40-components/teaser/10-teaser-variation.twig
- docs-site/src/pages/pattern-lab/_patterns/40-components/teaser/15-teaser-linked.twig
- docs-site/src/pages/pattern-lab/_patterns/40-components/teaser/15-teaser-with headline-link.twig
- packages/components/bolt-headline/headline.schema.js
- packages/components/bolt-headline/src/_typography.twig
[https://pegadigitalit.atlassian.net/browse/DS-245](https://pegadigitalit.atlassian.net/browse/DS-245)
Allow links in the headline of bolt-teaser to use the target attribute.
Allowed a new target attribute on bolt-teaser be passed into bolt-headline, and ultimately set a target on bolt-link to allow for opening links in a new tab.
There's a demo in bolt-teaser.
Add target option to bolt-teaser.
> DS-245: Links to external sites in Teaser headlines not opening in new tab

- packages/components/bolt-copy-to-clipboard/src/copy-to-clipboard.standalone.js
[https://pegadigitalit.atlassian.net/browse/DS-268](https://pegadigitalit.atlassian.net/browse/DS-268)
Update copy-to-clipboard to the latest renderer standards. 
Update copy-to-clipboard to the latest renderer standards. 
To test the conversion:
- Test copy-to-clipboard demos
> DS-268: Update copy-to-clipboard WC to latest renderer

- docs-site/.patches/faster-compile-times--add-twig-cache-support--file-system-loader.patch
- docs-site/.patches/faster-compile-times--add-twig-cache-support--pattern-loader.patch
- docs-site/.patches/faster-compile-times--add-twig-cache-support--string-loader.patch
- docs-site/config/config.yml
- docs-site/src/pages/pattern-lab/_patterns/40-components/headline/25-headline-icon-variations.twig
- docs-site/src/pages/pattern-lab/_patterns/40-components/icon/10-icon-size-variation.twig
- docs-site/src/pages/pattern-lab/_patterns/50-pages/35-d8-events/05-event-detail.twig
- docs-site/src/pages/pattern-lab/_patterns/50-pages/35-d8-events/10-event-form-example.twig
- docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/02-molecules/cards/_vertical-card.twig
- packages/components/bolt-background/background.schema.js
- packages/components/bolt-card-replacement/src/card-replacement-actions/_card-replacement-action.twig
- packages/components/bolt-card-replacement/src/card-replacement-body/_card-replacement-body.twig
- packages/components/bolt-chip-list/__tests__/__snapshots__/chip-list.js.snap
- packages/components/bolt-chip-list/src/_chip-list-macros.twig
- packages/components/bolt-chip-list/src/chip-list.twig
- packages/components/bolt-headline/src/_typography.twig
- packages/components/bolt-icon/icon.schema.json
- packages/components/bolt-share/src/share.twig
- packages/elements/bolt-button/button.schema.js
- packages/elements/bolt-text-link/text-link.schema.js
https://pegadigitalit.atlassian.net/browse/DS-42
Restores both schema validation and twig dump function in Pattern Lab.  Also fixes numerous schema violations.
#1802 disabled twig debugging in the name of performance.  That broke several useful things, including schema validation and the ability to use the twig [dump](https://twig.symfony.com/doc/2.x/functions/dump.html) function.
This PR does the following:
1. Updates the pattern lab patches to allow twig debugging to be enabled
2. Enables twig debugging by default in docs-site/config/config.yml
3. Fixes all the schema errors that have been added in while schema validation was broken
The only downside is that Item 2 decreases performance somewhat.  I found my re-compile times to be about 10 seconds before these changes and about 15 …
> DS-42 restore schema validation twig dump

- packages/components/bolt-video/src/video.scss
https://pegadigitalit.atlassian.net/browse/WWW-421
Fixes a bug where time remaining shows on videos that are placed within tabs or accordion
This _should_ be testable in Bolt on the [tabs content](https://boltdesignsystem.com/pattern-lab/?p=components-tabs-content) and [accordion content](https://boltdesignsystem.com/pattern-lab/?p=components-accordion-content-variations) pages, but it's not.  For some reason, videos in those scenarios get the `vjs-layout-medium` class instead of the `vjs-layout-tiny` class that happens on pega.com production, and for which this CSS was originally written.  Maybe there's a race condition of some sort?  @colbytcook and I are stumped 🤷 .
Edit: it appears that videos inconsistently get either `vjs-layout-medium` or `vjs-layout-tiny`.  It's likely some race …
> WWW-421: Do not show remaining video time in accordion or tabs

- packages/components/bolt-tooltip/__tests__/__snapshots__/tooltip.js.snap
- packages/components/bolt-tooltip/src/tooltip.twig
https://pegadigitalit.atlassian.net/browse/DS-277
Fixes a bug where any inline tooltip does not render correctly inside a paragraph of text when JS is turned off.
Replaced all `div`s in twig template with `span`s, because `div` can not go inside `p` elements.
Run the branch locally and check tooltip docs with JS turned off.
> DS-277 Replace divs with spans in tooltip

- docs-site/src/pages/pattern-lab/_patterns/20-elements/button/20-button-with-icon.twig
- docs-site/src/pages/pattern-lab/_patterns/20-elements/text-link/20-text-link-with-icon.twig
Fixes two typos in text link and button element docs.
The html code snippet was written with the wrong class name, change from `before` to `after` properly in the docs involving text and icons.
Run the branch locally and proofread the Text Link with Icon and Button with Icon docs.
> Docs: fix element docs typos

- packages/components/bolt-background/src/background.scss
https://pegadigitalit.atlassian.net/browse/DS-275
Fixes a bug where the background component does not fill up its parent container.
Moved the absolute position CSS rules to the outer most container which is `<bolt-background>`.
Run the branch locally and check the background docs.
Create some dummy code to test the background component inside a CSS grid:
```
.container {
display: grid;
grid-template-columns: repeat(3, 1fr);
position: relative;
width: 500px;
height: 500px;
}
<div class="container">
<p>Some text here.</p>
</div>
```
> DS-275 Make the background component absolute positioned

- packages/core-v3.x/styles/02-tools/tools-full-bleed/_tools-full-bleed.scss
https://pegadigitalit.atlassian.net/browse/DS-276
Fixes a bug where the full bleed mixin is creating negative margins top and bottom, causing a visual bug between bands.
Removed the negative margin top and bottom. Checked in Firefox and everything is working as expected (because there was an old comment about Firefox).
Run the branch locally and check the Pages section.
Create a dummy page with 2 bands:
1. Top band: full bleed, dark theme
2. Bottom band: full bleed, light theme, and spacing none. Nest another band inside, set it to not full bleed and light theme
Check the line where the top and bottom bands meet, the line should be perfectly straight.
> DS-276 Remove -0.5px top/bottom margins from full bleed mixin

- packages/experimental/micro-journeys/src/interactive-pathway.js
WWW-446 - Unable to tap/select first step in microjourneys experiences on mobile
Unable to tap/select first step in microjourneys experiences on mobile
(Explain the changes in enough detail fo reviewers to understand.  Raise any questions for reviewers to consider.)
* Open any microjourney experience on mobile.
* Switch to any step (but not first)
* Try to switch back to first step
> Unable to tap/select first step in microjourneys experiences on mobile

- docs-site/src/components/pattern-lab-utils/pattern-doc-page.twig
- docs-site/src/templates/_page-header.twig
- docs-site/src/templates/base-template.twig
- docs-site/src/templates/default-redesign.twig
- docs-site/src/templates/default.twig
- docs-site/src/templates/homepage.twig
- docs-site/src/templates/sassdoc.twig
Updates doc site navigation to have "Elements" and update display logic on doc template.
1. Elements link is added to main navigation on the homepage.
2. Doc template now has logic to display whether Twig or HTML code snippet based on which one is available.
Run the branch locally and check the homepage navigation and docs using the doc template (everything under Elements).
> [Docs] add elements to nav and add logic to doc template

- packages/global/styles/00-vars/_vars-page-width-and-spacing.scss
- packages/global/styles/index.scss
https://pegadigitalit.atlassian.net/browse/DS-278
Adds page padding CSS vars to global styles.
1. Responsive CSS vars are created to handle page padding and page max-width.
2. The method of using a wrapper element is no longer needed. Instead, setting padding using these vars will achieve the same effects.
Run the branch locally. Create a dummy element and test out the CSS vars, make sure it works as expected.
```css
.test {
@include bolt-full-bleed;
padding-right: var(--bolt-page-padding-x);
padding-left: var(--bolt-page-padding-x);
background: red;
}
```
> DS-278 add page padding css vars

- packages/components/bolt-video/brightcove/_video.scss
Fixed a CSS error in the new Brightcove Player
Fixed a CSS error in the Brightcove CSS in order to get the icons to display correctly on small screens
> Fixed a Brightcove CSS error for the new player

- packages/components/bolt-tabs/src/tabs.scss
- packages/core-v3.x/styles/01-settings/settings-global/_settings-global.scss
Fixes a color regression on tabs' show more button's active state caused by the color variable conversion.
Removed a line of CSS that caused the double background color.
Run the branch locally and check Tabs doc page. Make the browser narrow and click on the more button of truncated tabs. Make sure it's background color is the same as the hover state's background color.
> Fix: tabs show more button active color

- .autorc
- .travis.yml
- auto-release.js
https://pegadigitalit.atlassian.net/browse/DS-238
Removes hard-coded `release/2.x` in release scripts, allows the release script to run from any release/* branch.
I don't know of a good way to test this outside of Travis.  A good, careful code review might be the best way to check, short of pushing to Travis and seeing if anything breaks while doing a release.
> DS-238: Add support for 3.x releases

- docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/03-organisms/collections/dashboard/_dashboard-band--my-missions.twig
- docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/03-organisms/collections/search/_search-results--results-list.twig
- packages/components/bolt-icon/icon.schema.json
https://pegadigitalit.atlassian.net/browse/DS-295
Removes `xsmall` size from Icon component that was added by mistake.
1. Removed `xsmall` from icon schema.
2. Removed `size` prop value from 2 Academy pages where it's not needed at all.
Run the branch locally and check the the 2 Academy pages: Dashboard and Dashboard (My Missions). Make sure the chevron down icon for the decision hub version dropdown is matching the text's font size.
> DS-295 remove xsmall icon size

- docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/index.scss
- packages/global/styles/00-vars/_vars-mode.scss
N/A
Fixed the background color of xxdark theme and converted Academy CSS to use CSS vars.
1. Added backward compatibility for `.t-bolt-xxdark`.
2. Converted Academy CSS to use CSS vars.
Run the branch locally and check the Academy Mission Landing pages, make sure all text is rendering the proper colors in xxdark theme.
> Fix: academy colors and xxdark theme

- packages/global/styles/00-vars/_vars-mode.scss
N/A
Fixes a bug where the secondary color variable is not rendering white in all themes.
Run the branch locally and check secondary buttons on Button docs or other demo pages. Make sure the background color of the secondary buttons is white.
> Fix: secondary color variable

- packages/base-element/src/Slotify.js
https://pegadigitalit.atlassian.net/browse/DS-300
If a component is initially empty (i.e. no text or elements inside), content added later never appears. This PR updates `Slotify` to handle this case, which happens on Academy in the `pega_modal` module.
`Slotify` does a one-time setup where it loops through the child nodes of a component and assigns them all to various slots. If there are no child nodes, no slots are created and when content is later added there is no slot for the content to appear in. The fix ensures that at least a default slot is always added to the `slotMap` so that when content is added it will display if it's supposed to (i.e. only if the component template says to render the default slot)
On Academy, the `pega_modal` module appends an empty `<bolt-modal>` to the …
> DS-300 Fix Slotify empty component bug

- packages/build-tools/utils/manifest.get-pkg-info.js
n/a
This adds `@bolt/build-tools` to a whitelist so that we don't see the dependency warning every time we start up Bolt.
Warning is thrown because Micro Journeys adds `@bolt/build-tools` as a dependency. We should try [removing that dependency](https://github.com/boltdesignsystem/bolt/pull/1993) but that requires time to test. For now this just adds `@bolt/build-tools` to a whitelist with other core components, like `@bolt/core-v3.x`.
Run `yarn start`. You should see no warning and everything else continues to work as expected.
> Whitelist "build-tools" to prevent warning on `yarn start`

- docs-site/src/pages/pattern-lab/_patterns/999-tests/popover/00-popover-auto-open.twig
- packages/components/bolt-popover/__tests__/popover.e2e.js
- packages/components/bolt-popover/src/popover.scss
https://pegadigitalit.atlassian.net/browse/DS-305
Fix popover content background color.
> Note: if this is the only item to hotfix we will merge directly into `release/2.x`. If not, we'll create a separate branch to combine our hotfixes.
When popover has a parent with a theme class, such as `t-bolt-xxdark`, that theme class overrides the "theme" set on the component itself. If you set the popover to theme "light" (`<bolt-popover theme="light">`) it will still be dark. This is because the right CSS vars aren't being included in the component's constructed stylesheet.
We missed this bug because our Popover theme demo used the `no-shadow` prop (for Nightwatch testing purposes), and so shadow dom encapsulation didn't factor in.
This PR fixes the bug and moves the `no-shadow` demo to the Tests …
> DS-305 Fix popover background

- packages/components/bolt-button/src/button.scss
Fixes a bug when `bolt-button[type]` is rendering browser default button styles.
1. Changed the CSS to specifically target `bolt-button[type]`.
2. We need to avoid using existing HTML attribute name as prop name. This is a prime example of unexpected behaviors.
Run the branch locally and find a bolt-button, add `type="submit"` and see if it produces browser default button styles in Safari. Also check the typeahead docs, make sure the search icon button does not look like a browser default button.
> Fix: remove bolt-button[type] browser defaults

- packages/components/bolt-page-header/src/_page-header-desktop.scss
https://pegadigitalit.atlassian.net/browse/DS-306
Fixes a bug where the page header's primary nav full width nested item is not taking up full width.
Rewrote some CSS for a flex method that can easily allow an item to be full width.
Run the branch locally and view the Academy demo under the Page Header component docs. On desktop, hover over the first item in the primary nav, check the dropdown activated by hovering, make sure the "View all products" link is taking up full width.
> DS-306 fix desktop primary nav full width item

- packages/components/bolt-button/src/button.js
https://pegadigitalit.atlassian.net/browse/DS-311
Remove `style` prop from Button web component. It is Twig-only.
If `style` gets set as a prop, it overwrites the native `style` tag and can throw JS errors.
> Hotfix: Filter out `style` prop from button WC

- packages/base-element/index.js
- packages/base-lazy-queue/index.mjs
- packages/base-lazy-queue/package.json
- packages/build-tools/cli.js
- packages/build-tools/create-webpack-config.js
https://pegadigitalit.atlassian.net/browse/DS-238
Update Bolt build tools and dependencies to work with `pega_bolt_theme` build.
- Polyfills are not getting bundled in `pega_bolt_theme`, and we couldn't easily figure out why. So, simply include the polyfills where they are needed (lazyqueue and element). Remove polyfills from the Bolt webpack config.
- Update function that gets `boltrc.js` file to be asynchronous as `pega_bolt_theme`'s `boltrc.js` runs several tasks and returns asynchronously.
- Skip brightcove entry in 'drupal' environment. Otherwise throws error `Can't resolve '@bolt/components-video/brightcove.scss' in '/var/www/docroot/themes/custom/pega_bolt_theme'`. This file is only needed in Bolt mono repo so skip in Drupal.
> Note: before we officially release any of this we need …
> Hotfix/DS-238 Build updates

- packages/components/bolt-action-blocks/__tests__/__snapshots__/action-blocks.js.snap
- packages/components/bolt-action-blocks/action-blocks.schema.js
- packages/components/bolt-action-blocks/src/action-blocks.twig
[https://pegadigitalit.atlassian.net/browse/DS-294](https://pegadigitalit.atlassian.net/browse/DS-294)
update action-block twig conventions
action-block still used the old validation so this updates action-block validation to use `{% set this = init(schema) %}`. also used this time to remove `base_class` variable.
- test unexpected props and classes.
- visual test demos against master.
Deprecated Action Blocks `children` prop. Use `content` instead.
> DS-294: update action-block twig conventions

- packages/build-tools/tasks/icon-tasks.js
- packages/components/bolt-icon/icon.schema.json
https://pegadigitalit.atlassian.net/browse/DS-315
Fix Icon schema formatting conflicts.
When you run `yarn start` the Icon schema file is automatically updated with icon svgs found in the filesystem. The schema file was previously formatted with node's `writeJson()` formatting options. These are a bit different than our Prettier settings. This PR updates the icon task to use Prettier to format the schema.
- Checkout master and run `yarn start`. You should see a modified Icon schema file.
- Checkout this feature branch and repeat. There shouldn't be any modified file afterwards.
> DS-315 Fix icon schema formatting

- packages/components/bolt-background/src/background-item.twig
- packages/components/bolt-background/src/background-overlay.twig
- packages/components/bolt-background/src/background-shapes-wrapper.twig
- packages/components/bolt-background/src/background.scss
- packages/components/bolt-background/src/background.twig
[https://pegadigitalit.atlassian.net/browse/DS-297](https://pegadigitalit.atlassian.net/browse/DS-297)
update background twig conventions
background still used the old validation so this updates background validation to use `{% set this = init(schema) %}`. also used this time to remove `base_class` variable and update as many other twig standards as I could manage.
- test unexpected props and classes.
- visually test demos against master.
> DS-297 Update background twig to latest conventions

- packages/components/bolt-blockquote/__tests__/__snapshots__/blockquote.js.snap
- packages/components/bolt-device-viewer/__tests__/__snapshots__/device-viewer.js.snap
- packages/components/bolt-figure/__tests__/__snapshots__/figure.js.snap
- packages/components/bolt-image/__tests__/__snapshots__/image.js.snap
- packages/components/bolt-image/__tests__/image.js
- packages/components/bolt-image/src/image.js
- packages/components/bolt-image/src/image.twig
- packages/components/bolt-logo/__tests__/__snapshots__/logo.js.snap
[https://pegadigitalit.atlassian.net/browse/DS-316](https://pegadigitalit.atlassian.net/browse/DS-316)
make alt prop persistent
we want an alt prop show even if its blank, edited the conditionals to make alt prop persistent
remove the alt prop from a twig include in the demos and verify that there is still an alt listed in the element props.
> DS-316: make alt prop persistent

- packages/base-element/src/Slotify.js
- packages/components/bolt-accordion/__tests__/__snapshots__/accordion.js.snap
- packages/components/bolt-button/__tests__/__snapshots__/button.js.snap
- packages/components/bolt-modal/__tests__/__snapshots__/modal.js.snap
https://pegadigitalit.atlassian.net/browse/DS-321
If a component initially contains only whitespace, content added later never appears. This PR updates Slotify to handle this case, which happens on [Collaboration center](https://pegadigitalit.atlassian.net/browse/CC-416).
Add some conditional logic to handle the case where there _are_ child nodes, but they contain only whitespace. Ensures a `<slot>` is added when that is true, as is the case when you use the Modal Twig template and pass `content: ''` - Twig adds line breaks.
- To reproduce the bug, go to [modal demo on `2.30.2` site](https://v2-30-2.boltdesignsystem.com/pattern-lab/patterns/40-components-modal-05-modal/40-components-modal-05-modal.html) or do the same on `master` locally.
- Via Chrome dev tools delete the `<bolt-modal>` …
> DS-321 Update Slotify to handle only whitespace as content

- packages/build-tools/utils/manifest.get-pkg-info.js
Revert changes made in #2068 that may be causing `regeneratorRuntime is not defined` error downstream.
> Hotfix/Revert adding build-tools to missing pkgs whitelist

- packages/base-element/src/lib/decorators/json-schema-props.js
- packages/components/bolt-button/src/button.js
- packages/components/bolt-popover/src/popover.scss
https://pegadigitalit.atlassian.net/browse/DS-291
Fix Sass loader error happening only in Pega Bolt builds.
The CSS `min()` function is not supported by LibSass, and we're tied to LibSass for now because of Pattern Lab. In order to use `min()` we need to workaround this limitation of LibSass.
We previously used the [unquote hack](https://github.com/boltdesignsystem/bolt/pull/2065/files#diff-4e38e563a47ffbc725eb1e53049eff038ead79a819d61c678b4dd3ca20b323afR157), but that hack only works for a single build. In sites that consume Bolt, compiled Bolt CSS is re-compiled using the same Sass loader and we see the error on the second build.
I'm replacing the "unquote" hack with the ["capitalize" hack](https://css-tricks.com/when-sass-and-new-css-features-collide/#the-solution). SASS is case …
> Hotfix/DS-291 SASS loader min() error (v2.31.2)

- packages/base-element/src/lib/decorators/json-schema-props.js
- packages/components/bolt-button/src/button.js
https://pegadigitalit.atlassian.net/browse/WWW-446
Fix JS error that breaks Microjourneys editor.
In a [previous PR](https://github.com/boltdesignsystem/bolt/pull/2081) I removed the `style` property from the Button component schema via the `delete` operator. Using `delete` appears to delete it everywhere, even in the Editor, where the schema is imported separately. The editor needs the `style` prop to exist in order to [remap it](https://github.com/boltdesignsystem/bolt/blob/master/packages/experimental/editor/src/setup-bolt.js#L364) onto the `color` prop. When it's missing, it throws an error and breaks the editor.
To fix this bug and [the original](https://pegadigitalit.atlassian.net/browse/DS-311), I'm keeping `style` in the schema, but filtering it out at the renderer level, as this …
> Hotfix/WWW-546 Fix JS error in MJ editor (v2.30.3)

- packages/components/bolt-carousel/carousel.schema.js
- packages/components/bolt-carousel/src/carousel.twig
[https://pegadigitalit.atlassian.net/browse/DS-323](https://pegadigitalit.atlassian.net/browse/DS-323)
Allow users to have 4 slides per view.
Change schema to allow 4 slides per view and a max sliders per view of 4. Deprecate auto from slides per view to avoid further confusion.
Check out carousel demos
`auto` has been deprecated from the carousel `slides_per_group` prop.  Use an integer (1, 2, 3, 4) for `slides_per_group` instead.  Note that the number of items shown will be always automatically reduced as necessary at smaller breakpoints.
> DS-323: deprecate auto slides per view. set max slides to 4.

- packages/components/bolt-trigger/__tests__/__snapshots__/trigger.js.snap
- packages/components/bolt-trigger/__tests__/trigger.js
- packages/twig-integration/twig-extensions-shared/src/Utils.php
https://pegadigitalit.atlassian.net/browse/DS-303
Fix an `init()` bug where `this.props` and `this.data` values do not match when a prop like `target` is passed via `attributes` object. Also, omit deprecated props from the object returned by `init()`.
**Include matching attributes in `this.data`**
On the Button component, when you pass `attributes: { target: "_blank" }` (something I assume we support because there is a Jest test for it), that `target` value is added to `<bolt-button>`, but the default value, `_self`, is added to the inner `<a>`. This is because attributes that match a component prop are added to `this.props` but not `this.data`, and we use `this.data` to determine what value the `<a>` gets. This PR updates `init()` to include matching attributes in `this.data`.
**Omit …
> DS-303 Fix init() bugs

- docs-site/src/pages/pattern-lab/_patterns/40-components/modal/30-modal-trigger-variations.twig
N/A
Replaces "link is not supported as a modal trigger" with a demo of a link as a modal trigger
> Add link trigger to modal docs

- packages/build-tools/package.json
- packages/configs/babel-preset-bolt/index.js
- packages/configs/babel-preset-bolt/package.json
- packages/testing/testing-jest/package.json
- packages/website-ui/uikit-prerender-spa-plugin/package.json
- packages/website-ui/uikit-prerenderer/package.json
- packages/website-ui/uikit-workshop/package.json
- yarn.lock
n/a
Upgrade `@babel/core`, `@babel/preset-env` to fix "No 'exports' main defined" error.
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in node_modules/@babel/helper-compilation-targets/package.json
```
From [Github issue](https://github.com/babel/babel/issues/11216), the solution is to `update all @babel deps to v7.8.7 or above`.
I found it was only necessary to update `@babel/core` and `@babel/preset-env`. Both of which have a dependency on `@babel/helper-compilation-targets`, older versions of which seem to cause the bug.
I'm targeting Node v12 for this fix because that version has [long-term support](https://nodejs.org/en/about/releases/) and it is the version currently used by many of us and Pega properties. Later this year we might consider upgrading to Node …
> Upgrade @babel/core, @babel/preset-env

- docs-site/src/pages/pattern-lab/_patterns/40-components/modal/20-modal-theme-variations.twig
- packages/components/bolt-card-replacement/src/card-replacement/card-replacement.scss
- packages/components/bolt-modal/src/modal.scss
- packages/global/styles/00-vars/_vars-mode.scss
https://pegadigitalit.atlassian.net/browse/DS-393
Fixes an issue where theme colors are not displaying correctly in modals.
1. Added the new mode css vars to modal.scss so they are loaded inside the shadow dom as well.
2. Updated the same method in card.scss.
Run the branch locally and view the card and modal theme docs. Make sure colors are displaying as expected.
> DS-393 fix theme colors for modals

- packages/components/bolt-button/__tests__/__snapshots__/button.js.snap
- packages/components/bolt-button/__tests__/button.js
- packages/components/bolt-button/src/button.twig
https://pegadigitalit.atlassian.net/browse/DS-388
Allow `download` attribute to be added to the inner `<a>` of `<bolt-button>` and download a resource without opening in a new tab.
Initially I thought the solution would be to allow arbitrary attributes to be added to to the inner element, but this is too risky as many attributes are already used on `<bolt-button>` in the wild, and suddenly applying them all to the inner element is a potential breaking change.  Instead, simply check for the `download` attribute and add it to the `<a>` like we do for `target`.
Note: only applies if Button has `url`.
- Run locally and paste this example into PL:
```
{% include "@bolt-components-button/button.twig" with {
text: "This is a button",
url: …
```
> DS-388 Allow `download` attribute to be added to inner `<a>`

- packages/build-tools/plugins/sass-export-data/index.js
- packages/build-tools/plugins/sass-export-data/package.json
- packages/build-tools/utils/package.json
https://pegadigitalit.atlassian.net/browse/DS-399
Fix security vulnerabilities with `js-yaml` and `node-notfier`.
Replace `@theme-tools` with `merge`, which is the library `@theme-tools` uses under the hood, minus the security vulnerabilities. Upgrade `node-notifier`, a library used for outputing messages to the console. Seems pretty straight forward, no major API changes.
- Build is passing
- Runs locally
> DS-399 Replace theme-tools, upgrade notifier

- docs-site/src/pages/pattern-lab/_patterns/40-components/page-header/-example-pegaworld.twig
- docs-site/src/pages/pattern-lab/_patterns/40-components/page-header/05-page-header.twig
- packages/components/bolt-page-header/page-header.schema.js
- packages/components/bolt-page-header/src/_page-header-desktop.scss
- packages/components/bolt-page-header/src/_page-header-mobile.scss
- packages/components/bolt-page-header/src/_page-header-settings-and-tools.scss
- packages/components/bolt-page-header/src/page-header.scss
- packages/components/bolt-page-header/src/page-header.twig
https://pegadigitalit.atlassian.net/browse/WWW-467
Adds an example of PegaWorld navigation under Page Header component docs.
1. `theme` prop is added to Page Header to handle various color themes.
2. `subheadline` prop is added to Page Header to handle additional text next to the logo.
3. When there is a subheadline, desktop main nav items are pushed to the right side as seen in the PegaWorld navigation.
4. Updated CSS to make sure all color themes are working correctly.
Run the branch locally and check the PegaWorld example under Page Header.
> WWW-467 Create PegaWorld navigation with Page Header component

- packages/build-tools/package.json
- packages/configs/stylelint-config/ideal.js
- packages/configs/stylelint-config/index.js
- packages/configs/stylelint-config/package.json
- packages/core-v3.x/package.json
- yarn.lock
https://pegadigitalit.atlassian.net/browse/DS-399
Upgrade `yaml-loader`, remove `stylelint-selector-bem-pattern`.
This is the last of this round of dependency-cleanup. It upgrades `yaml-loader` and removes `stylelint-selector-bem-pattern` to fix security vulnerabilities. The latter stylint package does not appear to do anything (cc: @mikemai2awesome).
The remaining security vulnerabilities are so ingrained in Pattern Lab and Jest that they cannot be addressed unless we upgrade both of them. As far as I can tell, the vulnerabilities are not in the code we ship, but in the libraries we use in the monorepo. So, they could only be exploited by a contributor. @adamszalapski does that sound right?
- Review code
- Tests pass
> DS-399 Dependency cleanup

- packages/build-tools/package.json
- packages/configs/babel-preset-bolt/package.json
- packages/testing/testing-jest/package.json
- yarn.lock
https://pegadigitalit.atlassian.net/browse/DS-405
Upgrade Babel to latest minor release to fix Edge 18 JS error.
After the `@babel` upgrade from `7.4.x` to `7.8.7` to fix a Node JS error (#2111), there is a new JS error in Edge (18/44) that breaks JS execution completely. I looked into the error but never pin pointed the exact cause, just that it appears after the upgrade. Upgrading all `@babel` dependencies from `7.8.7` to `7.13x` finally fixed the error and everything appears to work as expected. I attempted to find the exact release which "fixed" the issue but the whole cycle of switching versions, cleaning, installing and rebuilding is extremely time-consuming. In the end, since the latest version works, I just went with that.
- Runs locally
- No errors in Edge …
> DS-405: Upgrade babel to latest minor release to fix Edge 18 JS error

- package.json
- packages/build-tools/package.json
- packages/testing/testing-helpers/package.json
- packages/twig-integration/twig-renderer/package.json
- packages/website-ui/uikit-workshop/package.json
- yarn.lock
https://pegadigitalit.atlassian.net/browse/DS-410
Upgrade remaining instances to Babel to > `7.8.7` to fix `@babel/helper-compilation-targets` bug.
Removes a couple unused packages from `uikit-workshop`.
Upgrade to `shelljs` fixes a [warning](https://github.com/shelljs/shelljs/issues/991) you see if you are on Node `v14`.
The last instances of Babel came from Basalt's [Twig renderer](https://www.npmjs.com/package/@basalt/twig-renderer). Even the newest versions of this package do not have new enough versions of Babel to fix the issue. So, I copied the library to [a separate repo](https://github.com/boltdesignsystem/basalt-twig-renderer), [upgraded Babel](https://github.com/boltdesignsystem/basalt-twig-renderer/blob/master/package.json#L22-L23) there, and [linked to …
> DS-410 Babel node fixes

- packages/components/bolt-carousel/src/carousel.js
[https://pegadigitalit.atlassian.net/browse/DS-383](https://pegadigitalit.atlassian.net/browse/DS-383)
Resolve click behavior inconsistency in carousel. 
Remove swiper setting `slideToClickedSlide` to resolve click behavior inconsistency in carousel. 
Add a demo with `slides_per_group` set to `1` and verify that clicking on the last slide does not advance the carousel.
> DS-383: Carousel slides_per_group=1 changes click behavior

- packages/components/bolt-hero/hero.schema.js
- packages/components/bolt-hero/hero.twig
[https://pegadigitalit.atlassian.net/browse/DS-421](https://pegadigitalit.atlassian.net/browse/DS-421)
Creating custom attribute list and passing them to the band include.
As in summary. The explanation why this change is needed is in the ticket in Job Summary.
As far as Drupal projects are concerned
- add Hero component to the content page
- try to pass something as an attribute e.g. from within the hook `pega_bolt_hero_paragraph_view`, it should be added to the band markup
There should be no visual changes as long as nothing is passed.
> DS-421: passing custom attributes to the band

- packages/build-tools/utils/manifest.js
n/a
Remove missing dependency warning.
```
Warning! Some of the components being compiled have Bolt dependencies and/or peerDependencies that appear to be missing from your build configuration. 
```
This warning is no longer relevant because we are not planning to remove the feature which automatically adds missing dependencies to the Bolt manifest. It's not worth reworking this part of the build when we will be redesigning this in the next iteration.
Build passes and you do not see this warning.
> Remove dependency warning

- package.json
n/a
Upgrade `stylelint` to fix issues with autofix.
Older versions of `stylelint` don't seem to [handle autofix properly](https://github.com/stylelint/vscode-stylelint/issues/100#issuecomment-612113626). Upgrade so that VS Code format-on-save and `yarn fix` command respect stylelint "ignore" comments.
- Checkout feature branch and run `yarn`.
- Add this line to a SCSS file to test:
```
/* stylelint-disable function-name-case */
width: var(--c-bolt-popover-bubble-width, Min(65vw, 250px));
```
- Verify that after saving the file and after running `yarn fix` the "Min" rule still has capital "M".
- Remove the stylelint-disable comment and repeat. It should change the "M" to "m".
> Upgrade stylelint to fix autofix bug

- packages/components/bolt-listing-teaser/src/listing-teaser.twig
- packages/components/bolt-page-header/src/page-header.twig
Fixes a few instances of Twig conditions missing `.value` in Page Header and Listing Teaser.
Run the branch locally. Check the following:
Make sure the `static` prop works as intended, the `c-bolt-page-header--static` should not be generated unless the prop value is `true`.
Make sure the `more_info` and `warning` prop work as intended. This wasn't broken, we are just adding `.value` to stay consistent.
> Fix Twig conditions in Page Header and Listing Teaser

- packages/components/bolt-tabs/src/tabs.js
https://pegadigitalit.atlassian.net/browse/DS-425
Waiting until Tabs component is fully rendered to dispatch the "ready" event.
Tabs is not really ready on initial render. It takes one more cycle of rendering before the Tabs markup is all there. The base class, however, dispatches the "ready" event after first render in [the `firstUpdated()` function](https://github.com/boltdesignsystem/bolt/blob/master/packages/base-element/src/lib/decorators/render-and-rendered-events.js#L15-L23). This PR updates Tabs to wait until after the second render to call the base class `firstUpdated()` function.
- Review the code.
- On `master` add this code to `docs-site/src/index.js`:
```
const tabs = document.querySelector('bolt-tabs');
tabs.addEventListener('ready', function(e) {
if (tabs === e.target) { …
```
> DS-425 Fix Tabs "ready" event

- packages/components/bolt-page-header/src/page-header-nav-li.twig
Related to https://pegadigitalit.atlassian.net/browse/WWW-467, though that doesn't describe the bug
Fixes attributes in page header links.
The bug this fixes is that custom classes cannot be passed in `link.attributes` without breaking the two existing hard-coded CSS classes, `c-bolt-page-header__nav-link` and `c-bolt-page-header__nav-link--heading`.
Whenever they're used, `Attributes` should be expected to potentially contain all HTML attributes.  Use `addClass()` to add additional classes, or `|without()` if you wish to print some attributes separately.
- On master, create a page header link that adds a custom class using link.attributes 
```
{% include '@bolt-components-page-header/page-header-nav-li.twig' with {
link: {
content: 'Foo',
desktop_heading: true,
attributes: {
class: …
```
> WWW-467: Remove separate hard-coded classes on desktop heading links

- packages/components/bolt-teaser/src/teaser.scss
https://pegadigitalit.atlassian.net/browse/WWW-606
Removed the word break from the Teaser description text
This fix prevents words from being broken (without hyphens) in the hover description text. This came up on testing of WWW-606.
Review the /pattern-lab/?p=components-teaser-text-options page and check how the hover description text breaks to a new line and hyphenates
> WWW-606: Hover Description Text Update

- packages/components/bolt-carousel/__tests__/__snapshots__/carousel.js.snap
- packages/testing/testing-helpers/index.js
https://pegadigitalit.atlassian.net/browse/DS-447
Fix broken promise in renderWC to fix intermittent Jest snapshot failures, especially on the Carousel component.
[This promise](https://github.com/boltdesignsystem/bolt/blob/master/packages/testing/testing-helpers/index.js#L53) in renderWC does not work because `customElements` and `whenDefined` objects do not exist within the Jest page context.
Because this promise does not actually wait, the HTML returned may vary, resulting in intermittent snapshot failures. If we fix this broken promise, Jest test snapshots that use `renderWC` should return consistent results, or at least fail less often and for different reasons.
> DS-447 Fix broken `renderWC` promise

- packages/components/bolt-modal/src/modal.scss
https://pegadigitalit.atlassian.net/browse/DS-418
Modal scroll fix
The fix prevents a scroll but from appearing when a image is taller than the viewport
Navigate to "/pattern-lab/?p=components-modal-usage-image-and-caption" and open up the "Enlarge image and show caption" modal and scroll down. The modal overlay should not scroll up with the page.
> DS-418: 2.30 regression: Image modal scroll dragging overlay up

- docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/index.scss
Quick filter colors now correctly display in dark themes
Changed the CSS color vars to be match the secondary text color value
Navigate to "/pattern-lab/?p=pages-boc-gallery-phase2", change the containing ".c-bolt-band" to a dark theme and click on one of the quick filters, the text will no longer display as white on a white background
The Quick Filters (Best of Content) labels will now correctly display when this component is rendered in a dark theme
> Fixed a active state color bug on the quick tabs

- packages/components/bolt-modal/src/modal.scss
https://pegadigitalit.atlassian.net/browse/DS-448
(Enter a one-line summary of the changes in this PR. This will be included in the release notes)
Added a webkit specific workaround to fix a iOS bug that was having the bottom bar cover the bottom portion of the modal
On iOS (I plugged my iPhone in my computer to test, but I think Browserstack would also work), navigate to "/pattern-lab/patterns/50-pages-65-best-of-content--20-boc-gallery-phase1/50-pages-65-best-of-content--20-boc-gallery-phase1.html", open the "More Filters" button and observe that the modal footer is not being covered by the bottom bar. 
On iOS, the modal will now behave with the Safari bottom bar (it appears when scrolling)
> DS-488: PW Replay facets :On IOS mobile upon trying to apply the filter the save option is not in the viewport. Upon scrolling able to see the same

- packages/components/bolt-teaser/src/teaser.scss
https://pegadigitalit.atlassian.net/browse/DS-449
Fix stacking order of like/share buttons in Teaser.
In FF you cannot click on like/share buttons inside the Teaser, [see example](https://boltdesignsystem.com/pattern-lab/patterns/50-pages-65-best-of-content--25-boc-listing-pegaworld-phase1/50-pages-65-best-of-content--25-boc-listing-pegaworld-phase1.html).
In every other browser the stack order works differently and like/share are still hoverable/clickable. In FF it seems that because we set the "actions" container to `order: 0` it lowers the stack order and they're covered up by the headline link. If I remove the `order` rule it fixes itself in FF. So, without any alternative, I added `z-index: 1`. Sorry @mikemai2awesome. Let me know if you have a better idea.
- View [this …
> DS-449: Fix stacking order in FF

- packages/components/bolt-page-header/page-header.schema.js
- packages/components/bolt-page-header/src/page-header.twig
https://pegadigitalit.atlassian.net/browse/WWW-467
Fixes a minor header translation bug and adds missing docs
- The `|t` filter should only be used on actual translatable strings of text, not variables.  It won't work if you use in on a variable (e.g. `{{ logo.label|t }}`), and will actually prevent translating the original string.  The correct way to handle this is to print the variable as-is (`{{ logo.label }}`) and translate the string that gets passed in (e.g. `logo: { label: 'Home'|t }`)
- Adds missing schema entry for `subheadline`
N/A really, unless you want to test translation in Drupal.  Read more here if you don't believe me: https://www.drupal.org/docs/8/api/translation-api/overview#s-variables-in-user-interface-text
> WWW-467 Header tweaks

- packages/components/bolt-teaser/src/teaser.scss
- packages/components/bolt-teaser/src/teaser.twig
https://pegadigitalit.atlassian.net/browse/DS-450
Fixes an issue where the teaser view count has a higher stacking order than the teaser headline link.
1. Limited the z-index usage to only the like and share buttons
2. Renamed a container element to be less confusing
Run the branch locally and test this page: http://localhost:3000/pattern-lab/?p=components-teaser-status-and-actions, make sure the like and share still work as expected and view count is not blocking the headline link, in Firefox, Safari, Chrome, and Edge. Also test the same thing in Best of Content phase 2 gallery page.
> DS-450 Fix stacking order of Teaser view count in FF

- packages/components/bolt-teaser/__tests__/__snapshots__/teaser.js.snap
- packages/components/bolt-teaser/src/teaser.scss
- packages/components/bolt-teaser/src/teaser.twig
https://pegadigitalit.atlassian.net/browse/DS-450
Fixes an issue where the teaser view count has a higher stacking order than the teaser headline link.
See https://github.com/boltdesignsystem/bolt/pull/2163
> Hotfix: DS-450 limit z-index to like and share buttons

- package.json
- packages/configs/stylelint-config/package.json
- yarn.lock
n/a
Fix missing `min-indent` error.
`min-indent` package was removed from yarn.lock recently. I don't think it was related to any of our changes, just a change to one of our dependencies. Perhaps there is an undeclared dependency in one of our dependencies? I fix this by adding `min-indent` to our `stylelint-config` package.
In the process of debugging I also found dupe stylelint dependencies at different versions. I removed the older versions.
- Review changed files
- This branch builds on Travis
> Fix `min-indent` error

- packages/core-v3.x/styles/01-settings/settings-font-family/_settings-font-family.scss
- packages/core-v3.x/styles/01-settings/settings-global/_settings-global.scss
- packages/servers/testing-server/index.js
https://pegadigitalit.atlassian.net/browse/DS-89
Remove remaining code related to old JS font-loading approach.
Removes `js-fonts-loaded` class in SCSS and testing server HTML. We no longer use this class for anything. It was removed [as part of `3.0`](https://github.com/boltdesignsystem/bolt/commit/142e8730b712ddfc7959e9d2222323b9c6dd8d47#diff-eecf057daf323883b3a840cf8fdbdc64afba36274164320b02bf3aa972f4605fL19-L22).  No usage downstream except for [Bolt Emulsify POC](https://gitlab.com/search?group_id=5804310&repository_ref=&scope=blobs&search=loaded-class%2A&snippets=false).
- Verify no regressions to fonts
> DS-89 Remove font-loading code

- packages/testing/testing-nightwatch/package.json
- scripts/package.json
- yarn.lock
n/a
Upgrade chromedriver to 89 to fix Travis builds.
- Already passing here: https://travis-ci.com/github/boltdesignsystem/bolt/builds/223221219
> Upgrade chromedriver to 89 to fix Travis builds

- packages/components/bolt-share/src/share.twig
https://pegadigitalit.atlassian.net/browse/WWW-696?focusedCommentId=26785
As @remydenton discovered a while ago, Drupal doesn't like when you use set with renderable content.
https://www.drupal.org/project/drupal/issues/2994673
This caused share's menu display to output raw HTML. This changes the variable structure so Drupal doesn't try to escape it.
For menu_items, change `{% set menu_items = ` to `{% set menu_items %}{% endset %}` instead.
I don't think it can be reproduced in Bolt, but I can confirm it fixes the issue for me locally in Drupal.
N/A
N/A
> WWW-696 Fix Drupal escaping markup when using 'set foo = bar'.

- packages/components/bolt-share/src/share.twig
https://pegadigitalit.atlassian.net/browse/WWW-696?focusedCommentId=26785
https://github.com/boltdesignsystem/bolt/pull/2173
> Hotfix: WWW-696 Fix Drupal escaping markup when using 'set' in Share component

- packages/components/bolt-modal/src/modal.js
https://pegadigitalit.atlassian.net/browse/WWW-694
Added a class to prevent the page from being scrollable when a modal is opened
Tested in the following browser/devices
- Edge (latest)
- Chrome (latest)
- FF (latest)
- Safari (latest)
- Safari iOS (latest)
- Android 9, 10, 11
Pull down the branch
Test examples of the modal in Patternlab
A modal will no longer allow the page to scroll behind it and will be 100% the hight of the viewport
> WWW-694: PW Replay facets :On IOS mobile upon trying to apply the filter the save option is not in the viewport. Upon scrolling able to see the same

- packages/components/bolt-icons/src/svgs/utility/lock-solid.svg
- packages/components/bolt-teaser/__tests__/__snapshots__/teaser.js.snap
N/A
Fix the rendering issue with lock-solid.svg icon on dark theme
Add to svg file `fill="1F2555"` attribute.
Check if the icon on a dark theme is rendered in white color.
Icon before
Icon after:
> Fix lock-solid.svg to work with dark theme

- docs-site/src/pages/pattern-lab/_patterns/40-components/teaser/35-teaser-text-options.twig
- docs-site/src/pages/pattern-lab/_patterns/40-components/teaser/40-teaser-description-on-hover.twig
- packages/components/bolt-share/src/share.twig
- packages/components/bolt-tabs/index.js
- packages/components/bolt-teaser/__tests__/__snapshots__/teaser.js.snap
- packages/components/bolt-teaser/src/teaser.scss
- packages/components/bolt-teaser/src/teaser.twig
n/a
Cherry-pick changes from:
- https://github.com/boltdesignsystem/bolt/pull/2161
- https://github.com/boltdesignsystem/bolt/pull/2152
- https://github.com/boltdesignsystem/bolt/pull/2164
- https://github.com/boltdesignsystem/bolt/pull/2176
This is an overview of the the files that were changes and the important changes that will be needed
- packages/components/bolt-share/src/share.twig
- packages/components/bolt-share/src/share.twig (_Line 99_)
- packages/components/bolt-teaser/src/teaser.scss
- packages/components/bolt-teaser/src/teaser.twig  (_Line 37_)
- packages/components/bolt-teaser/src/teaser.scss
- docs-site/src/pages/pattern-lab/\_patterns/40-components/teaser/35-teaser-text-options.twig
- docs-site/src/pages/pattern-lab/\_patterns/40-components/teaser/40-teaser-description-on-h …
> Hotfix 3.4.4

- packages/components/bolt-toc/src/_toc-item.js
- packages/components/bolt-toc/src/toc.js
- packages/core-v3.x/utils/waypoint/index.js
https://pegadigitalit.atlassian.net/browse/DS-452
Rename Waypoint `target` top avoid conflict with target prop
Waypoint adds data to "target" elements. This PR changes the name of that data from `target` to `waypointElement` to avoid conflict with elements that may have a `target` prop already.
- Checkout feature branch and verify TOC component works as expected
> DS-452: Rename Waypoint "target"

- packages/base-element/src/lib/decorators/json-schema-props.js
https://pegadigitalit.atlassian.net/browse/DS-456
Fixes bug where two components that both extend `BoltActionElement` can overwrite each other's default prop values.
In v3.5.0 we converted `BoltActionElement` to use [the `this.props` getter](https://github.com/boltdesignsystem/bolt/pull/2132/files#diff-a64f2ffab2e85d31369c13ddf85e88b3031f3e4f5ede41751fde038c34ec47e7R13). This led to a bug where the default props of `BoltChip`, say, are applied to `BoltActionElement`. Then, when `BoltButton` extends `BoltActionElement` it inherits `BoltChip`'s default values.
To fix this, I am now always [resetting `defaultProps`](https://github.com/boltdesignsystem/bolt/blob/f445c23ebfd7e2d606523df22d4c4f475711264f/packages/base-element/src/lib/decorators/json-schema-props.js#L26), rather than inheriting …
> DS-456: Overwrite, do not merge, `this.defaultProps`

- packages/components/bolt-tabs/src/tabs.js
https://pegadigitalit.atlassian.net/browse/DS-426
Fix the a bug where the Tabs overflow menu does not display on load.
On initial page load the Tabs overflow menu should display if Tab Labels overflow the container. It appears this broke around `v2.30.0`, probably when we upgraded the Bolt Trigger renderer.
On load, the JS that calculates the width of each Tab Label was returning `0` because the Tab Labels, which are web components, were not yet ready. I added a `Promise` that waits for the Tab Labels to finish rendering before proceeding to the overflow menu step.
- To reproduce the bug, go to [current Tabs demo](https://boltdesignsystem.com/pattern-lab/patterns/40-components-tabs-05-tabs/40-components-tabs-05-tabs.html).
- Shrink the browser width until the overflow menu kicks in. Then, …
> DS-426 Fix Tabs overflow menu bug

- auto-release.js
Attempt to fix auto-deploy script and cut next minor release.
The last release failed. I believe this command, run by `auto`, exceeds the max buffer length:
`git log -n 9007199254740991 --pretty="@begin@\t%H\t%an\t%ae\t%B@end@" v3.5.4..HEAD --name-status`
See https://travis-ci.com/github/boltdesignsystem/bolt/jobs/503811542#L738
There were an unusually high number of commits and changed files in this release and it's possible we hit an upper limit for the first time.
This PR increases `maxBuffer` [option](https://github.com/shelljs/shelljs#execcommand--options--callback) when we run the `auto` command.
Merge and watch Travis 🍿
> Release 3.6.0

- docs-site/src/pages/pattern-lab/_patterns/40-components/accordion/40-accordion-content-variations.twig
- docs-site/src/pages/pattern-lab/_patterns/40-components/band/30-band-with-pinned-content.twig
- docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/20-listing-teaser-status-and-action.twig
- docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/60-listing-teaser-use-case-article-list.twig
- docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/65-listing-teaser-use-case-search-result-list.twig
- docs-site/src/pages/pattern-lab/_patterns/40-components/share/00-share-docs.twig
- docs-site/src/pages/pattern-lab/_patterns/40-components/share/05-share.twig
- docs-site/src/pages/pattern-lab/_patterns/40-components/share/_share-variables.twig
- docs-site/src/pages/pattern-lab/_patterns/40-components/teaser/30-teaser-status-and-actions.twig
- docs-site/src/pages/pattern-lab/_patterns/50-pages/20-d8-press-and-media/00-d8-news-landing.twig
- docs-site/src/pages/pattern-lab/_patterns/50-pages/20-d8-press-and-media/05-d8-browse-page.twig
- docs-site/src/pages/pattern-lab/_patterns/50-pages/20-d8-press-and-media/20-d8-details-page-press.twig
- docs-site/src/pages/pattern-lab/_patterns/50-pages/40-d8-content-hub/00-sticky-navbar.twig
- docs-site/src/pages/pattern-lab/_patterns/50-pages/45-d8-blog/05-blog-post.twig
- docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-gallery.twig
- docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-homepage.twig
- docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-listing-customers.twig
- docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-listing-pegaworld.twig
- docs-site/src/pages/pattern-lab/_patterns/50-pages/99999-bolt-dev-sandbox/_wip-doc-layout.twig
- docs-site/src/pages/pattern-lab/_patterns/999-tests/accordion/00-accordion-no-shadow.twig
- docs-site/src/pages/pattern-lab/_patterns/999-tests/share/05-share.twig
- packages/components/bolt-menu/menu.schema.js
- packages/components/bolt-share/__tests__/__snapshots__/share.js.snap
- packages/components/bolt-share/__tests__/share.js
- packages/components/bolt-share/share.schema.js
- packages/components/bolt-share/src/share.twig
- packages/components/bolt-teaser/__tests__/teaser.js
https://pegadigitalit.atlassian.net/browse/DS-476
Deprecated the URL prop on the Share component to allow for more flexible Drupal integration
- Added 'attributes' to the share and menu item items schema to allow for data attributes to the added to the bolt-share on both the "display="inline" and display="menu" types.
- Rewrote the share component jest test to the latest standards (added a deprecated test and added a 'display' prop test)
- Updated the Teaser jest test to the new snapshot
- Updated the doc site with the new share schema structure
Pull down this branch and confirm that the share functionality is still work
Able to pass in data attributes to the share component for custom functionality
> Hotfix v3.6.1

- packages/components/bolt-share/src/share.twig
https://pegadigitalit.atlassian.net/browse/WWW-745
Adds support for attributes on copy to clipboard within share
The copy to clipboard component supports attributes, but there was previously no way to pass them through the share component.  Now there is.
- In the [_share-variables.twig partial](https://github.com/boltdesignsystem/bolt/blob/master/docs-site/src/pages/pattern-lab/_patterns/40-components/share/_share-variables.twig#L32), add attributes to the demo_copy_to_clipboard array
```
{% set demo_copy_to_clipboard =  {
text_to_copy: 'https://boltdesignsystem.com',
attributes: {id: 'foo'},
} %}
``` 
- Confirm that without this PR, attributes do no appear on the copy to clipboard element, but after they do.
> WWW-745: Allow attributes to be passed from share to copy to clipboard

- packages/components/bolt-share/src/share.twig
https://pegadigitalit.atlassian.net/browse/WWW-745
Fixes support for copy to clipboard attributes in share.
This is a follow up to https://github.com/boltdesignsystem/bolt/pull/2214.  I neglected to add support for share components that have `display` set to `menu` 🤦 .
- In the _share-variables.twig partial, add attributes to the demo_copy_to_clipboard array
```
{% set demo_copy_to_clipboard =  {
text_to_copy: 'https://boltdesignsystem.com',
attributes: {'foo': 'bar'},
} %}
```
- Confirm that without this PR, attributes appear on the copy to clipboard element only on share components with `display` set to `inline`, not on share components with `display` set to `menu`.  After this PR, attributes should work in both places.
> WWW-745 share copy attributes

- docs-site/src/pages/pattern-lab/_patterns/999-tests/popover/05-popover-no-shadow.twig
- docs-site/src/pages/pattern-lab/_patterns/999-tests/tooltip/00-tooltip-no-shadow.twig
- packages/components/bolt-popover/src/popover.js
- packages/components/bolt-popover/src/popover.scss
- packages/components/bolt-tooltip/src/tooltip.js
- packages/components/bolt-tooltip/src/tooltip.scss
https://pegadigitalit.atlassian.net/browse/DS-481
Fix popover and tooltip when rendered to light dom, for example when inside a `<form>`.
Popover and tooltip were breaking when inside a `<form>` where shadow dom is disabled (for legacy reasons). It was breaking because the "content" slot was not actually being rendered in the light dom version of these components. It is automatically rendered when using the shadow dom version, but not rendered at all when shadow dom is disabled. To fix this, I'm now explicitly rendering the "content" slot and hiding it via CSS. This now works when shadow dom is on and off.
This wasn't discovered earlier because rendering a popover or tooltip to the light dom is an edge case, but this is a good reminder to include light dom testing when we're working with …
> DS-481: Fix popover/tooltip when shadow dom disabled

- yarn.lock
n/a
Upgrade `chromedriver` and `yarn.lock` to fix travis issues.
> upgrade chromedriver, lock file

- packages/components/bolt-card-replacement/card-replacement.schema.js
- packages/components/bolt-card-replacement/src/card-replacement/card-replacement.twig
https://pegadigitalit.atlassian.net/browse/DS-467
Removes deprecated borderRadius prop from card component
borderRadius has been replaced with border_radius and will be removed in 4.0
The `borderRadius` prop in the card component has been renamed to `border_radius`.  Usage of the `borderRadius` prop will no longer work starting in Bolt 4.0.
> DS-467 remove card deprecations

- packages/components/bolt-link/link.schema.js
- packages/components/bolt-link/src/link.twig
https://pegadigitalit.atlassian.net/browse/DS-432
Adds back in support for deprecated link props removed in #2220
As decided in dev huddle, we want to deprecate the link component altogether in favor of the link element.   It's not that spending time on removing deprecated props is wrong, but that the time is better spent elsewhere.
- Checkout the branch locally
- Set `schemaErrorReporting` to `none` in [pattern lab's boltrc](https://github.com/boltdesignsystem/bolt/blob/master/docs-site/.boltrc.js#L24) to allow it to build when deprecated props are passed.
- Try adding any of the four deprecated props that this PR adds back and confirm they work
(testing probably isn't required since this just reverts previously existing code)
> Revert "DS-432: Remove deprecated props from link component"

- docs-site/src/pages/pattern-lab/_patterns/30-layouts/site/00-site-docs.twig
- docs-site/src/pages/pattern-lab/_patterns/30-layouts/site/05-site.twig
- packages/base-starter-kit/.boltrc.js
- packages/base-starter-kit/package.json
- packages/layouts/bolt-site/README.md
- packages/layouts/bolt-site/index.scss
- packages/layouts/bolt-site/package.json
- packages/layouts/bolt-site/site.schema.js
- packages/layouts/bolt-site/src/site.scss
- packages/layouts/bolt-site/src/site.twig
https://pegadigitalit.atlassian.net/browse/DS-335
Introduces a Layout called Site. The classic pancake stack site layout that enables the footer to be always positioned on the bottom.
1. Site added under Layouts.
2. This replaces `.c-bolt-site`.
3. Once this is implemented into the base theme and all sites convert to use the base theme template without overrides, we can remove everything related to `.c-bolt-site`.
Run the branch locally and check all the docs under Layouts > Site. Make sure all props and blocks work as expected.
> DS-335 Set up site layout

- packages/components/bolt-navbar/__tests__/__snapshots__/navbar.js.snap
- packages/components/bolt-navbar/src/navbar.js
- packages/components/bolt-navbar/src/navbar.twig
- packages/components/bolt-page-header/src/page-header.twig
- packages/components/bolt-sticky/index.js
- packages/components/bolt-sticky/package.json
- packages/components/bolt-sticky/src/sticky.js
- yarn.lock
https://pegadigitalit.atlassian.net/browse/DS-248
Update classes used for tracking sticky elements in Navbar and Page Header components.
Adds class `js-bolt-sticky` to Navbar and `js-sticky-page-header` to Page Header. This allows us to track sticky elements globally via the former class and track the sticky page header specifically via the latter class. This is required to calculate the page offset when we smooth scroll to an element. These classes are used internally by Navbar, but primarily used in base theme where smooth scroll code is integrated.
In the future, when we rebuild smooth scroll, this convention may change. In the meantime, this at least standardizes our approach.
I'm also removing an unnecessary [sticky polyfill](https://caniuse.com/css-sticky). The polyfill was applying …
> DS-248 Update sticky classes

- auto-release.js
One more try at fixing auto-release. Then I will just run it locally where `maxBuffer` does not appear to be an issue.
> Release v4.0.0

- docs-site/src/templates/homepage.twig
- packages/components/bolt-navbar/src/navbar.scss
https://pegadigitalit.atlassian.net/browse/DS-528
Fix version selector on PL homepage.
If you try to use the version selector on https://boltdesignsystem.com/ you will see that the menu is unclickable once open and the font-weight is bold when it should be normal. This PR fixes both by setting the navbar to sticky (gives it a higher z-index order) and sets the Navbar title to `font-weight: initital` so that is a header tag is passed the font-weight is unchanged.
- Run locally and verify version selector on homepage is usable
- Verify the version selector menu items have normal font-weight, not bold
- Verify no other regressions to title font-weight elsewhere in the Navbar docs
> DS-528 Fix PL homepage navbar

- package.json
Upgrade `@bolt/testing-utils` to fix yarn error that is breaking the release process.
> Hotfix v4.0.1

- docs-site/src/pages/pattern-lab/_patterns/20-elements/button/25-button-with-icon-only.twig
Add `e-bolt-button--icon-only` to element button doc demos.
It wasn't obvious that we needed this class so i added it to the demo to hopefully save someone in the future some time.
> Add icon-only class to element button docs.

- packages/components/bolt-carousel/__tests__/__snapshots__/carousel.js.snap
- packages/components/bolt-carousel/__tests__/carousel.js
- packages/components/bolt-carousel/src/_carousel.next-previous-buttons.scss
- packages/components/bolt-carousel/src/carousel.js
- packages/components/bolt-carousel/src/carousel.twig
[https://pegadigitalit.atlassian.net/browse/DS-526](https://pegadigitalit.atlassian.net/browse/DS-526)
Replace component button with element button in carousel component.
we're deprecating and removingt the button component. this replaces instance of the button component in carousel with the button element.
look at the demos in pattern lab as well as the code and the updated jest snap.
The button element is slightly larger than the button component for accessibility purposes, this is expected.
> DS-526: Replace Button in Carousel Component

- docs-site/src/pages/pattern-lab/_patterns/999-tests/tabs/10-tabs-deep-linking.twig
- packages/components/bolt-tabs/src/tabs.js
https://pegadigitalit.atlassian.net/browse/DS-524
Fix smooth scroll bug that prevents user from scrolling after navigating to a deep linked tab.
There is a bug that prevents the user from scrolling after navigating to a deep-linked Tab. Oddly this does not appear to happen in production, but you can see it in PL if you:
1. Go to https://master.boltdesignsystem.com/pattern-lab/patterns/40-components-tabs-45-tabs-deep-linking/40-components-tabs-45-tabs-deep-linking.html?selected-tab=tab-3
2. In the inspector add padding to the body (so you can scroll)
3. Try to scroll
The solution was just to add a fallback `offset` value to smoothScroll. Apparently if you pass this `undefined` it breaks completely.
- See test page and verify you can scroll after initial scroll-to …
> DS-524: Fix smooth scroll bug on deep linked Tabs

- packages/components/bolt-band/band.schema.js
- packages/twig-integration/twig-extensions-shared/src/Utils.php
https://pegadigitalit.atlassian.net/browse/DS-563
Fixes two separate but related bugs in the twig `init()` function
Fixes these two bugs:
1. If an attributes object is already present in the current `context` when `init()` is called, it will be unintentionally populated by `init()`.
2. If a schema property type is `array` or `object`, it's ignored by `init()`.  However, if the type is `any`, it will not be ignored, but it should be.
Note, we may want to consider waiting to merge this until the 4.0 hotfixes needed in https://pegadigitalit.atlassian.net/browse/DS-562 are ready too.
(I have not tested with these exact steps, I'm testing directly in Drupal where the problem was discovered).
Issue 1
* Create a navbar in pattern lab.  Then create an empty attributes object (it must by an …
> DS-563 twig init() fixes

- docs-site/src/pages/pattern-lab/_patterns/999-tests/navbar/05-navbar-with-active-link.twig
- packages/components/bolt-navbar/src/navbar-li.twig
https://pegadigitalit.atlassian.net/browse/DS-533 (bug discovered during implementation)
Fix boolean attribute syntax in navbar
When trying to set the `current` attribute to `true` in Drupal, I got an error that `setAttribute()` was missing an argument (only had one instead of two).  This PR fixes the syntax by passing `TRUE` as the second argument to boolean attributes.
The Drupal docs don't explicitly address boolean attributes, but this seems correct to me based on the other docs at https://www.drupal.org/docs/8/theming-drupal-8/using-attributes-in-templates#s-attributessetattributeattribute-value
This may only be a problem in Drupal, but it seems like you should be able to test by creating a navbar item with `current` set to `true`.  If attributes behave the same in pattern lab as …
> DS-563: Fix boolean attribute syntax

- packages/components/bolt-accordion/src/AccordionItem/accordion-item.scss
- packages/components/bolt-banner/src/banner.scss
- packages/components/bolt-button/src/button.scss
- packages/components/bolt-list/src/list.scss
- packages/components/bolt-video/brightcove/_video.scss
- packages/components/bolt-video/src/_videojs-enhancements.scss
https://pegadigitalit.atlassian.net/browse/DS-554
Remove `text-align: left;` if `text-align: start;` is present
Codebase was searched for `text-align: left;`
Search the codebase for `text-align: start;`. If `text-align: start;` is defined there should not be `text-align: left;` in the same ruleset.
> DS-554: Remove Text Align Left Update

- docs-site/src/pages/pattern-lab/_patterns/999-tests/navbar/22-navbar-title-tags.twig
- packages/components/bolt-navbar/src/navbar.scss
https://pegadigitalit.atlassian.net/browse/DS-562
Removes unexpected margin-bottom when you use a heading tag (`h1`, `h2`, etc.) with Navbar title.
If Navbar title uses a heading tag, it inherits global heading styles. This PR removes the margin-bottom that global styles add.
- Review changed files
- View [test page](http://localhost:3001/pattern-lab/?p=tests-navbar-title-tags) to verify there is no margin-bottom on Navbar titles.
> DS-562 Remove unexpected margin bottom on Navbar title

- packages/global/styles/04-elements/_elements-code.scss
- packages/global/styles/04-elements/_elements-misc.scss
https://pegadigitalit.atlassian.net/browse/COM-780
Fixes `kbd` styles so that it doesn't overlap other content.
1. Updated the `kbd` styles to reduce the padding.
2. Updated `code` font-size to match `kbd`, allowing code text to relatively update its size along with neighboring text.
Run the branch locally, create a dummy page with some placeholder text, add some `kbd` and `code` in the text content. Make sure these elements don't overlap each other when they are close.
> COM-780 keyboard input styles

- packages/build-tools/create-webpack-config.js
https://pegadigitalit.atlassian.net/browse/DS-574
Disable `cssnano` "calc" optimizations.
`cssnano` is breaking certain "calc" rules when it tries to optimize them.
We use the ["default" config option](https://cssnano.co/docs/optimisations) with a handful of [additional options disabled](https://github.com/boltdesignsystem/bolt/blob/7aa85514e8309775f1bb6c25c1d1c53998af19cc/packages/build-tools/create-webpack-config.js#L344-L349). I'm adding "calc" to the list of disabled optimizations.
Down the road we will switch to the "lite" config. For now, just to be safe, disable only "calc".
- Smoke test of PL site
> DS-574: Disable cssnano `calc` optimizations

- packages/build-tools/create-webpack-config.js
Redo https://github.com/boltdesignsystem/bolt/pull/2282, which released as `4.1.1`. This time it should release as `4.0.3`.
> Hotfix v4.0.3

- packages/components/bolt-toolbar/toolbar.scss
- packages/components/bolt-toolbar/toolbar.twig
https://pegadigitalit.atlassian.net/browse/DS-577
Fixes edge case where breadcrumbs content is passed with wrapping `<div>` and vertical centering is thrown off.
Adds wrapping `<div>` to Toolbar component and targets _that_ for vertical alignment, rather than counting on `bolt-breadcrumb` being the top-level element passed as `content_before`.
> Note: this was originally intended as hotfix to `4.1.x`, but at this point let's just merge into `master` and release with `4.2.0`. The effort of cutting all these hotfixes is really adding up. Sites can just skip to `v4.2.0`.
- See Academy demo (link TBD) and verify breadcrumb is vertically aligned
> DS-577 Fix toolbar breadcrumb centering

- docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/00-color/10-theming-system.twig
Fixed a typo on the Theming System doc page.
> Fix: typo on theming system doc

- packages/components/bolt-page-header/src/_page-header-desktop.scss
https://pegadigitalit.atlassian.net/browse/WWW-467?focusedCommentId=35239
Updates desktop top level links to black and view-all links to same font-size as other links on the same level.
View page header docs and confirm the 2 changes.
1. Page header desktop top level links are now black
2. Page header view-all links are slightly smaller
> WWW-467 fix page header link font-size and color

- packages/testing/testing-nightwatch/package.json
- scripts/package.json
- yarn.lock
n/a
Force upgrade `chromedriver`.
Change `chromedriver` dependency syntax from `latest` to `*` to see if it makes any difference in the future. If this fails again, both npm and Travis are getting hardcoded. cc @remydenton @colbytcook @adamszalapski 
Build is passing
> Upgrade chromedriver

- scripts/release/update-read-only-git-repos.sh
N/A
Fixes broken publishing to read-only repos ([bolt_connect](https://github.com/boltdesignsystem/bolt_connect) and [core-php](https://github.com/boltdesignsystem/core-php))
Previously, changes weren't being published to these repos due to a hard-coded condition that only allowed publishing from the `release/1.x` or `release/2.x` branches.  This PR removes all conditions, under the assumption that any conditions for running or not running this script should happen outside this script itself.
Additionally, I updated the old domain (bolt-design-system.com) to the new (boltdesignsystem.com)
Any merges to a `release/*` branch should run this script now.  Alternatively, you can run it locally.
Note that the script will update the two read-only github repos as long as you have permission to do …
> Fix read-only repo publishing

- packages/components/bolt-page-header/src/_page-header-mobile.scss
- packages/components/bolt-page-header/src/_page-header-settings-and-tools.scss
https://pegadigitalit.atlassian.net/browse/WWW-960
Makes unselected top-level mobile links black for consistency
See screenshots in the "visual changes" section below.  All other colors should be unchanged.
See screenshots in the "visual changes" section below.  All other colors should be unchanged.
In the global nav, top-level links are now black instead of dark navy when not selected.  For example, on https://boltdesignsystem.com/pattern-lab/?p=components-page-header-example-main-site-with-subnav
Before:
After:
> WWW-960: mobile nav top link color

- docs-site/src/pages/pattern-lab/_patterns/40-components/teaser/30-teaser-status-and-actions.twig
- docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/-05-boc-homepage-phase0.twig
- docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/-10-boc-gallery-phase0.twig
- docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/-15-boc-homepage-phase1.twig
- docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/-20-boc-gallery-phase1.twig
- docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/-25-boc-listing-pegaworld-phase1.twig
- docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/-30-boc-homepage-phase2.twig
- docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/-35-boc-gallery-phase2.twig
- docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/-40-boc-listing-pegaworld-phase2.twig
- docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/-45-boc-listing-customers-phase2.twig
- docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/05-boc-homepage-phase0.md
- docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/10-boc-gallery-phase0.md
- docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/15-boc-homepage-phase1.md
- docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/20-boc-gallery-phase1.md
- docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/25-boc-listing-pegaworld-phase1.md
- docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/30-boc-homepage-phase2.md
- docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/35-boc-gallery-phase2.md
- docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/40-boc-listing-pegaworld-phase2.md
- docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/45-boc-listing-customers-phase2.md
- docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-gallery.twig
- docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-homepage.twig
- docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-listing-customers.twig
- docs-site/src/pages/pattern-lab/_patterns/50-pages/65-best-of-content/_boc-listing-pegaworld.twig
- packages/components/bolt-teaser/__tests__/__snapshots__/teaser.js.snap
- packages/components/bolt-teaser/src/teaser.scss
- packages/components/bolt-teaser/src/teaser.twig
- packages/components/bolt-teaser/teaser.schema.js
- packages/core-v3.x/styles/02-tools/tools-inline-icon-wrapper/_tools-inline-icon-wrapper.scss
https://pegadigitalit.atlassian.net/browse/DS-529
Download slides CTA was added. All phases from the `Best-of-content` were removed and only one final version was kept.
Download slides CTA was added to the `bolt-teaser` component and to the `best-of-content` pages in relation to the proposed wireframe.
Pull the branch. Check out the `bolt-teaser` component and `best-of-content` pages where the new `Download slides` CTA was added. Make sure the new CTA is correct in terms of semantics and accessibility.
- Added new CTA to the Listing Teaser actions list on the `bolt-teaser` component and the `best-of-content` page.
- Action list is now aligned to the left.
> DS-529: Pega.com: Add 'Download slides' CTA to PW Replays "Best Of" cards

- docs-site/src/components/pattern-lab-utils/schema-docs.twig
- packages/components/bolt-navbar/navbar-li.schema.js
- packages/components/bolt-navbar/navbar-ul.schema.js
- packages/layouts/bolt-layout/layout-item.schema.js
https://pegadigitalit.atlassian.net/browse/DS-582
Add information about the twig file name on the schema section.
Applies to components with multiple schemas:
- packages/components/bolt-listing-teaser
- packages/components/bolt-navbar
- packages/components/bolt-page-footer
- packages/components/bolt-page-header
- packages/components/bolt-side-nav
- packages/layouts/bolt-holy-grail
- packages/layouts/bolt-layout
Run this code locally and check if the twig file name is shown on components with multiple schemas and it's not visible on single schemas.
> DS-582 Add information about twig file name on schema section

- packages/components/bolt-headline/__tests__/__snapshots__/headline.js.snap
- packages/components/bolt-headline/package.json
- packages/components/bolt-headline/src/_typography.twig
[https://pegadigitalit.atlassian.net/browse/DS-600](https://pegadigitalit.atlassian.net/browse/DS-600)
Replace `component-link` with `element-text-link` in the `bolt-headline` component.
This is part of the ongoing campaign to deprecate the `component-link`.
Review the code changes and the text demo for `bolt-headline`.
Replace component-link with element-text-link in the bolt-headline component.
> DS-600 Replace Link in Headline Component

- docs-site/src/pages/pattern-lab/_patterns/30-layouts/layout/-10-layout-template.twig
- docs-site/src/pages/pattern-lab/_patterns/30-layouts/layout/-15-layout-sub-template.twig
- docs-site/src/pages/pattern-lab/_patterns/30-layouts/layout/-35-layout-horizontal-alignment.twig
- docs-site/src/pages/pattern-lab/_patterns/30-layouts/layout/-40-layout-vertical-alignment.twig
- docs-site/src/pages/pattern-lab/_patterns/30-layouts/layout/-45-layout-item-vertical-alignment.twig
- docs-site/src/pages/pattern-lab/_patterns/30-layouts/layout/-50-layout-item-order.twig
Fixes a few typos in the Layout docs.
Run the branch locally and check the layout docs. Make sure whenever example code is demonstrating `template`, the values are passed as array, not string.
> Fix: layout demo typos

- docs-site/src/pages/pattern-lab/_patterns/50-pages/75-optimized-campaign-landing/-05-oclp-gated-pdf.twig
- docs-site/src/pages/pattern-lab/_patterns/50-pages/75-optimized-campaign-landing/-10-oclp-gated-external-link.twig
- docs-site/src/pages/pattern-lab/_patterns/50-pages/75-optimized-campaign-landing/-15-oclp-gated-video.twig
- docs-site/src/pages/pattern-lab/_patterns/50-pages/75-optimized-campaign-landing/oclp.scss
https://pegadigitalit.atlassian.net/browse/WWW-920
Updates the Optimized Campaign Landing Page templates with a "preview" chip for image and image carousel, and fixes mobile ordering of preview and checklist.
1. Added CSS to position the chip
2. Added markup to contain the image and the chip
3. Moved preview and checklist above text content in mobile view for Gated templates
Run the branch locally and check the Optimized Campaign Landing Pages. For both Gated PDF and Gated External Link templates, the image or image carousel should have a preview chip in the same style as the preview chip for videos. For all Gated templates, the preview and checklist should render right after the headline in mobile view.
> WWW-920 Add preview image chip and re-order preview and checklist in mobile view

- packages/components/bolt-navbar/src/navbar-li.twig
- packages/components/bolt-navbar/src/navbar-ul.twig
https://pegadigitalit.atlassian.net/browse/DS-649
Fixes Navbar schema name, broken in https://github.com/boltdesignsystem/bolt/pull/2316 which was released in `v4.5.0`.
- Go to Navbar demo: https://boltdesignsystem.com/pattern-lab/?p=components-navbar
- See bugs in console
- Repeat on this hotfix branch and note the bugs are gone
> Hotfix: DS-649 Navbar schema key name

- packages/components/bolt-navbar/src/navbar-li.twig
- packages/components/bolt-navbar/src/navbar-ul.twig
https://pegadigitalit.atlassian.net/browse/DS-649
> Note: accidentally merged https://github.com/boltdesignsystem/bolt/pull/2337 into `master`. This one points at `release/4/x`.
Fixes Navbar schema name, broken in https://github.com/boltdesignsystem/bolt/pull/2316 which was released in `v4.5.0`.
- Go to Navbar demo: https://boltdesignsystem.com/pattern-lab/?p=components-navbar
- See bugs in console
- Repeat on this hotfix branch and note the bugs are gone
> Hotfix: DS-649 Navbar schema key name (take 2)

- packages/components/bolt-form/src/form.scss
https://pegadigitalit.atlassian.net/browse/DS-468
Prevent inputs with label "before" from shifting height on focus.
As part of https://pegadigitalit.atlassian.net/browse/DS-468, this PR fixes the shift in height that you see when you focus on an input with label "before". Fixing this helps us match the height between the current input and the Multi-select component.
- View demo with `labelDisplay: "before"`: `/pattern-lab/?p=components-form-label-positions`
- Click into the input and verify input height does not change.
Form inputs with label "before" the field (not floating inside) will no longer shift in height when they get focus.
> DS-468 Fix input height on focus

- packages/components/bolt-banner/src/banner.scss
https://pegadigitalit.atlassian.net/browse/DS-648
Update the background and text colors of "information" banner.
As requested by Academy/Collaboration Center, banners with "information" status will now have light blue background and dark blue text.
- Review Banner demos, particularly "status" demo
- Banner with status "information" are now light blue with dark blue text. Previously they were white with black text.
> DS-648 Update "information" banner colors

- packages/components/bolt-code-snippet/src/code-snippet.js
- packages/components/bolt-typeahead/typeahead.js
n/a
Fix missing icons in Code Snippet and Typeahead.
In the conversion to individually exported icons, a couple got missed.
Run locally and open Code Snippet and Typeahead demos. Verify there's no console error.
> Fix missing icons

- docs-site/src/pages/pattern-lab/_patterns/999-tests/code-snippet/15-code-snippet-table.twig
- packages/components/bolt-code-snippet/index.js
- packages/components/bolt-code-snippet/src/code-snippet.js
- packages/components/bolt-table/package.json
- packages/components/bolt-table/src/table.js
https://pegadigitalit.atlassian.net/browse/DOCS-189
Fixes Code Snippet bugs when used inside Table component.
Table component strips whitespace around tags and text and in the process rewrites the DOM for every element inside. This breaks indentation on Code Snippets and loses any event handlers added prior to Table initializing.
Long term, Table will be rewritten to not do any of this. Short term, this PR tells Code Snippet to not automatically initialize when inside a Table. Then, tells Table to call the Code Snippet initialization after the Table is rendered.
I had to add Code Snippet as a dependency of Table, which means Code Snippet is loaded whenever a Table is present (not just when a Code Snippet is present). I did a few lighthouse checks and didn't notice any difference before …
> DOCS-189: Fix Code Snippet bugs when used inside Table component

- packages/components/bolt-teaser/__tests__/__snapshots__/teaser.js.snap
- packages/components/bolt-teaser/src/teaser.scss
- packages/components/bolt-teaser/src/teaser.twig
Fixed a markup error on the teaser twig
(Explain the changes in enough detail fo reviewers to understand. Raise any questions for reviewers to consider.)
Run the branch locally and confirm that the teaser on `/pattern-lab/?p=components-teaser-status-and-actions` is rendering properly
> Fixed a markup error on the teaser component

- docs-site/src/pages/pattern-lab/_patterns/40-components/background/00-background-docs.twig
- docs-site/src/pages/pattern-lab/_patterns/40-components/background/05-background.twig
- docs-site/src/pages/pattern-lab/_patterns/40-components/background/10-background-opacity-variations.twig
- docs-site/src/pages/pattern-lab/_patterns/40-components/background/15-background-focal-variations.twig
- docs-site/src/pages/pattern-lab/_patterns/40-components/background/25-background-fill-variations.twig
- docs-site/src/pages/pattern-lab/_patterns/40-components/background/35-background-valign-variations.twig
- docs-site/src/pages/pattern-lab/_patterns/40-components/band/35-band-with-background.twig
- docs-site/src/pages/pattern-lab/_patterns/40-components/band/40-band-nested.twig
- packages/components/bolt-background/src/background-item.twig
Updated the Background Component to use the Image Element instead of the Image Component
In order to allow for a more performant Hero, we need to remove all the Image Component. On of the steps to do that is to replace the Image Element from the Background Component so we can leverage more perforrmant methods (for example, appending `loading="eager"` to all images in a hero).
* Review the code and pull down the branch.
* Review the Bolt Background, and the Bolt Band docs.
* Review the docs "Pages" folder
The Background Component now leverages the Image Element instead of the Image Component. This is a step to create a more performant Hero
> Background Component Image Update

- packages/base-starter-kit/.boltrc.js
- packages/components/bolt-background/package.json
- packages/testing/testing-nightwatch/package.json
- packages/testing/testing-utils/__tests__/test-utils.test.js
- scripts/package.json
- yarn.lock
Updated dependencies for the background component updates.
* Added the "@bolt-components-images" as a backgroumd component dependency
* Reordered the .boltrc.js to ABC order
* Fixed a test-util jest test error
* Review the changes
* run `yarn clean`, `yarn setup`, `yarn start`, `yarn test:js` and `yarn` to confirm that all the commands work
> Background Component Updates

- docs-site/src/pages/pattern-lab/_patterns/30-layouts/holy-grail/10-holy-grail-use-case-navigation.twig
- docs-site/src/pages/pattern-lab/_patterns/50-pages/70-community/-community-doc-layout.twig
- packages/components/bolt-side-nav/src/side-nav.scss
- packages/layouts/bolt-holy-grail/src/holy-grail.scss
https://pegadigitalit.atlassian.net/browse/DS-669
Fixes the triangle symbol in Side Nav links to render better in Windows and Holy Grail sidebar to have a max-width.
1. Used a different HTML entity to render the triangle in side nav so it appears normal in Windows
2. Set a max-width on the holy grail sidebar so any long side nav link text would not make the sidebar so wide that it squishes the main content
Run the branch locally and check the Community Doc Layout page in Windows. Make sure the triangle in the side nav looks similar to what you see in Mac. Also the side nav at any breakpoint is at a reasonable width that doesn't squish the main article content too hard.
> DS-669 side nav and holy grail layout enhancements

- docs-site/src/pages/pattern-lab/_patterns/40-components/headline/40-headline-numbered.twig
- packages/components/bolt-headline/headline.schema.js
- packages/components/bolt-headline/src/_typography.twig
- packages/components/bolt-headline/src/eyebrow.twig
- packages/components/bolt-headline/src/headline.scss
- packages/components/bolt-headline/src/headline.twig
- packages/components/bolt-headline/src/lead.twig
- packages/components/bolt-headline/src/subheadline.twig
- packages/components/bolt-headline/src/text.twig
https://pegadigitalit.atlassian.net/browse/DS-304
Fixes a mismatch between the headline component and Drupal admin ui's authoring options.
1. Enabled subheadline to use any size and tag options (although this is against the design guidelines, subheadline should only be used at large, xlarge, and xxlarge sizes, and its tag can be just headings or paragraph).
2. Fixed a doc error where the size variable is not rendering on the numbered headline docs.
We are making this change rather than fixing the Drupal implementation because it's safer. Efforts will be put in to refactor foundational Drupal paragraphs (including headline) in the future, and the headline component will need a refactor (downgrade to element) on the design system side as well.
Run the branch locally and check the headline …
> DS-304 add subheadline sizes to match Drupal admin ui

- docs-site/src/pages/pattern-lab/_patterns/40-components/chip/30-chip-color-variations.twig
- packages/components/bolt-chip/chip.schema.js
- packages/components/bolt-chip/src/chip.js
- packages/components/bolt-chip/src/chip.scss
- packages/components/bolt-chip/src/chip.twig
https://pegadigitalit.atlassian.net/browse/WWW-1072
Fixes a bug where the gray color option for the chip component is not rendering any CSS.
1. Fixed the relevant modifier class in CSS.
2. Updated the twig and js files to reflect the default color.
3. Fixed an height issue where chips with icon is taller than chips without icon.
Run the branch locally and check the chip docs. Make sure all color variations are rendering the correct color in all color themes.
> WWW-1072 Fix chip component's gray color option

- packages/components/bolt-background/src/background-item.twig
Updated the Bolt Background lazy load conditional to default to lazy
1. Pull down the branch locally
2. Navigate to http://localhost:3000/pattern-lab/?p=pages-d8-homepage
3. Inspect the Bolt Background image and confirm that **loading="eager"** is present
4. Change the twig value on line 107 in "docs-site/src/pages/pattern-lab/_patterns/50-pages/05-d8-homepage/00-d8-homepage.twig" to "true"
5. Reload the page http://localhost:3000/pattern-lab/?p=pages-d8-homepage
6. Inspect the Bolt Background image and confirm that **loading="lazy"** is present
> Background Component LazyLoad Update

- docs-site/src/pages/pattern-lab/_patterns/999-tests/chip/00-chip-and-icon.twig
- packages/components/bolt-chip/src/chip.scss
https://pegadigitalit.atlassian.net/browse/WWW-1121
Fixes chip icon mis-alignment.
Breakpoint specific adjustments are added to CSS along with Safari specific adjustments. This is a subpixel issue and can't be fixed 100%, but the alignment should be fine most of the time now.
Run the branch locally and check the chip and icon test page under Tests. Make sure the icon's vertical alignment is almost close to center at all breakpoints and across all browsers.
> WWW-1121 adjust chip icon alignment

- docs-site/src/pages/pattern-lab/_patterns/30-layouts/holy-grail/10-holy-grail-use-case-navigation.twig
- packages/layouts/bolt-holy-grail/src/holy-grail.scss
https://pegadigitalit.atlassian.net/browse/DOCS-232
Fixes a grid width issue with the Holy Grail Layout that causes responsive tables to not render correctly.
Use `1fr` in CSS grid template is causing certain components miscalculate the width of its parent container. It has been changed to `minmax(0, 1fr)` as a fix. 0 min-width straightens out the issue.
Run the branch locally and check the Holy Grail Layout docs. The table in the use case demo should be able to horizontally scroll when the viewport is smaller than ~1000px.
> DOCS-232 Fix holy grail layout content width

- packages/build-tools/tasks/task-collections.js
- packages/configs/stylelint-config/package.json
- yarn.lock
https://pegadigitalit.atlassian.net/browse/DS-688
Fix build errors found when pulling in 5.x to Drupal.
We were requiring a script that assumed the `lerna.json` file was accessible. This is a safe assumption in the monorepo but not in the Drupal environment. The solution is to skip this script in Drupal.
A few of our stylelint-related packages are not compatible with stylelint < v14, and one of the packages has a missing peer dependency (`postcss`). I upgraded the packages and added the expected peer dependency.
The takeaway here is to pay attention to the peer dependency warnings we see when running `yarn install`. Mismatches here at some point became actual bugs.
- Check out this branch and run `yarn`, `yarn lint:scss`, `yarn fix`, `yarn start`, and `yarn build`.
- Travis is passing.
> Hotfix: v5.1.1 fix build errors

- packages/elements/bolt-image/src/image.scss
https://pegadigitalit.atlassian.net/browse/DS-695
`content-visibility: auto;` is conflicting with our JS that calculates scroll position. Comment-out to avoid bugs until we can fix the root issue.
When an image is far enough outside of the viewport, `content-visibility: auto;` will hide the image and the height thereafter is determined by the `height` attribute of the image. If there is no `height` attribute, the height is `0`. Either way, this change in height can happen while the TOC is in mid-scroll toward a target section. Upon arrival at that section, the page has shifted and it arrives at the wrong spot. Until we can figure out how to work with this new property, I am commenting-out this rule.
Review files changed. Nothing else to review.
> DS-695 Comment-out content-visibility rule

- packages/components/bolt-form/src/form.js
https://pegadigitalit.atlassian.net/browse/SN-96
Updates the selector used to apply JS validation so that React form elements are skipped.
You can now add the class `js-bolt-react-component` to any React input which also uses the `c-bolt-input` class for styles and opt out of the default Bolt validation.
On Accounts this validation is handled via a separate React library.
Review code and verify existing for JS works as expected. For example, blurring a required field triggers an error message.
> SN-96 Skip JS validation on React form elements

- packages/components/bolt-listing-teaser/src/listing-teaser.twig
https://pegadigitalit.atlassian.net/browse/DS-697
The if conditional was added to prevent rendering empty div - `c-bolt-listing-teaser__flag-content`
`c-bolt-listing-teaser__flag-content` is rendered if one of the following properties is added: 
- `meta_items`
- `description`
- `warning`
- `chip_list`
- `reply`
Check if div with the class `c-bolt-listing-teaser__flag-content` is rendered only when one or more properties are added
> DS-697 Prevent Listing teaser from outputting empty div

- docs-site/src/pages/pattern-lab/_patterns/40-components/page-footer/05-page-footer.twig
- packages/components/bolt-page-footer/page-footer-nav-ul.schema.js
- packages/components/bolt-page-footer/src/page-footer-nav-ul.twig
https://pegadigitalit.atlassian.net/browse/WWW-1215
https://pegadigitalit.atlassian.net/browse/WWW-1217
Adds a `open` prop to Page Footer's nav list template.
1. Updated twig and schema.
2. The prop will make a nav list expand by default in mobile view.
Run the branch locally and check the Page Footer docs, make sure the `open` prop works as expected.
> WWW-1217 add open prop to page footer nav list

- docs-site/src/pages/pattern-lab/_patterns/40-components/modal/10-modal-width-variations.twig
- docs-site/src/pages/pattern-lab/_patterns/40-components/modal/25-modal-scroll-variations.twig
- docs-site/src/pages/pattern-lab/_patterns/40-components/modal/30-modal-trigger-variations.twig
- docs-site/src/pages/pattern-lab/_patterns/40-components/modal/40-modal-usage-image-and-caption.twig
- packages/components/bolt-modal/src/modal.scss
- packages/components/bolt-tabs/__tests__/tabs.e2e.js
https://pegadigitalit.atlassian.net/browse/DS-699
An image center position on Safari was fixed
When `max-width: value;` inline style is applied to an `<img>` and modal width property is set to `auto`, the image should stay in the center position.
Pull the branch. Add an inline style to an image for example `max-width: 600px` and set the modal width to `auto`, Check if modal width adjusts to the image width and the image stays in the center position.
> DS-699 Safari Image Position Bug

- docs-site/src/pages/pattern-lab/_patterns/999-tests/tooltip/15-tooltip-link-whitespace.twig
- packages/components/bolt-popover/src/popover.js
- packages/components/bolt-tooltip/src/tooltip.js
https://pegadigitalit.atlassian.net/browse/DOCS-53
Remove whitespace around tooltip/popover trigger.
When you pass a link as tooltip/popover trigger there is whitespace added by JS. This removes the whitespace.
This does not fix the whitespace added by Twig, which is still an issue on Tooltip.
- Review code
- Checkout this branch locally and see new test page: `/pattern-lab/patterns/999-tests-tooltip-15-tooltip-link-whitespace/999-tests-tooltip-15-tooltip-link-whitespace.html`
- Verify there is not any whitespace after the tooltip or popover.
> DOCS-53 Remove whitespace around tooltip/popover trigger

- packages/components/bolt-page-footer/src/page-footer-nav-li.twig
- packages/components/bolt-page-footer/src/page-footer-nav-ul.twig
- packages/components/bolt-page-footer/src/page-footer.scss
- packages/components/bolt-page-footer/src/page-footer.twig
Fixes the naming convention within the Page Footer component.
1. All changes are within the templates and CSS
2. Make sure if raw HTML was used before, update class names `c-page-footer*` to `c-bolt-page-footer*`
Run the branch locally and check out the page footer docs. Make sure everything works exactly as before.
> Fix: namespace Page Footer component code

- packages/components/bolt-modal/src/modal.scss
Adds a max-width to regular modals.
1. Updated CSS for the `regular` option for Modal component's width prop
2. The max width is set to be exactly the same as the overall site max width (1400px)
Run the branch locally and check the modal docs. Modals with width set to `regular` should be no wider than 1400px.
Any modal that has `width` set to `regular` now has a max-width of 1400px. This means the modal width will not get wider than 1400px. For modals that require going beyond that max-width, use `width: full` instead.
> Fix: add max width to regular modal

- packages/components/bolt-page-footer/src/page-footer.scss
https://pegadigitalit.atlassian.net/browse/WWW-1289
Fixes an issue where the Page Footer button's chevron icon is out of place.
Updated CSS to use flex instead of grid.
Run the branch locally and check the page footer doc with viewport set to 480px or smaller. Make sure the chevron icon that  is in each section heading is displayed on the same line as the text and to the right edge.
> WWW-1289 fix page footer button's chevron placement in iOS 14

- packages/experimental/micro-journeys/src/interactive-pathways.js
https://pegadigitalit.atlassian.net/browse/WWW-1284
Restores microjourneys, which have been broken as of 5.0.0
This appears to have originally broken with
https://github.com/boltdesignsystem/bolt/commit/3a8a24ca83c3e2fd44bafb4290decc250638c5b9.  By removing the reference to an undefined variable, micro journeys work again and themes are still supported.
On this branch, go to /pattern-lab/?p=experiments-micro-journeys and confirm that the micro journey loads.  Optionally, add a `t-bolt-dark` class to confirm all parts still work with a dark theme.
> WWW-1284: Remove reference to undefined `themes` variable

- docs-site/src/pages/pattern-lab/_patterns/999-tests/animations/banner-test-fade-ins.twig
- packages/global/styles/06-animations/_999-animations-on-load-test.js
- packages/global/styles/06-animations/_animations.scss
https://pegadigitalit.atlassian.net/browse/DS-692
Edits to the animation work in https://github.com/boltdesignsystem/bolt/pull/2419.
- Removed cascade SCSS which was adding +40kb of CSS to the bolt-global.css and handled the cascade animation with JS instead.
- Minor tweaks to demo JS.
Review files changed.
> DS-692 Animation Tool Set (edits)

- packages/components/bolt-tooltip/src/tooltip.js
- packages/components/bolt-tooltip/tooltip.schema.js
[https://pegadigitalit.atlassian.net/browse/DS-734](https://pegadigitalit.atlassian.net/browse/DS-734)
`aria_type` property on `bolt-tooltip`. remove `aria-expanded` use on `bolt-tooltip`.
Add a new property to `bolt-tooltip` that allows users to choose `labelledby` or `describedby`. Remove the dependency on `aria-expanded` to prevent conflicts with other components.
Pull the branch and set some demos to use `describedby` instead.
new `aria_type` property on `bolt-tooltip`
> DS-734: Tooltip aria_type Prop

- packages/components/bolt-page-footer/src/page-footer.scss
- packages/experimental/micro-journeys/src/interactive-pathways.js
This hotfix includes the following two PRs, which have separately been approved and merged to master already.  Releasing them as a hotfix unblocks deploying 5.0 to production in Drupal (mostly for pega.com).
https://github.com/boltdesignsystem/bolt/pull/2441
https://github.com/boltdesignsystem/bolt/pull/2442
> Hotfix: footer and micro journeys

- packages/website-ui/styleguidekit-twig-default/views/partials/general-footer.twig
Brightcove Playback rates logic update to support video.js v7.13+ and provide a fallback to previous versions
(This PR is to maintain consistency between BC, Drupal and Bolt, this code is being tested and merged [here](https://gitlab.com/pegadigital/bolt/pega_bolt/-/merge_requests/287))
> Brightcove Playback Rates update

- docs-site/src/pages/pattern-lab/_patterns/40-components/page-header/-page-header-example-saleshub.twig
- packages/components/bolt-page-header/src/_page-header-desktop.scss
- packages/components/bolt-page-header/src/page-header-nav-li.twig
Fixes a bug where signifier only links in the Page Header's utility nav is mis-aligned.
Updated twig and css to accommodate signifier only links that don't have children. 
Run the branch locally and check the Saleshub page header demo. Make sure the Pulse link in page header is an icon only link without children. When hover or tab to, a tooltip shows the word "pulse".
> Fix: page header pulse icon link for Saleshub

- docs-site/src/pages/pattern-lab/_patterns/999-tests/button/00-button-without-states.twig
- packages/elements/bolt-button/src/button.scss
https://pegadigitalit.atlassian.net/browse/DS-729
HTML elements different than `<a>` and `<button>` can look like the bolt button element but without the interactive features.
Interactive features of `<button>` like:
- hover
- active
- cursor pointer
were scoped only to semantic HTML `<button>` and `<a>` tags.
A test page of the examples was added to the Tests folder.
Pull the branch. Try to add `e-bolt-button`  class to different HTML tags than `<a>` and `<button>`. For example `<span>` or `<div>`.
If an HTML tag with an `e-bolt-button` class is not a semantic `<button>` or `<a>`, the element will only look like the button (shape, color, etc), without the interactive features of the button.
> Ds 729 Scope button state styles to a and button elements

- packages/components/bolt-page-header/src/page-header-nav.js
- packages/components/bolt-page-header/src/page-header.js
[https://pegadigitalit.atlassian.net/browse/DS-630](https://pegadigitalit.atlassian.net/browse/DS-630)
`Enter` and `Space` key interaction not working with screen readers active.
The screen readers are sending `click` events instead of `keypress` events when using `Enter` or `Space`. This ticket is to add the click `click` events and allow users to navigate the page header while using a screen reader.
Test in BrowserStack with NVDA on, or otherwise use PAWS and NVDA, then make sure you can navigate the pege header.
Modify page-header keypress interaction.
> DS-630: Screenreader Keypress Navigation in Page Header

- packages/components/bolt-typeahead/__tests__/__snapshots__/typeahead.js.snap
- packages/components/bolt-typeahead/typeahead.js
- packages/components/bolt-typeahead/typeahead.scoped.scss
- packages/components/bolt-typeahead/typeahead.twig
Fixes a visual regression where the typeahead's search button is misaligned.
1. Cleaned up Typeahead's HTML and CSS
2. Removed unnecessary  CSS that is prone to bugs
Run the branch locally and check the typeadead docs with and without JS. When tabbing to the icon-only search button within the typeahead, it should not be misaligned.
> Fix: typeahead search button misalignment

- packages/twig-integration/twig-extensions-shared/src/TwigFilters.php
https://pegadigitalit.atlassian.net/browse/DS-751
Adds support for placeholders in translatable strings
Proper string translation requires the ability to use variables.  For example, if you wanted to translate the string "Tom's Profile", where "Tom" was a variable that corresponded to the user's name, you couldn't just expect a translator to convert "'s profile" into, say, Spanish.
Instead, you should ask the translator to translate "@user's profile".  A Spanish translator could then understand the context of what they were translating and rearrange the words to "Perfil de @user".
This PR adds support for  basic placeholders in translated strings in Bolt to match how the Drupal `|t` filter already works in Drupal.  See https://www.drupal.org/docs/theming-drupal/twig-in-drupal/filters-modif …
> DS-751: Add support for placeholders to Bolt-only version of |t filter

- docs-site/src/pages/pattern-lab/_patterns/20-elements/article/05-article.twig
- packages/elements/bolt-article/src/article.scss
https://pegadigitalit.atlassian.net/browse/DS-748
The ordered list can be rendered as [the example here](https://pegadigitalit.atlassian.net/browse/DS-748) for any free-form content areas.
Styles were updated that `<ol>` uses `list-style-type`s:
- decimal (first and fourth level)
- alphabetical (second and fifth level),
- roman numbers (third, sixth, and larger than the sixth level)
Pull the branch. Create an ordered list using HTML `<ol>` tag and check if is rendered correctly with the Jira example.
The ordered (`<ol>`) list has new level indicators for nested items.
The ordered list uses decimal, alphabetical and roman numbers for the nested items for any free-form content areas.
> DS 748 update ordered list formats in article element

- packages/components/bolt-page-footer/src/page-footer.twig
- packages/components/bolt-page-header/src/page-header-primary-nav.twig
Updated navigation labels in page header and page footer to be more descriptive.
Run the branch locally and view the page header and page footer docs. Turn on VO (`cmd` + `f5`), and enable rotor (`ctrl` + `opt` + `u`). Press left/right arrows to view all landmarks. Make sure each navigation has a descriptive name.
> Fix: add proper navigation labels

- packages/build-tools/package.json
- packages/website-ui/uikit-workshop/package.json
- yarn.lock
https://pegadigitalit.atlassian.net/browse/CC-843
https://pegadigitalit.atlassian.net/browse/DS-745
Removes [fibers](https://www.npmjs.com/package/fibers) as an npm dependency
This project is resulting in an error in our Docksal container after upgrading to PHP 8.
That would be worth resolving if it weren't for the fact that it isn't actually used anywhere in our code and fibers explicitly says it's obsolete on its npm page.
How did it get introduced in the first place?  A giant sloppy PR from Salem (https://github.com/boltdesignsystem/bolt/pull/1725, https://github.com/boltdesignsystem/bolt/pull/1711), where he evidently just slammed in unused dependencies and couldn't be bothered to spend the time to clean up after himself, preferring instead to leave that work to his colleagues (we all …
> CC-843 remove fibers dependency

- docs-site/src/pages/pattern-lab/_patterns/999-tests/animations/banner-test-fade-ins.twig
- docs-site/src/pages/pattern-lab/_patterns/999-tests/animations/gallery-test-fade-ins.twig
- docs-site/src/pages/pattern-lab/_patterns/999-tests/animations/icon-test-fade-ins.twig
- docs-site/src/pages/pattern-lab/_patterns/999-tests/animations/video-test-bounce-ins.twig
- packages/global/styles/06-animations/_999-animations-on-load-test.js
- packages/global/styles/06-animations/_animations.scss
https://pegadigitalit.atlassian.net/browse/DS-756
Attributes selectors were replaced with specific classes.
- `[class*='a-bolt-']` replaced with `.a-bolt-base`
- `[class*='a-bolt-in']` replaced with `.a-bolt-in`
- `[class*='a-bolt-out']` replaced with `.a-bolt-out`
- JS file was updated with the new class
- Animation test pages were updated with the new classes in the Tests folder.
Pull the branch. Check if new classes are specific enough to avoid targeting other random classes. Go to test pages and confirm that animations work as previously.
> DS-756 Fix css animation selector

- packages/components/bolt-form/src/form.scss
https://pegadigitalit.atlassian.net/browse/DS-732
The search icon should be visible on mobile IOS.
The search icon should be visible inside the search input.
Pull the branch. Go to `pattern-lab/?p=components-form-search` on mobile ios and check if the search icon is rendered.
> DS-732 Mobile | IOS Search icon is not visible in the search bar

- docs-site/src/pages/pattern-lab/_patterns/40-components/switch-button/05-switch-button.twig
- packages/components/bolt-switch-button/__tests__/__snapshots__/switch-button.js.snap
- packages/components/bolt-switch-button/src/switch-button.twig
https://pegadigitalit.atlassian.net/browse/DS-760
Fixes a bug where the switch button's label text is announced twice.
1. Aria attributes added to prevent the redundant announcments
1. Doc page updated with better copy
1. Run the branch locally
2. Go to the Switch Button doc
3. Use screen reader and tab to the switch button in the demo.
4. Press either enter or space
5. Listen to screen reader
> DS-760 fix switch button label text

- docs-site/src/pages/pattern-lab/_patterns/40-components/floating-action-buttons/-05a-floating-action-buttons-demo.twig
- docs-site/src/pages/pattern-lab/_patterns/40-components/floating-action-buttons/-10a-floating-action-buttons-demo-show-on-scroll-selector.twig
- docs-site/src/pages/pattern-lab/_patterns/40-components/floating-action-buttons/-15a-floating-action-buttons-demo-toggle-button.twig
- docs-site/src/pages/pattern-lab/_patterns/40-components/floating-action-buttons/-999a-floating-action-buttons-demo-use-case-offsets.twig
- docs-site/src/pages/pattern-lab/_patterns/40-components/floating-action-buttons/05-floating-action-buttons.twig
[https://pegadigitalit.atlassian.net/browse/DS-540](https://pegadigitalit.atlassian.net/browse/DS-540)
Demo was added with #2423, this PR is to add a warning about pattern-lab.
Add a warning that the smooth animation does not work inside the pattern-lab wrapper and that it should be opened in a new tab.
Read the demo text added in PR.
> DS-540: scroll to top demo warning

- docs-site/src/pages/pattern-lab/_patterns/40-components/headline/40-headline-numbered.twig
- docs-site/src/pages/pattern-lab/_patterns/999-archive/academy/05-pages/t2-inner-pages/challenge-details/acd-challenge-detail-page.twig
- docs-site/src/pages/pattern-lab/_patterns/999-tests/headline/headline-numbered.twig
- packages/components/bolt-headline/headline.schema.js
- packages/components/bolt-headline/src/_headline.numbered.scss
- packages/components/bolt-headline/src/_typography.twig
https://pegadigitalit.atlassian.net/browse/DS-232
The headline component’s `purple` option is updated with the brand color `violet`.
- `numberText` was renamed to `number_text`,
- `numberColor` was renamed to `number_color`,
- CSS was updated with the brand color `--bolt-color-violet`,
- All usages in PL are updated,
- Schema was updated with new props and old props are indicated as deprecated,
- Test page was created in the Tests folder `/pattern-lab/?p=viewall-tests-headline`
Pull the branch. Check if there is no regression on the headline component where `number_text` and `number_color` are used. Make sure the props are deprecated properly.
- `numberText` prop is depracated (please use `number_text`),
- `numberColor` prop is deprecated (please use `number_color`) ,
- `purple` color was …
> DS-232 Update headline numbered variation "purple" option

- packages/website-ui/uikit-workshop/src/scripts/components/pl-nav/pl-nav.iframe-helper.js
https://pegadigitalit.atlassian.net/browse/DS-459
Comment out PL JS that is preventing escape key event from firing.
This appears to be a part of the PL Search or navigation component. It captures escape keypress and prevents it from returning in certain cases. I don't believe we even have PL search anymore so I feel comfortable removing this. If it causes any minor escape-key regressions in PL I'm also fine with that as it's interfering with core component functionality (we need escape key to close dialog).
- Review code
> DS-459 Comment out esc key hijack in PL

- packages/elements/bolt-button/__tests__/__snapshots__/button.js.snap
- packages/elements/bolt-button/__tests__/button.js
- packages/elements/bolt-button/src/button.twig
- packages/twig-integration/twig-extensions-shared/src/TwigExtensions/BoltCore.php
https://pegadigitalit.atlassian.net/browse/DS-777
Pilots a new strategy for validation in button elements
* Previously, when button type and href were both missing, no tag would be set and the button would render with a missing tag (the following screenshot shows two valid buttons followed by a button that is missing the type attribute):
This PR adds a default type of `button` in that scenario.  If a button like this somehow makes it to prod, it will probably work as originally intended.
* However, to warn developers that they shouldn't omit the button type, if twig debugging is enabled (we use `enable_json_schema_validation` as a proxy), the button will be replaced with an error message telling them what's wrong.
1. Create a button with no type attribute in pattern lab:
```
{% include …
```
> DS-777 button element type validation

- package.json
- packages/configs/stylelint-config/ideal.js
- packages/configs/stylelint-config/package.json
- yarn.lock
n/a
Upgrade stylelint, add support for `dvb`
Upgrade stylelint to get support for dynamic viewport units: https://github.com/stylelint/stylelint/pull/5970/files
Still have to add "ignore" rule for `dvb` as it's only supported by Safari.
- Review code
- Checkout branch
- Add these rules to any SCSS file temporarily
```
block-size: 100dvh; // test new supported unit
block-size: calc(100dvb); // test unsupported, ignored unit
```
- Run `yarn`, `yarn lint:scss`
> Upgrade stylelint, support for `dvb`

- packages/components/bolt-page-header/src/_page-header-desktop.scss
- packages/components/bolt-typeahead/typeahead.scoped.scss
[https://pegadigitalit.atlassian.net/browse/DS-769](https://pegadigitalit.atlassian.net/browse/DS-769)
This PR is to fix the typeahead button still being clickable even when the menu is closed.
The submit button was still clickable even when the menu was closed. This moves the `pointer-events: all;` line to only be applicable when the menu is open.
Follow the steps-to-reproduce shown in the ticket.
> DS-423: Typeahead Button only Clickable When Menu is Open

- docs-site/src/components/pattern-lab-utils/docs.twig
n/a
Update logic in `docs.twig` to prevent a condition from unexpectedly returning true.
This only affects PL docs pages. There is [a line](https://github.com/boltdesignsystem/bolt/blob/master/docs-site/src/components/pattern-lab-utils/docs.twig#L8) that checks if a schema contains multiple schemas by seeing if a certain key exists. For example, if `schema["dialog"]` exists we know this component contains multiple schemas. If the component has only a single schema it is structured this way: `schema[...allTheSchemaProps]`. This went awry when we created a component called "Type", as `type` is a schema key name.
To avoid restructuring Bolt data (a big PITA), the simplest fix here is to add another check to just be sure that we're not mistaking a component name for a schema key. I'm doing …
> Docs page schema logic fix

- packages/build-tools/create-webpack-config.js
- packages/build-tools/package.json
- yarn.lock
Removed the `write-file-webpack-plugin` dependency since it is not being used anymore
Removed the `write-file-webpack-plugin` dependency from the build  tools, this is due to research because of the dependabot PR (https://github.com/boltdesignsystem/bolt/pull/2504). We will  be closing PR #2504 after this is merged.
> Remove write-file-webpack-plugin package

- packages/global/styles/05-objects/objects-ratio/ratio.js
- packages/global/styles/05-objects/objects-ratio/ratio.scss
- packages/global/styles/05-objects/objects-ratio/ratio.standalone.js
- packages/global/styles/05-objects/objects-ratio/ratio.twig
- packages/global/styles/index.js
- packages/global/styles/index.scss
https://pegadigitalit.atlassian.net/browse/DS-796
Ratio object is removed from the global > styles > 05-objects folder.
Referring to the previously [research ticket](https://pegadigitalit.atlassian.net/browse/DS-652) we don't need the ratio object anymore.
**Note that this is a copy of [this old pull request](https://github.com/boltdesignsystem/bolt/pull/2501). I did it again because something went wrong** 
Pull the branch. Check if there's no ratio object in the Bolt repository and usage of that.
The Ratio object has been removed. The [Ratio component](https://boltdesignsystem.com/pattern-lab/?p=viewall-components-ratio-deprecated) is deprecated. Use the [Ratio element](https://boltdesignsystem.com/pattern-lab/?p=viewall-elements-ratio) instead.
> DS-796: Delete ratio-object

- docs-site/src/pages/pattern-lab/_patterns/60-experiments/micro-journeys/combos/-95-in-page-example.twig
- docs-site/src/pages/pattern-lab/_patterns/999-archive/calculator/calculator.scss
- docs-site/src/pages/pattern-lab/_patterns/999-archive/calculator/results.twig
- docs-site/src/pages/pattern-lab/_patterns/999-archive/product-pages/_product-t3-extra-videos.twig
- docs-site/src/pages/pattern-lab/_patterns/999-archive/product-pages/_product-t3.twig
- docs-site/src/pages/pattern-lab/_patterns/999-archive/product-pages/product-landing.twig
- docs-site/src/pages/pattern-lab/_patterns/999-archive/product-pages/product-t2.twig
- docs-site/src/pages/pattern-lab/_patterns/999-archive/product-pages/product-t4.twig
https://pegadigitalit.atlassian.net/browse/DS-801
The `flag object` is deprecated. There are no instances in the Bolt repository of utilizing this object anymore.
The `flag object` is deprecated. All examples of its usage were replaced with the `Layout` using `template: 'flag'`
Pull the branch. Make sure there is no usage of the `flag object` in PL and whether replacing the `flag object` with the `Layout, template: 'flag'` makes no differences and regressions.
The `flag object` (`@bolt/flag.twig`) is deprecated. Please use the `Layout` with the `template: 'flag'` option whenever needed.
> DS-801 Flag Object Deprecation

- docs-site/src/index.js
- docs-site/src/pages/pattern-lab/_patterns/999-tests/popover/15-popover-disconnected-callback.twig
- packages/components/bolt-popover/src/popover.js
- packages/components/bolt-tooltip/src/tooltip.js
https://pegadigitalit.atlassian.net/browse/CC-959
When Popover/Tooltip is removed from DOM, be sure to destroy any related Tippy instances.
This fixes the bug where you replace a Popover on the page (via Drupal AJAX for example) and the old popover remains visible.
- Review code
- See demo page to verify Popover/Tooltip is removed when node is deleted
> CC-959: Cleanup Popover/Tooltip on disconnect

- packages/elements/bolt-button/src/button.scss
https://pegadigitalit.atlassian.net/browse/DS-821
Font size variable `--e-bolt-button-font-size` is adapted to the helper button class -> `.e-bolt-button--*SIZE* `
- The `.e-bolt-button--small` has small font size (`--e-bolt-button-font-size: var(--bolt-type-font-size-small)`)
- The `.e-bolt-button--xsmall` has xsmall font size (`--e-bolt-button-font-size: var(--bolt-type-font-size-xsmall)`)
- The only-icon buttons have the same `--e-bolt-button-icon-only-size: 1.1em` both in the case of `.e-bolt-button--small` and `.e-bolt-button--xsmall`
Pull the branch. 
- Go to `/pattern-lab/?p=elements-button-size`.
:point_right: Check if the small button and the xsmall button have appropriate sizes of the font. The small button should have a small font-size and the xsmall button should have xsmall …
> DS-821 WWW: Button Icon Size Bug

- docs-site/src/pages/pattern-lab/_patterns/20-elements/wrapper/00-wrapper-docs.twig
- docs-site/src/pages/pattern-lab/_patterns/20-elements/wrapper/05-wrapper.twig
- docs-site/src/pages/pattern-lab/_patterns/20-elements/wrapper/10-wrapper-use-case-custom-max-width.twig
- packages/base-starter-kit/.boltrc.js
- packages/base-starter-kit/package.json
- packages/components/bolt-band/__tests__/__snapshots__/band.js.snap
- packages/components/bolt-modal/__tests__/__snapshots__/modal.js.snap
- packages/elements/bolt-wrapper/CHANGELOG.md
- packages/elements/bolt-wrapper/README.md
- packages/elements/bolt-wrapper/__tests__/__snapshots__/wrapper.js.snap
- packages/elements/bolt-wrapper/__tests__/wrapper.js
- packages/elements/bolt-wrapper/index.scss
- packages/elements/bolt-wrapper/package.json
- packages/elements/bolt-wrapper/src/wrapper.scss
- packages/elements/bolt-wrapper/src/wrapper.twig
- packages/elements/bolt-wrapper/wrapper.schema.js
https://pegadigitalit.atlassian.net/browse/DS-811
A new wrapper element is created.
A new wrapper is a basic element that contains a basic schema with `content` and `attributes`.
Pull the branch. Check the wrapper docs and confirm it's a good equivalent of the old wrapper object.
The new `e-bolt-wrapper` will replace the old `o-bolt-wrapper` object.
> DS-811 Wrapper Element

- docs-site/src/pages/pattern-lab/_patterns/999-tests/animations/icon-test-fade-ins.twig
- packages/global/styles/06-animations/_animations.scss
https://pegadigitalit.atlassian.net/browse/DS-834
We have two options for animation duration:
- short
- long
- short duration is now our default value which is _200ms_
- long remained the same - _500ms_
- delay animation **short** was updated from _100ms_ to _200ms_ to correspond with the default animation duration which is also _200ms_
Check the `_animations.scss` and **Tests** folder with animations to confirm if elements appear as before.
> DS-834: Remove the medium animation duration 

- docs-site/src/components/pattern-lab-demos/_bare-list-demo.scss
- docs-site/src/components/pattern-lab-demos/pattern-lab-demos.scss
- docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/999-more-utilities/bare-list.twig
- packages/global/styles/07-utilities/_utilities-bare-list.scss
- packages/global/styles/index.scss
https://pegadigitalit.atlassian.net/browse/DS-802
A new utility class was created to achieve the same effect as the `bare-list-object` class.
A new `.u-bolt-bare-list` utility class is In the `More Utilities` folder. This class gets rid of **margin**, **padding** and **list-style-type** when added to the unordered list `<ul>` or ordered list `<ol>`.
Check if the new utility class behaves the same as the `o-bolt-bare-list` object.
The `bare-list` object is deprecated. Please use the utility class `u-bolt-bare-list`.
> DS-802 Bare List Object Deprecation

- docs-site/src/pages/pattern-lab/_patterns/20-elements/type/25-type-with-icon.twig
- docs-site/src/pages/pattern-lab/_patterns/50-pages/85-user/-user-sign-up.twig
- packages/components/bolt-teaser/src/teaser.twig
- packages/elements/bolt-button/src/button.twig
- packages/elements/bolt-text-link/src/text-link.twig
- packages/elements/bolt-type/src/type.twig
- packages/generators/bolt-generator/templates/element/element.twig
https://pegadigitalit.atlassian.net/browse/DS-694
Instances of spaceless filter `|spaceless` were replaced with spaceless tag `{% spaceless %}`.
To fix the vulnerability **spaceless tags** replaced **spaceless filters**.
Check if there are no more instances of spaceless filter `|spaceless` and whether `{% spaceless %}` fulfills its function.
> DS-694 Twig XSS Vulnerabilities

- packages/components/bolt-tabs/src/tabs.js
[https://pegadigitalit.atlassian.net/browse/DS-733](https://pegadigitalit.atlassian.net/browse/DS-733)
Make the tabs show-more button invisble on page-load to prevent an unstyled flash
Make the tabs show-more button invisble on page-load to prevent an unstyled flash
refresh a page with tabs on it, confirm that you are no longer seeing the more button flash before hiding again.
> DS-733: make tabs show-more button invisble by default

- docs-site/src/pages/pattern-lab/_patterns/40-components/profile/15-profile-avatar-edit-button.twig
- docs-site/src/pages/pattern-lab/_patterns/999-tests/profile/00-profile-edit.twig
- packages/components/bolt-profile/src/profile-avatar-edit-button.twig
https://pegadigitalit.atlassian.net/browse/DS-839
Fixes bug where button `type` is hardcoded and user classes are overwritten.
There was a regression in the avatar edit button template where `type` became hardcoded and user provided classnames were overwritten by base classnames. This PR fixes both and adds a test page verifying the required Drupal Ajax attributes will work when passed into the component.
- Review the code
- Review the Test page
> DS-839: Fix avatar edit button template

- docs-site/src/pages/pattern-lab/_patterns/999-tests/profile/00-profile-edit.twig
- packages/components/bolt-profile/src/profile.twig
https://pegadigitalit.atlassian.net/browse/DS-839
Fix broken schema to fix `full_bleed` prop.
In `5.7.1` we added multiple schemas to Profile but did not update the original `profile.twig` file to reference the schema. It now points to the schema properly and the `full_bleed` prop works again.
- Review code
- See Profile full bleed page and compare to [the latest version](https://boltdesignsystem.com/pattern-lab/?p=components-profile-full-bleed)
> DS-839: Fix broken schema to fix full_bleed prop

- docs-site/src/pages/pattern-lab/_patterns/999-tests/popover/15-popover-disconnected-callback.twig
- packages/components/bolt-popover/src/popover.js
- packages/components/bolt-tooltip/src/tooltip.js
- https://pegadigitalit.atlassian.net/browse/DS-817
- https://pegadigitalit.atlassian.net/browse/CC-959
Fixes a rare bug where a Popover/Tooltip inside of a Bolt List (or any other web component) fails to open.
When a Popover/Tooltip is inside another Bolt web component, and that other web component renders _after_ the Popover/Tooltip has rendered, it will trigger the Popover/Tooltip to disconnect. We are currently destroying the Tippy instance on disconnect. When the Popover/Tooltip reconnects, I expected it would reinitialize the Tippy instance, but it does not because the component's `firstUpdated()` lifecycle event only fires on the initial creation.
Instead of destroying the Tippy instance I am now just hiding it, which solves the original problem we sought to fix in …
> CC-959: Hide instead of destroy Tippy instance on disconnect

- docs-site/composer.json
- docs-site/composer.lock
- packages/twig-integration/twig-extensions-shared/composer.json
N/A
Changes fixed twig version requirement to range
Drupal is currently unable to update to a new version of twig since Bolt has a fixed version requirement.  This PR updates the composer requirement to be a semver range so that versions can be updated separately (within the same major version).
Within the `docs-site` directory, run `composer update twig/twig`.  Confirm that a version later than 2.14.11 is installed.
> Update twig version requirement to not be hard-coded.

- docs-site/src/pages/pattern-lab/_patterns/999-tests/table/30-table-sticky-headers.twig
- packages/elements/bolt-table/src/table.scss
- packages/layouts/bolt-site/src/site.scss
Fixed a bug where the sticky top header would go behind the rows.
Removed a unneeded CSS on the `tr` that was causing this issue.
Pull down the branch
Navigate to the `/pattern-lab/?p=tests-table-support-center` page
Scroll down on the table and observe that the top header is sticking
> DS-835: Table Sticky Top Bugfix

- packages/components/bolt-modal/__tests__/__snapshots__/modal.js.snap
- packages/components/bolt-modal/src/modal.js
https://pegadigitalit.atlassian.net/browse/WWW-1591
Changed the modal's accessibility headline from a `h1` to a `h2`
* Pull down the branch and run Patternlab
* Navigate to one of the Modal Component's PL page and tab through the page with Voice Over (cmd + F5 on a Mac)
* Confirm that the screen reader reads out the new modal `h2` headline
Changed the Modal Component's accessibility headline from a `h1` to a `h2`
> WWW-1591: Updated the modal's accessibility header headline

- docs-site/package.json
- package.json
- packages/build-tools/cli.js
- packages/build-tools/create-webpack-config.js
- packages/build-tools/package.json
- packages/build-tools/tasks/webpack-tasks.js
- packages/build-tools/utils/config-store.js
- packages/build-tools/utils/config.schema.yml
- yarn.lock
https://pegadigitalit.atlassian.net/browse/DS-872
Add bundle analyzer to the build to monitor bundle sizes.
[Bundle analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer) shows bundle sizes of the build in a list view and as an interactive visual tree.
Bundle analyzer can run in both dev and prod modes. Prod is most useful because it shows us the actual bundle sizes we ship. Unfortunately I was unable to "watch" in prod mode due to some build issues I do not have time to debug. So for now you can only watch in "dev" mode and build in "prod" mode.
This PR also adds `compiler.close()` to `packages/build-tools/tasks/webpack-tasks.js`. This is [recommended in the docs](https://webpack.js.org/api/node/#run). I added it while attempting to watch in "prod" mode - that didn't work …
> [6.x] DS-872 Add bundle analyzer to build

- docs-site/src/pages/pattern-lab/_patterns/999-tests/article/00-link.twig
- packages/elements/bolt-article/src/article.scss
https://pegadigitalit.atlassian.net/browse/DS-876
Long links shouldn't overflow parent containers
- The `article.scss` was updated on `a` tag with`overflow-wrap: break-word`
- A test page `/pattern-lab/?p=viewall-tests-article` was added to check the behavior of native HTML links and `e-bolt-links` inside `e-bolt-article`
Pull the branch. Go to the test page and confirm that long links wrap to another line if there's not enough space.
Long links within an article (`e-bolt-article`) wrap if there's no space enough
> [DO NOT MERGE] DS-876 Article Element Word Wrap

- docs-site/src/pages/pattern-lab/_patterns/999-tests/popover/20-popover-close-on-action.twig
- packages/components/bolt-popover/src/popover.js
[https://pegadigitalit.atlassian.net/browse/DS-774](https://pegadigitalit.atlassian.net/browse/DS-774)
Add event listener to close popover on click for anchors and buttons.
Add event listener to close popover on click for anchors and buttons.
Check the test page in browser and verify the popover closes when clicking on a link or a button.
> DS-774: Close Popover when inner action is clicked

- docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/45-listing-teaser-layout.twig
- docs-site/src/pages/pattern-lab/_patterns/40-components/listing-teaser/45-listing-teaser-line-clamp.twig
- packages/components/bolt-listing-teaser/listing-teaser.schema.js
- packages/components/bolt-listing-teaser/src/listing-teaser.scss
- packages/components/bolt-listing-teaser/src/listing-teaser.twig
[https://pegadigitalit.atlassian.net/browse/DS-868](https://pegadigitalit.atlassian.net/browse/DS-868)
Add a new prop for Listing Teaser to toggle the line clamp on the description.
Add a new prop for Listing Teaser to toggle the line clamp on the description.
Check out the new demo page.
> DS-868: Add description_clamp prop to Listing Teaser

- docs-site/src/pages/pattern-lab/_patterns/999-tests/notifications/00-notifications-long-strings.twig
- packages/components/bolt-notifications/src/notifications.scss
https://pegadigitalit.atlassian.net/browse/DS-893
The notification item doesn't overflow the container.
When we have really long strings or URLs in the notification item, they shouldn't overflow the container but break the longest string.
Go to the tests page `/pattern-lab/?p=tests-notifications-long-strings` and confirm that long strings don't overflow the container.
The long strings in the notifications item don't overflow the container.
> DS-893: Long strings in notifications causes some minor layout issues

- packages/components/bolt-card-replacement/src/card-replacement-media/_card-replacement-media.twig
https://pegadigitalit.atlassian.net/browse/DS-903
Fixes deprecation logic for image in cards
https://github.com/boltdesignsystem/bolt/pull/2520 introduced [a check](https://github.com/boltdesignsystem/bolt/blob/9e9619db775cc2f229aefa1bd51e4fbcb23a844f/packages/components/bolt-card-replacement/src/card-replacement-media/_card-replacement-media.twig#L15) for usage of the deprecated image component.
The check didn't take into account the possibility that a `src` prop could be passed either directly or as `attributes.src`.  In the later case, the logic incorrectly assumed that a render array was being passed rather than structured data.
Ultimately, this should be fixed on the Drupal side, but this update fixes the break.
On a local Drupal site, find a page that has cards with images and is …
> Update card media deprecation to check both src and attributes.src

- packages/build-tools/create-webpack-config.js
- packages/build-tools/package.json
- yarn.lock
https://pegadigitalit.atlassian.net/browse/DS-909
https://pegadigitalit.atlassian.net/browse/DS-910
Minify CSS that is loaded by JS, e.g. by our web components.
This step was unintentionally removed in the Webpack 5 upgrade. I've added it back with a comment so that we don't remove it again - unless it is no longer necessary.
1. Review code
2. Reproduce the issue
- Checkout `release/6.x`
- Delete `www/build` to remove any old build artifacts
- Open `packages/components/bolt-card-replacement/src/card-replacement/card-replacement.scss` and replace the entire file with: 
```
/* ------------------------------------ *\
Comment test 12345
\* ------------------------------------ */
.foo {
border: 1px solid red;
}
```
- Run `yarn build`
- Open …
> [6.x] DS-909 Minify CSS in JS
